### ISSUE TITLE
Bulk actions & set number of records to view on Posts List page

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#1023]
We have this on the User management page, perhaps we should add this on the posts lists page as well.

See ![screenshot](http://i.imgur.com/AgsKoru.png)

**Comment by rjmackay** [comment]
Assigning to @brandonrosage  - this would be something good to resolve in the mustang update. We should either have the ability to set page size everywhere or nowhere.

**Comment by brandonrosage** [comment]
I'm suggesting "nowhere," and instead having a default max (let's say, 20) number of results, [with a "Load more" button](http://github.ushahidi.org/platform-pattern-library/assets/html/5_layouts/settings-users.html) to add another 20. We could optionally layer "infinite scroll" over the top of this to auto-load more results for appropriate modes, like "Timeline," ideally for users with suitable bandwidth.

**Comment by rjmackay** [comment]
@jshorland this needs scoping / requirements from you right?

**Comment by jshorland** [comment]
The problem we're trying to solve is to complete bulk actions (delete, change status) on posts. The infinite scroll, while appropriate for timeline UX, doesn't sufficiently help users complete bulk actions of all appropriate posts. 

Proposed solutions:
1. users need to be able to select all posts (not just visible posts) that meet their selected criteria (ex: gmail attached) to complete bulk actions (delete, change status)
2. alternatively, we could simply let users choose how many posts to display, with a default of 25 instead of 10 (e.g. display 50, 100)

![screen shot 2016-09-12 at 12 16 13 pm](https://cloud.githubusercontent.com/assets/3224856/18449104/c1a31f42-78e2-11e6-97ce-b705dc037f83.png)

**Comment by brandonrosage** [comment]
Here is a collection of proposed solutions for bulk viewing and editing in the Timeline:

### 'Load X more'
When bringing posts into view, we currently have a "Load more" button at the bottom of the listing, which appends a preset number of posts to the listing (if there are more to fetch). The proposed revision would be to add a bit of functionality to that same button:

![load more](https://cloud.githubusercontent.com/assets/1136279/18560167/0c5848d2-7b40-11e6-9946-2baf040e914b.png)

So clicking the button (outside the number) loads the number of posts designated within the button. Selecting the number displays a list of alternative options:

![load more, numbers](https://cloud.githubusercontent.com/assets/1136279/18560206/36ec51c4-7b40-11e6-8f14-fbbddc977f8f.png)

This, of course, allows the user to configure exactly how many more posts they want to append.

### 'Select all' or 'Select all X posts in this dataset'
Users activate the listing toolbar today by selecting at least one post in the listing. One of the actions in the listing toolbar is "Select all," which selects every post that's currently in view. The proposed solution adds the option to "Select all X posts in this dataset."

![listing toolbar](https://cloud.githubusercontent.com/assets/1136279/18560414/071f07c4-7b41-11e6-95b0-279f22e92c67.png)

The "Select all X posts" label, of course, would display the total number of posts available in the current dataset (posts that match the filter criteria). And selecting it would simply change the listing toolbar summary to read:

![listing toolbar, whole dataset](https://cloud.githubusercontent.com/assets/1136279/18560378/ed071bce-7b40-11e6-9fe5-92ddcbb46797.png)

This action would not, however, load all of the posts in the dataset into view. It would simply indicate to the user that it had done so _programatically_.

I think this solution -- borrowing Gmail's approach in lieu of actually loading thousands of posts into view -- is a reasonable balance of obviousness and responsiveness.

----

@jshorland, @rjmackay, and @caharding: What do you think of these two solutions for improving the controls for a Timeline view of potentially hundreds (or thousands) of posts? Is it reasonable to implement? Would it be reasonably obvious to users?

I intend to do a simple user test on UserTesting.com as soon as I have something y'all have chimed in on.

**Comment by rjmackay** [comment]
@brandonrosage are you still waiting on us?

This looks really good to me so far. I'd probably err towards just implementing the 'Select all X posts in this dataset', and increasing the default page size. Rather than adding a 'Load x more'.. just because its simpler. That said we never implemented the 'load more' so we should fix that up anyway.

**Comment by brandonrosage** [comment]
@rjmackay I'm perfectly happy game-planning for this feature by saying we'll implement: 
* The "Select all X posts in this dataset" UX
* Replacing pagination controls with "Load more"
* Increasing the number of posts that are loaded from 10 to 20

We can table the "Load X more" pattern until we learn that the aforementioned solutions aren't cutting it.

**Comment by rjmackay** [comment]
Potential issues:
- User can't edit some or all the posts in the set
- How do we run auth on API

**Comment by rjmackay** [comment]
Initial thoughts on tech approach:
- I don't think this clearly matches a HTTP PUT semantics so it should probably use POST
- This should probably be an additional endpoint or 2 ie. `POST /posts/bulk...`
- The payload needs to include 1. the action to take 2. the filters params for the posts. This could look something like
```
{
    "action": {
       "status":"published"
    },
    "filters": {
        "tags": [1,2,3]
    }
}
```
- If we try to combined bulk delete and bulk update into a single endpoint its likely to be messy (ie. our usecase will be ugly)
     - Probably better to have /api/posts/bulk_delete and /api/posts/bulk_update endpoints
     - The alternate approach might be to use `PATCH /api/posts?condition=value` and `DELETE /api/posts?condition=value` 
- Either way the backend will need
     - New controllers, *and* a new usecase for each
     - New Post Repo methods to execute a bulk delete and bulk update as a single query (I *hope* this is possible)
- Both the bulk endpoints should only be available users with 'manage_posts' permission.
    - We restrict this explicitly to avoid having to run the post authorizer on *every* single post
- We also have to handle adding the entire set of posts to a collection.. not sure how to handle that since we normally do it through a collections/:id/posts endpoint

What have I missed? Whats wrong with this approach? @willdoran @zhalloran

**Comment by rjmackay** [comment]
On bulk add to collections: I think you can ignore that for this ticket since it would mean an entire extra endpoint. Do it if its easy. But otherwise we can just hide/disable the add to collection button when selecting an entire set of posts.

**Comment by zhalloran** [comment]
@rjmackay @jshorland Getting into the nitty-gritty of the update and was wondering about what fields we should allow for bulk updates. I'm of the impression that we should initially only use it for updating the published status of reports. To your point, @rjmackay, I think the use case for bulk adding and removing collections is different from managing them on individual posts and we need to scope out the changes in the UX before we proceed. Ideally, the workflow for updating tags on individual reports and on a collection of reports will be the same. The last thing we want to do is add complexity to the UX when we're trying to make things easier. Maybe we can discuss that next week? For now I'm just going to focus on updating the published status and am going to avoid everything else until we have a clear workflow defined.

**Comment by rjmackay** [comment]
@zhalloran you asked about UI for this yesterday. This comment https://github.com/ushahidi/platform/issues/1023#issuecomment-247398829 has a design for adding 'Select all 1000 posts in this dataset' .. once thats clicked any bulk actions using existing buttons should be sent to the bulk actions API.

**Comment by jshorland** [comment]
@rjmackay I'm moving this into a new milestone for upcoming work once devs move back onto platform

**Comment by rjmackay** [comment]
@willdoran I have some uncommited revisions to this locally. Ping me if/when you get to it.

**Comment by jshorland** [comment]
hasn't been touched in a year. moving to icebox along with the rest of the tasks epic.

**Comment by rowasc** [comment]
<img width="939" alt="Screen Shot 2019-06-09 at 14 53 29" src="https://user-images.githubusercontent.com/2434401/59162385-60944c00-8ac6-11e9-82cf-9c72985e5510.png">
Closing as we have bulk actions in data view now and infinite scrolling instead of a  number of posts to view
