### ISSUE TITLE
Mustang: Activity mode

### ISSUE THREAD

**Issue by rjmackay** [ushahidi/platform#1057]
- Update activity mode with new markup
- Confirm scope with Brandon, Jess and Robbie before building.
- Activity now differs from previous designs significantly.
  - Timeline is similar to timeline view, and previous designs
  - Charts should be based off old timeline and chart views - not view used in activity
  - Remove Map from activity entirely

Related bugs:
- https://github.com/ushahidi/platform/issues/305
- https://github.com/ushahidi/platform/issues/309

**Comment by rjmackay** [comment]
@brandonrosage @jshorland its not clear how the activity view is supposed to work right now.
I think I'm right in assuming the charts match old timeline and chart views.
However the old map just showed recent posts based on the week/month/all time filter.. is that still the idea here?

**Comment by brandonrosage** [comment]
@rjmackay "Activity" is a look at data in one of three date ranges: All time, this week, and this month. These are accessible from the "Filters" control in the toolbar.

The listing items leverage those date ranges, but individually can be configured to compare specified datasets. The "Activity by region" listing item doesn't happen to include its own "compare" control primarily because it doesn't have one in the product today.
