### ISSUE TITLE
Mustang: Post type settings updates

### ISSUE THREAD

**Issue by rjmackay** [ushahidi/platform#1062]
- Update post type settings based on new designs
- Function is similar to before
  - We shouldn't be adding any new functions or removing anything either
- Vertical tabs become horizontal. We might need a new directive for this, also used in #1054 

Related bug:
- #1021 
- https://github.com/ushahidi/platform/issues/773

**Comment by rjmackay** [comment]
@brandonrosage looks like the pattern library is missing a couple of things:
- How do you reorder the steps in a post type?
- How do you edit a step? (ie. edit its name, and if its required or not)

**Comment by brandonrosage** [comment]
@rjmackay Steps are represented in the Pattern Library as more narrowly-defined features. As we've discussed in the past, they're treated not as open-ended "Steps," but as 'templatized' tasks: Verify and Translate. So that's why ordering or editing its name is not represented.

Anticipating that this approach won't be implemented in this Mustang-implementation-release, I'll create an alternative layout demonstrating how it'd work with free-form "Steps" (which we're re-naming "Tasks" to set the stage for that feature).

**Comment by brandonrosage** [comment]
The aforementioned "alternative" layout is built: https://github.com/ushahidi/platform-pattern-library/blob/mustang/pattern-library/5_layouts/settings-survey-edit-alt.html

**Comment by rjmackay** [comment]
@willdoran did I see a comment about you working on this already?

**Comment by middle8media** [comment]
@willdoran assigned to you, via @rjmackay's above comment. Happy to help if/how I can.

**Comment by willdoran** [comment]
I wasn't working on this but I'll try to wire it up now
