### ISSUE TITLE
Posts created while not logged in not appearing in timeline or activity once logged in

### ISSUE THREAD

**Issue by Shadrock** [ushahidi/platform#1127]
### Expected behaviour
Ability to see "Shadrock Test Post" and "Shadrock Test Post 3" in timeline or activity view once logged in. Posts were made while I was *not* logged in but were confirmed by the "moderator will review your post" message.
### Actual behaviour
Couldn't find test posts anywhere. I checked timeline, activity, and searched by keywords. 
### Steps to reproduce the behaviour/error
Go to deployment. Make a post while not logged in. Log in. Look for post. Ball fists and curse impotently at the heavens through hot tears of rage.

**Comment by jshorland** [comment]
@Shadrock please confirm that this is for qa.ushahidi.com? I know it should be obvious, but you know what they say about assumptions.

**Comment by rjmackay** [comment]
I take it you were you logged in as an administrator, not a normal user?

**Comment by jshorland** [comment]
I can replicate this. 

Steps i took to reproduce:
1. go to qa.ushahidi.com
2. DO NOT LOGIN
3. add basic post with all required fields and save
4. login to deployment as admin
5. try to find post anywhere in that deployment

**Comment by Shadrock** [comment]
Sorry I missed this: just to (double) confirm: Jess' steps listed above are correct.

**Comment by rjmackay** [comment]
hrm. the problem here is the updated filter for "Who its visible to" https://www.dropbox.com/s/jt7mlq4ig4y9w93/Screenshot%202016-06-10%2015.04.20.png?dl=0

This default to "Everyone" but you'll only see those posts under the "Only you" label. However that label isn't even accurate for admins, since its visible to admins.

**Comment by rjmackay** [comment]
I'm going to update for now to:
1. Default to showing *everything* again.. I'm just not sure what to call this. Since 'Everyone' implies only showing posts visible to everyone, where we really want posts visible to Anyone. 
2. Rename "Only you" to "Only the author (drafts)" if the logged in user is admin.

Who its visible to:
- Everyone
- Admin
- Members
- Only the author (drafts)

**Comment by rjmackay** [comment]
Fixed. @jshorland can you retest on QA?

**Comment by jshorland** [comment]
This works as expected when I filter posts to those visible to Admin. I see posts created as a non-logged in user. 

cc: @Shadrock the ux needs re thinking here, but it's technically working.
