### ISSUE TITLE
Return ability to tell survey type of a post from Post List page

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#1157]
### Expected behaviour
This is what we had previously for:-
* A structured post
![screenshot](http://i.imgur.com/eIXvyWj.png)

A label for the survey the post belongs to would be great

### Actual behaviour
We only have an indication of 
* whether the post is public or not
* Source
* How to edit, add to a collection or delete the individual post

### Steps to reproduce the behaviour/error
* Click on Saved Search Star on homepage
* Select All posts
* View list of posts

Tagging @brandonrosage @middle8media cc @jshorland @rjmackay

**Comment by rjmackay** [comment]
I think this is mostly solved once Surveys have a colour and we can show that in the listing.. do we also need to include the survey name??

**Comment by brandonrosage** [comment]
I'll run a user test with 10-20 people that aims to answer this question.

I will say, though, that on the topic of "what data to call out in a post's summary "card," there's a related discussion about having the option to visually call out the post's category (instead of its survey). This type of flexibility (assuming it's embraced) makes the legend (filter control in the mode context) infinitely more important in visually distinguishing posts. So if we're headed that way, I think we should steer toward solutions that leverage that legend, versus just displaying more text in each card.

**Comment by brandonrosage** [comment]
@spiral99 Let's conduct a user test for this user question: "How do you create a new survey?"

This can be tested using the existing product. It doesn't require a prototype.

Of course, we want to know what _their_ answer is. But there is currently only one way for the participant to successfully complete this task: Settings > Surveys > "+" button

We're curious to know if it's necessary to provide an alternative path to creating a new survey, perhaps from the survey filter that's displayed in the Map and Timeline modes.

**Comment by brandonrosage** [comment]
We tested this matter in our Oct. 6 study and @spiral99 found that "testers were able to intuitively match colour strips to posts belonging to the same surveys, but had some difficulty when the surveys were hidden /not selected on the front page so the colour strips were not at the moment visible."

> Source: [Oct. 6, 2016 user test findings and recommendations](https://docs.google.com/a/ushahidi.com/document/d/1QW66bFOr5cjsHZpOUm1a0Qw39VCoL8JVdn8QChx-jmQ/edit?usp=sharing)

I think this tells us that the color-coding of surveys and the legend/filter in the mode context area is adequately telling users which survey any given post is related to.

Unless you object, @aoduor, I think we can close this issue.

**Comment by aoduor** [comment]
Yes please!
