### ISSUE TITLE
Change "unknown posts" to incoming messages?

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#1179]
We need to discuss the naming of unstructured posts. Now, it's "unknown". I'd prefer it to be "incoming messages" per a suggestion by @caharding. 

Only concern is that users get confused between this and posts that are already structured, but that have messages associated with them. 

Thoughts, @brandonrosage

**Comment by aoduor** [comment]
In my experience, users I spoke to/trained found the differentiation between structured and unstructured posts much clearer. I would go do keeping it as "unstructured" posts.

**Comment by rjmackay** [comment]
"Structured" terminology isn't used *anywhere* in mustang that I saw. I'm happy to bring it back (quickly if need be).. but for tomorrows release its gone.

**Comment by brandonrosage** [comment]
In Mustang, the use of "Unknown" was not intended to be a universal label for all unstructured posts in all contexts. It was to offer a survey filter with an intuitive label. In the Surveys filter, "Police encounters" represents posts whose survey is "Police encounters," and "Unknown" represents posts whose survey is unknown.

So I don't think we're under any pressure to decide what we call this type of content everywhere. I think we can label it correctly in each context. And test it accordingly.

For example, within a the detail view for a post with no survey, the 'postcard' shows the content in a default manner:

![Post detail, unknown](https://cloud.githubusercontent.com/assets/1136279/16011971/1419c380-314d-11e6-9edc-0859459918b7.png)

Appended to the raw post is a sheet prompting editors to "Add this post to a survey" and a sheet displaying "Conversations with (the) author." The latter displays the original "message," along with any messages the editors have tossed their way. These aren't called out as "messages" in any strict way. And we're not therefore beholden to calling every post of this sort a "message." It's simply that, in that context, the editors and author are exchanging messages.

With this approach, I'd suggest we call a pre-made Saved Search that displays all posts whose survey is unknown one of the following:

* Posts whose survey is unknown
* Posts not yet assigned a survey
* Posts waiting to be assigned a survey

I prefer "Posts waiting to be assigned a survey," because it suggests the necessary action.

**Comment by caharding** [comment]
We need the language about our features to be clear and human readable. The current format of structured/unstructured is abstract and not clear - I could not easily explain it to my grandmother. In the Ushahidi jargonverse, "unstructured" suggests that someone messaging Ushahidi meant to actually fill out a survey, when it is much more likely that they just wanted to report something or ask for help. 

Messages are common in tech and non-tech lexicon. Since all data source are necessarily unstructured, they really are just incoming messages. Any message should have an action that allows them to be converted into a post, but not necessarily, they could just be deleted. 

Sure it could create confusion between "messages" and "comments" but it is not nearly as confusing as "unstructured" and "comments," since it is impossible to infer what "unstructured" means without being deeply familiar with our internal jargon. This makes it harder to market the feature and will likely result in decreased adoption. 

Let's use human language as frequently as possible. In this case, messages has a much clearer meaning then structured.

**Comment by brandonrosage** [comment]
To be clear, the term "unstructured" is no longer used in Ushahidi. Mustang eliminated it.

**Comment by caharding** [comment]
*reviving this discussion. And reference #1254 at the very least this Survey type should not be viewable to users who have not configured a data source. And when they do it would require education that it would show up in "Unknown" but in that case it might as well just be "Data source" though I imagine people would want to separate Twitter from SMS/Email.

**Comment by brandonrosage** [comment]
@rjmackay How big a deal would it be to introduce a "Data sources" UX for an upcoming release that gave each "source" it's own view, rather than the all-in-one craziness we currently have?

**Comment by rjmackay** [comment]
When you say a "Data sources" UX - do you mean incoming posts from X, with views for twitter, sms, web etc?
Its probably not insignificant. But I think it might be worth it.

**Comment by brandonrosage** [comment]
No. I simply mean, when you go to Settings > Data Sources, you can click on "Email" and be taken to Settings > Data Sources > Email, with a dedicated view for all of its options.

**Comment by rjmackay** [comment]
Ah right. That should be fine @brandonrosage since we're just moving existing UI into a separate view. 
I was just confused by the prior discussion on this issue.

**Comment by rjmackay** [comment]
Related: #1096 - on the data sources settings change

**Comment by brandonrosage** [comment]
I've updated the PL to assume dedicated views for each Data Source. 

* [Data sources](http://github.ushahidi.org/platform-pattern-library/assets/html/5_layouts/settings-data-sources.html)
* [Data sources: Email](http://github.ushahidi.org/platform-pattern-library/assets/html/5_layouts/settings-data-sources-email.html)
* [Data sources: Twitter](http://github.ushahidi.org/platform-pattern-library/assets/html/5_layouts/settings-data-sources-twitter.html)

_A taste:_
![Twitter](https://cloud.githubusercontent.com/assets/1136279/16528186/c9ee41ae-3f80-11e6-906e-c75e5c4c5181.png)

There's some conditional logic to what appears when, and it's spelled out in HTML comments. But the idea is this...

When you click through to a Data source that isn't configured (like [the Email example](http://github.ushahidi.org/platform-pattern-library/assets/html/5_layouts/settings-data-sources-email.html)), it doesn't even show you the import-specific settings, like the toggle switch for turning on automatic imports. It only shows you the configuration stuff, prompting you to set things up and "Connect." Once you successfully connect to the source, the import settings 'form sheet' should appear above, with the option to "turn on" automatic imports.

When you click through to a Data source that _is_ configured (like [the Twitter example](http://github.ushahidi.org/platform-pattern-library/assets/html/5_layouts/settings-data-sources-twitter.html)), it shows you all settings, with the continued ability to revise (the button reads "update") your configuration.

**Comment by brandonrosage** [comment]
I've also added a "message" to [the "Data sources" layout](http://github.ushahidi.org/platform-pattern-library/assets/html/5_layouts/settings-data-sources.html) that suggests what would appear when...

* The user turns on automatic import for a source
* Selects "Done"
* Is directed to the "Data sources" landing page.

In other words, every time they turn on a data source and say "Done," they're returned to the "Data sources" page and told that their deployment is now "automatically importing" from that source.

![data source confirmation](https://cloud.githubusercontent.com/assets/1136279/16528976/c43902d0-3f85-11e6-9d4c-473ff9611fdd.png)

Furthermore, the "Data sources" layout demonstrates what the message would include if the source they had just turned on was configured to **_not_** add those imported posts to a specific survey. In this case, the message goes on to say:

> Because you've chosen to keep these posts' survey unknown for now, we've added an "Unknown" survey to your deployment's list of surveys. You can use this to quickly see any posts that are waiting to be added to a specific survey.

And it includes a button to "Show unknown survey posts," which would take them to a Timeline view with that filter applied.

**Comment by brandonrosage** [comment]
@caharding Does the above direction work regarding configuration of data sources and -- if a source isn't configured to add to a specific survey -- the education about the "unknown" survey?

**Comment by caharding** [comment]
Works. Thanks.

On Friday, July 1, 2016, Brandon Rosage <notifications@github.com> wrote:

> @caharding <https://github.com/caharding> Does the above direction work
> regarding configuration of data sources and -- if a source isn't configured
> to add to a specific survey -- the education about the "unknown" survey?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/ushahidi/platform/issues/1179#issuecomment-230002890>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABizaSwmlWatMOnLxXHE2crNwWrVJEV8ks5qRU1XgaJpZM4Iz_xq>
> .
>


-- 
Charlie Harding
Product Director

**Comment by caharding** [comment]
Closing in favor of #1925 as I don't think this issue was scoped well.
