### ISSUE TITLE
Redirect loop on private deployments

### ISSUE THREAD

**Issue by rjmackay** [ushahidi/platform#1232]
Private deployment redirects to /login.
Loops /views/map -> /login -> repeat

**Comment by tuxpiper** [comment]
Confirmed in my sandbox .io deployment, setting site.private = true causes the problem. Seems to be related to /login being a modal now.

The network trace shows requests from the client to read tags, forms, stats , geojson etc .. that are rejected with 403 , and thus causing the redirect to /login

**Comment by willdoran** [comment]
I think this issue occurs in part because these endpoints weren't accessed when the /login was served. Now that we redirect from /login to /, those aspects are triggering requests to the backend that are returning 403s and creating the loop as it causes a redirect to /login because of the 403. I'll repair the behaviour.

**Comment by rjmackay** [comment]
Thanks Will!. That sounds correct.
On private deployments it might make sense to render an empty page behind the login modal. Or a simple 'This deployment is private' message. Showing the map when there's no content is a little pointless.

**Comment by willdoran** [comment]
@rjmackay I think that would be a very straightforward fix. I'll do that. I'll make a "message" page, the contains a text string and opens behind the modal. That will solve the core issue.
