### ISSUE TITLE
CSV import needs to accept addresses

### ISSUE THREAD

**Issue by caharding** [ushahidi/platform#1246]
### Expected behaviour

On CSV import, people will have different address formatting. We require a specific lat/long data format. We either need a tool that converts other lat/long data formats (combined in one column, physical address etc.) and/or link to an external service that will help people convert their addresses to lat long in our format.

Aha! Link: https://ushahiditeam.aha.io/features/PROD-688

**Comment by Shadrock** [comment]
Just saw this the other day on the product call and wanted to add a few thoughts. These are just cursory reactions: not well researched yet. This problem will likely involve connecting to an external service and the results will largely depend on that service. Moreover, users can (and do) write addresses a myriad of ways (think about different types of abbreviations, etc.) so the service would have to be good at fuzzy logic. Localization of this could also be tricky: what services offer address lookup in Nepali? Moreover, I can't really think of a good solution in countries were addresses are non-standard and have no centralized point of truth upon which a database can be built. Because we're already connected to OSM, I'd suggest looking at their tool Nominatim ([repo here](https://github.com/openstreetmap/Nominatim) | [Wiki here](http://wiki.openstreetmap.org/wiki/Nominatim)).

**Comment by jshorland** [comment]
Also rquested during uchaguzi: 
In the event that I don't have lat/lon information on a CSV file, if we have location names indicated, it would be helpful to automatically geocode info.

Requested both for Uchaguzi and IFES UWIANO team.
