### ISSUE TITLE
Do not show unknown until a data source is configured

### ISSUE THREAD

**Issue by caharding** [ushahidi/platform#1254]
New users should not see Unknown unless they configure a data source. They should be educated about where these data sources go when they configure one.

**Comment by brandonrosage** [comment]
Yes. The intention is for the "Unknown" label to hold all posts that aren't yet assigned a survey -- which can only exist by way of a data source, like SMS or email. So, programmatically, this should be the logic for when that label is displayed on a deployment. 

And I'll push it along to @rjmackay to triage that part of the task. 

To that end, though, I've massaged the dropdown menus that are attached to each Survey name in the mode context filter control so that they offer a description (if one exists) for each survey, as well as the "Unknown" bucket: 

![image](https://cloud.githubusercontent.com/assets/1136279/16276175/e4641e92-3872-11e6-989a-46ed283cd28f.png)

You can see it for yourself here: http://github.ushahidi.org/platform-pattern-library/assets/html/5_layouts/timeline.html

I'll document additional system feedback about the "Unknown" label that will be displayed during the successful configuration of data sources.

**Comment by brandonrosage** [comment]
I've provided direction on the matter of system feedback -- education, really -- about the "Unknown" label in #1179, in two contexts:

* [During the configuration of a data source](https://github.com/ushahidi/platform/issues/1179#issuecomment-229993356).
* [In the confirmation message](https://github.com/ushahidi/platform/issues/1179#issuecomment-230001853) that appears immediately after turning on a data source that isn't configured to add its posts to a specific survey.

What I hope is obvious in these solutions is that it really steers users toward adding auto-imported posts to a specific survey:

![image](https://cloud.githubusercontent.com/assets/1136279/16529397/47ac368a-3f88-11e6-9967-57c05242007f.png)

And by choosing not to, they're thereby familiarized with the notion that their imported data will have no home, without intervention.

**Comment by rjmackay** [comment]
@jshorland another one to review and prioritize. I'll backlog for now
