### ISSUE TITLE
Need painfully obvious way to see all posts that need editing/approval

### ISSUE THREAD

**Issue by Shadrock** [ushahidi/platform#1263]
**This is for the COMRADES deployment**: http://comrades.ushahidi.com/views/map
Notes come from a training with 7 very tech savvy users.

### Expected behaviour
Users should be able to log onto a deployment and quickly be able to see only those posts that needed approval/triage.
### Actual behaviour
Users logged on proceeded to view reports via Map and Timeline views. In neither case were they entirely clear about how to find posts that needed approval. I purposefully had them work on the post they had created before logging in, which helped: but the process was still really confusing for most users. 
### Steps to reproduce the behaviour/error
Users logged on to the COMRADES deployment and proceeded to [review/edit/publish post according to the steps in this tutorial](https://docs.google.com/document/d/1rmx1pO8ZmNWvgjVaoxxYXAiWDkDafOQjQBOjSV4w1EQ/edit#bookmark=id.knk2tllvfiz0).

**Comment by brandonrosage** [comment]
I've lost some hair this week working through the heart of this issue. And I have a proposed solution that's illustrated in a handful of Pattern Library layouts.

The idea is basically this: From a user-facing point of view, let's scrap "Who can see this," and instead double down on "Post status." A post that's saved within a deployment is either:

* Published
* Under review
* Archived

Any user needs around the fine-tuned visibility of posts will therefore have to be constrained to Role configuration. This effects, well, a lot of screens. But here's the jist of it:

## Postcards
Anywhere you see a postcard (including as [a map popup](http://github.ushahidi.org/platform-pattern-library/assets/html/5_layouts/map.html), in [the Timeline](http://github.ushahidi.org/platform-pattern-library/assets/html/5_layouts/timeline.html), and [post detail](http://github.ushahidi.org/platform-pattern-library/assets/html/5_layouts/post-detail.html)), you'll see a consistent email-like treatment of its "status."

Example:
![postcards](https://cloud.githubusercontent.com/assets/1136279/16350397/2018537e-3a24-11e6-889a-a638fa580aff.png)

In the top-left of the postcard, a status indicator is displayed with one of the three status icons. If it's "Under review," it glows yellow (similar to an "unread" indicator), suggesting it requires attention. Otherwise, it's a subtle icon.

If you mouseover it, a short description of the status appears:

![mouseover](https://cloud.githubusercontent.com/assets/1136279/16350516/ae0da940-3a24-11e6-92a0-135f36e6ac63.png)

You can, of course, change a post's status when you edit it. But you can also change its status from:

1. The listing toolbar:
![listing toolbar](https://cloud.githubusercontent.com/assets/1136279/16350541/e42e8274-3a24-11e6-963a-2b316a92309a.png)

2. The post's actions dropdown:
![actions dropdown](https://cloud.githubusercontent.com/assets/1136279/16350552/03f0b2c6-3a25-11e6-89ef-36870917cc8b.png)

The status-related actions available correspond to the post's current status.

## [Map](http://github.ushahidi.org/platform-pattern-library/assets/html/5_layouts/map.html) & [Timeline](http://github.ushahidi.org/platform-pattern-library/assets/html/5_layouts/timeline.html)

The tools we provide for mashing up the data you're looking are naturally affected by this. 

In both Map & Timeline modes, the "toolbox" first displays a "status" fieldset, so you can quickly refine the data set:

![toolbox](https://cloud.githubusercontent.com/assets/1136279/16350626/87084e6c-3a25-11e6-85da-2fd77cccc28e.png)

Of course, the toolbar's more exhaustive "Filters" control also includes this feature:

![searchbar](https://cloud.githubusercontent.com/assets/1136279/16350664/be221464-3a25-11e6-8a6a-d94510290801.png)

## [Survey settings](http://github.ushahidi.org/platform-pattern-library/assets/html/5_layouts/settings-survey-edit.html)

Part of a survey's definition is who can add posts to it and whether posts requires review before they're published. The language and user interface is updated to be more conversational:

![survey settings](https://cloud.githubusercontent.com/assets/1136279/16350765/637cabcc-3a26-11e6-9d83-00552df2ef02.png)

If you choose to require review before publishing, more advanced options appear, in case you want to also require verification be completed:

![survey settings](https://cloud.githubusercontent.com/assets/1136279/16350777/8a39f95e-3a26-11e6-9281-50be7b0fa8a2.png)

And if you select any of those options, you can then assign them:

![survey settings](https://cloud.githubusercontent.com/assets/1136279/16350797/a88c7ada-3a26-11e6-86b2-c5b88f316c42.png)

## [Post edit](http://github.ushahidi.org/platform-pattern-library/assets/html/5_layouts/post-edit.html)

The example I've staged also assumes the user can edit the post time (and author). But you can see there's a very visible control there for changing the post's status:

![post edit](https://cloud.githubusercontent.com/assets/1136279/16350839/eb2064b0-3a26-11e6-8383-9bc34046c8e0.png)

## [Import CSV](http://localhost:8000/assets/html/5_layouts/settings-import-values.html)

One last thing worth noting is the import use case; where a user might import data into a survey that requires posts be reviewed before they're published, but wants them to be published right away. You can see that the flow for importing CSV data already includes a step for configuring data like this. I've just updated the fields to match this new approach:

![import](https://cloud.githubusercontent.com/assets/1136279/16350926/7c7b54d8-3a27-11e6-8023-b1db8c056b34.png)

cc/ @Shadrock, @jshorland, @rjmackay, @caharding

**Comment by caharding** [comment]
Wow I think you've thought through this really effectively. It makes sense
that visibility should be managed by roles and permissions not by
individual posts. The publish/draft/archive works very well and is a great
compromise. That it is viewable in filters makes it much easier to work
through these posts.

On Fri, Jun 24, 2016 at 2:20 PM, Brandon Rosage <notifications@github.com>
wrote:

> I've lost some hair this week working through the heart of this issue. And
> I have a proposed solution that's illustrated in a handful of Pattern
> Library layouts.
>
> The idea is basically this: From a user-facing point of view, let's scrap
> "Who can see this," and instead double down on "Post status." A post that's
> saved within a deployment is either:
>
>    - Published
>    - Under review
>    - Archived
>
> Any user needs around the fine-tuned visibility of posts will therefore
> have to be constrained to Role configuration. This effects, well, a lot of
> screens. But here's the jist of it:
> Postcards
>
> Anywhere you see a postcard (including as a map popup
> <http://github.ushahidi.org/platform-pattern-library/assets/html/5_layouts/map.html>,
> in the Timeline
> <http://github.ushahidi.org/platform-pattern-library/assets/html/5_layouts/timeline.html>,
> and post detail
> <http://github.ushahidi.org/platform-pattern-library/assets/html/5_layouts/post-detail.html>),
> you'll see a consistent email-like treatment of its "status."
>
> Example:
> [image: postcards]
> <https://cloud.githubusercontent.com/assets/1136279/16350397/2018537e-3a24-11e6-889a-a638fa580aff.png>
>
> In the top-left of the postcard, a status indicator is displayed with one
> of the three status icons. If it's "Under review," it glows yellow (similar
> to an "unread" indicator), suggesting it requires attention. Otherwise,
> it's a subtle icon.
>
> If you mouseover it, a short description of the status appears:
>
> [image: mouseover]
> <https://cloud.githubusercontent.com/assets/1136279/16350516/ae0da940-3a24-11e6-92a0-135f36e6ac63.png>
>
> You can, of course, change a post's status when you edit it. But you can
> also change its status from:
>
>    1.
>
>    The listing toolbar:
>    [image: listing toolbar]
>    <https://cloud.githubusercontent.com/assets/1136279/16350541/e42e8274-3a24-11e6-963a-2b316a92309a.png>
>    2.
>
>    The post's actions dropdown:
>    [image: actions dropdown]
>    <https://cloud.githubusercontent.com/assets/1136279/16350552/03f0b2c6-3a25-11e6-89ef-36870917cc8b.png>
>
> The status-related actions available correspond to the post's current
> status.
> Map
> <http://github.ushahidi.org/platform-pattern-library/assets/html/5_layouts/map.html>
> & Timeline
> <http://github.ushahidi.org/platform-pattern-library/assets/html/5_layouts/timeline.html>
>
> The tools we provide for mashing up the data you're looking are naturally
> affected by this.
>
> In both Map & Timeline modes, the "toolbox" first displays a "status"
> fieldset, so you can quickly refine the data set:
>
> [image: toolbox]
> <https://cloud.githubusercontent.com/assets/1136279/16350626/87084e6c-3a25-11e6-85da-2fd77cccc28e.png>
>
> Of course, the toolbar's more exhaustive "Filters" control also includes
> this feature:
>
> [image: searchbar]
> <https://cloud.githubusercontent.com/assets/1136279/16350664/be221464-3a25-11e6-8a6a-d94510290801.png>
> Survey settings
> <http://github.ushahidi.org/platform-pattern-library/assets/html/5_layouts/settings-survey-edit.html>
>
> Part of a survey's definition is who can add posts to it and whether posts
> requires review before they're published. The language and user interface
> is updated to be more conversational:
>
> [image: survey settings]
> <https://cloud.githubusercontent.com/assets/1136279/16350765/637cabcc-3a26-11e6-9d83-00552df2ef02.png>
>
> If you choose to require review before publishing, more advanced options
> appear, in case you want to also require verification be completed:
>
> [image: survey settings]
> <https://cloud.githubusercontent.com/assets/1136279/16350777/8a39f95e-3a26-11e6-9281-50be7b0fa8a2.png>
>
> And if you select any of those options, you can then assign them:
>
> [image: survey settings]
> <https://cloud.githubusercontent.com/assets/1136279/16350797/a88c7ada-3a26-11e6-86b2-c5b88f316c42.png>
> Post edit
> <http://github.ushahidi.org/platform-pattern-library/assets/html/5_layouts/post-edit.html>
>
> The example I've staged also assumes the user can edit the post time (and
> author). But you can see there's a very visible control there for changing
> the post's status:
>
> [image: post edit]
> <https://cloud.githubusercontent.com/assets/1136279/16350839/eb2064b0-3a26-11e6-8383-9bc34046c8e0.png>
> Import CSV
> <http://localhost:8000/assets/html/5_layouts/settings-import-values.html>
>
> One last thing worth noting is the import use case; where a user might
> import data into a survey that requires posts be reviewed before they're
> published, but wants them to be published right away. You can see that the
> flow for importing CSV data already includes a step for configuring data
> like this. I've just updated the fields to match this new approach:
>
> [image: import]
> <https://cloud.githubusercontent.com/assets/1136279/16350926/7c7b54d8-3a27-11e6-8023-b1db8c056b34.png>
>
> cc/ @Shadrock <https://github.com/Shadrock>, @jshorland
> <https://github.com/jshorland>, @rjmackay <https://github.com/rjmackay>,
> @caharding <https://github.com/caharding>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/ushahidi/platform/issues/1263#issuecomment-228464926>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABizaQH4bRXmI2KwgwJyiMTvIP7BBZ3Oks5qPEo6gaJpZM4I8Ab2>
> .
>



-- 
Charlie Harding
Product Director

**Comment by Shadrock** [comment]
This looks pretty good to me, Brandon. It is a bit of a complicated problem, and it's difficult to really sense how it would work with the cursory reading I gave this, but it's seems like a really sound response to the problem.

**Comment by rjmackay** [comment]
Love it. Thanks @brandonrosage .. this looks amazing and I know this has been a pretty hairy thing to work through.

**Comment by citizenkepler** [comment]
I am building out a grassroots ushahidi platform for politics in America. We had the similar question on finding posts that needed approval/action.  I have looked at the proposed system and I think this would also be applicable to our environment and the proposed fix would also work great for us as well. 

Thanks and I just want to voice support for these changes.

**Comment by rjmackay** [comment]
@citizenkepler Thanks for the feedback. This should be built out in the next couple of sprints so you'll see this change soon.
