### ISSUE TITLE
Display of Post Responses only works if User named their survey

### ISSUE THREAD

**Issue by nickbadams** [ushahidi/platform#1336]
### Expected behaviour

User should not have to type in a Title to name their survey. And even if users do not type in a Title, admins should still be able to easily browse their post responses in the timeline without clicking the menu button to the right, then the edit button. 
### Actual behaviour

If user's do not type in a Title for their survey response (an action that almost no user would expect to need to do when filling out a survey since surveys almost never require the respondent to give a title to their list of answers), admins cannot easily browse their responses. Admins must instead, click multiple times to see those responses.
### Steps to reproduce the behaviour/error

Try browsing Post responses in 'timeline view" that do or do not have user-generated Titles.

**Comment by jshorland** [comment]
@brandonrosage -- really good UX issue noted here. If a fix for this is possible to get done quickly, I'd like to prioritize it. If we need to put more thought into this design, we can group this in with a larger epic to make sure we allocate an appropriate amount of time to a solution. What are your initial thoughts?

**Comment by brandonrosage** [comment]
I've been dancing around this problem whole tackling some other issues. And they all come to this question: "Must a 'title' and 'description' be assumed for every post?"

When the answer is "yes," it creates a number of problems, including @nickbadams'. It also makes postcards in Map and Timeline modes very clumsy when it comes to featuring other content, like a photo. We can assume a title and description, but why assume a custom photo field should be appended there? Why not another custom text field?

When the answer is "no," the only problem I'm familiar with is uniformity -- how would we display a timeline of posts with wildly different structures?

I'd propose we answer "no," and answer the follow-up question regarding uniformity with this: Postcards' structure _should_ be different, if their surveys are structured differently. The visual consistency across postcards would continue to make Timeline and Map modes useful.

We could then intuitively say that postcards simply display the first three survey fields (whatever they may be) -- or, alternatively, provide a checkbox for every survey field, determining whether it's included in the postcard.

There's a lot of versatility that would come with this. It'd better address a lot of use cases. ANd, from a design perspective, it'd simply require an iteration to how we treat metadata (e.g. author post date), since we can;t always assume it'll follow a title.

I propose we resolve our approach to this in Montreal next week, and include the solution in its own epic; possibly following "Tasks."
