### ISSUE TITLE
After mapping a CSV with a few hundred rows, clicking finish import actually finishes import but doesn't tell the user that or change the screen to list view

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#1349]
steps to reproduce:
First, I uploaded a CSV with ~60 rows. all good.
Then, I uploaded a CSV with ~280 rows. all good until i hit "finish import" after mapping to my fields in my survey. Nothing happened and I had no indication that it had uploaded. so i clicked again. and again. 
Then, navigated away from importer to list view and there were 3x the number of posts in the original csv because i clicked three times.

**Comment by willdoran** [comment]
@jshorland Ok, this is an issue of async, we should disable the finish import button once they have clicked it and put a loading comfort noise. The page will eventually transition but it appears to be slow for large files. we should probably give them the option to navigate away - they will ultimately receive the notification saying import complete/failed irrespective of where they are in the app when it completes. That is a neat feature but it's almost a side effect because it's not capture by our flows.

I'm not sure how to fix this as it's a UI bug. But I would suggest the following:
1. When Finish Import is clicked go to a final page that says "Import in progress"
2a. If we could feedback progress from the API for large imports that would be pretty good, that doesn't exist right now, it's technically feasible but I'm not sure how complex it is, I would have to investigate.
2b. If we don't feed back then we should have a message saying "You can continue using the system, we will notify you when the import has completed." 
3. When the import has completed a notification will appear - this happens now - it's just that we don't tell people it's going to happen.

What do you think?

**Comment by jshorland** [comment]
@willdoran these sound like good options. I prefer 2a to 2b depending on dev time to do it. Could 2a be a good stop gap in the interim? I'd need to really understand technical difficulty of each to properly prioritize. @brandonrosage -- can you input as well in terms of UX of each option?

**Comment by willdoran** [comment]
@jshorland I will take a look at how we run the import and if there is an ability for the CSV create usecase to feedback as it runs through the import. It does seem slightly slow actually for even a couple of hundred entities may be there is also a speed up. I'll spend today looking into it.

**Comment by brandonrosage** [comment]
I think the ideal solution would be:

After the user selects "Finish," a fourth screen (using Layout C, which has no toolbar) appears with:

* Content explaining that the import is still in progress, that they'll be notified when the process is done, and that they can navigate away while that process is completed.
* A progress bar.

![Plan A](https://cloud.githubusercontent.com/assets/1136279/18254372/ae33fa42-7362-11e6-8b87-8ddd7ab2359d.png)

When the process is complete, regardless of where they are in the deployment, a **message** is displayed:

![Message](https://cloud.githubusercontent.com/assets/1136279/18254534/358f2cfe-7364-11e6-8387-3ba32406a503.png)

Also, if they had remained on the fourth screen -- the progress messaging screen -- it would update its contents:

![Updated content](https://cloud.githubusercontent.com/assets/1136279/18254620/1d88a9ea-7365-11e6-8150-74a914ae1c2f.png)

Selecting "See imported posts" would take the user to a Timeline view of that dataset. Selecting "Import another CSV file" would take the user to the first screen in the "Import" flow: "Choose file."

## Concessions

1. We could implement this first _without_ the progress bar and only the messaging.
2. We could implement this without the fourth screen if the user was taken instead _back_ to the first screen and immediately delivered a message with the intended content (e.g. "The data from your CSV spreadsheet is still being processed. You're welcome to leave this page or wait until the process is complete. Either way, we'll notify you when your data is ready.")

**Comment by willdoran** [comment]
@jshorland @brandonrosage ok, I will look at this today - feeding back progress will not be possible in the first iteration.

**Comment by brandonrosage** [comment]
@willdoran I'll be sure to prepare the `<progress>` pattern for use in an "indeterminate" state, just to show that the process is underway, even if we can't show progress.

**Comment by willdoran** [comment]
@brandonrosage Ok excellent that would be very helpful

**Comment by jshorland** [comment]
This is great. I get clear feedback on progress and don't click a thousand time. 

Passes QA, tested in qa.ushahididev.com
