### ISSUE TITLE
Add 'show this task to everyone' toggle to tasks

### ISSUE THREAD

**Issue by rjmackay** [ushahidi/platform#1363]
Migrated from #1283 
- [x] API: Add is_public field to post stages
- [x] Add "Show this task to everyone when the post is published" to task settings

@willdoran has a branch with this already partially implemented

**Comment by rjmackay** [comment]
@willdoran what were the outstanding questions on this?
I remember:
- Better wording around if it is visible when viewing or editing
- Should we allow editing of the task by the author? or just users with 'manage tasks'?
- Should this be added alongside the 'who can complete this task' control?

**Comment by willdoran** [comment]
@rjmackay I think those were key, I think the core issue is who exactly the Tasks are visible to. is_public would seem to imply that it is simply not published but that signed up users would have the ability to see it. That is the direct interpretation I take from:
"Show this task to everyone when the post is published"
However, if it is intended that only users with a certain permission "manage tasks", for example, can see it then I would suggest that the sentence needs to be rewritten as it is then capturing two things:
1. The task won't be publicly viewable on publication
2. Ordinarily the task won't be viewable by users without a certain permission.
This causes a problem, I think, because the granularity is weird. If for example I generally do not want this task to be published that's one thing. If I however might for one or N posts make this task viewable to internal users, I can't without make that task on all posts of this survey type viewable.

I'm not clear what this setting is trying to accomplish. If it is only that the task won't be published then the setting should be hidden when for private deployments. If it is intended to hide the task from certain user levels then I think the setting needs to be split in two:
Show this task when post is published
Restricted task visibility to roles with Manage Tasks permission.

**Comment by jshorland** [comment]
@brandonrosage just checking that you've got this included in your designs for tasks?

**Comment by willdoran** [comment]
@rjmackay Both of those are in, though the var is called show_task_when_published, which might be better as show_when_published to be explict. But right now it defaults to don't show, is that correct?

**Comment by rjmackay** [comment]
I think so? Whats the current behaviour of tasks? We should maintain that, any tasks already in a deployment should keep the visibility they already had.
For new tasks, I'll defer to @jshorland. Should tasks default to hidden from the public?

**Comment by rjmackay** [comment]
@Celestine22 there's a little potential for confusion between our current post 'status' (Published, Under Review, Archived) and the client's status as a custom field. Could you confirm if there's any relationship between which posts are visible to the public, and the posts status?
