### ISSUE TITLE
CSV import improvements

### ISSUE THREAD

**Issue by rjmackay** [ushahidi/platform#1366]
- We removed the configure posts step from CSV import
- We need to re-instate this but ensure the UX is more inline with the pattern library.

**Comment by rjmackay** [comment]
Assigned to myself to figure out if there are any issues with the current PL designs.

**Comment by rjmackay** [comment]
Suggested minimal version of this:
- Add global toggle for published, or option to map to CSV column
- Add missing mapping for CSV column to categories, post status, etc
- Switch mapping columns so we list all post fields, and dropdown of CSV columns

**Comment by brandonrosage** [comment]
@jshorland, @rjmackay: I've staged the three layouts for the revised CSV import flow in the `sprint-11` branch. You can sample them like this:

* [Step 1](http://preview.ushahidi.com/platform-pattern-library/sprint-11/assets/html/5_layouts/settings-import.html): The screen you see when you first visit "Import."
* [Step 2](http://preview.ushahidi.com/platform-pattern-library/sprint-11/assets/html/5_layouts/settings-import-configure.html): The screen you use to configure things like post status, field values, and categories.
* [Step 3](http://preview.ushahidi.com/platform-pattern-library/sprint-11/assets/html/5_layouts/settings-import-complete.html): The screen that, if the import is still processing, tells you as much. The layout includes "nearly complete" and "complete" states. In any case, the idea is that, when the process is finished, you're greeted with a message that includes an optional link to a Timeline view of the posts that were just imported.

**Comment by jshorland** [comment]
@brandonrosage What's the best way to provide feedback on the designs

**Comment by brandonrosage** [comment]
No. 1, if there are needs and requirements that are not addressed, please call those out in the comments here.

No. 2, if you have questions (about how it's supposed to work in various situations, or if something doesn't appear to be working), please toss those in the comments, too.

No. 3, if you have feedback about the visual design (e.g. it's not appealing or too messy), please make a comment. 

In any of those cases, It helps me a lot to have them captured in this thread (rather than something more abstract, like InVision comments).

**Comment by jshorland** [comment]
got it. 

On screen for step 2, if the user chooses to map a column to set status and/or categories, is it possible to have them complete this at the same time they map the other fields? I believe this would require some back end complications of populating the mapping fields after the user selects the methods of configuring these two. But to me, it's confusing/redundant to do it separately rather than just all at once in the mapping step.

**Comment by jshorland** [comment]
Second note: we should remove the set all posts to X categories and just have it be mapped via a csv column. Each post will likely have it's own unique category set. Am I missing a user story/problem though?

**Comment by rjmackay** [comment]
1. I think the requirements were address.

However we had agreed to only pull the posts status out separately. I think categories should just be included with other post fields in the table. It doesn't need an option to define a fixed value for all imported posts.

3. I'm not clear why the visual design changed. The main problem could have been addressed by just adding the 'Imported posts should have their status...' section to the existing UI..
The UI change adds extra work, but I'm not clear that it solves any user need. 

I'm happy to just implement this as you've now designed - since reverting would be more work for you, and mess with the sprint timeline - *but* it seems to happen often that we completely redo a screen instead of just tweaking/adding the missing elements. If the larger design change isn't essential this seems like a problem to me, as it creates extra work.

**Comment by rjmackay** [comment]
@willdoran are there any red flags in the designs posted above?

**Comment by rjmackay** [comment]
Issues spotted during sprint:
- How do we handle required tasks if marking all posts published
- If a user maps CSV column to published, how do enforced required fields+tasks

Solution
- When importing from CSV, skip validation of required tasks
- Notify users that tasks will not be marked complete

**Comment by brandonrosage** [comment]
I just pushed a revision to the "[Settings: Import CSV, configure posts](http://preview.ushahidi.com/platform-pattern-library/sprint-11/assets/html/5_layouts/settings-import-configure.html)" layout, which includes the potentially-necessary alert content regarding published posts and incomplete tasks.

![csv alert](https://cloud.githubusercontent.com/assets/1136279/18519263/e679db4e-7a68-11e6-9a7d-76f4d8b158fc.png)

The revision also moves category mapping into the same UI used for every other post field.

**Comment by brandonrosage** [comment]
I also just pushed a revision to the "[Post: Edit](http://preview.ushahidi.com/platform-pattern-library/sprint-11/assets/html/5_layouts/post-edit.html)" layout for `sprint-11`, which includes the potentially-necessary message on page load explaining that, while the post's status is currently "published," it has incomplete tasks that must be complete before it can be re-published:

![message](https://cloud.githubusercontent.com/assets/1136279/18520798/fa666784-7a6e-11e6-8e13-321e4056be03.png)

**Comment by brandonrosage** [comment]
@willdoran I've staged a revision to the "stepper" pattern example on the "[Settings: Import](http://preview.ushahidi.com/platform-pattern-library/sprint-11/assets/html/5_layouts/settings-import.html)" layout that provides a layer of optional (and smart) "accordion" interaction. It's included in the `sprint-11` branch of the PL.

It works by leveraging the global `accordion.js` script in the following ways:

* [The wrapper has a `data-accordion-items` attribute](https://github.com/ushahidi/platform-pattern-library/blob/sprint-11/assets/templates/layouts.settings-import.hbs#L36), with the value `stepper-item`. This tells the script which class-based selector to use to identify what constitutes an accordion item within it.
* Elements used to trigger a transition from one accordion item to another have a `data-accordion-trigger` attribute, with an optional numeric value. If it has a numeric value, that value is used to indicate which accordion item to transition to, **by its index**. If it doesn't have a value, it just transitions to the accordion item that that elements belongs to. Elements that use this attribute include ["Continue"](https://github.com/ushahidi/platform-pattern-library/blob/sprint-11/assets/templates/layouts.settings-import.hbs#L62) and ["Cancel"](https://github.com/ushahidi/platform-pattern-library/blob/sprint-11/assets/templates/layouts.settings-import.hbs#L268) buttons, and [the stepper headings](https://github.com/ushahidi/platform-pattern-library/blob/sprint-11/assets/templates/layouts.settings-import.hbs#L67-L70).
* There's one _class name_ that needs to be added (or removed) from stepper items programmatically: **`.complete`**. It should be applied to [the wrapper for each stepper item](https://github.com/ushahidi/platform-pattern-library/blob/sprint-11/assets/templates/layouts.settings-import.hbs#L38) that is deemed complete (where necessary). When applied, it will transform that item's badge from a number to a checkmark.
* There's one _attribute_ that needs to be added (or removed) from stepper items and buttons programmatically: **`disabled`**. It should be applied to [the wrapper for each stepper item](https://github.com/ushahidi/platform-pattern-library/blob/sprint-11/assets/templates/layouts.settings-import.hbs#L66) that cannot yet be accessed. Similarly, if there is a button (e.g. "Continue") that should not yet be selected, it should have the `disabled` attribute; but removed once that action can be taken. Note that other elements that might serve as triggers (like stepper headings) do not rely on this attribute in order to prevent transitions. When users select them, `accordion.js` prevents the transition if they're targeting stepper items that are `disabled`.

Finally, note that the "[Settings: Import](http://preview.ushahidi.com/platform-pattern-library/sprint-11/assets/html/5_layouts/settings-import.html)" layout that demonstrates this behavior currently has the second stepper item disabled, as well as the first stepper item's "Continue" button. So sampling the transition requires at least removing the `disabled` attribute from the second stepper item in order to make it accessible.

**Comment by rjmackay** [comment]
Haven't tested the import yet, but noticed the 'This post is currently in an invalid state. ' is showing up all the time, even on a valid post.

**Comment by rjmackay** [comment]
Working in QA:
- [x] Mapping to categories
- [x] Mapping to other fields
- [ ] Mapping to post status 
- [ ] Validating required fields
- [ ] skipping required tasks
 

Issues from QA:
- No loading image when uploading the CSV
- If theres an error during import I get a dropdown notification, and I'm stuck at this step:
<img width="893" alt="screenshot 2016-10-05 15 02 46" src="https://cloud.githubusercontent.com/assets/7965/19098807/e9674896-8b0c-11e6-8d69-a61b25306e2d.png">
  - how hard would it be to bump to a different display when theres an error?
- Its not clear what format needs to be provided for post status columns in CSV
  - could we add a 1 sentence explanation? especially since draft <> in review.
- Got an error "slug must not exceed 150 characters long"
https://www.dropbox.com/s/y4og4qacnkiityc/Screenshot%202016-10-05%2015.12.53.png?dl=0

**Comment by willdoran** [comment]
@rjmackay 

1. We can easily give another display if there is an error, that page has a completed state, so itcan have an error state, what should it contain? The error and "import another csv file"?
2. When you click: "Defined by column..." there is a message
<img width="576" alt="screen shot 2016-10-05 at 11 24 54" src="https://cloud.githubusercontent.com/assets/2694405/19119630/60771408-8aee-11e6-99d5-e098474b9422.png">
Should this message be replicated somewhere else as well so it's clear if they ignore this step and simply map directly? 
3. That's interesting, could you give me the reproduce steps/file you were using? I'm not sure why it would be trying to set the slug

**Comment by rjmackay** [comment]
> there is a message 

sorry apparently I just don't read things!
Does it work if the user users 'Under review'? or do I need to use the backend value 'draft' ?

re 3: it'll be generating a slug based on title, and failing to truncate it.

**Comment by willdoran** [comment]
@rjmackay No, you're right, the backend doesn't remap under review to draft. I will change that tomorrow morning. and I'll investigate the slug

**Comment by rjmackay** [comment]
@willdoran can you prioritize finishing this? otherwise its going to block deploying anything else built off develop

**Comment by willdoran** [comment]
@rjmackay yep doing so now

**Comment by jshorland** [comment]
Is this ready for me to test?!? (she says way too eagerly)

**Comment by willdoran** [comment]
Hopefully shortly, I'm just fixing mapping for the under review to draft so that users can pass in under review via csv

**Comment by jshorland** [comment]
This is working well. 

@willdoran When I didn't map lat/lon to "basic post" lat lons in qa.ushahididev.com even though it wasn't required, I got an error that read "array_combine(): Both parameters should have an equal number of elements". It ONLY happens when I choose which column to map to lat, and then re-select "leave empty". 

I did the same action (map to a field, then re-select "leave empty") to both lat AND lon, and received this error: Columns must be mapped to unique survey fields. The following columns have more than 1 mapping: undefined. 

Everything else is working. Let me know if you want to do a quick screen share of the action described above.

**Comment by willdoran** [comment]
Ok, cool, I'll fix that first tomorrow morning and let you know when it's up! Thanks!

**Comment by willdoran** [comment]
Ok this should be fixed and in develop

**Comment by jshorland** [comment]
@willdoran the original issue with the errors is fixed. I noticed one more issue during a demo with brandon -- after successfully importing posts from a CSV file, you are given two options: see imported posts, or dismiss. Is this meant to have "import another" as well? Or not on this particular screen? And upon clicking  "see imported posts" I am taken to the timeline view of all posts, not just the ones I imported. On the particular import I was testing with, I marked them all as archived, but when taken to list view, couldn't see them as the archived posts are default filtered out (which makes sense, but in this scenario i was supposed to see my imported posts).

**Comment by willdoran** [comment]
1. I think import another is on the page but I can add it to the body of that message I think. 
2. I don't know if we ever filtered the posts. I will take a look first thing tomorrow. If it's straightforward I will add it immediately.

**Comment by jshorland** [comment]
Additional scope: 
- imported CSV posts should be automatically batched into a collection on the backend named "[import date and time] import"
- clicking on "see imported posts" should take me to the list view of that collection. 
- collection needs to be set to visible by admin by default. 
- needs to be a path for users to get to edit collection settings, as with any other collection view
