### ISSUE TITLE
Need a way to move to next post in edit mode

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#1379]
User need:
When I'm triaging a bunch of posts, I want to be able to quickly move to next post after I'm finished editing one. 
### Actual behaviour

Currently, after saving my edits, I am taken back to the same post's detail. I then have to go back to map and/or timeline (I go back to timeline because it's the easiest for me) and click on the next post. This gets especially confusing when I'm on page 5, choose a post to edit, save the edits, and have to then go back to find my place in the timeline. 
### Steps to reproduce the behaviour/error

See above.

Potential solutions:
1. next and previous navigation on post detail and/or post edit page
2. "save and go to next" or "save" which takes them back to their place in timeline or map

@brandonrosage you may have a more elegant idea of how to do this.

**Comment by brandonrosage** [comment]
@jshorland The thing that tripped me up on this when you first asked about it earlier this week was that it wasn't clear to me how we could assume (or how the user could indicate) whether the user, A, wanted to save their work on the post and return to what they were doing prior (which is the most common expectation for any page-level "Save" action), or B, wanted to jump straight into editing the next post in the current dataset (or, for that matter, edit the _previous_ post in the dataset).

And if the solution was to provide buttons in the toolbar, in all cases, for _all_ of those possibilities, the toolbar would become unwieldy.

I think I have a handle now on a reasonable way for the user to indicate what they might want to do after saving a post -- and for Ushahidi to therefore assume the actions they may want to take.

I'll mock this up completely this week, but the idea is this:

Using [the proposed listing toolbar improvements](https://github.com/ushahidi/platform/issues/1023#issuecomment-247398829), the user indicates to Ushahidi that they want to deal with a grouping of posts (as opposed to just one post) by selecting two or more posts:

![listing toolbar](https://cloud.githubusercontent.com/assets/1136279/18560925/4a1f5eb4-7b43-11e6-8169-fc9f1170fb1f.png)

The listing toolbar would then include an "Edit" button, as pictured above. And if the user had selected two or more posts and then selected the "Edit" button, they'd be taken to "Post: Edit" for the _first_ post in the grouping. And this view would include a modest amount of additional UI to:
* Indicate that they are editing "1 of X" posts in the group.
* Provide action buttons to "Save and edit the next/previous post in the group."

That UI is what I'd like to mock up, if you're keen on a solution like this.

Again, I think this type of solution reasonably addresses the need to restrict the added UI that we'd need to help users traverse and edit multiple posts without repeatedly throwing them back to the Timeline. And that restriction is that we wait for the user to first tell us that they'd like to work with a group of posts all at once -- by selecting them (bulk editing them).

**Comment by rjmackay** [comment]
This seems potentially more complicated/confusing than just providing a 'Save and edit next post' button regardless if I selected multiple posts or just hit edit next to a single post. Is there something that stops us always including "Save and edit next post"?

**Comment by brandonrosage** [comment]
> Is there something that stops us always including "Save and edit next post"?

@rjmackay Ostensibly, the problem with including an action like that in the toolbar at all times is this:

![busy toolbar](https://cloud.githubusercontent.com/assets/1136279/18674721/ceddf32e-7f15-11e6-8b68-a061cc0d992b.png)

It's why I think "bulk editing" is a thing we should take seriously, so we can offer tools catered especially for it. We already do this for bulk-editing postcards.

**Comment by jshorland** [comment]
@brandonrosage I think your solution makes a lot of sense, and agreed that we can't just have the save and edit next at all times.

**Comment by rjmackay** [comment]
- The common approach I've seen elsewhere is a split button with 'save' and a dropdown arrow to pick "save and edit next" etc, combined with having the client remember and default to whatever action you took previously. That removes the issue of buttons not fitting in the UI, but brings its own complications/isn't present elsewhere in our UI.
- I'd also expect most bulk editing with happen on a larger screen device, not a phone. 
- I'm still stuck on the idea of selecting multiple items then editing, it seems unexpected, ie, I don't think thats a behaviour I've ever seen elsewhere. Can we user test to see if users actually discover how to edit multiple posts? or is this something we just have to document and educate users on?
  - perfectly happy to be ignored if you think I'm just overthinking this.

**Comment by brandonrosage** [comment]
@spiral99 I'm preparing a design solution for this that will be ready to test early next week. 

Let's conduct a user test for this user question: "How do you edit a group of responses?"

This will require testing either a graphic prototype (using something like InVision) or a Pattern Library prototype (which I can help stage), since the solution isn't implemented in the product.

The proposed solution would provide a path to optimally complete this task by way of Timeline mode, where the user could select multiple posts, select "Edit" from the listing toolbar, and using the attached navigational tools to save and move between posts in the group.

**Comment by brandonrosage** [comment]
@spiral99 I've staged a couple of things for you in order to test the viability of this design solution:

* The Pattern Library includes a [`test-bulk_post_editing`](http://preview.ushahidi.com/platform-pattern-library/test-bulk_post_editing/assets/html/5_layouts/timeline.html) branch that includes a flow for editing multiple responses, assuming the user does so by selecting multiple response from the Timeline and selects "Edit" in the listing toolbar. You can [test it today](http://preview.ushahidi.com/platform-pattern-library/test-bulk_post_editing/assets/html/5_layouts/timeline.html).
* UserTesting includes a draft test, called "[Ushahidi: editing multiple posts](https://www.usertesting.com/st/PZ3XHyQdofzHq-Y_tA_p)." It has an open-ended task directing them to edit the description of the first three responses. It also asks them to verbally explain what their ideal method for accomplishing the task would be (whether that's what they discovered in Ushahidi or not).

So why don't you give the prototype a spin, see if you can complete the tasks, and let me know what's needed in order to run the test.
