### ISSUE TITLE
survey colour settings needs more colours.

### ISSUE THREAD

**Issue by spiral99** [ushahidi/platform#1437]
Currently we only have 4 colors Red,Blue,Gold and Green this will present an issue when users want to create more than 4 surveys.
![2016-10-12](https://cloud.githubusercontent.com/assets/7393879/19310968/38e15686-9095-11e6-9c56-1aeae319b22f.png)

**Comment by justinscherer** [comment]
@caharding @jrtricafort I question the need for any colours on map view. Most of the time they just get grouped together anyways, which erases the colours. 

In any case, if we decide to keep the colours, they should be generated from our brand colours.

**Comment by jrtricafort** [comment]
@justinscherer In my experience as an analyst, more color options is generally better. Can we have standard options but also a spectrum color picker for people who want to go custom?

**Comment by rowasc** [comment]
We already have a color picker with a way to add HEX values directly. I'm inclined to close this in favor of https://github.com/ushahidi/platform/issues/1942 (referencing so we can later find this one easily), since we should be actively looking at making the color picker more friendly in #1942 as HEX values are OK but not super accessible for less tech savvy folks. Thanks!
