### ISSUE TITLE
Create deployments per branch

### ISSUE THREAD

**Issue by tuxpiper** [ushahidi/platform#1445]
Before starting to work on this, clarify:
- [x] Multi-domain deployment? Against which backend URL/s?
- [x] Desired URL layout? (i.e http://{deployment}.{branch}.ushahidi.dev) 

Tasks:
- [x] Choose storage + web server (i.e. AWS S3, Rackspace cloud files , whatever is easier to automate)
- [x] Build (if it has to be built) something to map deployment URLs to web server and set up DNS
- [x] Write automation for bucket creation
- [x] Write automation for file upload / sync (if necessary)
- [x] Integrate in the CI pipeline
- [x] Write automation for cleanup of old branches

**Comment by rjmackay** [comment]
Ideally I think QA environments should be multidomain, but they could be single domain if that proves tricky. The should share the backend with ushahididev.com deployments.

> Build (if it has to be built) something to map deployment URLs to web server and set up DNS

we have a little piece of JS that handles this in config.js. It'll probably work untouched

**Comment by tuxpiper** [comment]
Alright I think I'm ready to start rolling with this. Some highlights:

1. I've been looking at the unused domains we have laying around. Not super psyched about it, but I think I'll settle with ushahidilab.com by now.

That means we would be looking at URLs like this: http://{deployment}.{branch}.ushahidilab.com  . We can change this easily later if someone has a better idea.

2. Although some time ago I created a nice little proxy server that allows hosting something like this in cloud storage, I think it's probably not worth to use that by now. (The reason I wrote the proxy is mapping a url like 'deployment.branch.ush.xyz' to a S3 bucket that is just named 'branch.ush.xyz')

So, there will be a server. The CI will push the built frontend files into a server folder, with the name of the branch. And a nginx daemon will serve that JS.

If the server catches fire and the branch build is lost, you can always re-trigger the CI build to get it back :)

This looks quite straightforward to do, I'll update you soon.

**Comment by rjmackay** [comment]
A couple of extra bonus points:
- We currently have heroku doing PR builds.. I thought these were broken but they actually work. Do you still think its worth building this out? I'm leaning towards yes, because the heroku builds don't match any of our other process
- One thing I'd like to reproduce from heroku is pushing notifications to the github deployments API with a link to deployments. We're doing this for the pattern library with https://github.com/ushahidi/platform-pattern-library/blob/master/after_deploy.js and https://github.com/ushahidi/platform-pattern-library/blob/master/before_deploy.js
You could use those, or grab one of the many go utilities for doing it :)

**Comment by tuxpiper** [comment]
Ok, just finishing this up, with the bonus points :)

**Comment by tuxpiper** [comment]
This is in the following PRs:

- ushahidi/platform-cloud-ansible#25
