### ISSUE TITLE
Immediately create posts from new survey

### ISSUE THREAD

**Issue by willdoran** [ushahidi/platform#1453]
### Expected behaviour

- On save the success slider notifcation should contain a button allowing the user to go straight to adding a new post of this survey type 
- Two buttons. "Dismiss" (default blue button style) and "Add to survey" (button-beta)

### Actual behaviour
- No button yet

**Comment by rjmackay** [comment]
I think this makes sense. @jshorland next steps? would you like to backlog/design/scope?

**Comment by willdoran** [comment]
Test these changes by:
- [ ] Having successfully created a survey the success slider now allows you to immediately start adding to the survey
- [ ] Having successfully imported a csv the text and buttons should have a tighter layout exacty as in PL

**Comment by jshorland** [comment]
Creating a new survey gives me the correct slider and clicking on both buttons on the slider works. See success in gif upload

**Comment by jshorland** [comment]
I am not able to successfully import a csv file. The deployment doesn't appear to recognize my .csv file.

**Comment by rjmackay** [comment]
@willdoran is this CSV upload issue related to the image upload changes?

**Comment by willdoran** [comment]
Actually, yes it was, I stupidly changed a variable name without checking other occurrences of it. I've fixed it now though

**Comment by jshorland** [comment]
After importing and mapping, I click "finish import" and then "see imported posts". I've marked them all as archived, so I'm assuming that's why I can't see them (i tested by marking as both draft and published). But since I'm logged in as an admin, and imported them which makes them a collection... shouldn't I be able to see them in the list form? May need to be new issue?

Styling looks great though -- check out the vid
![screen capture on 2016-10-25 at 19-18-10](https://cloud.githubusercontent.com/assets/3224856/19711118/427be3a2-9ae8-11e6-9cde-6b9a31ef6db9.gif)

**Comment by jshorland** [comment]
@willdoran punting back to you

**Comment by willdoran** [comment]
@jshorland yuck, that's kind of difficult....hmmmm...I'll have to think it out. I'm not sure that archived posts should be hidden in collections...or should they?

**Comment by jshorland** [comment]
No they should not be hidden in collections when being viewed by admin

iPhone iTypo

**Comment by jshorland** [comment]
Summary from our slack discussion on logic:
- after importing a CSV file, the logged in user who imported the CSV (thus, this user has manage posts and bulk import privileges) should be able to see posts that were marked as "archived" in the CSV import process after clicking "go to my imported posts". Right now, after going to the imported posts, it's not entirely obvious that "archived" is default filtered, and since I just uploaded them, I may need to review them to correct any errors, etc. 
- If this isn't possible, we can ship with what we have now and log this as a new issue at P2.

**Comment by willdoran** [comment]
@jshorland to add confusion we have this issue #1462, so what @rjmackay suggest is that all collections should behave in this way and not hide archived, also we need to add the active filters back but I think that is a separate bug

**Comment by jshorland** [comment]
Oh great! Do you have a recommendation as to how best to proceed? The way I see it we have two options: go ahead and push what we have now and address #1462 separately, or address it now and THEN push.

**Comment by jshorland** [comment]
Ok based on slack message, seems like we should try to wrap this up this week by also addressing #1462 tomorrow, and dealing with share menu today. Sound good?

**Comment by willdoran** [comment]
perfect will do

**Comment by jshorland** [comment]
I'm going to close this. This issue is done and passes QA.

**Comment by willdoran** [comment]
Ok, great, I'll figure out if it's a bug a submit a fix for it!
