### ISSUE TITLE
Left side bar doesn't scroll

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#1464]
Steps to reproduce:
1. navigate to usaelectionmonitor.ushahidi.io
2. try to scroll the surveys on the left side bar

**Comment by brandonrosage** [comment]
I don't know why, but @middle8media [changed the CSS for this specific behavior](https://github.com/ushahidi/platform-pattern-library/commit/22a63a928eadd6f61b721bb10938468cc5390a97) on the mode context last month. I've revised this in `develop` and published to npm.

**Comment by middle8media** [comment]
I changed it to fix this issue - https://github.com/ushahidi/platform-pattern-library/issues/78

**Comment by brandonrosage** [comment]
Thanks, @seth. Unfortunately, the only solution that I can conjure for [ushahidi/platform-pattern-library#78](https://github.com/ushahidi/platform-pattern-library/issues/78) is to ensure `tooltip` elements are always left-aligned. Otherwise, as we've seen here, we break scrolling.

The element referenced in that issue is aligned to the left in the `metadata` pattern improvements.

**Comment by willdoran** [comment]
@brandonrosage do we need to bump the PL version in client to pick this up?

**Comment by brandonrosage** [comment]
Yes, sir.

**Comment by jshorland** [comment]
PASSES QA! very excited to see this fixed so quickly. ~24 hours from logging to pushing fix to production.
