### ISSUE TITLE
Intelligently log out user

### ISSUE THREAD

**Issue by willdoran** [ushahidi/platform#1497]
### Expected behaviour
- If I am working on a deployment I expect to remain logged in unless I am idle for a certain amount of time

### Actual behaviour
- User is always logged out when token expires

### Steps to reproduce the behaviour/error
- Login, wait for token expiration
- Click to change to a different view, signin is requested

Aha! Link: https://ushahiditeam.aha.io/features/PROD-655

**Comment by willdoran** [comment]
A significant issue with this is detecting "activity". While changing views and making requests to the server is a clear way to indicate activity. If I am editing a complex post for more than the token expiration limit BUT I have not saved to the server or otherwise made request the system should still consider me active.

**Comment by rjmackay** [comment]
First step on this might just be to use refresh tokens to extend the life of a session

**Comment by tuxpiper** [comment]
Related to #431 .

And bump!

**Comment by jshorland** [comment]
From #398:

Automatic Session Expiration creates a frustrating experience for the user. We should warn the user two minutes before their session is due to end and offer them the opportunity to renew the session.

First of all the Platform uses the League Oauth2 Server and it's worth reading about how OAuth tokens work to get a basic understanding.

In the client the following code is responsible for login/logout management

As a attempt, it would be good to warn the user that their session is going to expire - at this stage we just want to send them a notification that there session will expire in 2 minutes time.

For the client notifications are controlled by the Notify service.

For example to send the user a confirm notification I would do the following:

 Notify.confirm('notify.notification.session_expiration_confirm').then(function () {
    // Do something about it
 });
So to start with it's important to determine:

When the session will expire from the Access Token information
How to Notify the user of this 2 minutes before the expiration
How to test this, this tutorial describes the testing framework that Ushahidi uses on the frontend
Ushahidi tries to use Test Driven Development as much as possible, as such the first step for this will be to define a set of tests that will describe the functions of the new service.

The session expiration warning can become part of the Authentication Service or it can be created as it's own Service.

Later, we will want to allow the user to renew the session using Refresh Tokens if they wish to do so when warned about session expiration.

**Comment by rjmackay** [comment]
Related to #1645

**Comment by tuxpiper** [comment]
@caharding just a note that we received a bump about this from one of our clients (ref:           https://ushahidi.slack.com/archives/C88G57ND6/p1519907151000071 )

**Comment by tuxpiper** [comment]
Depends on #1612 and #431
