### ISSUE TITLE
Show field type when editing a field

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#1555]
### Expected behaviour
When i click to edit a specific field on a survey/task, i'd like to know what kind/type it is i.e radio button etc
The title for the modal where we edit fields should have the field type, taken from the `attribute` object (keys to use to determine this are  `type` and `input`)  in the frontend . 

<img width="536" alt="Screenshot 2019-07-10 at 16 19 35" src="https://user-images.githubusercontent.com/11681324/60976736-8c595a80-a32e-11e9-9453-9e4fe2981e2e.png">

### Actual behaviour
At the moment, all i get is this screen with no indication of the type of field it is

![imgur](http://i.imgur.com/McNhvT3.png)

### Steps to reproduce the behaviour/error
* log into your deployment
* Click on survey settings
* Select a field to edit

### Hints to solving this issue

Hint 1 💡 : The title of the modal is set here: https://github.com/ushahidi/platform-client/blob/develop/app/settings/surveys/survey-editor.directive.js#L475

Hint 2 💡 : The strings for edit/add title is found here:
https://github.com/ushahidi/platform-client/blob/develop/app/common/locales/en.json#L290
https://github.com/ushahidi/platform-client/blob/develop/app/common/locales/en.json#L291

Hint 3 💡 : You can translate strings instantly with `$translate.instant("translation-string", {translationValue: "value to add"});

Hint 4 💡 : Its a bit tricky to figure out what field a field is once the label has changed (editing already existing fields). But it can be figured out by comparing the input and type of the attribute, see the different alternatives here: https://github.com/ushahidi/platform-client/blob/develop/app/settings/surveys/attribute-create.directive.js#L35

Aha! Link: https://ushahiditeam.aha.io/features/PROD-34

**Comment by brandonrosage** [comment]
[I've staged some revisions to the "Edit/Create survey" views](https://github.com/ushahidi/platform/issues/1511#issuecomment-275778898) that improve the display of fields during configuration, specifically addressing this issue. The work is aimed to address the "private fields" issue. But does it fix this issue, too, @aoduor?

Reference: #1511

**Comment by rowasc** [comment]
This is better now because radio buttons and some other types are shown with the correct type of field in the edit field modal  but it's still confusing 
These are 3 different fields with different types and no indication of the type in both the field edit and field add  feature

<img width="778" alt="Screen Shot 2019-06-07 at 19 07 41" src="https://user-images.githubusercontent.com/2434401/59136036-b5fe1b00-8957-11e9-9596-9c392b6cae7c.png">
<img width="672" alt="Screen Shot 2019-06-07 at 19 07 52" src="https://user-images.githubusercontent.com/2434401/59136038-b5fe1b00-8957-11e9-9e53-05d838ccf97d.png">
<img width="558" alt="Screen Shot 2019-06-07 at 19 08 05" src="https://user-images.githubusercontent.com/2434401/59136039-b5fe1b00-8957-11e9-97fd-d7889ddfa531.png">

This one you could recognize because it renders the radios/checkbox
<img width="585" alt="Screen Shot 2019-06-07 at 19 07 48" src="https://user-images.githubusercontent.com/2434401/59136037-b5fe1b00-8957-11e9-9a1a-64d6d66ba3a7.png">

@Erioldoesdesign tagging you since this would bee a good first issue for other folks, but we'd need to know where to display the type

**Comment by Erioldoesdesign** [comment]
I would suggest the simplest thing to do is add in the kind of field in the title so 'Edit video field' 'Edit description field' 'Edit short text field'

<img width="536" alt="Screenshot 2019-07-10 at 16 19 35" src="https://user-images.githubusercontent.com/11681324/60976736-8c595a80-a32e-11e9-9453-9e4fe2981e2e.png">


buuuutt I think the label then needs to be smart enough to know what field is being edited so that's BE and FE changes?

**Comment by rowasc** [comment]
>I would suggest the simplest thing to do is add in the kind of field in the title so 'Edit video field' 'Edit description field' 'Edit short text field'

Yea I like this, this would be a super small task actually , just grabbing the field type from the attribute object. 

>buuuutt I think the label then needs to be smart enough to know what field is being edited so that's BE and FE changes?
Luckily, this already happens.  It'd only be frontend changes, the attributes that come through the API already have a field type (that's how we decide what we will render later in the data view and form submission ) .

**Comment by ari-hacks** [comment]
I'd like to try this out if it's still available?

**Comment by Erioldoesdesign** [comment]
@ari-hacks I think it's up for grabs! the assignee is a product manager so I can assign it to you (or you can if you like!) if it has the good first issue or hacktoberfest labels it's a community issue usually!

I don't think any recent changes have affected this behaviour but I'd suggest your first action would be going and double-checking the current functionality and seeing if the original ticket still describes the behaviour that needs changing. Does that make sense?)

**Comment by rowasc** [comment]
@ari-hacks assigned to you. Thanks ! LMK if you run into anything weird

**Comment by ari-hacks** [comment]
@rowasc great, thanks!

**Comment by ari-hacks** [comment]
@rowasc, I had to unassign here. A little low on bandwidth but thanks, hope to contribute at a later time! 🙂

**Comment by ypresion** [comment]
Hi @rowasc, would be happy to work on this issue. :) The only thing is, I can see that for now you set the title using a value from a .json file ("edit_field" : "Edit field"). To add the type of the field I'd either have to scrape it completely or change it to edit_field" : "Edit". What would be preferable?

**Comment by rowasc** [comment]
hey @ypresion thanks for contributing!
mmm I think I'd go for modifying "Edit field" to "Edit {fieldType} field" and then doing using the translate-values syntax in the tag attributes 
An example of this can be found in how we do the "nav.selected_items" translation in app/common/directives/list-toolbar.html which has its corresponding lang key in 'nav' > 'selected_items' around line 615 of the en.json file 
Does that sound okay?

**Comment by ypresion** [comment]
Sounds good, will start working on it! :)

**Comment by ypresion** [comment]
Hi @rowasc, I managed to get the API and client working, although I can't access the surveys. When I log in, no 'settings' option shows up. Read through documentation although didn't find any answers. Tried changing the URL path to '/settings' but it redirects me to the main map. Any idea why this might be happening?

**Comment by rowasc** [comment]
@ypresion hrm that's interesting, are you logged in with an admin user? You should see a sidebar with a settings icon (like a gear icon) 
Like this
![Screenshot from 2020-10-10 18-32-07](https://user-images.githubusercontent.com/2434401/95665475-f3178600-0b26-11eb-89bf-3a87f8d283ea.png)

Thanks!

**Comment by ypresion** [comment]
@rowasc, my mistake, I was using my personal account!
The PR is now raised and ready for a review, hopefully it looks alright :)

**Comment by Angamanga** [comment]
Closing this in favour of https://github.com/ushahidi/platform-client/pull/1630
