### ISSUE TITLE
Add save draft

### ISSUE THREAD

**Issue by willdoran** [ushahidi/platform#1584]
### Expected behaviour
- As I work on a post, it should automatically be saved as a draft every X amount of time

### Actual behaviour
- If I am logged out I loose my work

### Steps to reproduce the behaviour/error

Related https://github.com/ushahidi/platform/issues/2306

Aha! Link: https://ushahiditeam.aha.io/features/PROD-630

**Comment by caharding** [comment]
This issue was described on intercom where a researcher lost 2 hours of survey design about Measuring User Innovation in Nigeria's Small and Medium Entreprises .

**Comment by jshorland** [comment]
awesome -- putting a p1 on this. Frustrations run high and seems like a huge barrier to long term user engagement/adoption.

Work should *ideally* be saved as close to real-time as possible as changes are made. 

In addition to technical functionality, we will need:
1. design for notifying the user that their changes are being saved
2. design for notifying the user when changes failed to save
3. design for notifying the user of the last save time (last saved at 4:56pm EDT) with a "save now" option (which we already have functionality for, but good to review design of this with this functionality change of auto-saving as draft)
4. design for incomplete CSV import (allow user to pick up where they left off if they didn't successfully complete the CSV import)

This should apply to any changes made to:
1. Map settings
2. Users and roles
3. Adding/editing posts
4. Adding/editing surveys (which begs the question whether we need to add a functionality of draft/publishing of surveys similar to how we manage post status -- I think YES)
5. data source integration set up (e.g. if you enter an API key and you're logged out or something without finishing the integration)
6. CSV import - we should save as "incomplete imports" and the user can pick up where they left off

Auto saved drafts should be able to be "overwritten" by clicking the normal "save" button. 

Should also apply where appropriate to mobile (which it already does, but stating it explicitly here).

cc: @brandonrosage Am I forgetting anything here in this high level scope?

**Comment by brandonrosage** [comment]
I'm thrilled to see this prioritized.

Before I offer some design direction, let me contribute a few things to the scope:

### Draft vs. Auto-save
I think we're talking about two functionalities that (in some cases) work in concert.

- **Draft**: A distinction available only to individual posts.
- **Auto-save**: The process of saving a user's work on an entity (e.g. post, role, survey) without requiring them to deliberately do so.

_A small note on drafts_: I could see this implemented for posts in the backend as yet another "post status." But I don't think it should be exposed in the UI among the other post statuses. I think we need to treat it as a distinct thing. In other words, draft posts should not be something you could mix into a data set with published posts. They need to live outside traditional data sets -- not treated as proper posts.

### Messages about post drafts
When a user deliberately saves a post as a draft, we need to provide transient messages confirming the success of their action, as well as standard messages (in the appropriate views) to remind them that they have drafts (with a pathway to retrieve them).

### Where users retrieve drafts
For **posts** saved as drafts, I'm proposing they live in a user's private "Drafts" collection. Once they're submitted (e.g. published or put under review), they're removed from that collection. More on this in a bit.

Alright, let's get into how this might work.

## Auto-save feedback

When a user decides to create a new entity by clicking a button, they're taken to thats entity's "add" view. After they've changed the value of a field, that entity is automatically saved. Default values are therefore important (e.g. Untitled role) because they'll be used to save the new-but-unfinished entity.

The entities (and corresponding views) that we're proposing to utilize this functionality include:

- Add/edit response
- Add/edit survey
- Edit data source
- Add/edit user
- Add/edit role
- Add/edit category

Any time a user edits or creates one of these entities in its "edit" or "add" view, that view adopts a (new) "modal" layout.

To be clear, we're not talking about packaging these views in modal windows displayed on top of another layout. It's still a standalone view, but with a (new) layout pattern (`.layout-modal`) tailored to the focused act of editing or creating the thing at hand. It removes everything that's either distracting, unnecessary, or an action that could cause the user to unintentionally bail on their work. So there's no mode bar. And the mode context is restyled to pin to the top of _all_ screen sizes, stretching the full width, providing more space for a back button and...a status indicator for auto-saving.

![modal toolbar](https://cloud.githubusercontent.com/assets/1136279/24305139/f11e6d78-1089-11e7-8bf9-24182b9a13ed.png)

The status indicator is also a tooltip target. So mousing over (or tapping) it reveals a bug with more information.

A successful auto-save when editing an existing entity yields:

![save success, edit](https://cloud.githubusercontent.com/assets/1136279/24305440/f5a546f4-108a-11e7-8893-e9750d9d621b.png)

A successful auto-save when creating a new entity yields:

![save success, add](https://cloud.githubusercontent.com/assets/1136279/24308359/a9cdcb38-1095-11e7-84b2-66030be37c21.png)

A save in progress yields:

![save progress](https://cloud.githubusercontent.com/assets/1136279/24307786/7bf33876-1093-11e7-82f2-c642aa7b486e.png)

A failed auto-save yields:

![save fail](https://cloud.githubusercontent.com/assets/1136279/24307902/f500456a-1093-11e7-851a-ec3dda55fc77.png)

## Saving an unfinished entity

Entities that can be auto-saved are both revised and created via this functionality, even if the user hasn't finished their work. An untitled survey will be saved as "Untitled survey." A label that hasn't yet been assigned for use on any surveys will be saved such that no surveys can see it. So default values matter.

Surveys and labels, in particular, require carefully-considered default values because they're very visible once they're created. Surveys appear in the mode context in Map & Timeline modes, for example. Soon, labels will, too. So it's important that, with this auto-save functionality applied, these two entities adopt the following default values:

### New survey
- Name: _Untitled survey_
- Require responses be reviewed before they're published: _Unchecked_
- Hide author information: _Unchecked_
- Who can submit responses to this survey: _Nobody_
- Survey color: _Empty_

### New label
- Name: _Untitled label_
- This label is child to _nothing_
- Who can see this label: _Nobody_
- Which surveys use this label: _None checked_

If either of these entities are saved with their respective "Who can submit/see" controls set to "Nobody," they'll appear in their settings listing with a "lock" icon:

![listing](https://cloud.githubusercontent.com/assets/1136279/24360564/4d254e44-12cd-11e7-9097-32f2779c6903.png)

Entities for users, roles, and data sources take a similar approach to default values, with relatively smaller implications:

### New user
- Name: _Unnamed user_
- Role: _Member_

### New role
- Name: _Untitled role_
- Permissions: _None checked_

### Data sources
Turned off

In all of these cases, the `.layout-modal` pattern includes a back button that's pretty straightforward: It navigates you to the previous view. If work was auto-saved (even if unfinished), that entity will appear in the appropriate place (e.g. new 'Untitled role' appears in the Roles listing). If no work was auto-saved, it just goes back to the previous view with no changes to the deployment.

### New posts (survey responses)

Posts require an extra layer of logic and data modeling when auto-saving new entities. Like other auto-saving entities, they're created in the backend upon the first auto-save. But what posts must also consider is a "Draft" distinction.

For example, the back button in this case has some important logic applied when you click it. 

- If there are no auto-saved changes (e.g. your new response is still empty), it just goes back to the previous view.
- If there are auto-saved changes, a modal window appears asking if you want to save a draft:

![draft modal](https://cloud.githubusercontent.com/assets/1136279/24308421/e478baa4-1095-11e7-8332-e1142410e6f3.png)

Selecting "Discard" will delete the auto-saved post and return to the previous view. Selecting "Save draft" will save the post with the "draft" distinction, add it to your private "Drafts" collection, return to the previous view, and display a transient message:

![draft saved, message](https://cloud.githubusercontent.com/assets/1136279/24308539/4a8b7c96-1096-11e7-9584-2dc5face2c2e.png)

If you go to the "Drafts" collection, it will return a Timeline view for the collection with no toolbar, where you can delete or resume editing your response.

If, instead, you go to submit a new survey response, the "post add" view will include a standard message reminding you that you still have drafts waiting:

![submit, draft reminder](https://cloud.githubusercontent.com/assets/1136279/24360717/c5ee33a4-12cd-11e7-8719-d954230e2cca.png)

The only other top-level actions you can perform on the response while editing it are the most important and foundational ones: "Submit" and "Submit & add another." Either of those choices obviously remove the "draft" distinction, remove it from the "Drafts" collection, and promote it to the appropriate post status.

------

I've staged this work in the `f-auto_save` branch of the PL. I respect that there's a lot of backend implications here. So I'm happy to talk through the technical spec'ing process to get it right (and reasonable).

Bring on the questions and feedback!

**Comment by brandonrosage** [comment]
I also want to pay some lip service to "Import CSV," which @jshorland included in the scope, but I didn't mention in the previous roundup.

That's because, first and foremost, the UX for in-progress and problematic imports was [largely addressed in its most recent implementation](https://github.com/ushahidi/platform/issues/1448#issuecomment-256472844). But I awnt to refine and better articulate it below. 

Secondarily, I don't think auto-saving or a "draft" distinction is appropriate here because it doesn't concern the creation or editing of an entity -- it's the process of automatically creating multiple posts.

Okay, here's the recommended solution:

# Starting a new CSV import

By navigating to "Import," the user sees a listing of supported data we can import -- in this case, just CSV:

![import](https://cloud.githubusercontent.com/assets/1136279/24367681/2c4066c6-12e3-11e7-8681-f4c1e98f82f9.png)

By selecting "CSV," they see a single form sheet (using `.layout-d`) with a "stepper" to indicate that it's a guided two-step process:

![import csv 1](https://cloud.githubusercontent.com/assets/1136279/24367829/aed29028-12e3-11e7-8ce5-17ce1213902f.png)

By choosing a CSV file and selecting a survey, they can select "Continue," at which point they'll see "Step 2," which includes controls for mapping CSV columns to survey fields (among other things).

![import csv 2](https://cloud.githubusercontent.com/assets/1136279/24367878/e130924a-12e3-11e7-9633-6d833039c41b.png)

By advancing passed Step 1, the 'back' button will now interrupt a click's return to the previous screen (Settings > Import) with a modal window:

![import csv abandon](https://cloud.githubusercontent.com/assets/1136279/24368483/3176029c-12e6-11e7-843f-7c10f84336d1.png)

Selecting "Abandon import" would remove all records while returning to Settings > Import. Selecting "Finish import" would close the modal and resume the underlying process.

When they've provided valid data for Step 2, the "Finish import" button is enabled. 

## When an import is in progress

When the user selects "Finish import" from Step 2, the form sheet + stepper is replaced with a form sheet with content about its progress:

![import csv progress](https://cloud.githubusercontent.com/assets/1136279/24369267/0ca06ff4-12e9-11e7-9e5a-2a5c3970373c.png)

At this point, the 'back' button would no longer interrupt navigating to the previous screen. Selecting "Import another CSV file" would start a fresh "Import CSV" flow at Step 1.

Active CSV imports use the `.layout-d` view that's used through the whole flow as the home for displaying progress and summary information. So if the user stays at this view, it'll continue to keep them updated.

If they leave, only the "Import" views (including Settings > Import) will offer a persistent update on progress:

![import progress message](https://cloud.githubusercontent.com/assets/1136279/24369240/f2e2c468-12e8-11e7-8e31-41190c3e2ebf.png)

This way, if (for example) they visit their Timeline and are curious about the import progress, they can return to "Import" and find a progress message pinned to the view.

## When an import is finished & successful

If an active CSV import successfully finishes and the deployer is _anywhere else_ in the deployment, a transient message will appear:

![import CSV finished message](https://cloud.githubusercontent.com/assets/1136279/24369467/b75246f2-12e9-11e7-8144-fd618292f580.png)

If an active CSV import successfully finishes while the user is on that import's summary view, it will update accordingly:

![import CSV finished](https://cloud.githubusercontent.com/assets/1136279/24369803/c8b6ebcc-12ea-11e7-981e-a7a101a65e4b.png)

## When an import is finished & problems are reported

Just like successful imports, messaging for completed-with-problems imports occurs using the same logic and conventions. But, obviously, the content must be appropriate.

If the deployer is on that import's summary view:

![import CSV problems](https://cloud.githubusercontent.com/assets/1136279/24369919/35269988-12eb-11e7-8ddc-21b7f5c38b64.png)

In this form sheet, if they choose to "Keep" the successfully imported records, the sheet reveals a second button:

![import CSV problems, keep](https://cloud.githubusercontent.com/assets/1136279/24370203/2cb13cda-12ec-11e7-9be5-d3cb16004356.png)

If the deployer is on any of the "Import" screens when this update occurs, they'll see a standard (persistent) message:

![import CSV problems message](https://cloud.githubusercontent.com/assets/1136279/24370090/bdba1dc4-12eb-11e7-9e32-8d9484d5bbb1.png)

The message's button would navigate them to the import's aforementioned summary view. If the deployer is _anywhere else_ in the deployment, they'll see the same message, but transient.

----

To wrap, it's worth noting that the same UX that exists today for storing and reviewing imported data would continue: Successfully imported records are added to a collection named with the date of the import, where links to "view imported records" navigate the user to.

I hope this refines, improves, and clarifies things.

**Comment by jshorland** [comment]
"Track changes", or, seeing past revisions on posts should be done after laravel

**Comment by jshorland** [comment]
to do: @jshorland create new issue about track changes that doesn't force this to be dependent on replacing kohana.

**Comment by rjmackay** [comment]
@jshorland @justinscherer 

- Is this 'draft' different from current 'under review'? Is it visible to other users?
- Do we validate the draft at all?
- What if this auto-saves changes that you later want to cancel?
