### ISSUE TITLE
Add warning about loss of data when deleting surveys/fields

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#1630]
### Expected behaviour
I expect a distinct warning notifying me that if i proceed with deletion of a survey, i will loose all my data associated with that survey

(I tested this out and yes, when you delete a survey, you loose all your posts)

### Actual behaviour
I just get the "Are you sure you want to proceed" pop up box, which isn't enough of a disclaimer methinks 

### Steps to reproduce the behaviour/error
* Log into qa.ushahididev.com
* Create a new testing survey
* Submit a post to the survey
* Save the post ID
* Delete the testing survey
* Attempt to access the post with the postID you saved

**Comment by Angamanga** [comment]
This sounds similar to https://github.com/ushahidi/platform/issues/1528 that was fixed in https://github.com/ushahidi/platform-client/pull/548. It was for some reason closed and not labeled for testing, I just added it back to correct column...

**Comment by aoduor** [comment]
Okidoks. I'll close this one.

**Comment by Angamanga** [comment]
Actually, it sounds slightly different so I'll keep it open...

**Comment by rjmackay** [comment]
@rowasc I'm not 100% what the current warning says right now. But we should swap it out for something a bit clearer about the potential for data loss.
I can double check the language when you're ready.

**Comment by rowasc** [comment]
@rjmackay ok, so at first glance, this looks like a text change and I'm sending the possible new texts here, but I think we could also have a form asking for more explicit confirmation (like when you try to remove a repo)  before we let them do something with so much potential data loss. 
### rough example here
This is for fields, but something similar would work for surveys as well. 
Asking for field and survey name because what If I am in the wrong survey? maybe instead we could show the survey name in the title of the modal. I don't know... 

**Disabled form:** 
<img width="476" alt="screen shot 2017-08-30 at 11 17 13 pm" src="https://user-images.githubusercontent.com/2434401/29903276-73c3c062-8dd9-11e7-8462-a265ba13e026.png">
**User confirms, submit button is enabled**
<img width="501" alt="screen shot 2017-08-30 at 11 17 41 pm" src="https://user-images.githubusercontent.com/2434401/29903275-738cb3ba-8dd9-11e7-83ab-56e1f6328405.png">





# Sending some examples for the new warnings/text. 

## Current behavior: 
Deleting a survey - modal alert

<img width="515" alt="screen shot 2017-08-30 at 10 49 28 pm" src="https://user-images.githubusercontent.com/2434401/29902615-861b3d52-8dd5-11e7-9736-8b46556614d6.png">

Deleting a field - modal alert
<img width="489" alt="screen shot 2017-08-30 at 10 51 37 pm" src="https://user-images.githubusercontent.com/2434401/29902660-da7e3106-8dd5-11e7-81c5-a103b9d84529.png">

## Suggested text: 
 Deleting a field - NEW modal alert text.
`This action cannot be undone. Deleting this field will remove its data from all existing posts.`
<img width="460" alt="screen shot 2017-08-30 at 11 01 21 pm" src="https://user-images.githubusercontent.com/2434401/29902879-2ae8ed60-8dd7-11e7-8714-ef86df3677a0.png">

 Deleting a survey - NEW modal alert text.
 
`This action cannot be undone. Deleting this survey will remove all of its data, including posts.`
or
`This action cannot be undone. This will also delete all fields and data for this survey.`

<img width="480" alt="screen shot 2017-08-30 at 10 58 48 pm" src="https://user-images.githubusercontent.com/2434401/29902814-cfee9af4-8dd6-11e7-8f4f-91a93fe69336.png">

**Comment by rowasc** [comment]
@jshorland What do you think?

**Comment by jshorland** [comment]
@rowasc the text looks great -- we should definitely move forward with that copy. and I like the idea of adding an extra manual step to delete. Two questions come up for me that I think @justinscherer can help answer in terms of UX:
- does the implementation of "undo" for all actions, which is slotted to be done before end of year, diminish the need for this extra step?
- Should we only show this when there's a substantial amount of data being affected? So if there's no data, or minimal unpublished data, it probably doesn't make sense to make the user go through that extra step.

**Comment by rowasc** [comment]
@jshorland ok Thanks! 

Also: 
- I noticed that **tasks** can also be deleted and they have the generic alert too. Should I add a similar warning to them?  ie:: "This action cannot be undone. Deleting this task will remove all of its fields, and any data in them."

- I had sent two options for the alert in the survey. Used  "This action cannot be undone. Deleting this survey will remove all of its data, including posts"  for now but just let me know if you prefer the other option.

**Comment by justinscherer** [comment]
@jshorland :
>does the implementation of "undo" for all actions, which is slotted to be done before end of year, diminish the need for this extra step?

Both undo and "are you sure" are preferable if we're talking about data loss. You want to both prevent errors and help users recover from them when they happen, as well as provide undo options. So both get my vote. 

>Should we only show this when there's a substantial amount of data being affected? So if there's no data, or minimal unpublished data, it probably doesn't make sense to make the user go through that extra step.

Always do it. That would involve a bunch of complex business logic that we're not going to surface to our users. It would be opaque rules. Consistency is also a good thing.

**Comment by rowasc** [comment]
Moving forward with this as per Justin's comment. I'll leave a comment when I have something usable or more questions

**Comment by rowasc** [comment]
UPDATE: I checked with Justin and the confirmation from his was to do only the copy changes, not the additional input check. 
So I'll just add the warning for tasks and then we are ready for PR/merging
