### ISSUE TITLE
Change the name of the default survey to "Untitled survey"

### ISSUE THREAD

**Issue by brandonrosage** [ushahidi/platform#1647]
**User story**: I want to know what I can change about the data in my deployment. I want to be able to easily figure out what's editable and what's fixed.

To keep in step with our implementation of [first-time deployers' on-boarding experience](https://github.com/ushahidi/platform/issues/1396#issuecomment-277732730) -- and to encourage the customization of surveys -- I'd propose we change the name of the out-of-the-box survey from "Basic post" to "Untitled survey."

"Basic post" is not useful or descriptive. Worse, though, is that it doesn't beg to be changed, or imply that it can be. "Untitled survey" accomplishes the following:

- It describes what it is: A survey; not a post
- It implies that it needs to be titled.
- It uses the same convention for suggesting an edit -- "Untitled" -- as Google Drive files (e.g. Docs, Sheets, Forms) do for their document titles & names.

Aha! Link: https://ushahiditeam.aha.io/features/PROD-623

**Comment by muchirijane** [comment]
Hey @Angamanga , Could I please work on this issue for the outreachy contribution.

**Comment by Angamanga** [comment]
@muchirijane This needs triage so it is not open for the community yet. Please check out this link if you can find something else you are interested in: https://github.com/ushahidi/platform/issues?q=is%3Aopen+is%3Aissue+label%3A%22Community+Task%22 We are adding more issues continuously but due to the large interest in Outreachy this year we are lagging behind. Please bear with us :)

**Comment by muchirijane** [comment]
Noted. Thank you.

**Comment by rowasc** [comment]
I'm officially entering this one into "Community task" status @muchirijane assigning it to you so you can work on it. Keep in mind this will involve not just the change in the code, but a change in user *docs* as well which @CeciliaHinga may need to guide you through

**Comment by muchirijane** [comment]
Hey @rowasc, Thank you. I will work on it. Yes I would absolutely appreciate some guidance.

**Comment by rowasc** [comment]
So this will require changes in the API code, not the frontend. Would that be something you are still interested in? If so, you'll need to modify the migrations/20150904021011_add_default_post_type.php so that it reads "Untitled survey" instead of "Basic Post". 
Note that this will *only* affect new deployments, so to test it, you essentially need to "re create" the database through the migrations to ensure they work as expected. I can help/guide you but let me know if you don't want to do backend changes and I'll un-assign . 

Meta note to everyone: while yes typically you wouldn't want to modify a migration, in this case this migration *specifically* runs for deployment creation and I do not feel we should ***add*** a migration because it would affect existing users of the platform (who may be perfectly happy with "Basic post" or would be confused if we change it in their existing deployments)

**Comment by muchirijane** [comment]
Hey @rowasc, I am still interested. I have seen the code in the file thank you. I would appreciate your help in the testing process of the code. How do I get started with "re-creating" the database?

**Comment by rowasc** [comment]
Hi @muchirijane 
I'm not sure if I already answered by email, but just in case: you do so by dropping the database locally, then re-running the migrations
Basically drop the database locally (you can do this through the mysql cli, inside vagrant) then run the migrations again with `composer migrate` .
Thanks
