### ISSUE TITLE
Facebook embed

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#1658]
- as a platform administrator, i want to be able to embed my map, forms, and individual posts within a facebook group/organization/page (I think facebook just calls them Pages now?)

**Comment by jshorland** [comment]
@tuxpiper can you look into this and give me a rough estimate of how much work would be involved to do this for 1 client?

**Comment by tuxpiper** [comment]
@jshorland : the most interesting question about this one is, what should appear as the image in the facebook post? If we would like to have specific images that are tailored to the shared content, that will be a significant part of the estimate.

Facebook will most probably not be able to generate the image automatically, because of the very dynamic nature of our frontend code (same reason why SEO is hard for us).

So, if we would like to have those images, we should decide (case by case) what they should be and then write code to pull the images or generate them.

The other part should be creating specific API routes to provide facebook with the proper oEmbed metatags , which looks more straightforward.
