### ISSUE TITLE
Images on posts rotated sideways

### ISSUE THREAD

**Issue by rjmackay** [ushahidi/platform#1675]
### Expected behaviour
Image should be shown without rotation

### Actual behaviour
Image is show rotated 90 degrees. For example

https://scattonetto.ushahidi.io/posts/238
But the raw image looks fine: https://74ddb495e3f187ded630-0b4c691ea14dad11384ab079da46af4f.ssl.cf2.rackcdn.com/scattonetto.api.ushahidi.io/5/8/58e74cdd65911-20170406_112123.jpg

https://scattonetto.ushahidi.io/posts/241
But again the image file seems right:
https://74ddb495e3f187ded630-0b4c691ea14dad11384ab079da46af4f.ssl.cf2.rackcdn.com/scattonetto.api.ushahidi.io/5/8/58e7511f1f1b1-20170402_103952.jpg

Refs https://app.intercom.io/a/apps/hl5rfiga/respond/inbox/unassigned/conversations/9191710659

Aha! Link: https://ushahiditeam.aha.io/features/PROD-615

**Comment by niccolov** [comment]
We are going to correct the post manually, but it would be nice to have it working or at least have a change to correct it by the backend (for example a buttom like replace image to rotate image would be nice).

**Comment by niccolov** [comment]
Lately it didn't happened again... did you work on it?
Can I correct the old images?

**Comment by niccolov** [comment]
@aoduor @rjmackay Unlikely it happend again a couple of times... we have correct them manually... Are you working on this bug? Can we correct the new upload or we have to leave uncorrect?

The 27 of April we will launch the project to the public... so we would like to know how to manage this cases. Thanks,

Niccolò

**Comment by rjmackay** [comment]
@niccolov No I haven't had a chance to work on this. My suspicion is that the images were originally rotated sideways, but with a camera that saved EXIF data about orientation. Chrome probably honors this when viewing an image directly, but within a webpage it doesn't.
The simple work around is to edit the images locally and ensure they're really rotated the right way.

The possible fix in the app is to add css `image-orientation: from-image` to our images.

**Comment by niccolov** [comment]
Hi @rjmackay Actually I've corrected the 2 images that where suggested on the task... the next one wrong I will let them rotated. 

The problem is the following: on the post on ushahidi the image appears rotated, but If I donwload it locally and I open it on my computers it appears correct!!!! In fact what I do is to rotate once left again once right to bring it backwards and I save the picture. Then I replace the image inside the post.

Why locally the image seems correct and not on Ushaidi? I think the faster solution could be to add, near replace image, a bottom like rotate left o right. I would be great to have it on the public form, but the best thing should be to have it when you modify the post.

Do you think is possible?
