### ISSUE TITLE
Omit everything except email body from email data source

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#1684]
User on intercom complained of email's being pulled into his deployment containing header information. See below

"Delivered-To: ********
Received: by 10.37.51.84 with SMTP id z81csp2829026ybz; Fri, 31 Mar 2017
02:29:55 -0700 (PDT)
X-Received: by 10.223.142.18 with SMTP id n18mr1958152wrb.188.1490952595088;
Fri, 31 Mar 2017 02:29:55 -0700 (PDT)
Return-Path: 
Received: from mail-wr0-x234.google.com (mail-wr0-x234.google.com.
[2a00:1450:400c:c0c::234]) by mx.google.com with ESMTPS id
185si2632983wmp.101.2017.03.31.02.29.54 for
(version=TLS1_2
cipher"

Refs https://app.intercom.io/a/apps/hl5rfiga/respond/inbox/angela@ushahidi.com/conversations/9053595529

**Comment by willdoran** [comment]
@aoduor I'm having trouble reproducing this, my concern is that the issue is the content of the email. Above looks like email headers, we don't pull in the headers at all we just grab the body of the email. I think what might be happening is that either the inbound message is including the headers in the body or there is an issue with retrieving them.

I've asked the user for further feedback. I've tested with gmaill, yahoo and riseup address and wasn't able to reproduce. So I'm going to put this in waiting for feedback.

**Comment by rjmackay** [comment]
If we can reproduce, then this should be closed.
