### ISSUE TITLE
1st iteration of comrades deployment

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#1686]
@shadrock @will let's clearly scope out what's required for this so we can appropriate schedule work to deliver by May 15!

**Comment by Shadrock** [comment]
The grant stipulates that the first version of the COMRADES platform will: 

> meet  the  general  requirements  from  WP2 [fieldwork from Nepal],  and  will  include  the  multilingual  content  processing  tools  from  WP3 [at this point, YODIE],  and  an  early  version  of  the  event  identification  and clustering methods from WP4 [CREES].

Because the requirements doc from WP2 is not yet finished, but the integration work @willdoran is doing moved so quickly we're on track to have: 

- YODIE: functionality as it is now is fine for this version.
- CREES: I'd like to see this at the same level of YODIE for the first pass. Better UI/UX can come later.

Additionally, there are 3 pretty clear take aways from WP2 that I think we are already moving on despite the lateness of requirements:

1. Privacy at the field level (is this done?)
2. Mobile version
3. Both #1694 (new data sources) and #1693 (feedback loops / alerts) respond to issues I saw in the field. 

Since 1 & 2 are in progress I would really, really like to see if there's anyway to make some progress on either new data source or feedback loops by delivery time. I would be look for about the same level of functionality that YODIE is at: I'm more concerned with just ensuring that it's possible and that we can build the "connecting pieces" to make it work. Refining UI/UX and workflows could come later. That would put us slightly ahead of the grant requirements, and make me feel much, much better about our EU performance evaluation in July. It would also give us some solid ground to test with in July. 

What do you think @jshorland ? I'm going to check in with Harith to confirm that these expectations will meet requirements from his perspective, but right now I feel like this would do it.

**Comment by Shadrock** [comment]
@jshorland @willdoran just confirmed the above with Harith. Would love to think about how to tackle that number 3. Anyways, they are feeling really good about where we're at! And we are AHEAD OF SCHEDULE! Joyfully so.

**Comment by willdoran** [comment]
@Shadrock @jshorland 
Taking these and converting them into items:

- [x] Privacy at the field level 
- [ ] Mobile version
  - [ ] What is the requirement for this? Is it met by our existing mobile app
- [ ] UX changes review, I would suggest that we do an initial iteration of this while we still have Brandon, this would cover the following:
  - [ ] Display accuracy for Yodie/Crees results
  - [ ] Crees Categories vs User set categories
  - [ ] User validation/verification, I believe this could be covered by a task with questions/checkboxes
- [ ] #1693 - I think adding notifications for non-users requires the following:
  - [ ] Dialog to collect user info
  - [ ] Email verification
  - [ ] Unsubscribe from notifications
- [ ] #1694 - Facebook integration
  - [ ] [Reading](https://developers.facebook.com/docs/graph-api/reference/v2.9/group/feed)
  - [ ] [Publishing](https://developers.facebook.com/docs/graph-api/reference/v2.9/group/feed#publish)
  - [ ] [Register Ushahidi Facebook app](https://developers.facebook.com/docs/apps/register), we may need a COMRADES specific one as opposed to Ushahidi - OSS users would have to setup their own
  - [ ] Create FB datasource client
    - [ ] Include authentication by user and storing of access tokens
  - [ ] Create FB datasource api
- [ ] #1693 - Publish data to 3rd parties
  - [ ] I believe this is primarily a matter of data formatting for export, we can define specific output formats along with CSV that meet the requirements for specific 3rd parties
  - [ ] If the goal is to publish directly from the Platform to the 3rd party then it would be necessary to define them as output for the export, both of the mentioned groups provide means for orgs to contribute data, we would have to define each as an end point for the data export. This could reuse code from both the current data exporter and the webhooks but it is still at least 2- 2.5 weeks work.

**Comment by Shadrock** [comment]
Looks great @willdoran. Our current mobile app does check the box (and so I have checked the box: super meta). It seems to me that the UX review is the most pressing concern. @jshorland what's the best way to move forward on this: I'd like to take advantage of what little time we have Brandon. I need a bit more time to mull over the other checkboxes...

**Comment by jshorland** [comment]
@shadrock Ok — can we talk about this next Monday morning at 8am pacfic? It’s my regularly scheduled catch up time with brandon and a good chance for you, he and I to do a full UX review.

**Comment by jshorland** [comment]
are we good to close this? we know what we have to deliver now?

**Comment by Shadrock** [comment]
Yeah, we're good on this version. I'll get together with you after the review to work out the delivery for the next version.
