### ISSUE TITLE
Change wording on "Embed Video" survey field

### ISSUE THREAD

**Issue by natmanning** [ushahidi/platform#1703]
### Expected behaviour
When I add the "Embed video" field to a survey it should read, "Embed Video: Embed Youtube or Vimeo videos in the post, or upload videos directly from the mobile app."

### Actual behaviour
When I add the "Embed video" field to a survey it reads, "Embed Video: Allows Youtube or Vimeo videos to be embed in the post."

We had a user who thought that the mobile app couldn't take direct videos and then upload them directly due to this language, and that it could only work through linking to Youtube or Vimeo.

Also was in the passive voice.

ALSO:
HyperLink "upload videos directly from the mobile app" in the above directly to the mobile app download.

### Steps to reproduce the behaviour/error

create a survey

**Comment by Erioldoesdesign** [comment]
You actually can't upload a video via the browser version:
![Screen Shot 2018-10-08 at 22.00.58.png](https://images.zenhubusercontent.com/5a6a0d5a4b5806bc2bc44bb9/43fe1a1c-83a1-4503-883f-bf62372c9f73)

So the mobile app needs to have separate wording saying you can upload a video

This ticket needs changing so when you add the field it reads: 
Embed video
"Allows Youtube or Vimeo videos to be embed in the post by using a URL/Link"

**Comment by rowasc** [comment]
Closing  as the mobile app no longer allowed uploading video in new versions. I checked in my phone and I only have a field that says "Enter a YouTube or Vimeo video url" . 
This (as far as I know ) was changed due to issues with Vimeo last year when doing security audits. 
https://github.com/ushahidi/platform/issues/3248#issuecomment-417475212 relevant comment confirming this is no longer available.
