### ISSUE TITLE
Cannot change password of default user ("admin")

### ISSUE THREAD

**Issue by tuxpiper** [ushahidi/platform#1714]
### Expected behaviour
OSS deployers should be able to change the password of the default user.

### Actual behaviour
In the user update screen, the username "admin" is rejected as invalid, and thus, no modifications are possible.

This is related to #955

**Comment by rjmackay** [comment]
Refs: https://github.com/ushahidi/platform/issues/928

**Comment by rjmackay** [comment]
I'd suggest we prompt users to set admin email and password on first login... that should resolve this. They shouldn't be able to continue with 'admin' as an email.

**Comment by rowasc** [comment]
I have been thinking about this. A few notes/questions: 

- Can the “first login” mean “you still have ‘admin’ as your username so I will bug you/block you from using the client _until you change your username and password_",  instead? I think that's a sensible approach because it also forces pre-existing users to fix their user credentials and we have less risk of `something` going wrong and the user missing the prompt. 
- we need a solution for platform-API consumers that don't use the platform-client. Most likely a CLI migration. I'm still thinking about the best way to do this part. I think an interactive "migration" linked from the composer scripts would be a good solution since it would prompt you on the initial setup as well, but I still need to think about it.
- do we need to trigger some kind of email confirmation?

**Comment by rowasc** [comment]
Frontend - Implementation
- [UI] When a user logs in with the `admin` email: 
    - open "Account settings"
    - Block the cancel button
    - show a warning text that they `must` change their email and password to continue using the platform.
     - Enable Save & Close once the user has changed the email. 


@jshorland @justinscherer any concerns? 
I'll get started because it's a P0 issue and I want to make sure I don't run into anything that can cause delays, but I'd like to make sure this is the right approach.
 
Backend - CLI implementation
- [Initial setup] Add a script to composer install that prompts the deployer for a new username and password

**Comment by rowasc** [comment]
@jshorland @justinscherer any concerns? 
I'll get started while I wait on more details/feedback because it's a P0 issue and I want to make sure I don't run into anything that can cause delays, but I'd like to make sure this is the right approach.

**Comment by rjmackay** [comment]
> Can the “first login” mean “you still have ‘admin’ as your username so I will bug you/block you from using the client until you change your username and password", instead?

Yup. That works for me, and because we already remove the `admin` user and replace it on .io deployments it neatly doesn't break those.

> we need a solution for platform-API consumers that don't use the platform-client. 

I'm not sure we need to worry about this TBH. They can continue with the existing admin/admin combo and won't hit any issues unless they try to update the user/password via the API.

> do we need to trigger some kind of email confirmation?

Not yet, its a backlogged task thats been ignored for a while :(

**Comment by rowasc** [comment]
@rjmackay ok great. Then I'll try to wrap it up today, it's all front end.

**Comment by rowasc** [comment]
@jshorland 
This is what I landed at. 

- When I log in with my admin user that still has an invalid "admin" email, I see a modal where I can change the email and password.
    - There is no close button in the modal
    - There is no cancel button in the modal
    - If I reload the page, I am shown the modal again. [TODO]
    - I cannot continue using the platform until I change the email. [TODO]

Does this look like the correct user flow to you? I think it's important that we bug the user a bit to change the email and password, but I don't know how far we want to go =)   We might want to show the cancel button, and only send them to this modal once per each login.  

@rjmackay FYI I'm waiting on this feedback before I continue with the ticket,  because this question can/will change the approach for calling the modal .

**Comment by jshorland** [comment]
@rowasc @rjmackay I think forcing them to change it is the only option. According to @rjmackay, if they DON'T change it, we can't send them notifications (although they might need to do other set up on that anyway), they can't change their password without setting a valid email, and they get a confusing login screen that asks for email (not username)

**Comment by rowasc** [comment]
great. Doing that now ! Thanks @jshorland.
