### ISSUE TITLE
Mobile App Configuration For Deployment's API Location

### ISSUE THREAD

**Issue by willdoran** [ushahidi/platform#1773]
### Expected behaviour
- Variables are consistently and clearly named for config.json
- Suggested naming:
  - multisite_api_domain
  - api_url <- not sure about this perhaps we should 
- Need more clarity of differentiation between domain/url expectations of mobile.

### Actual behaviour
- There is no clarity in terms of the purpose for each backend pointer var. Currently, there are two:
  - backend_domain, ostensibly the domain of the api, in reality it is the domain of the api for *multisite* setup
  - backend_url, ostensibly the fully qualified url of the api, in reality it is the fully qualified url of the single site domain

### Steps to reproduce the behaviour/error

Aha! Link: https://ushahiditeam.aha.io/features/PROD-599

**Comment by ClearLakeHABMap** [comment]
Does this affect the ability to link to systems like SMSSync, the Ushahidi App, and other contributing sites?

**Comment by ClearLakeHABMap** [comment]
I am finding that our deployment backend address is not linking to the SMSSync app and will not work with the newest version of the ushahidi app. The description stated that it would work with privately hosted maps, but I am unable to get it to link to the map. Is this issue related? It appears to be based on the URL issues.

**Comment by jshorland** [comment]
cc: @dalezak are you able to shed any light on what may be the issue here?

**Comment by ClearLakeHABMap** [comment]
@jshorland It is my understanding that this may have been an issue resolved in the latest Ushahidi update. We are about to see if that will work. Can you confirm this is the case?

**Comment by dalezak** [comment]
Ideally, the `config.json` should _only_ have `backend_url` which points to the absolute URL of the API, and `backend_domain` wouldn't be used at all.

However there was an issue with **.IO** build process, not knowing what the subdomain is for the final deployment. I don't know the exact reason why the build script doesn't know this, but `backend_domain` was only created as a workaround for **.IO** deployments because of this limitation.

For example, the deployment https://dale.ushahidi.io should include the `backend_url` value of https://dale.api.ushahidi.io, but since it can't it returns `"backend_domain": "api.ushahidi.io"` and then I use some complicated logic to extract the subdomain from https://dale.ushahidi.io and then prepend it to the `backend_domain`.

Here is what https://dale.ushahidi.io/config.json currently returns.

```
{
"client_id": "ushahidiui",
"client_secret": "35e7f0bca957836d05ca0492211b0ac707671261",
"backend_domain": "api.ushahidi.io",
"google_analytics_id": "UA-12063676-1",
"intercom_app_id": "hl5rfiga",
"mapbox_api_key": "pk.eyJ1IjoidXNoYWhpZGkiLCJhIjoiY2lxaXRrbmF5MDdxNmZubmUyN2p6bms5biJ9.o7pmKDIN1EtwMBp1VIzITQ",
"raven_url": "https://198dd82fe71b41d587ebc870121154a2@app.getsentry.com/88045"
}
```
