### ISSUE TITLE
Error when trying to save survey

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#1809]
I *think* it has to do with renaming the survey and adding a description? unclear. But here's the error I get:

You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '))' at line 1 [ INSERT INTO `forms` (`name`, `description`, `type`, `disabled`, `created`, `hide_author`, `require_approval`, `everyone_can_create`, `tags`) VALUES ('Critical injuries', 'Injuries that need urgent medical attention', 'report', '0', 1497563385, '0', '1', '1', ()) ]

And I'm unable to save my survey. 

This is for a duplicate of my "basic post" survey in https://crisisdemo.ushahidi.io/

I duplicated basic post, tried to edit, but was never able to save because of that error.

**Comment by ryanchristo** [comment]
It looks like this is happening for any attempt to duplicate a survey and the issue is occurring when attempting to duplicate the "tags" property associated with the original survey.

There might be a better solution but a quick fix would be to prevent this attempt to duplicate "tags" property associated with the survey by clearing the field along with "id", "created", "updated", "url", and "can_create" before saving the new duplicated survey:

`delete $scope.survey.id;
delete $scope.survey.created;
delete $scope.survey.updated;
delete $scope.survey.url;
delete $scope.survey.can_create;
delete $scope.survey.tags;`

This fixes the issue and allows the user to save a new duplicate survey. The new duplicate survey when saved does not show the fields initially after save but they show up after refreshing the page (which looks like a separate issue that also occurs when creating a new survey from scratch). If the survey has a categories field, the categories field and whatever categories selected are copied over.

I'm new to the project and still finding my way around but I thought I might share my findings so far.

**Comment by jshorland** [comment]
We <3 devs who share!

Thanks, ryan. Our team is in the midst of traveling to our team retreat so we will be a bit delayed but will respond soon!

**Comment by rjmackay** [comment]
@jshorland just need to test this on staging now.
