### ISSUE TITLE
User registration must include email and phone number

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#1819]
Require phone number when they register, admin needs to be able to see phone number to follow up via phone if necessary. Login/Registration page needs to pop up first, option to navigate to deployment without logging in or registering. Account will be automatically signed up for notifications on status changes on posts they submit.

**Comment by rjmackay** [comment]
Client comments about login flow

> "what we need, is the normal sign up we have using email address and password. Besides that, users can anonymously report an incident, yet, there will be a mandatory field for email address and this field will retrieve the stored email for registered users and will ask the anonymous user to enter it so admin can verify the incident and communicate with the reporter"

**Comment by Celestine22** [comment]
IMPORTANT: Email field for registered users will be automatically pulled in when they need to submit a new post! Phone number must not be mandatory!
Non registered users who don't want to log in via default platform way, but want to quickly submit a post will be required to submit an email address at the minimum!

**Comment by willdoran** [comment]
@rjmackay @Celestine22 Is this still the case?
**"Email field for registered users on the survey will be automatically filled in when they need to submit a new post!"**

I'm not sure this was in the original spec

**Comment by Celestine22** [comment]
@willdoran this is correct! Let's huddle on a call later today so you can be on the clear about this spec!

**Comment by jshorland** [comment]
@willdoran is going to check with @rjmackay on the best way to do this.

**Comment by willdoran** [comment]
@rjmackay: 

My understanding of the requirement that the Email field of the Survey be prepopulated for registered users is that we will have to "assume" presence of this field in the Post Editor.

- Retrieving the current user's email is straightforward

There are lots of ways to do this 2 choices are:

1. Attach a "special" field like title/description to the Post model called email that is always present and immutable
2. Add a simple function to the Post Editor called giscon_kuwait_prepopulatePostEmailField(), which checks for presence of the "Email" field on the survey - if they change the survey this breaks completely

Do you have any other ideas?

I would like all custom code functions to be prefaced with "giscon_kuwait_" to make them easy to remove and ideally they would live in their own services/classes.

**Comment by willdoran** [comment]
Requirements:

1. User registration page includes Phone Number
2. Login/Registration Modal appears on page load
3. Visitors can choose to cancel Modal and continue to deployment
4. User accounts will be automatically signed up for Notifications on Posts they create
??. Survey contains Email Field, for registered signed in users this field will be prepopulated with their Email address

**Comment by willdoran** [comment]
Tech Spec:

API
- [ ] Add test for User creation with Phone Number
- [ ] Add test for User registration including Phone Number
- [ ] Add test for User creation with invalid Phone Number
- [ ] Add test for Automatic creation of Email Contact for New User
- [ ] Add test for Automatic enabling of Contact for New User for notification
- [ ] Add Phone Number field to User object
- [ ] Add Phone Number validation for User
- [ ] Add config var to enable "Login/Signup appears on page load when user not logged in/registered"
- [ ] Add automatic creation of contact for New User for provided Email only
TODO: Address email prepopulation issue

Client
- [ ] Add Phone Number field to registration modal
- [ ] Add Phone Number Validation top registration modal field
- [ ] Set Login/Signup modal appearance on page load when no user logged in to be controlled by config var from API

**Comment by rjmackay** [comment]
>  Add Phone Number field to User object

Why add it to the user object rather than saving it into `contacts`?

**Comment by rjmackay** [comment]
### Re: collect user phone number during registration:
The spec looks solid, my only suggestion alteration would be to suggest we save the users phone number into contacts, even if we accept it via the users API. (vs adding a phone number field to the users table)

### RE: saving user email on posts:
I'd suggest we take a quick look at #1571. Previously we had an author name + email collected when posting without logging in, the backend still supports this. Rather than use a custom field for email, could we 
1. Reinstate the author name + email collection when not logged in (this would go back to core)
2. Prefill author name + email for logged in users (this would be specific to this deployment)

The advantage here is that its less fragile: we're not relying on a custom email field being present in the survey, and we get something extra in core.

**Comment by willdoran** [comment]
@rjmackay So that it can just mimic the email pattern mostly. I believe that the use case for the phone number is that they will want to be able to see it in terms of the User, so on the user's page in settings and this makes doing that vastly more straightforward. Adding it as a contact is also fine but we'll have to add code to the user page to pull through contacts, which may be we should do anyway. I think that would be the only diff though so if that's the preferred route I can change to do that.

**Comment by willdoran** [comment]
@rjmackay I've moved the email prefill to it's own issue here #1853

**Comment by rjmackay** [comment]
First, for this issue I don't think it matters if you follow contact or directly on the user object, since its a customization for just this deployment. Assuming you are building this - use your judgement, and pick whichever makes the most sense for you. 

-- 

That aside, I think we should eventually tend towards email and phone numbers stored in contacts *only*, not duplicated on the user object. This is similar to how we handle this in Rollcall. And eventually contacts should be probably be updated via the Users API, not their own separate API. This avoids extra API calls, and reflects that fact that contacts are really part of the user, not a separate bit of info.

Particular problems with the current set up are:
- when a user is created, the matching contact entry for their email is *not* created. They have to manually set this up themselves
- when the users updates their email, or the email contact later - they are not sync'd. ie. if I edit user.email, the contact.email stays the same and vice versa.

*For notifications on this deployment* we should at least resolve the issue of a users email not automatically becoming a contact and being enabled for notifications. But we probably don't need to fret about the user.email and contact email getting out of sync.

**Comment by rjmackay** [comment]
@willdoran I assume Dale needs to implement this in the mobile app? Whats does the post to the API look like?

**Comment by willdoran** [comment]
@rjmackay done
