### ISSUE TITLE
Distribute notifications via email

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#1822]
All users who submitted reports receive notifications about any status change of their reports via email they used when they created their accounts. Should have opt out option.

Should build as if we will put back into platform if we have time to do so.

**Comment by Celestine22** [comment]
@willdoran @rjmackay seems like Robbie mentioned that the requirement for non registered users to get notifications via email is not a hard requirement (since we're already writing custom code anyway). Could we pull this off in time? It would be an ideal scenario for the client and us if we can push to get this!

**Comment by willdoran** [comment]
@Celestine22 I am not aware of a way to do this at all. @rjmackay how had you intended to do this?

**Comment by willdoran** [comment]
@Celestine22 Just for clarification is 'non-registered user' equivalent to anonymous?

**Comment by Celestine22** [comment]
@willdoran in this case, yes it is

**Comment by rjmackay** [comment]
The current task spec's a custom notification ie. sending a notification on status change. Where right now we only send notifications when the post is published. So we need to write at least custom code to trigger notifications based on status change, maybe custom code for sending them too.

Given that, if we're collecting user email along with each report, I think we could use that email to send the notification rather than requiring any separate notification sign up at all.

However it depends what the client expectations are. If they're not expecting this to work for anonymous users, then we shouldn't promise it. But keep it in mind in case it turns out to be an easy addition.

@Celestine22 I had assumed, maybe incorrectly, that the client expected all users to get notifications about their reports, regardless of if they sign up for notifications. Is that correct? or do they expect users to opt-in to notifications?

**Comment by willdoran** [comment]
@rjmackay The original ticket issue says "All users who submitted reports receive notifications about any status change of their reports via email they used when they **created** their accounts."

I wasn't sure how much custom code we were writing to do this but we are expecting to expect the email survey field to be present always and unchangeably?

**Comment by Celestine22** [comment]
@rjmackay correct - the client expects all users to get notifications about their reports, this is not an opt in approach! It seems important to them for the users to get notifications about the status of their post!

**Comment by willdoran** [comment]
Requirements:
1. All registered users receive notifications about any **status change** of their reports
2. Users should automatically receive notifications about any **status change** of their reports
3. Users can opt out of receiving these notifications
4. _Non-registered users that have submitted reports receive notifications about any **status change** of their reports_

If point 4 is not a requirement from the client or in the spec I would advise against doing it.

**Comment by willdoran** [comment]
Tech Spec:

API:
- [ ] Add test to ensure Notification entity can be saved with a post_id or set_id
- [ ] Add test to ensure that when a User creates a new Post they are automatically signed up to receive notifications for that Post
- [ ] Add test to ensure that Notifications are sent for a New User when the status of a post they own is modified
- [ ] Add test to ensure that a given User can disable receipt of notifications(This should all ready be the case since you can disable notification receipt in user profile)
- [ ] Add test to ensure notifications are created on Post status change
- [ ] Add post_id to Notifications entity
- [ ] Add post_id to Notification validation
- [ ] Add getNotificationContacts by post_id
- [ ] Add PostUpdateListener which triggers notification creation on **Status change**

Client:
- [ ] Users will continue to opt out via their User Profile Notifications tab

**Comment by rjmackay** [comment]
>  Add getNotificationContacts by post_id

Where? to what?

### A few things we might need to cover too:
- Configure cronjob to run notifications (maybe? assuming they're not run by the standard notification sender)
- Create a custom notifications sending command, with text that talks about status change. The current `bin/ushahidi notifications` will send a "New post" message which won't make sense for status changes.
- Modify the message sending code to handle sending a message to an arbitrary email (ie. from an anonymous post). The current code assumes we're sending to a contact in the db.

**Comment by willdoran** [comment]
@rjmackay Updated 

- Configure cronjob to run notifications (maybe? assuming they're not run by the standard notification sender)
  -  @tuxpiper Can this be handled in the sameway comrades webhook crons are?

**Comment by tuxpiper** [comment]
Yes, we can easily configure any additional number of cron jobs involving execution of the ushahidi cli command

**Comment by rjmackay** [comment]
Maybe more relevant here than on #1819 

> For notifications on this deployment we should at least resolve the issue of a users email not automatically becoming a contact and being enabled for notifications.

ie. when a user is created, a contact should be created with the same email (I think?)

**Comment by Celestine22** [comment]
@willdoran my assumption here is that we are now doing dev work for this "Non-registered users that have submitted reports receive notifications about any status change of their reports" !? Any other concerns here that I should be aware of?

If so, I will let the client know? This is not in the initial tech spec, and the client will be fully aware we went above and beyond! Makes my job easier so thank you team!

**Comment by willdoran** [comment]
@Celestine22 I'm not positive about that, might be best for you to double check that with Robbie. It's actually quite a big piece of work to add though Robbie might have a good solution for it.

**Comment by Celestine22** [comment]
@willdoran by big, do u mean it will it throw us off our timeline? 

@rjmackay just double checking that you have a good/fast solution for this, and we can commit do pushing this to prod?

**Comment by rjmackay** [comment]
This entire issue is still in the backlog, and so isn't started yet. 

> Non-registered users that have submitted reports receive notifications about any status change of their reports

^ Will is correct, this expands our scope significantly. I'd suggest we deliver this feature *without* support for non-registered users. While we can offer to build that if its a must have for the client, we shouldn't offer to do it in the original timeframe.

**Comment by rjmackay** [comment]
@Celestine22 ^^

**Comment by Celestine22** [comment]
@rjmackay noted! At least I didn't commit!

**Comment by rjmackay** [comment]
This issue was moved to ushahidi/platform-fix-our-environment#23
