### ISSUE TITLE
White labeled app for GISCON kuwait

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#1828]
Full scope of customizations here: https://docs.google.com/spreadsheets/d/1fMlJDRa64RoYp7vE9VZkOIckVeYY3_enVYpR3PTFzuk/edit#gid=1612533017

Justin is waiting on feedback from client on #1827 before he can do designs. 

We should also wait until contract is signed to actually start doing work, but it would be good to get out ahead of this and spec out what will need to be done (if anything) on the backend to do this. 

our first white labeling! exciting!

**Comment by justinscherer** [comment]
We can get started on the structural changes to the onboarding flow before I get design assets from the client. See attached first crappy draft of an onboarding flow for the app:


![Kuwait onboarding flow.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/593714fffc98e900201ba2a5/125516c66e82c728ace21e0d46c3818d228b97e980e7bd4ca54ff49d27416775250bb4693cc7f33ab0487e021b4d44be445d0b45fdad8a7ea0e06e768d5f0bbbd16d5775cf6f13f8aa9e0dfd50e474d412dcfce9c85ecafa3e24ed8a8b463618001f8afb5d34a39e5985.jpg)

Change notes:

1. We need to change the splashpage
2. we need a custom app icon, I'm hoping to just use a version of their logo
3. We need to cut out the "add deployment" stages of onboarding and just have the user land on the deployment's about page. 
4. I've changed the items in the global nav because the deployment doesn't link to other deployments, as well as for a bunch of little flow improvements. Happy to expand on this if need be. 
5. The about page and global navigation need signed out and signed in states because only enrolled and authenticated users can submit reports.
6. Changed the yellow CTA and secondary CTAs on the about page to manage enrollment / authentication
7. Added an enrolment page (will be formatted just like our current login page)
8. login page has a password recovery option. I just stubbed in the password recovery flow for now. 

Looking for feedback from @dalezak @rjmackay @jshorland

**Comment by rjmackay** [comment]
This looks pretty good to me. I also imagine a chunk of this is going to be common to most whitelabel deployments ie. custom splash page + icon, dropping the deployments in the menu.

> The about page and global navigation need signed out and signed in states because only enrolled and authenticated users can submit reports.

Its looking like that might not be the case. Waiting on some clarity from client + @Celestine22

**Comment by dalezak** [comment]
I'm leery about changing the flow of the app for the whitelabel, especially considering the short timeframe to deliver the contract. So unfortunately I don't think its gonna be possible to move primary actions like _Log in_, _Responses_, etc from the Deployment details screen into the side menu. We discussed this on the intro call last week. 

As an alternative for the whitelabel apps, I suggest the path we take is to skip the initial _Add Your Deployment_ screen, instead automatically add the custom deployment then jump right into the Deployment details screen. Or optionally, for whitelabel apps we could show a single Welcome screen the first time with the deployment name, description and logo.

Regarding the side menu, with adding multilingual support we'll need a way to change the language, which is well suited for the side menu. So the main Ushahidi app will have Languages above the Deployments selection in the side menu, where as the whitelabel apps will simply hide the Deployments list, which prevents them from adding or changing Deployments.

Ushahidi Side Menu

![simulator screen shot jul 4 2017 4 07 50 pm](https://user-images.githubusercontent.com/91811/27843626-f1cd2202-60d2-11e7-8671-3f6acd79e333.png)

![simulator screen shot jul 4 2017 3 50 18 pm](https://user-images.githubusercontent.com/91811/27843627-f68ff486-60d2-11e7-96c7-45e160d261df.png)

Whitelabel Side Menu

![simulator screen shot jul 4 2017 3 50 18 pm](https://user-images.githubusercontent.com/91811/27843629-fa72bcfa-60d2-11e7-90ff-2d63e6f591e7.png)

**Comment by justinscherer** [comment]
See #1827 for theming colours/assets
