### ISSUE TITLE
Saving user email on posts

### ISSUE THREAD

**Issue by willdoran** [ushahidi/platform#1853]
### Expected behaviour
- For registered users the client expects the Email field on a survey to be pre-filled with the logged in users email address

### RE: saving user email on posts:
I'd suggest we take a quick look at #1571. Previously we had an author name + email collected when posting without logging in, the backend still supports this. Rather than use a custom field for email, could we 
1. Reinstate the author name + email collection when not logged in (this would go back to core)
2. Prefill author name + email for logged in users (this would be specific to this deployment)

The advantage here is that its less fragile: we're not relying on a custom email field being present in the survey, and we get something extra in core.

Here's a quick attempt at #1571 which I think we could extend for Kuwait...
ushahidi/platform-client#682

**Comment by rjmackay** [comment]
- Land #1571 
- Confirm the API will accept both user id and author_email on a post, if not modify the validator
- Modify client to prefill author_email based on user.email

@Celestine22 do we need to include + prefill phone number? or just email?

**Comment by rjmackay** [comment]
@Celestine22 I'm not sure which phase this is expected in. It wasn't in our timeline at all.

**Comment by Celestine22** [comment]
@rjmackay just email! It can be moved to phase 3 @jshorland your thoughts?

**Comment by rjmackay** [comment]
@Celestine22 I've merged some changes for this. We're now collecting user email when they submit a report (when not logged in). If they are logged in, we just show their user email on the report. I'm not sure if I need to continue with 

> Prefill author name + email for logged in users (this would be specific to this deployment)

I can demo this to the client and get feedback.

**Comment by rjmackay** [comment]
Should email be required for not-logged-in reports?

**Comment by Celestine22** [comment]
@rjmackay its required as it will help them manually send notifications about post status of a report!

As for showing their user email on the report for as long as they're logged in, I think that's enough and I've added this to the agenda for tomorrows meeting.

**Comment by Celestine22** [comment]
Points to note;

- This approach works for client. 
- No point of pre-populating the user email when the user is logged in.

**Comment by rjmackay** [comment]
@dale this is the task for the author fields. They're a part of the main posts API, have been for a while but we lost the UI for them a while back.
- Basically for any user who isn't logged in we ask for name + email
- We send that to `author_realname` and `author_email` on the post object
- I probably need to finesse the language so if you have better ideas for labelling that'd be great. Possibly just 'Enter your name', 'Enter your email'.. and 'Author' could be come 'Your contact details'
- For a logged in user, we don't show these fields at all
- This isn't in the upstream repo yet, because I'm waiting on feedback from Justin + Jess on the UI.

**Comment by rjmackay** [comment]
This issue was moved to ushahidi/platform-fix-our-environment#20
