### ISSUE TITLE
Checkbox "Make response private" doesn't works for "Description" field

### ISSUE THREAD

**Issue by AntonShevchuk** [ushahidi/platform#1854]
### Steps to reproduce the behaviour/error
Create new survey with default fields: "Title" and "Description"
Check "Make response private" for "Description"
Save it

Submit new survey and publish it

### Expected behaviour
Open "Timeline" page
Show survey without description

### Actual behaviour
Open "Timeline" page
Shown survey *with* description

**Comment by ryanchristo** [comment]
This also applies to "Make response private" for "Title", which makes me think the toggle option for these two fields might not be intended. Should title and description have the ability to toggle "Make response private"? It would be a quick fix to remove the option from these title and description.

@AntonShevchuk For your particular use case, would it make sense to create a separate field and keep the description public or is it important that the description field itself is private?

**Comment by AntonShevchuk** [comment]
@ryanchristo So, I can create new private field description but my users will be puzzled with two description fields

**Comment by ryanchristo** [comment]
@AntonShevchuk You're right, that would be a little puzzling with two description fields. You can change the name of the description field and the new field but if it's the description field itself that you want to hide from users then removing the option to toggle would not help.

**Comment by AntonShevchuk** [comment]
Yep, I really need this fix, this is last obstacle for migration from old version to new platform

**Comment by ryanchristo** [comment]
@AntonShevchuk It looks like the team is exploring "free form surveys" (https://github.com/ushahidi/platform/issues/1335), which would break from the current pattern of postcards (e.g. title, description, metadata). The title and description are not currently handled in the same way as the other fields (metadata), which is why the `Make response private` feature is not working.

With the implementation of "free form surveys", all fields would function the same and the title and description fields could be hidden or never even added in the first place. It looks like the issue you came across adds another reason to why they are considering "free form surveys".

I'll keep an eye out for a short-term solution but it looks like the current pattern might not support the ability to hide the title and description and the team is looking into a long-term solution.
