### ISSUE TITLE
UX: Title field on survey form

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#1862]
Feedback from uchaguzi trainees is that the Title field doesn't pop out as a text field. It's longer than all other fields, while description field ( which is supposed to cover a larger area) is seen to be smaller.

see ![screenshot](http://i.imgur.com/5Mxga3z.png)

@kamaulynder can probably speak to this much better than I can

**Comment by kamaulynder** [comment]
It's basically not easy to tell that is where to type the title until you click

**Comment by wanjar** [comment]
The problem is in the css. Left and right margins set to 0 and left and right border colors set to transparent on the form template in the pattern library. Two solutions exist. Either remove the title class from the new post page or make changes to the pattern library by altering the margins and the border colors.

**Comment by wanjar** [comment]
The problem is in the css. Left and right margins set to 0 and left and right border colors set to transparent on the form template in the pattern library. Two solutions exist. Either remove the title class from the relevant div on the post page or make changes to the pattern library by altering the margins and the border colors. The latter may cause a global layout change.
![screenshot 2](https://user-images.githubusercontent.com/8712110/28994370-4340de24-79d5-11e7-99b5-60bec3880431.png)

**Comment by wanjar** [comment]
Looking at the css, the left and right margins set to 0 and left and right border colors set to transparent on the form template in the pattern library. Two solutions exist. Either remove the title class from the relevant div on the post page or make changes to the pattern library by altering the margins and the border colors. The latter may cause a global layout change.
![screenshot 3](https://user-images.githubusercontent.com/8712110/28994373-65e02fca-79d5-11e7-90e6-c5b634aa348f.png)

**Comment by wanjar** [comment]
Looking at the css, the left and right margins set to 0 and left and right border colors set to transparent on the form template in the pattern library. Two solutions exist. Either remove the title class from the relevant div on the post page or make changes to the pattern library by altering the margins and the border colors. The latter may cause global layout changes.
![screenshot 4](https://user-images.githubusercontent.com/8712110/28994387-d0a4c910-79d5-11e7-86f6-888c6d26e267.png)

**Comment by Celestine22** [comment]
@wanjar @rjmackay this looks good, border color is purple, separating the fields, and description box is  indented and 
<img width="723" alt="screen shot 2017-08-07 at 2 43 18 pm" src="https://user-images.githubusercontent.com/8900438/29025373-0640de38-7b7f-11e7-91d3-33945e180775.png">
visible.
