### ISSUE TITLE
Tasks/categories ambiguous

### ISSUE THREAD

**Issue by justinscherer** [ushahidi/platform#1874]
For a novice user, tasks and categories are confusing. Categories should be configurable from within survey customization.,

Aha! Link: https://ushahiditeam.aha.io/features/PROD-578

**Comment by caharding** [comment]
- [ ] In Uchagzui 2017 it is very confusing that I both have to mark a category AND flip switch to complete a task. This is because we don't have a real tasking method, instead categories are being used to create tasks 
- [ ] When I complete a task, there is no log of my participation in that post

![screenshot 2017-08-07 12 39 06](https://user-images.githubusercontent.com/1618793/29042820-6bd7c3a4-7b6d-11e7-896a-67d8c9156fb5.png)
