### ISSUE TITLE
remember user email on subsequent logins

### ISSUE THREAD

**Issue by justinscherer** [ushahidi/platform#1889]
remember user email on subsequent logins

Aha! Link: https://ushahiditeam.aha.io/features/PROD-565

**Comment by rowasc** [comment]
This could be a community task, a "remember me" checkbox for email (probably just using local storage since everything is setup for it already) 
@Angamanga I think this might be a good first issue (assuming technical knowledge) , checking with you in case you disagree :) 
@Erioldoesdesign cc in case you have ideas on UI for this

**Comment by Erioldoesdesign** [comment]
Hmm Re. UI i would suggest something like:

<img width="532" alt="Screenshot 2019-07-10 at 16 28 49" src="https://user-images.githubusercontent.com/11681324/60977470-d2fb8480-a32f-11e9-9010-fe95bf05589f.png">

So also including the ability to remember password too!

But! tricky thing would be making sure it doesn't interfere with google save passwords/lastpass etc.

**Comment by Erioldoesdesign** [comment]
Also better spacing than my hacky inspect CSS please!

**Comment by rowasc** [comment]
uh. I kind of prefer not to remember their password in the client to be honest for security reasons. Their browser will be the one suggesting this already and it gives more control in the form of their browser choice and security choices (ie if they use last pass, one pass, etc)

**Comment by Erioldoesdesign** [comment]
Very happy to be over-ruled on that aspect. No 'remember password' in this solution (if a community member takes this task) 💯

**Comment by AishaSaman** [comment]
Hello I am an Outreachy internship Applicant and I want to work on this issue.
Can someone explain me in which files I have to work for this issue. Thanks

And what I understand is that the email id have to be stored in the cookie so that the next time user wants to log in the browser remembers the email id. Am I right?

**Comment by Angamanga** [comment]
@AishaSaman Yes please go ahead! The files for the login-box is found in this folder: https://github.com/ushahidi/platform-client/tree/develop/app/common/auth

You can see an example on how we are using local storage here: 
Setting local storage: https://github.com/ushahidi/platform-client/blob/develop/app/common/services/translation.service.js#L102

Getting local storage: https://github.com/ushahidi/platform-client/blob/develop/app/common/services/translation.service.js#L74

**Comment by AishaSaman** [comment]
@Angamanga  I can't solve this for now, sorry. Please assign me any first-timer-issue. Thanks

**Comment by Angamanga** [comment]
@AishaSaman I don't think we have many first-timer issues left, but check here if you find something interesting: https://github.com/ushahidi/platform/labels/Community%20Task.
