### ISSUE TITLE
When navigating to a saved search, the saved search list doesn't disappear automatically

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#1948]
### Expected behaviour
On sandbox.uchaguzi.or.ke, After I click on a saved search in the list, it will navigate to it and close the saved search list window. 

### Actual behaviour
The window with saved search list doesn't go away. I have to manually X out of it. 

### Steps to reproduce the behaviour/error
![mdg5q](https://user-images.githubusercontent.com/3224856/28903199-6d010064-77b8-11e7-98c6-95779d2af249.gif)

**Comment by rowasc** [comment]
https://github.com/ushahidi/platform-client/pull/707
@rjmackay does this look like the right approach? I went for the most simple solution I could think of, to avoid overcomplicating what used to be a simple href=//, but it might not be the right one..

@jshorland I'm uploading a quick test/demo video (like yours) in a few minutes (to github)

**Comment by rowasc** [comment]
![video1948.gif](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5940898e29d5f5001ab2826d/125516c66e82c728ace21e0d46fe9d9e268dd2f0dbb1fd0fe64de29b234324676b5ee17e2581b279bb117e57090d48ab42580944fcf18822f4b46862964e49bc8f3900299f7744eeaa880dbc00b0218e4f84bfbd884bc1e13527e699c2.gif)

Ok, my video is pretty bad but basically, it shows that now the modal box is being closed when a saved search is selected, instead of having to manually close it.
