### ISSUE TITLE
Unable to select categories across multiple surveys on main map page

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#1955]
### Expected behaviour
I would like to be able to select categories across all surveys while interacting with data on the main map

### Actual behaviour
The moment I select a category on a particular survey, all other surveys get deselected. See 
![gif](http://i.imgur.com/J6YXXgG.gif)

**Comment by willdoran** [comment]
@aoduor I will look at this but there is a high change it can't be fixed because of a code design issue

**Comment by willdoran** [comment]
This is done, but very hacky

**Comment by rjmackay** [comment]
This is kinda concerning. We made this change because otherwise the UI was really misleading. For a user *without* a deep background in the platform, its totally unclear that their changes to the categories filtered apply to *all* surveys, not just the survey they've currently expanded.

I understand the inability to filter by multiple surveys + categories at the same time is problematic, but I think limited filtering is better than completely misleading filtering.
