### ISSUE TITLE
Post edit locking improvements -- indicate who is working on it

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#1962]
To make it easier for folks to identify who is working on what.

Currently, we block the edit button, but its hard for team members to figure out who's working on what.

Kinda urgent :D

**Comment by Celestine22** [comment]
Jumping in just to say its very urgent :)

**Comment by jshorland** [comment]
We don't have time to get this in. @willdoran and I had talked about it last week while he was building it, and it's too much work.

**Comment by jshorland** [comment]
Bumping this up to P1 just in case.

**Comment by willdoran** [comment]
Adding this is relatively straightforward, I'll try to include it when preparing locking for merge to core.

**Comment by jshorland** [comment]
Post locking 
- [ ] Locking is only relevant and displayed to users who are logged in and have post edit permissions
- [ ] Default sort order of post cards in data mode (left pane) is “unlocked on top”
- [ ] As soon as a user has decided to edit a post and enters edit mode, it becomes locked against others editing it
- [ ] As soon as a user saves or navigates away from a post they are editing that post becomes unlocked for others to work on
- [ ] if a user has selected a report, but it is not editing it, and another person tries to enter edit mode on that report, the report will appear as locked and notify the user that it is locked, and indicate which user is editing it. 
- [ ] A small lock icon appears in the postcard’s top left corner when it is locked
- [ ] if an admin user hits an edit lock, an unlock button is available to them to force unlock of the post
- [ ] if an admin clicks “unlock” it immediately takes them to post edit mode of that post with success message that reads “you have unlocked this post and we have notified <<user who was booted>> <— THIS DOESN’T HAVE DESIGNS YET - DO WE ACTUALLY NEED IT?
- [ ] if admin manually unlocks a post that you are editing, you get “booted” from edit mode and a notification appears telling you that your report has been unlocked so that <<admin>> can edit it


Questions:
- is there a timeout?
- should just selecting a post really lock it?

**Comment by jshorland** [comment]
Designs
![post.locking.png](https://zube.io/files/ushahidi/0836e3993bd6936f3d34c3f7498e0206.png)

**Comment by willdoran** [comment]
I want to use https://socket.io to push the notifications to those getting booted
