### ISSUE TITLE
User should be able to define Categories as radio buttons or checkboxes

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#2012]
I'm not sure if this is something that would apply across, or if this is something that would have been best handled using custom fields ( given that we currently cannot search by custom fields ), BUT, it would be INSANELY helpful to have had some of the categories we were using for Uchaguzi as radio buttons instead of checkboxes e.g geolocation status etc.

Perhaps something to think about when setting up categories? Let user determine if they want it to be checkboxes or radio buttons?

Aha! Link: https://ushahiditeam.aha.io/features/PROD-537

**Comment by Celestine22** [comment]
@aoduor thanks for this one! LOVE IT! The user should be able to select whether they want it to be a checkbox or a radio button because both are useful given the scenario. :)

**Comment by jshorland** [comment]
Clarifying question for my own understanding: is this because they want the user to either a). be able too select multiple categories (as a checkbox), or b). only be able to select ONE (as a radio button)? or is it for some other reason?

**Comment by jshorland** [comment]
and spot on @angela that this would be a quick hack to the real problem that is not being able to filter by custom field.

**Comment by rowasc** [comment]
Note for when someone tries to implement this; We'll probably have to have 2 "types" of categories to define this in the backend, and we'll need to change backend logic so that 1 type of categories uses AND logic and others use OR , and probably a bunch of other changes that I'm not realizing right now because It's been a while since I went down the categories rabbit hole 😅
