### ISSUE TITLE
Cannot submit survey

### ISSUE THREAD

**Issue by gsvlopez** [ushahidi/platform#2029]
I tried to submit a response to my own Ushahidi survey - https://hatespeechtracker.ushahidi.io - and it is not allowing me to submit. It says that one of my fields is "required" - but I filled in this field. It is the second field, titled "Enter content of hate speech here", and there is no option to make it required/not required.

To reproduce, go to link above, click (+), fill out survey with "Test" in all required fields, and try to submit. 

### Expected behaviour

![screenshot](https://user-images.githubusercontent.com/10912348/29724596-0024afcc-8997-11e7-9a2e-510ca5c34205.JPG)

**Comment by aoduor** [comment]
Flagging this is p0. Experienced the same issue on two separate ushahidi.io deployments today while testing. Platform does not seem to detect content in the title field or description field (even when edited) and marks it as needing to be filled during submission 

Cc @jshorland.

**Comment by jshorland** [comment]
Hey @gsvlopez we're looking into this ASAP! Thanks for filing.

**Comment by jshorland** [comment]
Replication efforts:
- we believe it happens on deployments in production when you change the field name of Title and/or Description. 
- it's NOT happening on our internal QA deployment (unable to replicate at all there)

**Comment by jshorland** [comment]
Additional details:
Have you created any tasks on that particular survey?

- No, but: I did temporarily change the first question - Title - to the same exact text on the next question - "Enter the content of the hate speech here". The reason I did that was because Title didn't seem to make much sense in the context of this survey. Because the field that originally said Title had a character limit, and we want people to be able to submit longer posts in that box, I decided to change it back to how it was originally. I have a feeling that may have been what caused this bug, but I'm not sure.

Have you made any of the fields on that survey private?
- Yes - the final field (add image)

**Comment by jshorland** [comment]
cc @rjmackay

**Comment by Angamanga** [comment]
This commit is missing from master/production: https://github.com/ushahidi/platform/commit/0de372c08b824518c7ecdda35967ec275e3cfeb0

**Comment by rjmackay** [comment]
Ah right. I think @willdoran fixed this after I deployed. I can just do another release today :)

**Comment by rjmackay** [comment]
@gsvlopez this should be fixed now. I've just deployed the changes. Can you test it out and let me know if it solved your issue?

**Comment by dCogs** [comment]
That fixed it.  Thanks.

**Comment by jshorland** [comment]
Fixed. Closing!
