### ISSUE TITLE
Image field within a task throws a validation error that it must be a digit

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#2050]
### Expected behaviour
when I upload an image within a task, it should not throw an error at me. 

### Actual behaviour
It gives me the following: Validation Error The field New image field must be a digit, Given: changed
### Steps to reproduce the behaviour/error
1. Fill out all required fields in this survey
2. upload an image within the "translation" task at the bottom
3. click submit

**Comment by rjmackay** [comment]
Duplicate? https://github.com/ushahidi/platform/issues/2006

**Comment by tuxpiper** [comment]
@jshorland @rjmackay @diegodorgam . Confirmed it's the same problem reported by Diego in #2006 . It's happening on my local environment too.

For some reason, in this scenario
1. the client doesn't attempt to upload the media and
2. sends to the backend the string "changed" as the value of the media field (instead of the media record numeric id)row id

**Comment by tuxpiper** [comment]
Turned out to be a quick fix: ushahidi/platform-client#749

**Comment by rjmackay** [comment]
This is live now on ushahidi.io
