### ISSUE TITLE
Time shown in post metadata is always in another language, when I select English as a language

### ISSUE THREAD

**Issue by Celestine22** [ushahidi/platform#2065]
This is happening our enterprise clients deployments, specifically sfcg and giscon, to reproduce, open the SFCG deployment https://sfcgguineaewer.ushahidi.io/views/list and change the language to English, observe the post metadata, the time shown is NOT english. See below.
<img width="586" alt="screen_shot_2017-09-19_at_3_33_16_pm" src="https://user-images.githubusercontent.com/8900438/30592588-05b89b20-9d50-11e7-95de-6654742c2cdf.png">

**Comment by kinstelli** [comment]
I wanted to share some updates on some of the issues I've found related to this. If anyone ( @willdoran ?)  is familiar with these pieces, please let me know if you have thoughts on the following:

1. These dates/times are being constructed by moment.js, but moment.js locale isn't always updated whenever the language is changed. And this change, in turn, isn't being propagated to the various post-metadata directives. These directives might need some refactoring (not sure if an $on or $watch approach might be okay here) so they call their own functions to immediately recalculate their date/time fields.

2. It looks like moment.js has its own files for localization, but some of the codes used throughout platform don't seem to match up to the codes moment.js's uses, (e.g., there is no 'pt-BR.js', 'vi-VN.js', 'ht.js', or 'zh.js' ). When this happens, moment.js can't load an appropriate localization file, so it fails semi-silently. In that case, the translated strings are updated, but the dates/times don't get changed, even after a page reload. This error also seems to cause some other side-effects that prevent the locale from being changed further.

3. There may be a small bug explicitly preventing moment.js from changing to 'en'. English seems to work fine if it's the default, but switching to 'en' from another language seems to have issues.

--
1 and 3 seem straightforward to fix, but I'm not sure what should happen with 2. There might be a way to align the list of translated languages with the options available with moment, but I'm not sure what approach would be best.

**Comment by Celestine22** [comment]
Thanks for this feedback @kinstelli , @rjmackay @willdoran please take a look at this! 

Adding @tuxpiper in cc as its tied to gis and sfcg

**Comment by willdoran** [comment]
@kinstelli The giscon work unfortunately has to finish this week, for them we need as immediate a solution as possible. To address your points in reverse order:

3. Is this a bug with momentjs or us?
2. That is somewhat irritating, are we using non-standard codes or are they?
1. To effect the actual updates, $watch is probably the best approach(though I would prefer $on because I think it's more explicit and less "weird" state prone) for this situation.

**Comment by rjmackay** [comment]
- Pushed a small fix that I think resolves 3.
- Is the issue with generate dates simple because they were generated when the view first loaded and then aren't refreshed? or is it more complex than that?
- Is the missing locales a case of mismatched locale codes? or just missing locales? (ie. languages moment is not translated too)
