### ISSUE TITLE
Add Lock Timeout to Site Settings

### ISSUE THREAD

**Issue by willdoran** [ushahidi/platform#2130]
### Expected behaviour
- I can configure the timeout length of a post lock via the site settings
### Actual behaviour
- Not currently available
##### Where
- [ ] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [ ] Ushahidi.io / SaaS solution 
- [ ] Ushahidi's QA environment
- [ ] Other (explain):

Aha! Link: https://ushahiditeam.aha.io/features/PROD-510

**Comment by rjmackay** [comment]
@willdoran is there a default timeout now? Is it configurable in the backend?
I don't think this is something normal users should be able to configure TBH, but maybe just something we should be able to override for clients.

**Comment by willdoran** [comment]
@rjmackay I think there are usecases that justify making this a part of the general settings. I'm not sure why we would want to tune it for individual end users, locking itself is a feature how long the lock lasts is something individual deployments may want to decide on their own. But perhaps I'm wrong, @aoduor was there a usecase for this in uchaguzi or no?

**Comment by rowasc** [comment]
@aoduor @Erioldoesdesign is there user research backing the need for this? Should we keep this issue? -the user research might be "Angie actually found a need for this during 2chaguzi " BTW, that'd be ok if that's the case - 

It's not hard to do, it's just that I want to know if it's something we want or not. 

Right now it looks like locks are active for 5 minutes (according to LockRepository::isActive).

**Comment by Erioldoesdesign** [comment]
I'm actually unclear on this feature improvement...no research that I can remember but it sounds valid and useful because:

I can configure the timeout length of a post lock via the site settings

So I am a post responder (not a deployment owner/logged in etc.)
I make a post
I want to edit that post
I open the edit settings and leave it open, x time elapses but I can still return to editing many hours later. effectively 'stalling' the post from being able to be managed by a deployment owner.

So yes, it's very useful to have a timeout on this if it's not covered by the whole deployment timeout function. 

So perhaps what we need to to check that the whole deployment log out then 'saves' a posts edits to be able to be used by a deployment owner.

**Comment by rowasc** [comment]
There is a timeout for the locks already, just not a setting to change how
long it lasts.
