### ISSUE TITLE
Show the "unsaved changes" warning on route change (manual URL change or otherwise) and page reload 

### ISSUE THREAD

**Issue by rowasc** [ushahidi/platform#2144]
### Expected behaviour
I should see a warning that I am leaving a post with unsaved changes whenever I'm about to leave the page with an unsaved post. 
### Actual behaviour
I see a warning, but only if I navigate around the app.

##### Where
- [ ] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [ ] Ushahidi.io / SaaS solution 
- [x] Ushahidi's QA environment
- [x] Other (explain): http://sandbox.uchaguzi.or.ke

**Comment by crcommons** [comment]
Cancel button isn't working https://github.com/ushahidi/platform/issues/2212

**Comment by jshorland** [comment]
I don't see a warning at all when
- I go to edit mode on any post
- I make changes but do not save those changes (i do NOTHING before the next step)
- I type in adifferent post number into the URL instead of navigating within the app

This still exists as far as I can tell within sandbox.uchaguzi.or.ke. Moving backward

**Comment by jshorland** [comment]
Fixed. closing.
