### ISSUE TITLE
Clearing search text does not cause search to refresh

### ISSUE THREAD

**Issue by willdoran** [ushahidi/platform#2172]
### Expected behaviour
- When I click the 'x' in the search input box, I expect the search to rerun without the search text this time
### Actual behaviour
- Text is cleared but search is not rerrun
### Steps to reproduce the behaviour/error
- On either map or data view
  - Type a search query into the search inpiut box
  - Hit enter, search should run
  - Click the 'x' in the right hand side of the search input box
  - Text will clear
  - Search is not rerun

##### Where
- [ ] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [ ] Ushahidi.io / SaaS solution 
- [ ] Ushahidi's QA environment
- [ ] Other (explain):

**Comment by rowasc** [comment]
@jshorland @willdoran this means that in data mode, now the filters react to changes without apply filters.  Right? 
I agree that in map mode, it should re-run instantly. 

Frankly, having two views that share a feature (filters, search) and having that feature behave in two completely separate ways  is `very` confusing right now.

**Comment by rowasc** [comment]
@willdoran https://github.com/ushahidi/platform-client/pull/838
Sent over a PR since I was waiting for codeship to run on another issue and had a few minutes. 

LMK what you think  (of the feature itself)
@jshorland please feel free to check this with the "view deployment "  test button too. Any input is appreciated. 


There's a dropdown and searchbox style issue I need to look at that is completely unrelated to this, please ignore it.

**Comment by jshorland** [comment]
Fixed. passes QA.

**Comment by Obadha2** [comment]
@rowasc appears this is a regression?
