### ISSUE TITLE
Use "gray out" or other indicator of what post is being viewed in Data layout

### ISSUE THREAD

**Issue by Shadrock** [ushahidi/platform#2185]
### Expected behaviour
To quickly and clearly understand which post is being viewed in the Data layout

### Actual behaviour
Currently, the only indicator of which post is being displayed is a slight indent (see pink arrow in photo). 

<img width="1334" alt="uchaguzi grey out vs indent" src="https://user-images.githubusercontent.com/4574998/31784194-7e4f05c6-b509-11e7-9a18-c530d4fb43c5.png">

### Suggested Solution
Trainees at the Uchaguzi training session were asking for something more distinct: a change in color, an indication icon, etc. Angie suggested the 'grayed out' option that was suggested during the initial design phase.

##### Where
- [ ] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [ ] Ushahidi.io / SaaS solution 
- [x] Ushahidi's QA environment
- [ ] Other (explain):

Aha! Link: https://ushahiditeam.aha.io/features/PROD-508

**Comment by justinscherer** [comment]
@Shadrock 

This is an interesting request. 

Did they say why they want a stronger on-state? Was it creating actual errors? How did they/we frame the feedback?

I got rid of the grey-out because it's not accessible (there isn't enough contrast with the background if we grey things out), and grey-ing things out tends to read as "you can't edit this" when the opposite is true. 

If this is creating actual user errors, then I will re-assess a quick fix in the short term, otherwise, it can probably wait till our next round of testing.

**Comment by justinscherer** [comment]
Leaving this for now until we have some more information.
