### ISSUE TITLE
Map container is already initialized

### ISSUE THREAD

**Issue by rowasc** [ushahidi/platform#2189]
### Expected behaviour

- I don't reinitialize the map every time, or I properly do it instead of causing an error in leaflet.
### Actual behaviour
- I try to have more than 1 leaflet map, which is not supported. 

### Steps to reproduce the behaviour/error
- Data mode: click on a post card with a map . You won't see the map.
- Go to map
- You will see the console error `Error: Map container is already initialized.` and `Error: Map container is being reused by another instance`
##### Where
- [ ] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [ ] Ushahidi.io / SaaS solution 
- [ ] Ushahidi's QA environment
- [ ] Other (explain):

**Comment by willdoran** [comment]
@rowasc where does this happen?

**Comment by rowasc** [comment]
mmm it might have been fixed with Mark's map fix, because it doesn't happen anymore.Closing for now.

**Comment by rowasc** [comment]
Reopening. This was not fixed. 
`Map container is already initialized` is also not fixed. 

Details will be added in description right now.

**Comment by rowasc** [comment]
@jshorland moved this to inmediate because we need to know the errors caused by this and also because apparently maps are not visible when you click the postcards. Please feel free to reprioritize! This might in fact be a P0 but I didn't want to tag it as such until I have more details. LMK if this changes  priorities . Thanks
Thanks.

**Comment by rowasc** [comment]
@jshorland dismiss that, we will update when we know more

**Comment by kinstelli** [comment]
From what I can tell, maps are currently displaying correctly, despite these errors.

However, Leaflet is complaining about resources being reused or already initialized, because the common maps service is trying to create a new map every time the post-map directive is refreshed and calls the services' createMap function, which also tells Leaflet to make a new map.

For some reason, checking whether a map already exists, then trying to destroy it (either with `map.remove()` and/or `map.off()` ) doesn't fix this issue.

I'm guessing that rather than trying to destroy the map, updating the configuration on the existing map will probably fix this, but I'm deferring that task until we're done with testing.

**Comment by jshorland** [comment]
@kinstelli do you mind QA'ing this? I'm not sure how to do so from a user perspective on sandbox.uchaguzi.or.ke
