### ISSUE TITLE
Replace ngRouter with ui-router

### ISSUE THREAD

**Issue by rjmackay** [ushahidi/platform#2201]
## Why?
UI router allows nested views which is very useful for multi-pane layouts ie. the data view. We use this in rollcall to handle multipane views.

In particular this should allow easy handling of URLs ie. /post/:id where you need to load both the current post detail + the data view beside it.

## What?
- [x] Install ui-router
- [x] Remove ngRouter
- [x] Convert existing routes to states
- [x] Fix/Adjust unit tests for uirouter where needed
- [ ] Test all routes still work
--- This is a good point to ship something --- 
- [ ] Convert data view to use [nested states + views](https://github.com/angular-ui/ui-router/wiki/Nested-States-and-Nested-Views)
- [ ] Convert states to use components directly where possible (ie. where there already a single component for an entire view)

**Comment by rjmackay** [comment]
I'm not sure if we can feasibly do this till after 2chaguzi, but it should probably be high priority afterwards otherwise our code is going to get harder to maintain.

**Comment by rowasc** [comment]
> Fix/Adjust unit tests for uirouter where needed
this was done but I broke them again. 
So I'll update later when I get to it

**Comment by rowasc** [comment]
UPDATE:  TLDR most things are working, and what's not working is logged in here or we are working on it. Fairly close to a mergeable state. 

- map view works.
- most things working AFAIK. Need massive amounts of testing because obviously this impacted the whole app.. 
- saved searches work https://github.com/ushahidi/platform-client/pull/912
- collections work https://github.com/ushahidi/platform-client/pull/912
- data mode works https://github.com/ushahidi/platform-client/pull/919/files
- edit in data mode works https://github.com/ushahidi/platform-client/pull/919/files

WIP: 

- [ ] Spinners/loaders are being worked on by Anna, I might pair with her in the morning to wrap things up together
- [ ] Carolyn helping out on code reviews :thumbsup:  :thumbsup: 
- [ ] Need to route to map view when loading site home page (localhost:3000 or localhost:3000/) (I think Carolyn did it in  a PR already, need to review)
- [ ]  Logout should route to map view (I think Carolyn did it in  a PR already, need to review)

TODO: 

- [ ] Post delete should update the list in data mode.
- [ ] We should route to data view after you save a post with that post selected

**Comment by rowasc** [comment]
Working on  "We should route to data view after you save a post with that post selected" this next

**Comment by rowasc** [comment]
working on this next:  the post detail (right side) in data should be updated when selectedPost changes after a status update

**Comment by rowasc** [comment]
Linked all the PRs into the main branch .  @rjmackay

**Comment by rowasc** [comment]
Issues found : 
- selectedPost in the right side of data view changes before you decide to continue/save and does not go back to unselected if you don't continue to it.
