### ISSUE TITLE
Hitting 'return' on a post triggers the cancel action not save

### ISSUE THREAD

**Issue by rjmackay** [ushahidi/platform#2216]
### Expected behaviour
Hitting return within the form should save it.

### Actual behaviour
Hitting return triggered the cancel action.

### Steps to reproduce the behaviour/error
- Go to data view
- Select a post.
- Click edit
- Click in a text field, type something
- Hit return

##### Where
Uchaguzi sandbox

**Comment by rowasc** [comment]
<img width="650" alt="screen shot 2017-10-23 at 11 09 51 pm" src="https://user-images.githubusercontent.com/2434401/31921768-68cddcf4-b847-11e7-9d0e-3894cc64fbb5.png">

Adding screenshot because I for some reason associated cancel action wrong (assuming it was the "cancel" itself and I don't want to forget.

**Comment by jshorland** [comment]
I can't seem to replicate this now on sandbox. When I follow the steps in the original issue and then hit "return", nothing happens at all.

**Comment by jshorland** [comment]
Closing.
