### ISSUE TITLE
Slash and burn the "star" in the search and filter menu

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#2232]
### Expected behaviour
I shouldn't see the star icon anymore. The only place saved searches should exist are in the saved search drop down within the search and filter drop down

### Actual behaviour
It's still there. i see that star and its ruining everything in mobile.

cc: @middle8media

**Comment by middle8media** [comment]
Removing the star is easy enough, but I agree that "sort and filter" is too long. @justinscherer @jshorland Any thoughts on alternatives.

**Comment by middle8media** [comment]
@justinscherer's idea about wrapping the "Sort & Filter" below the search could work, but will be too deep a dive for 2chaguzi.

**Comment by kinstelli** [comment]
I was trying to get an idea of icons that other people are using for search and filter. Mostly these involve a hybrid of funnels and up/down arrows (for example [https://www.iconfinder.com/search/?q=sort+and+filter](https://www.iconfinder.com/search/?q=sort+and+filter) ). 
 I don't love these, but I also worry about how long these translations will be. In Spanish and German, they're already pretty long.

**Comment by justinscherer** [comment]
> I was trying to get an idea of icons that other people are using for sort and filter. Mostly these involve a hybrid of funnels and up/down arrows

Yeah, there's basically no really good filter/sort icon. There is a good icon for search, though. 

> I also worry about how long these translations will be. In Spanish and German, they're already pretty long.

Great point re: language. 

We should probably re-factor the bar a bit when things settle down to just make it cleaner and minimize the number of separate clickable items in the top there. 

Another option is to just use the word "Filters" and remove the yellow circle with a "0" in it when there are no filters present. 

Ideally, I would want to test whether or not removing the explicit sort callout at the top level trips people up who only want to filter, though, before we do that.

**Comment by jshorland** [comment]
please be aware of #2239 before removing this icon altogether. It's possible that removing it should fix that issue, but if it doesn't, we completely lose the ability to successfully access a saved search within data mode.

**Comment by Angamanga** [comment]
Things we need to decide on before we get rid of the star:
If just removing the star, we have no way of filtering through a saved-search nor accessing the saved-searches. It does not work like the other filters so the dropdown in the filter-bar does currently not work or update the filters (this issue: https://github.com/ushahidi/platform/issues/2239). We don't have support for searching for a saved-search in the backend in the same way as the other filters work. 

@justinscherer Could we find another place for the saved-searches in the platform, outside the filtering-bar? Previously, when clicking the star, it added the filters to the filter-dropdown, if we would make any changes to the filters, we got an option to save a new saved search or update the current one in the mode-context-bar. This possibility is now removed since the mode-context-bar is not there anymore.

**Comment by jshorland** [comment]
slight update: @kinstelli is doing some testing on the API to make sure we know how to fix the saved search issue.

**Comment by jshorland** [comment]
Moved back to ready for dev until #2239 and #2246 are fixed

**Comment by rjmackay** [comment]
Replaced by #3753
