### ISSUE TITLE
Sub-categories cannot be selected without selecting parent in filters

### ISSUE THREAD

**Issue by crcommons** [ushahidi/platform#2248]
### Expected behaviour
I should be able to search/filter only by a sub-category
### Actual behaviour
When I select the sub-category, it also selects the parent, which means all posts that fit the parent category are included in the filter
### Steps to reproduce the behaviour/error
For example: select filters dropdown, add a filter for "needs translation" and see results. Then clear filters and add a filter for "translated." Results should be the same as before.

##### Where
- [ ] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [ ] Ushahidi.io / SaaS solution 
- [ ] Ushahidi's QA environment
- [ ] Other (explain):

**Comment by rowasc** [comment]
From Angie's feedback: 
`When we're setting status of a post, e.g geolocation, you have 3/4 scenarios
1. You can't geolocate ( needs geolocation)
2. Geolocated
3. Unable to geolocate
Each time you select either of the three options, it picks the parent category ( Geolocation). This means that every post, irrespective of what scenario described above, is essentially subscribed to the top level category.
When filtering, I want to see JUST one of the scenarios below. I only want to filter by the CHILDREN. not the top level, because filtering by the parent category is moot.`

**Comment by rowasc** [comment]
@crcommons @aoduor if I do check the parent, it should select all its children, right? (but not the other way around)

**Comment by crcommons** [comment]
I believe so, yes

**Comment by aoduor** [comment]
this is p0 now. Geo team is unable to see what the need to see...

**Comment by Angamanga** [comment]
Looks like this is fixed in sandbox, not in production.

**Comment by willdoran** [comment]
Passes QA for me
