### ISSUE TITLE
Background of postcards should be tappable

### ISSUE THREAD

**Issue by justinscherer** [ushahidi/platform#2273]
### Expected behaviour
![group 2](https://user-images.githubusercontent.com/29209303/32293227-21453c52-bf08-11e7-978b-ebe5edc8a006.png)

Clicking on the pink area should select the postcard.
### Actual behaviour
![group1](https://user-images.githubusercontent.com/29209303/32293233-232a8478-bf08-11e7-8f11-cf7c002a4cde.png)
### Steps to reproduce the behaviour/error
Try to click on the grey background of a postcard. The postcard will not become active. 

##### Where
- [ ] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [ ] Ushahidi.io / SaaS solution 
- [ ] Ushahidi's QA environment
- [ ] Other (explain):

**Comment by crcommons** [comment]
@middle8media This will need to be a change on the styling for the postcard. You can see in the screenshot below that the padding of the outer postcard element is causing the clickable area to shrink. We need to keep the click event on the inner element so that the meta-data isn't clickable. If you change the outer element to have no R and L padding and give R and L margin to the inner element, it should work correctly.

**Comment by kinstelli** [comment]
I was poking at this and starting thinking that if the header is the only part that shouldn't accept the select event, is it possible to clarify that visually, maybe with a divider or different color? I find myself clicking the areas above or beside the metadata, (okay, maybe I'm the only one who does this), and it's not visually obvious to me why that shouldn't also select the card.

Otherwise, among the items in the header, is it only the dropdown button that shouldn't accept a select event? If that's the case, maybe there are other ways to prevent that event from happening just for that button?

**Comment by crcommons** [comment]
@justinscherer What do you think about Mark's idea?

**Comment by justinscherer** [comment]
@kinstelli  

> Otherwise, among the items in the header, is it only the dropdown button that shouldn't accept a select event?

That's right. The ellipses icon accepts a different event (opens the dropdown). Otherwise the whole card background and everything on top of it is tappable to select the card. Does that make sense?
