### ISSUE TITLE
A saved search should behave like a collection of filters

### ISSUE THREAD

**Issue by justinscherer** [ushahidi/platform#2276]
### Expected behaviour
![filter open with saved search](https://user-images.githubusercontent.com/29209303/32294869-22a207ba-bf0d-11e7-8fd4-6e665827d0fd.png)

- [x] Filters within a saved search are show as subordinate to the saved search
- [x] There's no unlabeled star icon
- [x] Closing the "saved search" bug clears all the filters associated with it
- [x] Closing one of the bugs within the saved search brings up the "Save search" CTA below (i.e. "you've changed this save search, would you like to save it") <--not shown
- [x] Removing one filter from the saved search should only remove that filter, not all related filters
- [x] Adding a filter should not add it to the UI of the saved search; it should be added below the saved search but separate from the saved search
- [x] When you update a saved search; any new filter bugs should be added to the saved search UI

### Actual behaviour
<img width="1679" alt="screen shot 2017-11-01 at 2 03 30 pm" src="https://user-images.githubusercontent.com/29209303/32294986-7c77919c-bf0d-11e7-953c-260776201020.png">

Using the star icon brings up the filters associated with a saved search in the wrong layout (they should list horizontally and wrap, not list vertically with one per line)

Using the saved search dropdown brings up a saved search bug, but with no child bugs.
<img width="1672" alt="screen shot 2017-11-01 at 2 04 44 pm" src="https://user-images.githubusercontent.com/29209303/32295041-b28d1a86-bf0d-11e7-8c50-80cf0da9325c.png">

**Comment by rjmackay** [comment]
@middle8media I think we'll need you to take a look at the styling for this. Particularly the styling for showing filters as subordinate to a saved search - I don't think that pattern exists at all.

**Comment by Angamanga** [comment]
@justinscherer Is this line supposed to be there or is it just a guide?

**Comment by justinscherer** [comment]
The line is supposed to be there.

**Comment by Angamanga** [comment]
The patterns for this is in PL-tag v3.7.2-rc.23 but the behaviour needs to be implemented in the client

**Comment by rowasc** [comment]
@justinscherer @jshorland  sorry we probably already discussed it, but with this change the user wouldn't have access to the saved search URL anymore, since they cant go to it in the modal after we remove the star icon. Is that ok? Is there any alternative? 
Steps to reproduce what we would "lose" : click star icon. See list of saved searches. Click on a saved search.  (There won't be a way to click on it and go to a saved search url anymore) 

Thanks. 
cc 
@rjmackay  this is what you asked in the chat, documenting here so we get to a decision

**Comment by rjmackay** [comment]
@rowasc I chatted with Jess. Its ok to just lose the link to saved searches. We'll add an issue to the backlog for a generic 'sharable url for any search'. Leave the routes in for now in case we want them in future.

**Comment by aoduor** [comment]
Trying to catch up on this thread and related issues. Forgive me if this has already been answered and I missed it, or it’s just plain wired, but...

With these changes, where would users gain access to existing saved searches then?

**Comment by rowasc** [comment]
@rjmackay ok great to know. Thanks! 
@aoduor I think we only let them do that through filters with this decision? cc @jshorland 

A couple other things I had not really thought about before. 
- when a user updates a saved search they are taken to /savedsearches/:id in data map view, do you think we should remove that redirect and just leave them in the same url as they were but with the same saved search applied? -I think YES, to avoid confusing the user more ? -

- right now the mode context bar appears only in the saved search urls, so we should make it so that the mode context bar appears (in the map) when you change your selected saved search in the dropdown filters too. Right?  - since they can't go to a saved search link anymore directly - @jshorland

**Comment by jshorland** [comment]
@rjmackay ok great to know. Thanks! 
@aoduor I think we only let them do that through filters with this decision? cc @jshorland 
---> yes. they access them at the top of the filters drop down box


A couple other things I had not really thought about before.

when a user updates a saved search they are taken to /savedsearches/:id in data map view, do you think we should remove that redirect and just leave them in the same url as they were but with the same saved search applied? -I think YES, to avoid confusing the user more ? -
---> yes! lets no redirect them if we dont have to

right now the mode context bar appears only in the saved search urls, so we should make it so that the mode context bar appears (in the map) when you change your selected saved search in the dropdown filters too. Right? - since they can't go to a saved search link anymore directly - @jshorland 
---yes. good catch

Also, as I understand it, we should redirect to normal map/data view with that saved search selected when you access a saved search URL, just for consistency/backwards compatibility to people who already have a bookmarked url. is that right?
---> CORRECT! 

Boom. Good stuff @rowasc

**Comment by rowasc** [comment]
Awesome. Thanks. Back on this  now

**Comment by rowasc** [comment]
- working on branch:  `3745-saved-searches-hierarchy`

@willdoran is looking into improving diffing and two bugs: 
- text treated as array (order by, order, other keys)
- helping/integrating with the saved search button from the other ticket with @crcommons 
- ? something else?

@willdoran @rjmackay I am really unsure about this in general, but I tried to leverage the fact that we still have getMode/setMode because it avoids using the filters as a way to have a saved search that has filters which was creating some messes and things are much easier to follow that way. I think it's better conceptually than using the savedsearch as a filter itself which we had stopped doing already, but I might be wrong =/ hopefully, it's a good enough solution while we wait for state management. 

- I redirect users to map or data when they are in the savedsearches URL as explained below. But, the problem is that we don't resolve the modecontext view based on params (and I have no idea how to do that :( ) so the mode context is not correct in that scenario. Can you check for a way to do that?  
(Note: since this would also affect us when you change searches in the dropdown, it's relevant as a bug even if we were not redirecting)

**Comment by rjmackay** [comment]
@rowasc please create a PR for work so far. Its much easier to comment directly on the code.

In principle leveraging setMode to track more of filter state makes a lot of sense. I haven't had a chance to review the code in depth yet though

**Comment by rowasc** [comment]
https://github.com/ushahidi/platform-client/pull/933
WIP PR sent here, I'm annotating as I go since it's up for tons of discussion :/

**Comment by Angamanga** [comment]
Passes QA
