### ISSUE TITLE
Allow for multiple deployments to belong to one organization BETA

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#2283]
Ultimately, the org admin needs to align information, expectations, etc. across multiple deployments, stakeholder, media, etc. She needs to be able to pull this thing up in a meeting, or throw a screenshot in powerpoint and have it get a point across quickly. She needs to have a sense of what's going on at a high level. 

She needs to feel like she's in control of these deployments. So we don't want to dumb down the information too much

- As an organization admin, I want to be able to "own" multiple deployments that belong to my org
- As an org admin, I want to see each deployment with high level stats that are important to me 
- As an org admin, I should have admin privileges on each deployment that belongs to my org
- As a deployment admin, I should only have admin privileges to the deployment I created as the original admin and/or any deployments to which an org admin or other deployment admin give me admin rights
- As an org admin, I want to "add" already existing deployments to my organization 
- As an org admin, I want to "remove" deployments from my organization
- As an org admin, I want to add other org admin users
- As a deployment manager, I want to see what organization my deployment belongs to
- (MAYBE) As any user, I want to be able to see all other public deployments that belong to the org

High level dashboard of stats (brainstorm)
- Number of surveys
- Number of posts (aggregate? Within each survey?)
- Number of contributors
- data sources?

This is only for enterprise users at this point, so it’s important to note that for this version, we could handle set up on the backend instead of developing interfaces for every interaction that needs to happen in the set up, etc

Aha! Link: https://ushahiditeam.aha.io/features/PROD-489

**Comment by jshorland** [comment]
First sketches:

the most basic thing we can do for now is just show deployment modules in a vertically scrolling list. When we deploy this and get a better sense of what these types of clients actually need, we can start developing more modules for this view, worry about sorting, searching, and all the other crap we worry about with the reports themselves.

**Comment by jshorland** [comment]
Jess's thoughts/questions: 
- might this be a good opportunity to change from "deployment" rhetoric?
- I think the most important things to focus on in this version is the behavior of the cards, switching between dash view and deployment view, and the permissions of the org admin vs. deployment admin
- we should be forward thinking around what org admin will need/want to customize in the dashboard in the future. 
- we should also be considering a future in which there aren't even standalone separate deployments, but rather "walled gardens" within a single deployment depending on your location, your department in the org, or etc etc. Are there things we can/should do now or in the near future to make that possible?

**Comment by justinscherer** [comment]
Question for @jshorland 

If an Org admin adds a pre-existing "Project" (instead of deployment) which already has a paid plan (say they have a 99/mo plan), what happens to the pricing model of the project added? Does it change? Is it still managed separately within the child project? Or does the parent org inherit the project's costs somehow? Case-by-case basis?

**Comment by justinscherer** [comment]
Another question:

If you add a pre-existing project to an Org, and then remove it, do you remove it from the org only, or do you delete the deployment completely?

My initial feeling is that once a project is part of an org, the org has complete power, and removing it, removes it from everywhere.

**Comment by justinscherer** [comment]
Another question:

What are the permissions of adding a pre-existing project?

If an org wants to add a deployment for which you are an admin, do you have to give the org permission somehow? My initial feeling is yes, otherwise we let orgs just add deployments willy-nilly.

One option: we send an email to the existing project "owner" (is there a role for which there is only one per deployment? Because there can be multiple admins) with "Accept" / "Decline" binary CTAs. 

This org "takeover" of existing projects is pretty complicated, contractually, right? What if there's a hostile takeover of Ushahidi projects by some renegade org client? I might advocate we push this feature until we are sure our client orgs need it and it involves too many deployments to do manually, and we deal with the complexity then...

Thoughts @jshorland ??

**Comment by justinscherer** [comment]
After thinking through the design of team management features a bit: changing roles within child projects, bulk invites, etc. It would also deviate a little bit from the way we do user management within projects now. I also think there are some new use cases that are org specific that we don't have for projects right now. 

I wonder if we don't include these features for now, and refactor team/roles management in both projects and org views.

That would limit our scope for the end of the year strictly to the display of multiple projects within an org's dashboard with some interesting data for each, the ability to add net-new projects, and the ability to shut down projects that you've added already. 

@jshorland what do you think?
