### ISSUE TITLE
Child categories are in the wrong color when child selected but parent is not

### ISSUE THREAD

**Issue by rjmackay** [ushahidi/platform#2310]
### Expected behaviour
Child categories will use 'selected' color/opacity when selected, even if parent is not selected

### Actual behaviour
Child categories use 'deselected' color/opacity when selected if parent is not selected

Follow up to: https://github.com/ushahidi/platform/issues/2308

**Comment by rowasc** [comment]
Closing. 

This was addressed in the categories refactor 2018 in a different way and is no longer the same UI. Now you can select a child category even if the parent is not selected, it selected the parent automatically if you select all its children, and it won't let you unselect all children and keep thee parent (since that'd be weird when we mean "any of these categories that belong to this parent" by selecting parents)
