### ISSUE TITLE
Moving from collection to saved search does not update url

### ISSUE THREAD

**Issue by Angamanga** [ushahidi/platform#2323]
### Expected behaviour
When I move from a collection to a saved search, the url should update accordingly
### Actual behaviour
The collection-url is still visible although I am looking at a saved search
### Steps to reproduce the behaviour/error
1. select a collection with dataview as default
2. select a saved search, click apply filters
3. look at the url, its still the collection-url

##### Where
- [ ] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [ ] Ushahidi.io / SaaS solution 
- [ ] Ushahidi's QA environment
- [ ] Other (explain):

Aha! Link: https://ushahiditeam.aha.io/features/PROD-475

**Comment by rowasc** [comment]
@Angamanga @rjmackay yea. That's expected right now :( Robbie and I discussed it a couple days ago.. and we're still kind of trying to figure this one out. Basically, there are a lot of decisions to make regarding collections.  The URL after you change to a saved search is no longer affecting you tho, so that's good. (confusing .. but, good)

**Comment by Angamanga** [comment]
@rowasc Just adding the last finds I could find after testing, probably low prio though :)

**Comment by rowasc** [comment]
ha yea I know :) sorry I was just nothing this to make sure that we had context . Thanks @Angamanga !
