### ISSUE TITLE
Filter "bugs" should flow like tags

### ISSUE THREAD

**Issue by justinscherer** [ushahidi/platform#2386]
### Expected behaviour
Filter bugs should flow to fill the horizontal space available before breaking to the next line. 
### Actual behaviour

<img width="1088" alt="screen shot 2018-01-02 at 4 40 23 pm" src="https://user-images.githubusercontent.com/29209303/34504405-a875b6f8-efdb-11e7-9392-38aae86f3a02.png">

Aha! Link: https://ushahiditeam.aha.io/features/PROD-455

**Comment by Riju19** [comment]
Hi, I would like to work on this issue

**Comment by muchirijane** [comment]
Hey, @Angamanga Could I work on this issue if it's still open.

**Comment by Angamanga** [comment]
@Riju19 @muchirijane Sorry this issue is outdated. Closing it. Please check out this link if you can find something else you are interested in: https://github.com/ushahidi/platform/issues?q=is%3Aopen+is%3Aissue+label%3A%22Community+Task%22 We are adding more issues continuously but due to the large interest in Outreachy this year we are lagging behind. Please bear with us :)
