### ISSUE TITLE
Merge forms + stages + attributes into a single API resource

### ISSUE THREAD

**Issue by rjmackay** [ushahidi/platform#2392]
Iteration 1:
- Hydrate stages & attributes when returning a form (by default)
- Stages and attributes are read only in forms API

Iteration 2:
- Accept updates to stages and attributes via forms API

Iteration 3: (after some delay)
- Deprecate and finally remove old APIs. Or at least make them read only.

Question:
- Should this be a new 'survey' api?

Aha! Link: https://ushahiditeam.aha.io/features/PROD-453

**Comment by willdoran** [comment]
It might be worth considering whether we always want to hydrate these objects or whether it's context dependent in order to reduce data weight but perhaps that's an improvement in a future iteration?

**Comment by rowasc** [comment]
Iteration 1:

Hydrate stages & attributes when returning a form (by default)
Stages and attributes are read only in forms API
Iteration 2:

Accept updates to stages and attributes via forms API

Possibly Iteration 3:
Maybe add includes=? and any other fancy features we need to add the possibility of getting only what we want in these objects

Iteration 4: ( after a long delay and warnings of deprecation)

Deprecate and finally remove old APIs. Or at least make them read only.

> Question:

> Should this be a new 'survey' api?

mmmmm that might be a good idea  yea.
 
@tuxpiper what do you think about this?

**Comment by tuxpiper** [comment]
Ohh, API design, the mother of all developer discussions 👏  😁 

I think...

If there is an immediate benefit to Iteration 1 , I would suggest to go ahead with it, but in a way that will not break any (reasonably designed) API client . So no existing attributes would be affected and clients that know how to take advantage of the additional data, can just do that. This can take the shape of an additional parallel attribute in the response , or an enabling flag (just like Stripe API's  `?expand=true` )

Iteration 2 sounds like a transition to a different way of handling surveys.  Allowing CUD on the whole form-stage-attribute tree via a single endpoint, as a coherent object, means we have a different REST resource. So indeed this should be presented separately (`/api/v3/survey` sounds good to me)

From then onwards, it looks like we may be introducing deeper changes to the whole API philosophy? We could look at existing approaches (for example, JSON-API : https://jsonapi.org/format/ ). Ideally this would be something prominently featured in a roadmap and discussed with as many people as possible. My guess is that it would be a totally new, namespaced, version (`/api/v4` ?)  . I would say deprecation of forms, stages and attributes resources may be a part of that move as well.

**Comment by rowasc** [comment]
>If there is an immediate benefit to Iteration 1 , I would suggest to go ahead with it, but in a way that will not break any (reasonably designed) API client . 
Yea, basically this, I believe this is a super good thing to do and it's not very expensive to implement , but we absolutely should avoid breaking the client with it. 
 I am leaning towards doing it in a new /survey endpoint instead of expand=true because its what we would do for iteration 2 as you mention.

If you feel we would benefit from having this discussion In a call, that's totally ok with me as well, since I'd like to get this spec nailed down and documented so I can work on it when I have a chance.

----------


After iteration 2, I think you're right on this and it needs a larger discussion with more folks, since it's a much larger scope of work that deserves engagement from many people and a dedicated roadmap space if it gets done (plus it's also unlikely to get much attention until we resolve many other issues).

**Comment by kinstelli** [comment]
Hey all, I keep getting email alerts for this thread, since I was tagged on it 1.5 years ago. :D 

I don't know if it's worth looking at (quite possibly no?) or if you've already looked at it, but @dalezak, Robbie and I ended up discussing this in Slack way back when, and we drafted up a few example API schemes that should still be sitting around in there. (I don't have access anymore :'( ). This took a back seat to other priorities, of course, but if glancing at it saves either of you a few minutes, or at least provides a concrete starting point from which to discuss further details, I'd be glad to have helped out.

**Comment by rowasc** [comment]
Hey @kinstelli yea, I remember that discussion. Thanks 🙌

**Comment by tuxpiper** [comment]
@kinstelli  just saying hi :wave: and thanks!

**Comment by tuxpiper** [comment]
@rowasc 
> I am leaning towards doing it in a new /survey endpoint instead of expand=true because its what we would do for iteration 2 as you mention.

ok, either way works for me actually 👍  I have the feeling that the final decision will actually depend on what the representation of the object will exactly end up looking like.

**Comment by rowasc** [comment]
@tuxpiper yea, pretty much. OK I'll edit the spec after I'm done with some 🔥 thanks
