### ISSUE TITLE
As a deployment manager, I want the option to prevent visitors from exporting data. 

### ISSUE THREAD

**Issue by rowasc** [ushahidi/platform#2404]
### Acceptance criteria

- [ ] I can turn on data export
- [ ] I can turn off data export
- [ ] This is an option in the settings menu

# Tech spec notes
- [ ] Should be a global setting, saved in the database (config table?)

## Persona
Visitors: they are `logged in` users in deployments who want to extract publicly available data. These are often researchers/students who want to use the data to academically refute or validate hypotheses.

In addition to limiting permissions to field responses, Campaign for Tobacco Free Kids would like to block the public from being able to download the CSV file of their deployment data since they forsee collection of sensitive data.

**Comment by rowasc** [comment]
@kinstelli Assigning you as discussed. This one is pretty simple.

**Comment by rowasc** [comment]
TODO figure out where in the design this is done

**Comment by rowasc** [comment]
@Erioldoesdesign I can't find this in the designs. Is it designed?

**Comment by Erioldoesdesign** [comment]
![new-data-export-field](https://user-images.githubusercontent.com/11681324/35825234-125cdce0-0aad-11e8-884f-af936c43082c.png)

I added in a new checkbox with the label 'Data Export' to the list that exists when you edit a 'role' where an admin would be able to remove/approve the use of the Data Export function.

`<div class="form-field checkbox" ng-repeat="permission in permissions" ng-if="role.name != 'admin'">
                           <label for="5">
                               <input id="5" type="checkbox" value="permission.name" checklist-value="permission.name" ng-model="checked" class="ng-pristine ng-untouched ng-valid ng-not-empty" checklist-model="role.permissions">
                               Edit their own posts
                           </label>
                       </div>`



Since this isn't in the cycle let's check when @justinscherer is back to see if this would be how he'd solve this too.

Also what the user with restrictions would see if they tried to access Data Export:
![export-denied](https://user-images.githubusercontent.com/11681324/35828781-b342ee00-0ab8-11e8-8675-37d970bf66c2.jpg)

**Comment by Angamanga** [comment]
@rowasc @kinstelli Are you working on this? If so, could you move the issue to the correct column and if not could you deassign yourself?

**Comment by rowasc** [comment]
Nope this isn't in progress. I'm not really sure why it's part of cycle 4 actually since it's a P2?

**Comment by rowasc** [comment]
This was implemented through the "Data Export & Import" permission since we didn't want to add another new permission and make it more confusing. While there could be support for a more granular version, I think this should be enough for most use cases. Closing for the moment. .

**Comment by Erioldoesdesign** [comment]
Hmm I would argue that there is a way to stop exports from visitors and it's making posts/the deployment private...

I would also argue that if you are a grassroots org, then unless you're collecting sensitive data (which you really shouldn't be and we should be helping to educate people on data privacy on their deployments...) then Ushahidi should have access to that deployment to learn from and/or it should be publicly available.
