### ISSUE TITLE
SMS platform research + scoping

### ISSUE THREAD

**Issue by rowasc** [ushahidi/platform#2420]
Research needed to decide next steps on SMS development
@willdoran please add any details that might help here

**Comment by willdoran** [comment]
Current next steps:

1. Justin to complete first round of designs by EOD 02/02/2018
2. Eriol to iterate on these designs and do basic first round tests
3. Justin and Eriol to test designs beginning 12/02/2018

**Comment by jshorland** [comment]
Original scoping doc https://docs.google.com/document/d/1uUkSG0NsoDTxIkKfmVG6oSX5u1rVOVvAuOoY_E0VaTQ/edit

Designs 
Prototype: https://xd.adobe.com/view/f9cfe17d-55fa-42e1-bb90-3bc67f0956a9/
Design spec: https://xd.adobe.com/spec/ddad4025-b2a8-4d17-aeef-946283d18b7a/

**Comment by jshorland** [comment]
Questions/concerns to address during planning week:

My big question is, do we _really_ need to separate `Open` vs `Targeted` Surveys?

The Targeted Surveys aspect is where a lot of my concerns come from, because we're basically creating a separate Survey type which only supports plain text questions and is only accessible via SMS.

I think we've made the assumption, that this NGO-type use cases wants to keep it separate, however our platform _already_ supports several ways to distinguish different types of responses.

One is the `source` attribute, which the web client and mobile app submits, is displayed in the card and details as `via Web` or `via Mobile`. The SMS engine could set that value to `sms`, which means we could filter survey responses from their different sources.

Second is the `approval` option, where responses are not visible until they been _Approved_. If a Survey receives responses from both SMS and Web, then the deployer/manager has the option to only approve the SMS responses, if that's what they want to see.

I believe, using either/both of these options, would greatly outweigh the overhead for managers having to creating separate SMS vs Non-SMS Surveys, and avoid potential tech debt on platform of diverging Survey types.

cc: @dalezak

**Comment by caharding** [comment]
@willdoran can you confirm that this ticket should be closed in favor of the EPIC? Seems the research is done.

**Comment by willdoran** [comment]
@caharding yep
