### ISSUE TITLE
[Client handle CSV complete/fail event] As a deployment visitor, I want to be able to download my CSV after I'm notified that it is ready

### ISSUE THREAD

**Issue by willdoran** [ushahidi/platform#2442]
### Spec
Client: 
 - [ ] On receipt of File ready event display success notification formatted according to design
 - [ ] On receipt of Error state display error notification formatted according to design
 - [ ] Enumerate error states
 - [ ] Provide a path for QA to reach error state for testing purposes

### Test
- [ ] Request a data export for a small data set<define size>
  - [x] You should see a notification informing you that your export is in progress
  - [x] Within a reasonable time frame(less than X mins) you should receive a notification as shown below:

   <insert screen of notification of export success>

  - [x] There should be a link to the downloadable export file
  - [x] When you click on this link the file should download
  - [ ] When opened the file should contain the expected data 

- [ ] Request a data export for a large data set<define size>
  - [x] You should see a notification informing you that your export is in progress
  - [x] Within a reasonable time frame(less than X mins) you should receive a notification as shown below:

   <insert screen of notification of export success>

  - [x] There should be a link to the downloadable export file
  - [x] When you click on this link the file should download
  - [x] When opened the file should contain the expected data 

 Note: Need to provide way to cause fail event to test error messaging, possible disabling feature on API

**Comment by StaicyG** [comment]
@willdoran issue #2442 only passed the first test.
Please expound on what the "error below" is from "Within a reasonable time frame(less than X mins) you should receive a notification as shown below:"
It takes too long to export the data (around 2 hours) and even after waiting for that long your session expires so you have to redo the steps again. Due to this the export never completes both for small data set and large data set.

**Comment by willdoran** [comment]
@StaicyG I created most tickets but I am not necessarily owner of the specific issues. I'm not sure how we can capture who the right person to contact is

@rowasc @kinstelli Do you guys have any idea why the download would be taking two hours, is that normal? Does it indicate that the jobs might not be running? Or may be there is something with the job deployment?

**Comment by rowasc** [comment]
@willdoran when I tested they were taking ~5 minutes which is how QA was configured to run. 
From reading Stacy's comment, I'm concerned there might be some kind of mistake in the deployment tho. 
> It takes too long to export the data (around 2 hours) and even after waiting for that long your session expires so you have to redo the steps again

We have a history tab for this exact reason, so people can go and download it whenever they remember to download it, even if their session expires. The links last ~24hs so even then they should be fine.

@StaicyG can you paste the deployment url here? Is it "csvexportforever"?

**Comment by kinstelli** [comment]
@willdoran , @rowasc 

Some observations so far:
1. I don't see evidence on platform-export-qa to indicate that anything has been received from platform-job-queue:
- Per the queue logs on platform-export-qa, and the last job run was apparently on the 14th.
- Per the nginx logs, no calls have been received that look relevant (lots of scripts looking for phpmyadmin, though...should we whitelist IPs?).

2. Logs on platform-job-queue aren't helpful, since we're mostly logging errors, (maybe it's worth adding a success log, at least until we're certain this process is stable), but I don't see any evidence of CSV tasks running. The only thing I do see is `Error Deployment csvexportsforever has status migrating`.

**Comment by willdoran** [comment]
@StaicyG Can you retry we believe this should be working now?

**Comment by StaicyG** [comment]
@willdoran thanks for the heads up. Yes I agree we need to have a way of tagging the owner of the specific issues to make it easier for follow ups. 
I have tested it and it works fine now. Thank you. I shall run the test again.

**Comment by StaicyG** [comment]
@here 
Test 1: for the small data set:
The second column on the left reads "Import" instead of export
After selecting select data to export, a list of the fields to export appear but are not clickable or selectable. 
After clicking on "Export button" an error message displays because no data was selected

Test 2: Large data set
After opening the export file, the title for each column isn't visible hence difficult to know if all the data needed has been downloaded.

**Comment by kinstelli** [comment]
@StaicyG  - Sorry again for reassigning this, but can you try this again now that the data on the server has been updated?

**Comment by StaicyG** [comment]
@willdoran 

Test 1: Small data set. After exporting select fields from the deployment, the CSV file still has all the fields from the deployment and not just the selected ones. Therefore CSV file doesn't display the expected data.

**Comment by willdoran** [comment]
@StaicyG thanks, @kinstelli do you know this one?

**Comment by kinstelli** [comment]
@willdoran -- I see this requirement is spec'd in #2405, but I don't know if the API side of this was built.
@Angamanga , @rowasc : Do you know if there's a corresponding API piece for this? ("After exporting select fields from the deployment, the CSV file still has all the fields from the deployment and not just the selected ones." )

**Comment by rowasc** [comment]
@willdoran @kinstelli this was the "include"/"exclude" feature. In theory it was already built in the api, yes
