### ISSUE TITLE
Extend Post Exporter CLI Capabilities

### ISSUE THREAD

**Issue by willdoran** [ushahidi/platform#2443]
### Overview
This is the tool which physically loads, formats and outputs the Posts. 

### Spec
API:
- Post Exporter 
  - [ ] should handle filters to limit export data
  - [ ] should be use correct formatter to ensure fields are correctly formatted
  - [ ] should ensure data is written to file to avoid memory exhaustion
  - [ ] should return address of file created for the chunk it is responsible for
  - [ ] should correctly close file upon completion

### Test
- [x] Post Exporter CLI should accept filters
- [x] Post Exporter should output file with fields correctly formatter
- [x] Post exporter should output file with correct header column names
- [x] Post exporter should output file for only the chunk it is assigned

**Comment by kinstelli** [comment]
Should we include "should accept a set of column names in order to limit export data"?

**Comment by willdoran** [comment]
I think that should be handled by filters.

**Comment by kinstelli** [comment]
I'm not sure if this is more relevant to the CSV exporter tool, or if it's an issue with the creation of CSVs to begin with, but since this is a problem that exists at the 200-row line -- which is where each chunk is divided -- I think this might be related to the exporter. 

In short, the number of columns is different for the first export than it is for the subsequent chunks. See the ID column (column M) in this spreadsheet. The IDs exist in this column for the first 200 records, but as you scroll past line 200 and all subsequent records, this ID is moved to 
column J.

It looks like three of the eight columns showing M are getting truncated on subsequent exports, but unfortunately, that's not clear from our data set:
https://docs.google.com/spreadsheets/d/1e0svJkSYSpei6J-d4oTiOcQhSUn9gsfMhsdYAEQ70cI/edit?usp=sharing

**Comment by willdoran** [comment]
We should hold off on any implementation of removing empty columns it would be a complex piece of work for us to do whereas removing empty columns from any data analysis application is trivial. For me, this crosses a line into data cleaning which is not what we do. We are responsible for ensuring the data is in an intelligible consistent format.

@romina We should ensure that each of the files generated is consistent in terms of number of columns. Is there an issue where we are dropping/including columns dependent on filtering when generating the individual files?

**Comment by kinstelli** [comment]
Closing this as the original spec is complete. Issues related to appear to be defined in  #2730 and #2739
