### ISSUE TITLE
Port COMRADES features to core / v4

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#2509]
Ushahidi wants to incorporate COMRADES features into Platform Core. This issue stands in for those features. 

Productizing COMRADES pilot that enables automatic categorization and annotation of a post within an Ushahidi deployment. Vision: Significantly reduce the human effort needed to make data useable and auditable within their deployment.

Aha! Link: https://ushahiditeam.aha.io/features/PROD-425

**Comment by caharding** [comment]
@justinscherer for you to break down and prioritize what we could do in a cycle

**Comment by justinscherer** [comment]
## High-level design effort estimation

### Display meta information about results from ML tools

We could probably do a quick-ish version of this that would fit in a cycle, but I'd so badly want to expand it to be the first step in the overall, "make structuring suck less" vision. 

### Comrades: Data Filtering

This one will probably need a couple cycles because it will be nigh impossible to user test without actual live data. Also our filtering in general is a mess. User created labels (i.e. folksonomic tagging) could get really complex. 

### Map should support >30k geo points

Can we *please* add some sprucing up to this? E.g. better looking baselayers from Mapbox, improving map usability, refactoring our POI indictors. 

### 2chaguzi Facebook Bot Improvements

This can be done in a cycle I think

**Comment by Angamanga** [comment]
Archive but do NOT forget them if the need for those features comes up!
