### ISSUE TITLE
Importing CSV doesn't allow assigning multiple categories to a post

### ISSUE THREAD

**Issue by tuxpiper** [ushahidi/platform#2593]
### Expected behaviour
If a post has to be related to multiple categories, it should be possible to reflect this in a CSV file for importing.

### Actual behaviour
There's currently no CSV column formatting or mapping that platform can correctly parse to understand that the post needs to be assigned to multiple categories.

Only one category can be assigned to each imported post.

#### Is is ready for development when
- [ ] Has a description that includes purpose of this particular feature/improvement (how it will help the user and for which use cases)
- [ ] Can be delivered within a sprint (make sure issues are small pieces of work, not huge epics)
- [ ] Has all designs and UI assets available
- [ ] Has all (probable) dependencies identified
- [ ] Is estimated by the team
- [ ] Has acceptance criteria defined (do we want to do this before we send to dev? might help us identify dependencies/holes earlier?)

##### Where
- [x] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [x] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [x] Ushahidi.io / SaaS solution 
- [x] Ushahidi's QA environment
- [x] Other (explain):

Aha! Link: https://ushahiditeam.aha.io/features/PROD-411

**Comment by tuxpiper** [comment]
I believe this will affect importing any data types that can take multiple values: multiple select lists and checkbox lists .

The essence of the problem is this:

While the CSV import code in the API assumes that any multiple values will be spread across several columns in the CSV ... the UI doesn't have any way for the user to specify a mapping of multiple CSV columns to a single form value.

**Comment by tuxpiper** [comment]
Closing without merging due to the whole hackiness of it

**Comment by tuxpiper** [comment]
Convo from slack:

@rjmackay dixit:
> options that [would accept comma separated values in a single column, i.e. ("1,2,3")] we can do without too much rewriting, we could:
> 1. explode category values in the post repo. That'd allow us to do this for all category fields.
> 2. allow specifying that a value should be exploded as part of the transformer `map` ie. a map value of `fieldkey[]` instead of just `fieldkey`. We'd need to add a corresponding toggle in the UI ie. `[ ] cell's contain multiple values` when setting up mappings.

@tuxpiper dixit:
> I think for a quick fix, option 1 is good. Maybe just needs to document it to make it more transparent to the end-user, but it would make enough sense.
> Option 2 , that checkbox would only make sense in multi-value type columns (categories, multi-select, checkbox). I’m thinking what would it mean when the checkbox is not selected… that the user should expect they can only import single values in that case?

**Comment by aoduor** [comment]
I'll just leave this here..

![wailing](https://media.giphy.com/media/3ohfFLdE4NeyPQtJbG/giphy.gif)

**Comment by aoduor** [comment]
I'll just leave this here...

![wailing](https://user-images.githubusercontent.com/721918/39246855-67a08da6-48a0-11e8-8a42-ffcf79f6e7e4.gif)

**Comment by caharding** [comment]
@aoduor can you please illuminate the need for this feature enhancement. Where have users been running into it? What use cases is this problematic in?

**Comment by leninpaulino** [comment]
I've been looking at the code and the whole CSV import process. Definitively want to move forward with this one. 

@rowasc  are you okay with the category value of every imported record being exploded by comma if it contains multiple values?

I think we could apply the same logic for any form attribute with unlimited cardinality. 

Regarding the user experience, I think it would make enough sense for everyone. In fact, most spreadsheets software export values containing commas quoted.

**Comment by leninpaulino** [comment]
Update: Performed a small test and it works.

So, wrapping up the solution I suggest:

Refactor this block of code: https://github.com/ushahidi/platform/blob/f00e40bceb95fb52e1f9df1910679336976da30b/src/App/Transformer/CSVPostTransformer.php#L80

As of right now, the purpose of that block is to put all the form attributes (not post fields) in an array.

We could change that block to verify first if the cardinality of that form attribute is unlimited and if we do expect that form attribute to have multiple values separated by comma, transform the value accordingly.

Everything else remains the same.

Let me know if you have any concerns about this approach.

**Comment by rowasc** [comment]
@leninpaulino thanks Lenin for thinking through this one!

@tuxpiper do you have some time this week to check in here with any comments on approach, since I just realized you attempted to fix this already  and had some internal chats about it, but didn't get merged due to being hacky https://github.com/ushahidi/platform/pull/2594/files . 

I think Lenin's approach doesn't require too major of a change to the CSV file's format, and it's relatively intuitive compared to learning how to setup field mapping keys or even the location.lat and location.lon thing....  and may be generic enough to apply to different multi value fields since it uses cardinality to check what needs to go through that process, but would like to see your thoughts. 
I'm not sure if I'm missing something, for instance, that should be configured manually in the UI, since I see the original discussion definitely touched on manually selecting how to map fields, which I would prefer if we could avoid (Imports are confusing enough as it is). 
This should be accompanied by good docs on usage, of course, and maybe an example import CSV, or it'll be useless for the average user.

Thanks

**Comment by tuxpiper** [comment]
@rowasc @leninpaulino  I think it's a pretty good solution, and knowing of the multivalued nature of attributes could come in handy in other parts of the code (as in, it could become an attribute of the value type repo)

I think the main concern is something less related to this specific solution, than it is to how post values are set up to be processed all over the codebase. 

Quite usually, where one feels the need to implement something that works smartly according to the data type one is handling ... the information about that data type is not readily available.

And so, I think that at the point in the code that @leninpaulino is pointing at, all that code is doing is handling raw input data, with blind knowledge of the form, or of the value types that are attached to each of the array keys.

For each iteration of that loop, one would need i.e. to query the value attribute repository by the attribute key, get the specific value repository (i.e. PointRepository) from the factory and then see if it's multivalued or not.

Implemented naïvely, this could be terrifyingly expensive . With a bit of care, and extra lines of code that scream *this is a fix for speed!*, it could probably be implemented nicely ... but one wonders if it wouldn't be better to tackle a more fundamental change first, so that we don't have to keep being smart each time we want to implement something to work efficiently.

> Update: Performed a small test and it works.
> 
> So, wrapping up the solution I suggest:
> 
> Refactor this block of code:
> 
> https://github.com/ushahidi/platform/blob/f00e40bceb95fb52e1f9df1910679336976da30b/src/App/Transformer/CSVPostTransformer.php#L80
> 
> As of right now, the purpose of that block is to put all the form attributes (not post fields) in an array.
> 
> We could change that block to verify first if the cardinality of that form attribute is unlimited and if we do expect that form attribute to have multiple values separated by comma, transform the value accordingly.
> 
> Everything else remains the same.
> 
> Let me know if you have any concerns about this approach.

I think it's an interesting solution

**Comment by leninpaulino** [comment]
Sorry for the late response, I've been kind of busy these days.

I definitely agree with @tuxpiper and I think that's one of the reasons why design meetings are so important for teams. I personally don't like to make fixes for speed, and when I do I always try to point in the calendar the date for implementing the appropriate fix. That way we can avoid ending up drowning in a ocean of technical debts.

Said that, I think we can go over a few iterations on this thread until we all agree on the best solution for this issue.

I have some interesting findings regarding the Import CSV process:

1. The CSV Import starts with the creation of a CSV entity (`POST: /csv`, `CSVController@store`). This happens when the user upload a file and select the form it will map to. The "Choose CSV file" step. The CSV entity is created and the available data is returned to the frontend.
2. Then the user goes to the "Configure imported posts"  and defines the mapping of the file and the default status for all imported posts. When the user finish, a first request request is made (`PUT: /csv/{id}`, `CSVController@update`) which updates the CSV entity and after that a second request is made to the API (`POST: /csv/{id}/import`, `CSVImportController@store`).

    In resume, in the last call we prepare the posts import and some important pieces of the process:

    - We read the records from the stored file.
    - We build the `CSVPostTransformer`, setting how the CSV maps to the posts, setting fixed values, etc...
    - After that we build the a instance of the `ImportUseCase`, setting the records obtained from the file, the CSV entity, and the the already configured transformer.

## Interaction

### ImportUseCase

At this level we perform some basic interaction task:

- Verify the current user can import posts.
- Update the status of the CSV to 'PENDING'.
- Emit the `ImporPosts` event, with the records, the the CSVPostTransformer, the CSV entity and an instance of the Posts Repository.

    Listeners for this event:

    - `ImportPostsListener`

### ImportPostsListener

This is where the actual processing of the post records happens. 

It starts creating a new Set entity to group all imported records.

Then, it iterates over each one of the records:

- Transform the record to a Post entity.
- Validate the post data
- Save it to the database
- Add it to the set

After all records have been processed, it updates the CSV status to success.

### CSVPostTransformer

Transforms the provided record into the appropriated Post entity.

## Draft solution

1. Update the CSV entity to include which of the mapped fields (limited to the ones with multiple cardinality) will accept multiple values. It can defaults to the categories field or let the user select which of the form fields with multiple cardinality are supposed to be treated as multiple values input.
2. Pass the appropriated configuration to the  `CSVPostTransformer`,  indicating which fields it should check for multiple values when processing each record. Transform accordingly (explode by value by comma, trim, etc).
3.  After above modifications the post record can be stored with multiple values for the same field (categories, for example) without any further code modifications needed.

@tuxpiper does this look better?

**Comment by tuxpiper** [comment]
@leninpaulino I think that would work quite nicely!

**Comment by tuxpiper** [comment]
Reopening because #4257 is hackish
