### ISSUE TITLE
Enforce `priority` uniqueness for form, form_stages, form_attributes

### ISSUE THREAD

**Issue by kinstella** [ushahidi/platform#2675]
We are using `priority` to generate followup messages. If two priorities are the same within a survey, then questions could either get skipped, or we will have a condition where the automatic generation of the next question won't be accurate.

### Requirements
- [ ] Ensure that no new records are created with same priority for the same form.

Aha! Link: https://ushahiditeam.aha.io/features/PROD-387

**Comment by rowasc** [comment]
@willdoran @kinstelli we also need to decide how to handle it for pre-existing data. If two identical priority+stage entries are found, which one gets p=0 and which one is p=1? do we decide by attribute id being lower/higher?

**Comment by kinstelli** [comment]
Yeah, that's an excellent point, unfortunately. 

I suppose we could create some tool to reconcile conflicts based on the id (since presumably that would mean sorting this according to the order of creation), but since it sounds like we'd have to update data in _every single deployment_, (i.e., we can't feature-flag a db constraint can we?) maybe a platform-wide database constraint is out of scope for this cycle.

Instead, maybe we can focus on enforcing this via the API -- in other words, checking for potential conflicts before writing the db?

**Comment by rowasc** [comment]
Yep. That's the more sane-ish way to do it right now. 
- enforce via validation rules
- check for duplicate priorities when looking up the next message

**Comment by rjmackay** [comment]
I think ideally we should order by priority *and* attribute ID. So if priority is identical we go in ID order.

**Comment by rowasc** [comment]
I think this was fixed already but need to check. Tagging "Needs triage" for now to come back to it
