### ISSUE TITLE
Anonymization of Reporters Mobile

### ISSUE THREAD

**Issue by caharding** [ushahidi/platform#2685]
Reference #2398 for Client issue

Aha! Link: https://ushahiditeam.aha.io/features/PROD-385

**Comment by crcommons** [comment]
Waiting on Lumen branch, so moving to cycle 4

**Comment by rowasc** [comment]
@willdoran @jrtricafort @dalezak this is needed this cycle to be able to deliver anonymization right? 
@jrtricafort I'm not sure if Dale's availability allows it, but we need to spec this if we want it done. cc @dalezak FYI

**Comment by willdoran** [comment]
@rowasc good catch

**Comment by willdoran** [comment]
We could merge anon and just leave it disabled until some pays us to turn it on so this is not a blocker but would be good to have.

**Comment by rowasc** [comment]
Yea, I think so. We should also check if this is something that would break mobile if mobile does not implement it, and spec it to know what changes we need in the mobile app.
Maybe @dalezak can provide details ?  Dale , did you already implement this somewhere? if that's the case, can you provide a spec or acceptance criteria to add here?

**Comment by dalezak** [comment]
@rowasc the app is currently making use of `hide_author` attribute from the `form`, for example: 
```
{
	"id": 1,
	"url": "https:\/\/dale.api.ushahidi.io\/api\/v3\/forms\/1",
	"parent_id": null,
	"name": "Test Survey",
	"description": "Sample survey",
	"color": "#A51A1A",
	"type": "report",
	"disabled": false,
	"created": "2016-11-21T19:45:45+00:00",
	"updated": "2018-02-27T15:57:18+00:00",
	"hide_author": false,
	"require_approval": true,
	"everyone_can_create": true,
	"targeted_survey": false,
	"can_create": [],
	"tags": [],
	"allowed_privileges": ["read", "search"]
}
```
Does that suffice? Or is there more functionality required to anonymize the reporters?

**Comment by rowasc** [comment]
@willdoran @crcommons @dalezak flagging that we might need to meet and discuss this integration/what impact our changes have in mobile when the platform changes are ready/we know what the path fwd is exactly in the API . Please let me know if monday would be a good day for that or if it would be best to do it later in the week

**Comment by willdoran** [comment]
### Requirements
- [ ] Anon features for Time, Location and Author are integrated
- [ ] PR is merged with Develop
- [ ] Location anon value is configurable via General Settings
- [ ] Anon feature is feature flagged????
- [ ] API config for default location anon value is set

### Notes
- locationHidden is misleading--it rounds it up to a 500 meter radius; it “obscures” location
- Revisit use of “InteractWith” -- maybe worth creating an interactswith directory
- Check hideLocation in point repo
- Invert permission checkers so that things are anonymous by default
- hideLocation should be configurable in the API env settings, and in the future in the settings of the app (change in migrations as well)

**Comment by willdoran** [comment]
@jrtricafort Should this feature be feature flagged or will it be always available?

**Comment by jrtricafort** [comment]
@willdoran Similar to web app, should be always available.

**Comment by jrtricafort** [comment]
@willdoran @crcommons @dalezak circling back on @rowasc 's comment from last week above. Sounds like we need to have a discussion to get on the same page on this, is that correct?

**Comment by willdoran** [comment]
@jrtricafort Yes we should meet to be sure, but I'm not certain what needs to be changed on mobile. The information is redacted on the API side. You can't edit surveys config in mobile, right @dalezak?

**Comment by rowasc** [comment]
Removing from cycle as this is part of V2

**Comment by Erioldoesdesign** [comment]
Adding in comments from my MOZOL 6 project (finally)

Platform user says: Hesitation to automatically record responder mobile location. Responder may not be in the place that it happened and may be reporting it later at home or days/weeks after the incident. Responders should also be notified that their GPS could be used before it is used.

**Comment by tuxpiper** [comment]
Labeling issue for a re-write. As far as I understand, here are the points:

* there's no risk to leaking anonymised data because the data is hidden by the API
* When initialising the map with a GPS acquired location, the mobile app and the web client could be more transparent about indicating that it is the users current physical location is being reflected on the map.
