### ISSUE TITLE
[ErrorException]   The each() function is deprecated.

### ISSUE THREAD

**Issue by TechnoDexx** [ushahidi/platform#2705]
### Expected behaviour
Run Phinx Migration normally
### Actual behaviour
 Running migrations
Phinx by Rob Morgan - https://phinx.org. 0.8.0

using config file ./application/phinx.php

  [ErrorException]
  The each() function is deprecated. This message will be suppressed on further calls

### Steps to reproduce the behaviour/error
1. Install PHP 7.2 , clone Ushahidi Platform repo and run "bin/update"
#### Where does this issue happen?
- [ ] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [ ] Ushahidi.io / SaaS solution 
- [ ] Ushahidi's QA environment
- [x] Other (explain): 
Clone platform repo and prepare it for production (As described in the downloadable manual)

#### It is ready for development when
- [ ] Has a description that includes purpose of this particular feature/improvement (how it will help the user and for which use cases)
- [ ] Can be delivered within a sprint (make sure issues are small pieces of work, not huge epics)
- [ ] Has all designs and UI assets available
- [x] Has all (probable) dependencies identified
- [x] Is estimated by the team
- [ ] Has acceptance criteria defined (do we want to do this before we send to dev? might help us identify dependencies/holes earlier?)

![phinx migration error ushahidi](https://user-images.githubusercontent.com/9976626/38405034-82bc31f0-3976-11e8-9b69-1d5c5b32bc40.png)

**Comment by TechnoDexx** [comment]
We have new version  of Phinx (0.9.2 vs 0.8.0 in our project). Maybe it help to solve my problem. Thank you.

**Comment by rowasc** [comment]
Closing . PHP7.2 is not supported at the moment.

**Comment by tuxpiper** [comment]
I am currently running the tests successfully on PHP 7.2 and also PHP 7.3  .

@rowasc  maybe we should confirm we can support them for the next release?

**Comment by danryu** [comment]
I am attempting to run ushahidi-platform-release-v3.12.3
and when executing installation instructions (where PHP version is not specified)
https://docs.ushahidi.com/ushahidi-platform-user-manual/1.-installing-ushahidi/1.1-installing-the-latest-release
I get the same error when running phinx.php - each() function is deprecated.

Is there a workaround?

As it happens, the docs at
https://docs.ushahidi.com/platform-developer-documentation/getting-started/setup_alternatives/platform_release_install
specify PHP 7.0 - 7.2 as acceptable.

**Comment by tuxpiper** [comment]
@danryu 

mm 3.12.3 is quite an old one already ...  to be clear, the latest docs apply only to the latest release.

In any case, try to see if you can upgrade to a newer version of phinx (I suggest 0.8.1) by changing it in composer.json and running `composer install` . That may help.

**Comment by danryu** [comment]
Thanks @tuxpiper, in fact I've moved to 4.0.0 now, and the packaged phinx version is 0.8.1.
```
# ./bin/phinx -V
Phinx by Rob Morgan - https://phinx.org. 0.8.1
```

I did a clean install with Ushahidi v4 with a new DB, and I came across at least 2 issues:

- `Fatal error: Class 'Memcached' not found` when attempting setup DB migration
Fix: need to specify CACHE_DRIVER=file in .env
This is *not* specified in the docs, either in the release README or the website manual at https://docs.ushahidi.com/ushahidi-platform-user-manual/1.-installing-ushahidi/1.1-installing-the-latest-release

- `each() function is deprecated`
I am using PHP 7.2 which is standard on Ubuntu 18.04 and is apparently supported according to the docs.
However I have to do the hackfix at https://github.com/ushahidi/platform-release/issues/10#issuecomment-415334098 in order to even get ./bin/ushahidi to run from the cmdline.

Re docs and versioning:
I appreciate 4.0.0 is the latest release, but this is very inconsistently tracked in the docs.
The main section of the Ushahidi User Manual starts with a section titled: "Overview of Ushahidi Platform v3.0"(https://docs.ushahidi.com/ushahidi-platform-user-manual/overview-of-ushahidi-platform-v3.0). There are many such examples throughout the docs and also intermingled references to v2. 
Furthermore there are several conflicts between the README and the online installation manual.
For example:
Website: `./bin/phinx migrate -c application/phinx.php`
README: `./bin/phinx migrate -c phinx.php`
Yet more confusingly, some critical information are only in the [platform-release Release Notes](https://github.com/ushahidi/platform-release/releases/tag/v4.0.0) for 4.0.0, and **neither** in the release README **nor** in the online manual.
Eg Updated Database tokens ie `DB_CONNECTION=mysql`
The latest platform release is also v4.0 but the API version is apparently still v3 as reflected by the routes.

Currently, despite the above, I can't get my platform-release to load - I keep getting the error:

> Sorry, something went wrong. Try reloading the page.

in the browser and the error `TypeError: "e.data.errors is undefined"` in the browser console.
Kinda frustrating as I've been at this a while now. What am I doing wrong?

**Comment by tuxpiper** [comment]
Thank you @danryu for all this input. Apologies! We are in the process of amassing and organizing documentation and yep, coming across old documentation is frustrating.

I'm going to open a new issue about this and ping you with updated links and help.
