### ISSUE TITLE
Security Event: Malicious User Hijacking Login Pages

### ISSUE THREAD

**Issue by Brad-Anthony** [ushahidi/platform#2715]
### Expected behaviour
https://research.okap.io site should **not** redirect or display on external domains. The use of proper security headers may resolve this issue...

### Actual behaviour
https://research.okap.io login page is being hijacked to display on http://login.plugemail.net/views/map

### Steps to reproduce the behaviour/error

From Dreamhost tech/security support:
"It does appear that the owner of 'plugemail.net' has configured that subdomain to point to your instance's IP address and that **the configuration of whatever web server you are using on the instance is allowing any domain name to display your site's login page.** Unfortunately, since we don't have administrative access to instances or their data, we are not able to verify this for you. Additionally, since
'plugemail.net' isn't using our nameservers, we are unable to change/remove the custom DNS record for that 'login' subdomain."

#### Where does this issue happen?
- [Y] Other (explain): Cloud server on Dreamhost

Aha! Link: https://ushahiditeam.aha.io/features/PROD-380

**Comment by jrtricafort** [comment]
@caharding labeled this p0 and added to Cycle 3, let me know if you agree.

@willdoran assigning this to you for now since we started discussing on Slack. Feel free to change that.

@aoduor I'll assign to you so that after the change is implemented, you can make announcement to community, does that sound good?

**Comment by aoduor** [comment]
Yes, perfect @jrtricafort.

**Comment by willdoran** [comment]
WIP
Based on Security Headers test for our own .io servers the recommended headers we should add are

**Strict-Transport-Security**
 - This is intended to prevent MiTM attacks when a request on HTTP is bounced back to the browser to redirect to HTTPS. If an attacker is reading outbound HTTP requests or inbound HTTPS redirects on a network they can intercept the TLS connection to the remote server and pose as the victim while passing packets along to the victim in vanilla HTTP. [Here's how to do it](https://scotthelme.co.uk/wifi-pineapple-karma-sslstrip/).

  - This change requires the addition of 
`Strict-Transport-Security: max-age=31536000 to our headers`
Max age should not be 0 as this is disabled rather than infinite. It describes how long the User Agent should consider our policy valid. The setting essentially enforces TLS use. It will prevent any use of HTTP to access our hosted sites. [Complete description](https://scotthelme.co.uk/hsts-the-missing-link-in-tls/).

  - It's worth noting that in a number of countries the use of encryption is entirely illegal, these laws are generally designed as a potential means to enact censorship. When implementing this feature we should be mindful of users who may need to disseminate Posts to individuals in environments of significant censorship, though it would probably be inadvisable in those contexts for users to access such content without the use obfuscation technology.<sup>[1](#footnote1)</sup><sup>,</sup><sup>(#footnote2)</sup>



**Content-Security-Policy**

**X-Frame-Options**
  - This option will prevent framing of the site - for Ushahidi this is problematic to add as it would prevent the ability for embedding of the Ushahidi instance in other sites. There are[ real security concerns](https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Other_embedding_technologies#Security_concerns) around embedding via frames, however, at the moment we will not be adding this header as it will cause significant disruption to users. This should be reviewed as its own separate issue.

**X-XSS-Protection**

**X-Content-Type-Options**

**Referrer-Policy**

<a name="footnote1">1</a>: [The Zone 9 Bloggers are Free: but Ethiopia Still Thinks Digital Security is Terrorism](https://www.eff.org/deeplinks/2015/10/zone-9-bloggers-are-free-ethiopia-still-thinks-encryption-terrorism)
<a name="footnote2">1</a>: [https://www.eff.org/deeplinks/2016/12/crypto-state-law-end-2016](https://www.eff.org/deeplinks/2016/12/crypto-state-law-end-2016)

**Comment by Brad-Anthony** [comment]
@aoduor @willdoran @jrtricafort  I've linked in our security engineer Victor for additional comments.

**Comment by digitalhuman** [comment]
Ok so; because not everybody is aware of these kind of attacks, the OWASP security headers should be default implemented in Ushaidi. But be aware, if the server-side provides the same headers this will create conflicted web-requests and responses and can cause issues in loading CSS or JS files (or any other). Therefor it needs to be well documented and communicated to the end-users.

Personally I think you should raise Content-Security-Policy to 8. This is not an easy one and will cause blocking issues. Especially when using third party content.

**Comment by Brad-Anthony** [comment]
On private deployments or deployments with higher security issues which must **NOT** allow embeds the **X-Frame** option is probably essential. In fact, I think we would be looking to completely disable the embed function or remove it altogether.

**Comment by Brad-Anthony** [comment]
@willdoran @aoduor @rjmackay @caharding @tuxpiper @jrtricafort We're suspending our cloud server to fix the problems so the original issue reference links will no longer be functional. FYI.

Do you want to close this issue or keep it open for comments?

**Comment by willdoran** [comment]
@Brad-Anthony We will keep it open if that's ok as a reference point.

**Comment by aaron-hall-7** [comment]
I've implemented the following in our nginx config as per the above comments.

add_header X-Content-Type-Options nosniff;
add_header X-Frame-Options "SAMEORIGIN";
add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
add_header X-XSS-Protection "1; mode=block";

I've also setup specific vhost files for each of our sites and have disabled the default nginx site which should help reduce people pointing directly at our server(s).  If there are additional headers we can implement, or ones that I have missed, please let me know.

**Comment by Brad-Anthony** [comment]
@digitalhuman @caharding @willdoran @jrtricafort @aoduor Is there a consensus here that these improvements are addressing the critical vulnerabilities?

**Comment by tuxpiper** [comment]
While all the inputs in this issue are great, the originally described issue is actually possible because of the lack of effective CORS restrictions by default. Opened issue #3601 for that .

**Comment by tuxpiper** [comment]
No work to be done directly under this issue, close with #3601

**Comment by timmwille** [comment]
can be closed?
