### ISSUE TITLE
[Platform API] Map HXL tags & attributes to survey fields for an export job

### ISSUE THREAD

**Issue by rowasc** [ushahidi/platform#2805]
### Objective
- There is a way to create a HXL Export with an HTTP Request that includes
    - filters
    - selected_fields
    - field_to_hxl_map (where each form field is mapped to a tag+attributes or to "empty" )

## Acceptance critiera
- Deliver a (working) postman collection to create an export with the hxl tags mapped to attributes
    - Example getting a 422 response
    - Example getting a 200 response
 
#### Modifications to platform API:

- New endpoint /hxl/export
    - form_attributes: all the form attributes, with or without hxl_tags + hxl_attributes. 
        - if the form attribute is not mapped to anything, leave `null` as value
    **Example payload: **

    ```
        [
            {
                 "form_attribute_id": 999, 
                 "hxl_tag": null
            },
            {
                "form_attribute_id" : 1234,
                "hxl_tag": 
                  {
                      "hxl_tag_id": 12345,
                      "hxl_attribute_ids": 
                           [
                               199, 233                                         
                           ]
                   }
            },
            {
                "form_attribute_id" : 1234,
                "hxl_tag": 
                  {
                      "hxl_tag_id": 12345,
                      "hxl_attribute_ids": 
                           [
                               199, 233                                         
                           ] 
                   }
            }
        ]
    ```
    - filters: format as all filters. Include `form_id` corresponding to each form that has fields selected in the list

- New UseCase `HXLExport` extending the `CSVExport` usecase behavior
- New Formatter `HXLExport` using the existing CSV header/value formatting but adding the ability to have the HXL tags as a required row. We do not need to support "up to 25 rows of headers" before the HXL tags row at this time since we do not provide that to our users.
- New Authorizer for `HXLExport` that covers the rules in https://github.com/ushahidi/platform/issues/2858 and works with the cli using the user in the db
- DB  modifications: 
    - Add to export_job table 
        - `type` => options are `hdx`, `hxl_download`, `csv`
        - `hxl_organization` => the organization we want the export to be saved to, if it's a HDX export. This is set per export, not at the user level .
    - Add table: `export_job_hxl_mapping`:
        - `export_job_id` => FK export_job.id
        - `form_attribute_id` => FK form_attributes.id
        - `hxl_tag_id` => FK hxl_tags.tag
        - `hxl_tag_attribute_id`=> FK hxl_tag_attributes.id

**Comment by rjmackay** [comment]
> I suggest we refactor CSV to also send the list always to not have different logic for both which can be confusing.

It might be better to just have a special parameter for `all`. That would work better if we ever set up repeating exports. Also just less ugly than listing *every field*

> There needs to be a separate entity that references job_exports with the HXL tag + attribute to survey field association.

Just checking. You just mean the HXL mappings would be stored in another table?

> Because the user can choose different tags to be assigned in each exports, we cannot simply link survey fields to a specific tag+attributes globally, it has to be for each export

Did you have a plan for handling the default mappings define in survey settings? would the share the same HXL mappings table?

> hxl_datasource_id => the hxl_datasource_id is an id linking to the user's data source configuration (the table where their personal API key is saved)

Couldn't that just be derived from `export_job.user_id`?

Other questions:
- Whats the new endpoint being adding to the API?
- What would acceptance criteria look like for this ticket?

**Comment by rowasc** [comment]
@rjmackay answering: "other questions" 
>Whats the new endpoint being adding to the API?
the one to request a HXL job. Need to define . 
>What would acceptance criteria look like for this ticket?
A short version I think would be this: 
There is a way to create a HXL Export with an HTTP Request that includes
- filters
- selected_fields
- field_to_hxl_map (where each form field is mapped to a tag+attributes or to "empty" )
With the details for each field that I have in the ticket's description . 

+ a detailed test script

**Comment by rjmackay** [comment]
> > Whats the new endpoint being adding to the API?
> the one to request a HXL job. Need to define .

I would hope this could be shared with CSV export ie. so we have a single export job API, you just specify the `type` of export you want.

On acceptance criteria, maybe the deliverable should be a postman collection then? Thats something actually testable and demo-able. And slightly beyond just behat API tests.

**Comment by rjmackay** [comment]
> Yea. I think so. It can get pretty massive. Do you think it's overkill? Should I just save a json in the db and be done with it?

I don't think its overkill. But it might be worth seeing how far you could get without it? What issues come up if its just an optional field on the export job table? (only required if type = hxl)
I do think a new entity would be overkill, even if its a different DB table, we should probably handle it within a single Repo + entity... does that make any sense?

**Comment by rowasc** [comment]
@rjmackay re: endpoint - Yes, you are right that specifying the type might be best.
re: tables => I think that makes sense. I'll think more about that

**Comment by rowasc** [comment]
@willdoran @kinstelli can you review?

**Comment by willdoran** [comment]
@rowasc As well as a formatter, will an authorizer also be needed ?

**Comment by rowasc** [comment]
@willdoran yup good point. Adding

**Comment by rowasc** [comment]
@willdoran we need to add the configuration settings per export here beyond just org name

**Comment by rowasc** [comment]
So there's a few things we need to add in each export that are important to capture when creating the export job. I think we need to just create a table for HDX Exports or alternatively a table for hdx export settings .


<img width="1191" alt="screen shot 2018-05-11 at 4 17 10 pm" src="https://user-images.githubusercontent.com/2434401/39942723-c739be3e-5536-11e8-9036-7e697c8ad62d.png">

- Organization 
- Private/public
- Dataset title 
- Source
- Maintainer
- License
This all have to be saved and right now the spec does not capture that/ .

**Comment by willdoran** [comment]
To recap let me see if I understand what is happening here.

1. We need to define an endpoint that receives:
- Filters
- Selected fields to be included
- Field to hxl tag/attribute mappings

@rowasc Am I correct that in future the same behaviour will be available for both CSV and send to HDX. So the difference ends up being that you just don't get a CSV back if you send to HDX and instead it goes straight to HDX(I am eliding details about what 'it' is for brevity)

2. We need to define a means to stores
- The hxl tag/attribute mappings to their associate form_attributes
- This will be used by the HXL Formatter which will be called by the Exporter a job includes "hxl"?
- We are storing the filters and fields as serialised JSON at the moment so for brevity we should also store the mappings like that
- It would be cool to be able to store form_attribute, hxl_tag, hxl_attribute together as something indexable but I don't think it's super practical right now, there will be an entire v1 before this feature comes even close to prod and any data made by comrades in this context can be recreated as we don't allow people to reuse mappings between jobs.

3. We need to store data specific to this dataset, the hdx "meta data" as shown in the screen shot. 
- Ultimately we will want to suggest some of this data to the User but for now we should assume they will have to fill in user inputted data each time
- This data should be stored in a separate table explicitly for HDX_meta_data, and be linked to the Export_Job
- @rowasc The fields at the bottom look like drop downs, can you confirm they are just input boxes? Or am I crazy?

4. There is a distinction between an export that contains HXL and a HDX export. 
- Type shouldn't be used to differentiate between CSV and HXL this is wrong. All output files are CSV, it is a case of whether or not they contain HXL. This should be an explicit flag, JSON can also be formatted with HXL. 

The Type is CSV, there needs to be a flag related to HXL for the jobs, which determines the inclusion by the formatter of HXL. I don't see any pointing in identifying the type since we only support one type.

The destination of the export needs to be specified this should, we should have a list of available destination or output, right now it's either browser or hdx, though it could also be both in the future.

Please:
 1. Correct my misunderstainding
 2. Tell me anything I missed

I think that we should split this ticket into 4 at least and go from there.

**Comment by rowasc** [comment]
>@rowasc Am I correct that in future the same behaviour will be available for both CSV and send to HDX. So the difference ends up being that you just don't get a CSV back if you send to HDX and instead it goes straight to HDX(I am eliding details about what 'it' is for brevity)

YES

>We need to define a means to stores
>We are storing the filters and fields as serialised JSON at the moment so for brevity we should also store the mappings like that

Alright. This was defined as a table (the one in the spec) because storing this as json didn't really seem like a good idea. But it's ok if we have to go and do it in JSON . 

> We need to store data specific to this dataset, the hdx "meta data" as shown in the screen shot.
> Ultimately we will want to suggest some of this data to the User but for now we should assume they will have to fill in user inputted data each time
This is why we have organization and such as defaults that are saved at the user level


>@rowasc The fields at the bottom look like drop downs, can you confirm they are just input boxes? Or am I crazy?
Mantainer is incorrect. It should be an input. Licenses yeah, that's a dropdown. That's why we have a licenses endpoint.

>This data should be stored in a separate table explicitly for HDX_meta_data, and be linked to the Export_Job
YUP. I think so


>There is a distinction between an export that contains HXL and a HDX export.
>Type shouldn't be used to differentiate between CSV and HXL this is wrong. All output files are CSV, it is a case of whether or not they contain HXL. This should be an explicit flag, JSON can also be formatted with HXL.

Eh. Yea, I guess what you are saying is to change the name of the field. That's ok
>The Type is CSV, there needs to be a flag related to HXL for the jobs, which determines the inclusion by the formatter of HXL. I don't see any pointing in identifying the type since we only support one type.

Right. I know this. The type flag is the export type (of the export job), not a type of file.. to be clear, I don't care about the name, but this is NOT about the type of file. It's there because the export job table is being reused and you have to somehow differentiate between those.. 
>The destination of the export needs to be specified this should, we should have a list of available destination or output, right now it's either browser or hdx, though it could also be both in the future.

Yep ,instead of type, just call it destination

**Comment by kinstelli** [comment]
I'm mixed about whether the HXL/attribute mappings should be in their own table, but I guess I'm leaning to JSON, since according to the HXL description, it looks like it's possible to have several HXL tags mapped to a single Ushahidi attribute (and maybe even vice-versa?) If that's true, then those mapping queries would get ugly. I agree with @willdoran that JSON might capture this better, but could give us the flexibility to adjust in the future.

It also seems like the metadata (i.e., Private/public, Dataset title, Source, Maintainer, License, etc) are generally name/value pairs which seem to change on occasion { [example here ](https://humanitarian.atlassian.net/wiki/spaces/HDX/blog/2016/11/16/29523969/Data+Freshness+Part+1+Adding+a+New+Metadata+Field ) }. So it seems like we'd end up storing this as EAV in a table, but just like above, I'm not sure that's any easier to deal with than JSON :/ 

For the `export_job` table, I'm inclined to add boolean fields like `include_hxl_row` to differentiate from a more vanilla CSV. And if it's true that we might send directly to the browser and/or to hdx, then maybe boolean columns called something like `send_to_browser` and `send_to_hdx`would be clear. 

My name choices or modeling approach aren't strong opinions, though, just added opinions :)

**Comment by willdoran** [comment]
ok thanks for reading and parsing what I wrote for sense @rowasc @kinstelli, repharsing the above to be more clear, does this set cover the pieces of work:

1. Export Meta Data table - this table stores data about the export job and is linked by to the specific export job

2. We extend the current endpoint to take account of optional HXL mappings and to set a flag on an export job related to include_hxl_row, I think the placement of that flag is legitimate because it is closely related to the export job and is in fact a legitimate property that may be invoked irrespective of format or destination.

3. We need to capture the output point for the export, at the moment we have two options, 'directly to the user via browser' or 'directly to HDX', in the future we might want to send it to other places BUT at that point I believe we would need to define a new piece of UX that lets the user setup the destination and/or cross links to webhooks and stores destinations in a table.

For now we have two types of destination: browser, HDX. So we have the classical computer science problem of what to name that column, export_target, export_destination, export_method are all I can think of, I slightly prefer target but none are ideal. @rowasc @kinstelli this is the most important part others need to understand what the column does.

4. Attribute, tag, form_attribute storage, we have two options a table or a serialisation.

I am in favour of serialisation for the following reasons:
1. It is already the structure used for fields and filters
2. The reason to use a serialisation approach as opposed to a bag approach is to avoid generating enormous numbers of rows. Because ((fields x (attributes x tags)) x exports) is likely to be large but that the accessing is going to be done predominantly on the export field it's not wise to create that kind of overhead at this point.
  2 a. This is v0, there will be a v1, if in the course of v0 user testing we determine there is a rationale for being able to search and access this information we can adjust this easily then. Because none of the data that will be used in v0 deployments(COMRADES) will be long lived initially it is demo only material
  2 b. The benefit of storing data in this format is that we can 
    1. Intelligently suggest mappings
    2. Mine the mappings for extra information to add to our interface
    3. Search the data more easily
  2 c. There is no defined purpose for being able to search or parse mappings and the work of doing that is a stated purpose of HDX not Ushahidi 
  2 d. We do not have a data parsing or storage infrastructure, our DB setup would need to be heavily revisited before we undertake the kind of work that parsing large amounts of data entails so we would be making the decision to add complexity without purpose or capability at the moment
  
Am I:

1. Missing anything
2. Misrepresenting anything
3. Do you want to make an argument against anything I've written

Next steps: 
1. If the above is reasonable and you guys agree with the areas involved then I believe we should break this into 4 distinct smaller tickets
2. Spec each ticket with appropriate information
3. Review the specs and have them ready to go

**Comment by rowasc** [comment]
Thank you Will, this is excellent. I support  this 100%.

**Comment by kinstelli** [comment]
Yep, no objections to this.

My only tiny addition would be that adding individual columns for each of the possible destinations (`send_to_hdx` + `send_to_browser`) vs (`destination`/`target`) might spare us from making some enhancements in the future. It also might also make coding easier now, since a single-valued field inevitably means writing a lot of conditional blocks that interprets that single-value later.

**Comment by willdoran** [comment]
@kinstelli 
> adding individual columns for each of the possible destinations (send_to_hdx + send_to_browser) vs (destination/target) might spare us from making some enhancements in the future. It also might also make coding easier now, since a single-valued field inevitably means writing a lot of conditional blocks that interprets that single-value later.

I don't disagree, it might also be much simpler later because if we change to allow many destinations or connect to the webhook functionality we can easily write a migration to remove these fields and replace them with a foreign_key that links out to another table or to another system. It would make that migration much simpler since we won't have to do an odious text comparison for each row.

I think that browser and hdx are legitimate destination, since this is v0 if we hate the field names they are still changeable until the end of v1.

Can I get confirmation from @rowasc that this sounds ok? and I'll include in spec for that issue now.

**Comment by rowasc** [comment]
@willdoran yep that sounds ok. We can migrate it if we hate it
