### ISSUE TITLE
Users should be able to use any valid email to register and upgrade their plan in ushahidi.io

### ISSUE THREAD

**Issue by rowasc** [ushahidi/platform#2806]
### Expected behaviour
When I create a new user with an email user+something@something I should be able to upgrade my plan
### Actual behaviour
If I create a user romina+testing@ushahidi.com I can't update my plan because the UI fails to sent the correct information to the server and does not recognize my user.
When I attempt to upgrade, it says my password is wrong, unless I change my user to romina@ushahidi.com. 

### Steps to reproduce the behaviour/error
- Create a user and deployment in ushahidi.io. The email should be in a format like "yourusername+1234@ushahidi.com" 
- Try to upgrade to a responder plan
- You won't be able to upgrade because the password confirmation will fail 
#### Where does this issue happen?
- [ ] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [x] Ushahidi.io / SaaS solution 
- [ ] Ushahidi's QA environment
- [ ] Other (explain): 

#### It is ready for development when
- [ ] Has a description that includes purpose of this particular feature/improvement (how it will help the user and for which use cases)
- [ ] Can be delivered within a sprint (make sure issues are small pieces of work, not huge epics)
- [ ] Has all designs and UI assets available
- [ ] Has all (probable) dependencies identified
- [ ] Is estimated by the team
- [ ] Has acceptance criteria defined (do we want to do this before we send to dev? might help us identify dependencies/holes earlier?)

**Comment by Angamanga** [comment]
@rjmackay @kinstelli Could one of you spec this issue?

**Comment by rjmackay** [comment]
@Angamanga This seems to be a fairly well defined bug. I don't think I can add anything without actually debugging and solving the issue.
It sounds like the issue is probably in the ushahidi/platform-cloud-interface repo

**Comment by rjmackay** [comment]
I also hate to say it - but people using that style of email address are probably a minority so I'm not sure this represents a P1

**Comment by Angamanga** [comment]
Thank you @rjmackay. I am fine with down-prioritising this as we got a new P0 into the cycle                   today. @jrtricafort @caharding You ok with making it a P2 for now?

**Comment by rjmackay** [comment]
Ah. I tracked this down: We're not URL encoding the email sent to the cloud UI.
So we send:
`https://ushahidi.io/settings/login?subdomain=testemail&username=robbie+test@ushahidi.com&tier=responder`
instead of
`https://ushahidi.io/settings/login?subdomain=testemail&username=robbie%2Btest%40ushahidi.com&tier=responder`

**Comment by jrtricafort** [comment]
@Angamanga it isn't clear to me from the description which users are currently encountering this. If there is a high-priority deployment that totally blocked by this bug (e.g. they all have '+' characters) then I think we need to keep at P1. If not, and if this is just a known bug but one that no current users are actually encountering (because the format is uncommon) then, I agree we should downgrade to P2.

@rowasc do you know if there are users current blocked by this, and if so which users they are?

**Comment by Angamanga** [comment]
@jrtricafort Looks like @rjmackay already fixed it 💃 @rowasc could you review?

**Comment by rjmackay** [comment]
@Eve-wanderi this should be ready to test on the v3-qa.ush.zone deployments

**Comment by rowasc** [comment]
Adding to our cycle board since we merged it. 
Assigning to myself for testing

**Comment by rowasc** [comment]
@rjmackay while testing this, at signup I got this . Not really sure which ticket introduced the error, tho
<img width="971" alt="screen shot 2018-07-06 at 6 56 26 pm" src="https://user-images.githubusercontent.com/2434401/42402102-29def9c0-814f-11e8-9575-314333abfcfe.png">

**Comment by rjmackay** [comment]
@rowasc because of recent security fixes the /create page currently *only* works on HTTPS, the certs in QA are invalid. You'll need to add an exception then try again over SSL. I mentioned it in slack, but I guess I should have @ everyone https://ushahidi.slack.com/archives/CB9QBGAJC/p1530850571000033

**Comment by rowasc** [comment]
my bad. I didn't realize . But this passed 👍

**Comment by rowasc** [comment]
@rjmackay ah. Yea ok. I can login with my email and upgrade while creating the deployment so it passes.
