### ISSUE TITLE
[Platform-Client] HXL mappings on export

### ISSUE THREAD

**Issue by rowasc** [ushahidi/platform#2808]
## Description
HXL mappings on export: A way for users to export multi-survey data with HXL tags and attributes via the export setting menu item.

## View
Multiple Survey Export view
https://drive.google.com/drive/u/1/folders/1B0-2RnlTd6Tb8TtZYOBmdHGr9Caznuxo

## Notes
- Important to remember: CSV exports take ALL surveys included in a set of filters
- HXL tags represented with `bug icon` UI 
- Each tag also has the attributes Example: "#geo+lon+lat"
- The screen always starts empty if not coming from the "Edit" feature of HXL export history

**Comment by jrtricafort** [comment]
@rowasc Does this issue cover back-end implementation, front-end/UI implementation, or both? I just want to make sure the scope is clear in the issue.

**Comment by Erioldoesdesign** [comment]
@jrtricafort This looks like it covers a bit of both? BE & FE.

I think this criteria was initially just to make sure that if the user chooses 'Assign tags and attributes' on the first screen that they see all of the survey associated with a deployment (because the full prototype flow only shows one)

**Comment by Angamanga** [comment]
@rowasc Could you please review?

**Comment by Angamanga** [comment]
This is covered by other issues for HDX in the client, closing.
