### ISSUE TITLE
[UI]Sending data to HDX : required fields that user needs to fill out

### ISSUE THREAD

**Issue by rowasc** [ushahidi/platform#2811]
https://data.humdata.org/contribute/new#

 There are a few required fields that are more obvious there. 

Specifically:  Organization, and License are important and should be selected with an explicit decision from the user . Source could be Ushahidi+Deployment Name , I think?

We need a way for users to add this data.

**Comment by Erioldoesdesign** [comment]
Take a look at this page in the prototypes: 
https://xd.adobe.com/view/2690f082-d88d-4788-5db7-b04c9474a404-50a1/screen/1c15cc61-5a2e-4dbe-8018-a7bd2b559d40/Data-export-CSV-landing-page-HDX-single-survey-20?fullscreen

We'll need to discuss whether it covers everything needed (if I've missed some crucial information)

**Comment by rowasc** [comment]
This looks great. I'll creat the client and backend tickets for it now

**Comment by rowasc** [comment]
@Erioldoesdesign I think `source` should be plain text, maybe with the deployment name as a default?
cc @willdoran

**Comment by rowasc** [comment]
@Erioldoesdesign @willdoran I think maintainer would always be the person uploading the data, so maybe this could go in the api config (they would give us api key + username basically)?

**Comment by rowasc** [comment]
@Erioldoesdesign another question/suggestion: do you think it'd be worth it to add a short explanation to organization list like  "This is a list of all the organizations you are part of in the HDX portal." so users know how we got it?

**Comment by Erioldoesdesign** [comment]
@rowasc Agreed on the text above org field re. contextualisation.
Also agreed that source doesn't need to be a drop down if that's a good default for the user. Or are you suggesting a type-able field?

What i'll end up doing with a lot of these fields that have contextualisation text is heaviliy usertesting versions with text and without to see whether users 'get it' without contextualisation, because as we well know, users hate reading text :)
