### ISSUE TITLE
[Platform API] Start an HXL Export from lumen job

### ISSUE THREAD

**Issue by rowasc** [ushahidi/platform#2874]
### Description

- Platform API should be notified to call the usecase/command to upload the data
    - This could potentially (ideally) be a call like the one for regular CSV exports to a controller that then calls the export HXL usecase 
- Ideally we should reuse what we have done for CSV Exports as much as possible, to be able to meet our deadilnes. We can open a second ticket for any architecture changes that take place outside of the scope of HXL Export v0.

### important
This triggers: https://github.com/ushahidi/platform/issues/2814

**Comment by rowasc** [comment]
TODO: add how the queues will change to support this

**Comment by kinstelli** [comment]
For discussion, here is the current workflow, in its current, imperfect state:
1. *Platform User* requests export
2. A new job is created in `export_jobs` table with new `job_id`
3. At pre-defined intervals, *platform-job-queue* code looks for incomplete jobs in each deployment
4. For each discovered incomplete job, *platform-job-queue* sends an API request to *Export-Broker* to initiate a new job process 
5. A new task is created in  *Export-Broker* with the `job_id`, `subdomain` and `domain` of deployment
6. *Export-Broker* sends a COUNT request to `/api/v3/exports/count/{job_id}` on *Platform* to get `export_job` details
7. *Export-Broker* splits job into _x_ chunks, creates _x_ number of queued jobs in queue table with predetermined OFFSET values
8. *Export-Broker*'s queue worker picks up each queue'd job and starts to process them.
9. For each chunk:
     - 9.a. If this is the first chunk, (i.e., if the OFFSET = 0):
             -  9.a.1.  the *Export-Broker* creates a query string with `include_headers=true` 
    -  9.b. Otherwise  
             -  9.b.1. *Export-Broker* creates a query string with `include_headers=false`      - 9.c.  *Export-Broker* sends a CLI export request to *Platform* with `include_headers=false`  at `/api/v3/exports/cli/{job_id}`
    - 9.d. *Platform* exports a subset of data to a `tmp` file on our CDN
    - 9.e. If *Platform* sends a 200:
             -  9.d.1.  *Export-Broker* marks queue'd job as finished
    - 9.f. If this export is _not_ successful, *Platform* sends an error:
             -  9.f.1   *Export-Broker* valiantly attempts the same request several more times until it gets a successful result
10. If all queue'd jobs are successful for a specific export_job:
    - 10.a. *Export-Broker* concatenates each `tmp` file on the CDN into one large file
    - 10.b. *Export-Broker* sends an update with `SUCCESS` and the CDN file path to `/api/v3/exports/job/{job_id}` on *Platform*
11. If all queue'd jobs could not complete for a specific export_job:
     11.a. *Export-Broker* sends an update of `FAILED` to `/api/v3/exports/jobs/{job_id}` to *Platform*
- THE END

**Comment by kinstelli** [comment]
Proposed changes to incorporate HDX needs are in bold, assuming that we can use the existing export count/chunk code for doing HDX exports. 

Proposal 1 — We let Platform initiate its own send to HDX after the exports are completed.  This is potentially cleaner, since Platform will already know all about the data that has to be sent to HDX. This is also less migration if/when we abandon *Export-Broker* for deployment-specific lumen queues.  

  **1. *Platform User* requests HDX export**
2. A new job is created in `export_jobs` table with new `job_id`
3. At pre-defined intervals, *platform-job-queue* code looks for incomplete jobs in each deployment
4. For each discovered incomplete job, *platform-job-queue* sends an API request to *Export-Broker* to initiate a new job process     
**4.a If the export job includes HDX info, then `include_hdx_headers=true` will be included as a param in the request to *Export-Broker*** 
**4.b. If the export job needs to be sent to HDX, then `send_to_hdx=true` will be included as a param in the request to *Export-Broker***
5. A new task is created in  *Export-Broker* with the `job_id`, `subdomain` and `domain` of deployment
6. *Export-Broker* sends a COUNT request to `/api/v3/exports/count/{job_id}` *Platform* to get `export_job` details
7. *Export-Broker* splits job into _x_ chunks, creates _x_ number of queued jobs in queue table with predetermined OFFSET values
8. *Export-Broker*'s queue worker picks up each queue'd job and starts to process them.
9. For each chunk:
     - 9.a. If this is the first chunk, (i.e., if the OFFSET = 0):
             -  9.a.1.  the *Export-Broker* creates a query string with `include_headers=true` 
    -  9.b. Otherwise  
             -  9.b.1. *Export-Broker* creates a query string with `include_headers=false` 
    - 9.c. If this is an HDX request:              
    -  9.a.1.  the *Export-Broker* appends to the query string with `include_hdx_headers=true`      - 9.c.  *Export-Broker* sends a CLI export request to *Platform*  at `/api/v3/exports/cli/{job_id}`
    - 9.d. *Platform* exports a subset of data to a `tmp` file on our CDN
	   **- 9.d.1. If this includes a request for HDX, then *Platform* will also create a row for HDX tags, based on the tag-attribute mapping defined in the export_job**
    - 9.e. If *Platform* export is successful, it responds with a 200:
             - 9.e.1.  *Export-Broker* marks queue'd job as finished
    - 9.f. If this export is _not_ successful, *Platform* sends an error:
             -  9.f.1   *Export-Broker* valiantly attempts the same request several more times until it gets a successful result
10. If all queue'd jobs are successful for a specific export_job:
    - 10.a. *Export-Broker* concatenates each `tmp` file on the CDN into one large file
    **- 10.b. If the export job is an HXL export that needs to go to HDX, then *Export-Broker* sends an update with `PENDING_HDX` along with the CDN url  to `/api/v3/exports/job/{job_id}` on *Platform***	      
    **- 10.c. When *Platform* received an update with `PENDING_HDX`, it emits an event to send data to HDX**            
           **- 10.c.1. A Listener initiates a send to HDX.**         
               **- 10.c.1.1. If that send to HDX is successful, it updates the `export_job` database with `SUCCESS` and updates other relevant HDX data in the database with response data that is received from HDX**
**- 10.c.1.1. If that send to HDX failed, it updates the `export_job` database with `FAILED`**
**- 10.c. If the job was not an HXL export, *Export-Broker* sends an update with `SUCCESS` and the CDN file path to `/api/v3/exports/job/{job_id}` on *Platform***
11. If all queue'd jobs could not complete for a specific export_job:
     11.a. *Export-Broker* sends an update of `FAILED` to `/api/v3/exports/jobs/{job_id}` to *Platform*
- THE END

**Comment by willdoran** [comment]
@kinstelli This in principle sounds good, I have two comments which are not necessarily important right now.

1. Because we allow only one export at a time I think it is ok for Platform to send immediately to HDX when it get's the update `PENDING_HDX`
2. In future, when we have some kind of architecture that allows us to do more than one thing at a time, we should probably have a separate job that runs periodically sand checks for Jobs with the `PENDING_HDX` flag, it can then run through them and send them one at a time. But before we do something like that we should port export broker to core and before that we should figure out how to do modern queuing :D 

Could we break this into a change list to see how many distinct thing there are and if we need to create separate issues?

**Comment by kinstelli** [comment]
> Could we break this into a change list to see how many distinct thing there are and if we need to create separate issues?

We can definitely break this into as many changes / tickets as necessary, but I thought I'd wait until after we decided how much of a bad idea this proposed approach might be.

**Comment by kinstelli** [comment]
It's completely possible that we could avoid changing ExportBroker, if we:
1. Let platform recognize the HXL jobs and be in charge of adding any HXL headers, along with the row headers, when it gets the initial `include_headers=true`.
2. Figure out how to deal with the fact that platform-client is going to interpret the 'SUCCESS' flag as the job being complete and ready for download. (Maybe we update platform-client poller to look for other fields, too?)
3. Let platform be responsible for initiating the interactions with the HXL server (be it in a event or a queued job), once it receives the SUCCESS update from ExportBroker.

And nope, ExportBroker doesn't care about rows, it only cares about the files it finds.

I could update the proposal with this info, but I'm on my phone right now. :D

**Comment by rowasc** [comment]
I really like this since it avoids modifying the broker too much. I support not having export broker decide things about where an export will go, the platform should be responsible for that. 
regarding (2) : yea I think that'd be reasonable and easy to do with the current codebase
regarding (3): absolutely. I think that's ideal.
This is looking great @kinstelli @willdoran . I think we should divide in tickets and get into it while I finish the creation of the file itself.

**Comment by willdoran** [comment]
@kinstelli @rowasc 

>1. Let platform recognize the HXL jobs and be in charge of adding any HXL headers, along with the row headers, when it gets the initial include_headers=true.

Should be covered by #2521 

> 2. Figure out how to deal with the fact that platform-client is going to interpret the 'SUCCESS' flag as the job being complete and ready for download. (Maybe we update platform-client poller to look for other fields, too?)

Should be covered by #2942, can you both review

> 3. Let platform be responsible for initiating the interactions with the HXL server (be it in a event or a queued job), once it receives the SUCCESS update from ExportBroker.

Should be covered by #2814
