### ISSUE TITLE
[Platform API] On Export Job completion check destination and trigger functionality

### ISSUE THREAD

**Issue by willdoran** [ushahidi/platform#2942]
### Overview
When the Export Job API receives the final update from the Export Broker it needs to check the destination to which the output CSV file link should be sent. At present, this is either `send_to_browser` or `send_to_hdx`.

In the event of `send_to_browser`, the current behaviour should be taken which is to update the record.

in the event of `send_to_hdx`, the API should trigger a send to HDX event.

### Requirements
- [x] Export Job API should check update status for `EXPORTED_TO_CDN`
- [x] If update status is success and `send_to_hdx` is true then a Send to HDX event should be triggered.
- [x] If update status is success and `send_to_hdx` Export Job API should change status from EXPORTED_TO_CDN to `PENDING_HDX`

**Comment by kinstelli** [comment]
Now that I think about it, the less ExportBroker knows about the job's details, the fewer side-effects we'd potentially have to debug.

So, here's one option:
... after processing the export...
- ExportBroker creates a concatenated downloadable on CDN
- ExportBroker sends PUT of status:`EXPORTED_TO_CDN` to Platform at `/api/v3/export/jobs/{job_id}`
- Platform looks at the `export_job` data table, and decides the following:
   - If `send_to_hdx` is true, it updates its own `export_job` table to status:`PENDING_HDX` and emits an event to send info to the HDX server.
      - Then the event listener reads job metadata from the table and sends a request to the HDX server
      - If the request is successful, the `export_job` table is updated to status:`SUCCESS`
      - If the request is not successful, the `export_job` table is updated to status:`FAILURE` 
                     _(.. not sure what to do at this point, though)_
  - If `send_to_hdx` is false, both for standard CSV and HXL-enhanced files, Platform updates its own `export_job` table to status:`SUCCESS`, and the task can be considered complete, 

This would mean the following changes:
1. ExportBroker is updated to send `EXPORTED_TO_CDN` to Platform instead of `SUCCESS`
2. We add an event to Platform
3. We add an event listener that initiates a read of job status, sends files to HDX, and updates status depending on the success/failure of that request to HDX

**Comment by willdoran** [comment]
excellent:

>1. ExportBroker is updated to send EXPORTED_TO_CDN to Platform instead of SUCCESS

is covered now by #2943

>2. We add an event to Platform
>3. We add an event listener that
>  - initiates a read of job status
>  - sends files to HDX
>  - updates status depending on the success/failure of that request to HDX

Covered by #2944

**Comment by rowasc** [comment]
looks great.

**Comment by kinstelli** [comment]
APPROVED.

**Comment by kinstelli** [comment]
confirming that this line should be changed from:
`If update status is success and send_to_hdx Export Job API should change status from EXPORTED_TO_CDN to PENDING_HDX`
to
`If update status is success and send_to_hdx Export Job API should change status from EXPORTED_TO_CDN to SUCCESS`
