### ISSUE TITLE
[Platform API] Package Review

### ISSUE THREAD

**Issue by willdoran** [ushahidi/platform#2945]
### Overview
We should carefully limit the versions within our composer.json to avoid breaking dependencies for our supported PHP versions when 3rd party libs update.

We should review the existing libs and determine the proper limits and we should setup a tracking method for versions, may be something similar to greenkeeper but with a designated owner.

### Requirements
- [ ]  Review the existing libs and determine the proper version limits to ensure support of the correct PHP versions 
- [ ] Investigate setting a greenkeeper style tracker that encourages review of libraries on a regular basis.
- [ ] Review library license

Aha! Link: https://ushahiditeam.aha.io/features/PROD-342

**Comment by rjmackay** [comment]
> Review the existing libs and determine the proper version limits to ensure support of the correct PHP versions

I was thinking about this while fixing the composer.lock issues. This is what composer.lock is for. While versions shouldn't be completely open, we shouldn't have to heavily limit versions because composer.lock doesn't that for us. I think especially if we limit the PHP version in composer.json, then composer is supposed to handle this.
We should define how/when we run composer update though.
