### ISSUE TITLE
Validate that maintainer and API Key are correct against HDX API

### ISSUE THREAD

**Issue by rowasc** [ushahidi/platform#2984]
@rowasc Suggested spec:

### Overview
This encompasses multiple cleaning tasks for HDX

### Requirements
- [ ] Error handling
  - [ ] Ensure that all HDX errors are saved 
  - [ ] If the error returned is related to HDX unavailability(for example 503) reset the job to "pending" so that it can be rerun later
  - [ ] Add error field to the export job table to store the resulting errors that are produced async
  - [ ] Ensure that errors are displayed on the export history page in the client

### Acceptance Criteria
- [ ] The error triggered by an invalid user/api pair is correctly reported to the Export History tab via the error field

Aha! Link: https://ushahiditeam.aha.io/features/PROD-340

**Comment by rowasc** [comment]
Moving to V1 as discussed with @willdoran

**Comment by rowasc** [comment]
@willdoran ` Should fail gracefully if API key, maintainer or HDX url is not set for HDX.` I'm not entirely sure how to do this correctly, although it shouldn't happen now that we are moving the keys to the correct place with validation. 
Maybe we should be saving export errors in the job table so that we can show it in the export history and the notification shows up with details when the client pulls it?

**Comment by willdoran** [comment]
@rowasc What are the errors that could be triggered? How useful is the information? If they make a mistake configuring their api or username we should warn them that that has happened or that that was the error returned I think.

**Comment by rowasc** [comment]
@willdoran yea, for API and username I think we have it covered in the #2986  "move maintainer field" ticket since we are going to give feedback at the time they add it and submit. I'm not entirely sure what error states we can encounter (realistically) aside from HDX being down with metadata pre-created /validated and api key+maintainer also being pre-validated.

For HDX being down, we should retry I think, maybe that's the ticket I have to create "Have a retry mechanism if HDX is down / throws a 503 " , which I think would involve re-setting the job as pending_hdx and moving on. Right?

**Comment by willdoran** [comment]
@rowasc Suggested spec:

### Overview
This encompasses multiple cleaning tasks for HDX

### Requirements
- [ ] Set IMPORT_EXPORT permission back to normal (same permissions as CSV export had before HDX)
  - [ ] ???
- [ ] Move the [isOppositeBool function](https://github.com/ushahidi/platform/blob/c544cb9f07708dc3c32466671806c002480a8e55/src/App/Validator/ExportJob/Update.php#L104) to the Validator class
- [ ] Cleanup HDX Send to lower complexity 
  - [ ] ????
- [ ] Error handling
  - [ ] Ensure that all HDX errors are saved 
  - [ ] If the error returned is related to HDX unavailability(for example 503) reset the job to "pending" so that it can be rerun later
  - [ ] Add error field to the export job table to store the resulting errors that are produced async
  - [ ] Ensure that errors are displayed on the export history page in the client

### Acceptance Criteria
- [ ] The error triggered by an invalid user/api pair is correctly reported to the Export History tab via the error field
- [ ] criteria for permission???
- [ ] criteria for cleanup???

**Comment by rowasc** [comment]
edited ticket and created https://github.com/ushahidi/platform/issues/3125 and https://github.com/ushahidi/platform/issues/3124 as their own tickets.

**Comment by rowasc** [comment]
@jrtricafort Not sure if this should be implemented now or in a future epic
