### ISSUE TITLE
[Platform Client] Maintainer input should move to API Config screen for HDX

### ISSUE THREAD

**Issue by willdoran** [ushahidi/platform#2985]
### Overview
The "maintainer" field is constant and is tied directly to the API. The field should only be entered once by the user when they configure the HDX API Key.

### Designs
https://xd.adobe.com/view/d2db5a90-5a14-42f5-6a02-3ede842856b2-a4ea/?fullscreen

### Requirements
- [ ] Remove Maintainer field from HDX Details view
- [ ] Add user field to HDX API config page
- [ ] Change HDX Config Settings menu title and subtitle to match design
- [ ] Change maintainer field title to username
- [ ] Add explanation in the `Configure HDX API and username` page to show user where to find this id, it is distinct from the email they use to login to HDX and that is obtuse and potentially opaque to the user. 
- [ ] Show validation errors from the server

### Test script
- [ ] I can set up my maintainer id in the client by going to /settings/user-settings
- [ ] I can set up my API key in the client by going to /settings/user-settings
- [ ]  When no API Key or Maintainer is saved no 'cancel' button appears next to the Save button
- [ ]   When editing an existing Maintainer setting a text button appears next to the save button called 'cancel'
- [ ]   When 'cancel' is clicked the change mode is exited and the user is returned to the view mode
- [ ]   When editing an existing API Key setting, a text button appears next to the save button called 'cancel'
- [ ]   When 'cancel' is clicked, the change mode is exited and the user is returned to the view mode

**Comment by rowasc** [comment]
@Erioldoesdesign do you think we need a design for this? or should we just move the field in the client directly?

**Comment by rowasc** [comment]
@willdoran I think the requirements are ok, I only added "Show validation errors" to them. BUT, I tried to add test scripts and realized that we might need Eriol to take a look, since the API Key field is "hidden" under a link and we need to check how this should work in the client. After that I can add test scripts 

@Erioldoesdesign after thinking about this, I'd appreciate it if you can provide a design for this with the new field .

**Comment by Erioldoesdesign** [comment]
Sup!
What the add details screen should look like with maintainer removed:

![hdx maintainer removed](https://user-images.githubusercontent.com/11681324/42044636-6cd48484-7af1-11e8-943c-b2ac80ff612e.png)

4 screen prototype with the new settings page (copy changes) config page with added 'username' field and an error state if someone tries to save without adding in these to pieces of info.

Both bits of info are mandatory...but the use of an always active 'save' button isn't good UX here anymore as a person might want to save after 1 piece of information and look for the other. So I've made the save button 'disabled' until information has been entered into both fields and then the user can save. 
This may then throw errors on the field info. so the user can change/edit the info and save again. We can't inline validate due to needing to 'check in' with HDX right?

https://xd.adobe.com/view/d2db5a90-5a14-42f5-6a02-3ede842856b2-a4ea/?fullscreen

**Comment by rowasc** [comment]
@Erioldoesdesign looking good. 

We might not be able to do validation against HDX  right now (in cycle 6, but we need to re-spec and validate with Juan) but we should at least tell the users that the values cannot be empty. The good thing is that the design allows for both scenarios without changes, even tho it'll really be two requests to save the settings , we can send them one after the other.

**Comment by rowasc** [comment]
@Erioldoesdesign I can't find the link to where the user would find the username/maintainer id. Am I missing something?

**Comment by rowasc** [comment]
@Erioldoesdesign sorry for the 3rd notification :( should we add a more complete explanation of where they would see the user name (top of the page, on the right side, after they login), or is it obvious enough? Not sure what you think

**Comment by willdoran** [comment]
@Erioldoesdesign Can you confirm that the view where the API key is displayed as text rather than in an input box, has been removed?

Is there a reason that username is ordered after api key?

At the moment it works like this:

Display on initial load when both values are set:
<img width="1680" alt="screen shot 2018-06-29 at 15 54 53" src="https://user-images.githubusercontent.com/2694405/42112130-e2952444-7bb4-11e8-8665-7bdbc729e384.png">

When you click to change the user:
<img width="1680" alt="screen shot 2018-06-29 at 15 55 01" src="https://user-images.githubusercontent.com/2694405/42112135-e60eab2c-7bb4-11e8-83e8-977f0d231d96.png">

When you have clicked to change both:
<img width="1679" alt="screen shot 2018-06-29 at 15 55 10" src="https://user-images.githubusercontent.com/2694405/42112139-eb8a810c-7bb4-11e8-997b-7d80f1561aed.png">

**Comment by Erioldoesdesign** [comment]
@willdoran I don't quite understand this sentence: "Can you confirm that the view where the API key is displayed as text rather than in an input box, has been removed?"

> Is there a reason that username is ordered after api key?

Not really but actually would make more sense to guide the user to find the User ID and then the API key since the API key sits under the profile info.

Screenshots look good to me, when editing 1 if both have been set previously it makes sense to have a save button appear under the field being edited. 👍 

@rowasc 

> we should at least tell the users that the values cannot be empty. 

Makes sense, no worries if we can't validate as to whether it's an accurate api key/user id but I if we can throw an error for empty states that'd be great


> should we add a more complete explanation of where they would see the user name (top of the page, on the right side, after they login), or is it obvious enough? Not sure what you think

For sure we should give a little more guidance that you get this 'after you sign up/login. Giving 'right, left, top, bottom' guidance isn't advise for accessibility reasons because a non-sighted person wouldn't be able to use that info :)
Updating prototytpes now

**Comment by Erioldoesdesign** [comment]
Updated the prototype - Let me know i've I've missed anything :)

**Comment by willdoran** [comment]
@Erioldoesdesign This seems good, other than the addition of the second save button this is how it was behaving, we can add that so that it's clear they can be saved separately. It's actually good because they are independent objects.

**Comment by rowasc** [comment]
@willdoran this should move to code review right?

**Comment by willdoran** [comment]
@rowasc yep done

**Comment by willdoran** [comment]
@Erioldoesdesign How do they cancel the action to update?

**Comment by Erioldoesdesign** [comment]
@willdoran We may need to add in a cancel blue link that cancels the action to 'edit/change'

Does the input field 'clear' when you click 'change...'? or does the input field retain the previously inputted info? If that's the case the user can make no changes and then click save again.

Preference to having a 'Cancel change' next to the relevant 'Save'  button only viewable after having clicked a 'Change...' link.

Need a screen amend for this preference?

**Comment by willdoran** [comment]
@Erioldoesdesign 
> Does the input field 'clear' when you click 'change...'? or does the input field retain the previously inputted info? 
For API key it clears for maintainer/user id it doesn't

> Need a screen amend for this preference?
Nope that's cool it's pretty simple.

**Comment by rowasc** [comment]
Sending to QA

**Comment by rowasc** [comment]
@Eve-wanderi please test in http://qa.ushahididev.com/ (and add to testpad ) . Thanks!

**Comment by rowasc** [comment]
@Eve-wanderi this looks like your api key is not configured correctly. Please reach out in slack directly to verify that you are correctly setup.

**Comment by rowasc** [comment]
@Eve-wanderi also I want to point out that the video does not show the configuration screen that was ready for testing.  Did you test that one out, or were you unable to test?

**Comment by rowasc** [comment]
@Eve-wanderi can you check my comments above?

**Comment by rowasc** [comment]
tested and passed, comrades-hdx and ushahididev
