### ISSUE TITLE
Improve notification bar for HDX uploads

### ISSUE THREAD

**Issue by jrtricafort** [ushahidi/platform#2988]
This issue captures three changes to the notification bar when doing an upload to HDX:

1. After you click "Submit to HDX" the In Progress notification currently says  "We are preparing your CSV file..."
<img width="828" alt="screen shot 2018-05-23 at 8 15 41 am" src="https://user-images.githubusercontent.com/37776843/40434862-2e64fc0a-5e64-11e8-9b28-ded22f5d0349.png">
It should instead say "We are preparing your HDX upload..."

2. If you cancel while it is in progress, the notification says "Your CSV export has been cancelled..." This should say "Your HDX upload has been cancelled..."

3. If the HDX upload fails, there is no validation message i.e the system does not inform users of failed exports, instead it just shows Dismiss. Users cannot understand what this means. (See below)

![image.png](https://images.zenhubusercontent.com/5a730b1e4b5806bc2bc534d6/c0861430-ef0b-4a6b-9c4e-afec581ffaac)

This should say something like "Something went wrong with your HDX upload...". We can loop in design/@Erioldoesdesign on the exact wording of what that message should be.

Aha! Link: https://ushahiditeam.aha.io/features/PROD-339

**Comment by Erioldoesdesign** [comment]
@jrtricafort Messaging suggestions are good - I'll make a note to test the wording on users during usertesting sessions to uncover any jargon/messaging assumptions we may have overlooked. 👍

**Comment by jrtricafort** [comment]
@Erioldoesdesign Moving to Ready for Design

**Comment by Erioldoesdesign** [comment]
I've landed on the text for the snackbar to be "Something went wrong with your HDX upload. You can either try submitting the upload again or you can go back and export a tagged CSV file."

with two CTA's one should go 'back' to the page with the HDX account info where the user can re-submit to try again and the other CTA will take the user back to the 'finished' table with tags/attributes so the user can choose to export a CSV instead.

https://xd.adobe.com/view/65d44dab-3f5f-4fe9-6cd1-e91d7cd2f9dd-13e5/?fullscreen

This add a little complexity depending on how long the 'active' table of tags/attributes can be 'saved'. A compromise would be the 2nd CTA to be 'export a CSV' from the snackbar so that a user doesn't 'lose' their work on the tags/attributes.
