### ISSUE TITLE
Kenya Deployment Targeted Survey + Frontline Link not synced 

### ISSUE THREAD

**Issue by Nthiga** [ushahidi/platform#3025]
### Steps to reproduce the behaviour/error

More specific repro details available in Slack - ping @kinstelli @jrtricafort for more info from product side.

**Comment by kinstelli** [comment]
It appears that the messages are correctly getting picked up from Platform and sent to FrontlineSMS, but that no activities are being triggered within FrontlineSMS.

From my (very recent) understanding, the expected behavior is: 
1. A new outbound message is created in Platform
2. Platform-queues looks for all pending outbound messages
3. Platform-queues sends these messages to FrontlineSMS to be sent
4.  Platform-queues marks the messages as `sent` in Platform
5. An Activity in FrontlineSMS is triggered, based on certain criteria
6. That Activity sends the message to a service for delivery.

From looking at the database on Platform and the logs in Frontline, it appears that everything is working until step 5. This picture is taken from FrontlineSMS and shows that the most recent outbound message was delivered to FrontlineSMS, but did not trigger an Activity:

<img width="620" alt="no activities" src="https://user-images.githubusercontent.com/6600708/40732121-3a532d7c-63f8-11e8-8e5e-a1475015cc9d.png">

I'm not sure I'm enough of an expert in FrontlineSMS configurations to fully understand why this isn't working, but I can investigate and see if I can find other experts.

**Comment by dukedanny** [comment]
I have updated the deployment API key to match the one in the FrontlineSMS configurations. 

FrontlineSMS API Keys for DREAMS deployments
<img width="1203" alt="frontline sms config" src="https://user-images.githubusercontent.com/437728/40735475-edc4c53c-6443-11e8-9590-b85e5ea67f28.png">

ACWICT Deployment API Key
<img width="724" alt="deployment current api key" src="https://user-images.githubusercontent.com/437728/40735544-1b47a72c-6444-11e8-8e3d-2795ae9f6972.png">


@Nthiga After the above change, please test and share the status of this. I'm going to open another ticket to review all the other deployments to make sure they have the correct API Keys.

**Comment by Angamanga** [comment]
@jrtricafort I don't think it is related, the other issue is about Clickatell not sending messages to FrontlineSMS. The configuration between FrontlineSMS and the platform seems to work there.

**Comment by jrtricafort** [comment]
@Angamanga Got it thanks :)

**Comment by jrtricafort** [comment]
Update from @Nthiga after testing again after @dukedanny fixed the API keys:

> i have tested the messages again, my survey went out and i have received the message on my phone, i have responded to the message and my response also recorded on frontline but not on the deployment (edited)

> The other issue is the second message hasnt been delivered. How long does this take to get delivered? this could also be some delays from my connection

**Comment by jrtricafort** [comment]
Updating: We got on a call to investigate this. It was a configuration issue with Frontline and is now solved. 

@dukedanny could you add the names of the configuration fields that we changed here? It would be good to capture for our documentation of setting up targeted SMS.
