### ISSUE TITLE
User not receiving reset email after resetting password

### ISSUE THREAD

**Issue by StaicyG** [ushahidi/platform#3027]
### Expected behaviour
Requests reset password
### Actual behaviour
Receives notification below but never receives a reset email
![image.png](https://images.zenhubusercontent.com/5a8e72064b5806bc2bc7edf1/508de79a-a9ec-4d4d-b19b-cf3b867b52b1)
### Steps to reproduce the behaviour/error
Clicked on forgot password 
Keyed in my email address
Got the notification similar to the one on the screenshot
Did not receive a password reset email

#### Where does this issue happen?

- [ x ] Ushahidi.io / SaaS solution (example https://juantest.ushahidi.io/)

Public as well as private deployments.

**Comment by jrtricafort** [comment]
@StaicyG which deployment is experiencing this issue? Can you provide a link and a username that we can use to test? We would need this so we can help debug. Thanks!

**Comment by jrtricafort** [comment]
@rowasc Could we ask someone on the team to look into this? I believe this is P0 since there is no workaround if the user forgot their password.

Btw, this looks similar to issue #2608 except that 2608 is particularly for private deployments. In this case, I was able to reproduce the bug even on a non-private deployment: https://juantest.ushahidi.io/

**Comment by rowasc** [comment]
Checking it . I'll report back in a bit

**Comment by rowasc** [comment]
@jrtricafort also to clarify, this is not like #2608 since in this ticket we just don't get an email (at least for me ), while in 2608 the email was received but the link did not work. I'm not sure what's causing it yet

**Comment by jrtricafort** [comment]
@rowasc Got it. Thanks for investigating.

**Comment by rowasc** [comment]
@rjmackay can you take a look? I can't find any logs pointing to the issue

**Comment by rjmackay** [comment]
It turns out that way back in September 2017, somewhere near this commit https://github.com/ushahidi/platform-cloud-ansible/commit/2e730c483c35b00ec26e470f0bbb168cfb77895d#diff-04a78849dbc24e615f3b8487782d6a2b

We moved the postfix email configuration from the `ushahidi.cloud-common` role into `ushahidi.common`. However we failed to configure `smtp_user` and `smtp_password` correctly and so postfix configuration was skipped. This didn't break anything until we rebuilt the servers for PHP7.

I've fixed this and rerun playbook on v3-qa, staging and production to install postfix

@tuxpiper any ideas how we could avoid future failures like this? So far all I can think of is added some post_tasks to check the major services are running ie. nginx, php, postfix, etc. That could still be fragile but better than nothing.

**Comment by rjmackay** [comment]
I also found that password resets are broken in Lumen so fixed that separately in #3032

**Comment by rowasc** [comment]
confirmed that this is fixed. Received email and was able to change it 
@jrtricafort @StaicyG . 

thanks @rjmackay  🙌

**Comment by jrtricafort** [comment]
Huge thanks @rjmackay and @rowasc for solving this mystery! @StaicyG - please confirm here that the user is able to reset/login now :)
