### ISSUE TITLE
User feedback after post creation

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#303]
From David Kimaru

"After saving the post, I expected the app to navigate away from http://demo.platform.ushahidi.com/posts/create and go to a page where I could view my post (the one I just created). This didn’t happen."

**Comment by hollycorbett** [comment]
Incidentally - I think its worth checking up on the difference between "published" and "saved" - personally I found the distinction a little confusing at first.  I opted to change this on a "published to" basis - certainly on what I submitted, when I clicked "saved" it did redirect after saving (though I habitually log in as admin), but the post would also show up as unpublished until I actively published it - perhaps this is the underlying problem here?  A design question?
