### ISSUE TITLE
Expand Character limitations for the First Part of the targeted survey questions 

### ISSUE THREAD

**Issue by Nthiga** [ushahidi/platform#3091]
Current Behaviour: Character limitation at 160 characters. Partners have moved from just sending messages that need AGYW to sending useful notifications/PUSH messages. 

Secondly even with the current setting of sending out one question at a time. The typical message to an AGYW needs to have an intro/greeting plus instructions on how to respond 

e.g. 
Dear Vusha Girl. Thank you for sharing about your employment experience with us. What are some of the challenges that you have experienced at work? For your responses type VUSHA followed by your message and send to 20880 for free. Your message is confidential

or 
Greetings from BARHOSTESS. This is a reminder, if you have not visited the DICE to refill your PrEP drugs in the month of May 2018. Visit the DICE you first received PrEP from and pick up your PrEP drugs. For any questions or feedback type BARHOSTESS and send to 20880 for free. Your message is confidential. 
<img width="482" alt="screen shot 2018-06-20 at 10 08 26 am" src="https://user-images.githubusercontent.com/26707984/41642419-ecaca768-7470-11e8-939a-b85fb8c839ab.png">

Expected behaviour: Should be able to send a much longer message for the first text at the least

Aha! Link: https://ushahiditeam.aha.io/features/PROD-327

**Comment by willdoran** [comment]
@Nthiga @justinscherer @Erioldoesdesign 

It may be difficult to change this for the following reason:

We are not certain how multipart messages will deliver, in theory they can enter as much text as they want, however, SMS are sent over networks via a protocol called UDP which does not guarantee the order in which the messages are sent so it is possible that the message split into 160 char sms would arrive the second first then the first then the third which might be weird.

Having said that, the issue is likely to only affect very simple phones and very poor networks so it may occur in a very small number of cases. If the risk of a message like this:

"Greetings from BARHOSTESS. This is a reminder, if you have not visited the DICE to refill your PrEP drugs in the month of May 2018. Visit the DICE you first received PrEP from and pick up your PrEP drugs. For any questions or feedback type BARHOSTESS and send to 20880 for free. Your message is confidential."

would arrive like this:
SMS 1
"eived PrEP from and pick up your PrEP drugs. For any questions or feedback type BARHOSTESS and send to 20880 for free. Your message is confidential."

SMS 2
"Greetings from BARHOSTESS. This is a reminder, if you have not visited the DICE to refill your PrEP drugs in the month of May 2018. Visit the DICE you first rec"

Is not a huge problem for the partner orgs we can definitely change it. How the messages are delivered and displayed is controlled to an extent by the network they travel over and the phones they arrive on so we can do very little to force the messages to be delivered in order. But I will do more research to confirm there is no way to control this, it is possible that Africa's talking already control for this in some way.

**Comment by justinscherer** [comment]
My main concern on this is cost. If they are sending a targeted survey to 1000 people and they write 3 SMS worth of text, the cost of the message is 300% higher.
