### ISSUE TITLE
Decide on how to use the component-library in the client

### ISSUE THREAD

**Issue by Angamanga** [ushahidi/platform#3093]
## TODO
Make and document decision on how the component-library should be used in the client. 
Options:
1. Component-library in its own repo, publish through npm and import in client
2. Component-library in its own repo, import from github through npm and build in client
3. Component-library is integrated in the client in its own folder, all work is done in the client

**Comment by Angamanga** [comment]
@rowasc @jrtricafort @rjmackay I am not sure how this decision should be taken. Is it up to Robbie? Everyone? Me and @sethburtonhall ? There is pros and cons with all of the options, and its not a super-huge decision, but it should be taken. I advocate for option 3. Even though we mix our PL-work with the client-work it gives us the opportunity to: 

1. QA new styles directly in the client, without the hassle of going back and fourth to the PL
2. New components will already be there, ready to use, without any confusion of tags and versions of the PL
3. We can use the same packages and linter-settings as in client
4. No copying and pasting of code, components are there
5. Point of truth for the UI is in the client, always.

**Comment by rjmackay** [comment]
I'm happy to take your recommendation and go with option 3. It's also what I had suggested in January, before things got more complex with the JS migration.

On decision making I think: This should be up to you and Seth as the people doing most of the pattern library work, with input from other devs (which you've already got). I think @willdoran or myself could theoretically veto it, but I don't see any reason to do so.

A couple of minor concerns related to places with use the pattern library outside of client:
1. In ushahidi.io - particularly the plans and tour pages. I think it might be reasonable to suggest we redo the tour and plans pages as part of the UI refresh and address this then.
2. In platform-dashboard. This isn't super important since it's not in production. It should be easy to resolve by publishing the component lib to NPM (from within client) and importing it.

I don't think either of those are blocking, just making sure they're known by more people than me

**Comment by willdoran** [comment]
@Angamanga I concur with option 3 it sounds better, and slightly reduces unnecessary repo sprawl. If it gets very big to justify its own repo we can do that down the road, I think.

**Comment by Angamanga** [comment]
@rjmackay @willdoran @sethburtonhall I am happy to hear we all agree. Decision taken on option nb 3 and closing this issue for now. 🙌 🔨
