### ISSUE TITLE
Update Password for a user (person)

### ISSUE THREAD

**Issue by crcommons** [ushahidi/platform#3106]
## Overview
Add a separately functioning form in the people edit view that allows a user to update a password of another user.

## Requirements/User interface behaviors
- [ ] Create a separate form for updating the users password within the edit people view
- [ ] the password section should display 8 * to represent the password as a placeholder
- [ ] there are two password fields (enter and confirm)
- [ ] when a user types into the fields, the text is shown as *
- [ ] it should have a button that saves the password (updates the user's password) and on success it stays on the page and displays a success modal
- [ ] it should have a button that cancels which reverts the form to the placeholder * and keeps you on the page

### Component tree
-PersonEditForm(exists) -> ChangePasswordForm(new)

### State tree
Does not affect state

## Acceptance criteria / Test script
- Go to settings -> People and select a person
- change the password
- click save
- [ ] a success modal should appear and you should remain on the current page
- logout
- login with the credentials
- [ ] you should successfully be able to login
-------
- Go to settings -> People and select a person
- change the password to something less than 8 characters
- [ ] you should see an error state telling you the requirements for the password @Erioldoesdesign @justinscherer Is this correct?
------
- Go to settings -> People and select a person
- change the password in the first field
- start making a change to the password in the second field
- [ ] a response should appear telling you that the passwords must be the same 
- [ ] the response should disappear once the passwords are the same

**Comment by rowasc** [comment]
@crcommons can you add validation rules? as in , the two passwords should match, and whatever our password rules are, if any

**Comment by crcommons** [comment]
Add the point about the passwords. Agreed on a 2.

**Comment by rowasc** [comment]
APPROVED then

**Comment by Erioldoesdesign** [comment]
@crcommons re. the error state on min 8 characters for changing a persons password. Yes, if they try to do anything that we don't accept as password character criteria then the fields should have error validation on them notifying them of our general constraints and also that the password 'did not save due to it not following or requirements'

Can we make sure that the field remembers the characters that were inputted in this field? Will they display as dots?

I would like users to be able to check back on what they wrote to 'edit' in the text field rather than type all over again.

**Comment by Erioldoesdesign** [comment]
Side note: Does the user that is having their password change get an email notification that it's been changed? How do individual users know that their info/password has been changed?

**Comment by rowasc** [comment]
@Erioldoesdesign 
"Can we make sure that the field remembers the characters that were inputted in this field? Will they display as dots?" => do you mean when they edit? I would say no, if that's the case.

"Side note: Does the user that is having their password change get an email notification that it's been changed? How do individual users know that their info/password has been changed?"
Not right now, but I think that would be a high priority thing to do going forward. cc @jrtricafort do you agree? I think we need a ticket for this

**Comment by crcommons** [comment]
@Erioldoesdesign Because it's a password field, it will always display as ******, so the user wouldn't be able to see what the wrote in the text field.

**Comment by jrtricafort** [comment]
@rowasc "Side note: Does the user that is having their password change get an email notification that it's been changed? How do individual users know that their info/password has been changed?"

Yes, they should. This is industry standard for user accounts on the internet these days, and we should conform to that standard. I actually think that's P1 to include here.

Agreed with @Erioldoesdesign that we should also notify them if they're text includes characters we don't allow.

**Comment by rowasc** [comment]
@jrtricafort can you add that as a P1? it's actually a backend change mostly. I can spec it afterwards.

**Comment by rjmackay** [comment]
The general rule with passwords is to allow absolutely any character you can (we should maybe check if emoji passwords break our system), and then set a fairly high minimum length. Ours is too short 😞 , but thats out of scope for the UI itself.

**Comment by Erioldoesdesign** [comment]
I'm always a little proud of myself when I catch a thing like the email/notification thing...go me!

@rowasc I totally agree with your and @rjmackay 's password criteria. Love it. Don't reject characters but have a min and max. Puuurrfect.

I totally get the whole 'still displaying as dots' thing. Even when changing it. I would love to discuss at a **much** further date about building in show/hide buttons for when you delete the old password (set up by generic user) and when you start typing a new one. I find myself making typing errors when I can't see what I've typed because I have stupid fingers.

**Comment by justinscherer** [comment]
@jrtricafort is there an issue open for improving password management security?
