### ISSUE TITLE
Obfuscation (formerly "Anonymization") v2

### ISSUE THREAD

**Issue by jrtricafort** [ushahidi/platform#3181]
## Overview
Improve upon Anonymization v1, which was rolled into production in  Cycle 7, July 2018. 
v1: https://github.com/ushahidi/platform/issues/2685

## Who is it for? Who are the users?
- Users who want to anonymize certain posts

## What privacy impacts does it have?
- Increases privacy by reducing data availability and improving obfuscation funcitonality.
- Terms of Service would need to be updated
- Survey Settings description UI would need to be updated

## Requirements/New Functionality
Currently here is the new functionality we have for this epic. For most up-to-date info, see child issues of this epic. Information in child issues supercedes this high-level summary:
1. Ability to hide post author information from admins as well as non-admins
2. Ability to obfuscate location based on this best practice https://dhsprogram.com/pubs/pdf/SAR7/SAR7.pdf ( @willdoran and @Shadrock have more detail on this )
3. UX Issue - time obfuscation and sorting in data mode (see thread in #plat-anonymization for more detail, in absence of sub-issue)

### Who will this be deployed to?
- Currently, no plans to have this be feature gated. Similar to Anonymization v1, will be turned on to all production deployments by default. Need to verify this.

### What documentation needs to change?
- Anonymization feature support documentation

## Deployment
*Does this deploy new services?*
*Do the new services have health checks?*
*Can this be feature flagged and deployed disabled?*

## Dependencies

Aha! Link: https://ushahiditeam.aha.io/features/PROD-308

**Comment by jrtricafort** [comment]
cc @katymoney27 @justinscherer @rowasc @willdoran  creating this placeholder epic. This is not yet prioritized/planned.

**Comment by Erioldoesdesign** [comment]
Adding in comments from my MOZOL 6 project (finally)

Platform user says: The admins find it useful to know precise location of a report/response in order to lobby local authorities/government for better provisions (more street lighting, remove bushes etc.) in high volume response/post areas or extreme instances. Allows them to take direct action.
There is no need to know a persons name but certain demo graphics are very useful for informing policy.
Admins across BWV all know the details given in a post and there are policies in place internally to safeguard that information. Within this org there is no need to have multiple levels of access to users data at the moment.

**Comment by tuxpiper** [comment]
Confirming alive and relevant.

This is meant as an improvement on the current level of functionality given by this feature.
