### ISSUE TITLE
Unable to recover forgotten password

### ISSUE THREAD

**Issue by tuxpiper** [ushahidi/platform#3193]
In the develop branch (lumen), I'm unable to recover a user's forgotten password. The e-mail is apparently never sent. This information is left in the api logs:

```
[2018-08-08 15:02:34] lumen.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Class 'Ushahidi\App\Repository\Security' not found in /var/www/platform/src/App/Repository/UserRepository.php:193
Stack trace:
#0 /var/www/platform/src/Core/Usecase/User/GetResetToken.php(85): Ushahidi\App\Repository\UserRepository->getResetToken(Object(Ushahidi\Core\Entity\User))
#1 /var/www/platform/app/Http/Controllers/RESTController.php(216): Ushahidi\Core\Usecase\User\GetResetToken->interact()
#2 /var/www/platform/app/Http/Controllers/API/PasswordResetController.php(31): Ushahidi\App\Http\Controllers\RESTController->executeUsecase(Object(Illuminate\Http\Request))
#3 [internal function]: Ushahidi\App\Http\Controllers\API\PasswordResetController->store(Object(Illuminate\Http\Request))
#4 /var/www/platform/vendor/illuminate/container/BoundMethod.php(29): call_user_func_array(Array, Array)
```

**Comment by kinstelli** [comment]
This should be fixed with #3032

**Comment by rowasc** [comment]
Eve to retest in passage environment

**Comment by Eve-wanderi** [comment]
Failed QA i cannot reset my password i get the below error.

![image](https://user-images.githubusercontent.com/36038029/44257526-f055ca80-a214-11e8-8b02-d2176bf57c99.png)

**Comment by rowasc** [comment]
@kinstelli can you investigate?

**Comment by kinstelli** [comment]
For me:
1. Email was never sent from the passage server, but message is logged on the server.
2. Reset token is invalid.
<img width="478" alt="screen shot 2018-08-21 at 2 26 32 pm" src="https://user-images.githubusercontent.com/6600708/44424283-4052cb00-a54e-11e8-9f04-ecf088323fc7.png">

**Comment by kinstelli** [comment]
It appears that when the user clicks the reset password link, this value is not urldecoded before being compared to the value stored in the database. 

However, when the user pastes the reset token into the Reset Password dialog, the reset process works, since that version is not urlencoded in the first place.

Looks like the simplest fix for this would be to urldecode the token before passing it to the API via JSON, but only if it's grabbed from the original `resetpassword/confirm/<token>` URL param, not when submitted via form.

**Comment by kinstelli** [comment]
I'm not sure why passage is not sending reset emails at all, but I suspect it might be a server configuration. Investigating...

**Comment by rjmackay** [comment]
After chatting with @kinstelli we're pretty sure this is broken because mailgun isn't set up in lumen. Steps to fix this:
- [ ] Add config/services.php from  https://github.com/laravel/laravel/blob/master/config/services.php
- [ ] Add mailgun envvars to `.env.deploy`
- [ ] Add mailgun config into ansible configuration (both for AWS and non AWS set ups)

**Comment by tuxpiper** [comment]
@rjmackay  @kinstelli 

I did verify in the passage environment, that I could connect to localhost:25 in the api boxes and send test email messages to myself. The local MTA then would forward to mailgun. I thought lumen would also be using the local MTA.

**Comment by rjmackay** [comment]
Retested on Harbinger. This is resolved now.

**Comment by rowasc** [comment]
Getting this error on platcloud-prod.ush.zone 
Failed to validate users entity: Invalid or expired reset token Invalid or expired reset token DISMISS

**Comment by rowasc** [comment]
Now I'm also getting this error in passage

**Comment by rowasc** [comment]
now I'm also getting the error in harbinger. Checking what's going on

**Comment by rowasc** [comment]
Closed, this is working
