### ISSUE TITLE
Do not create a survey if something goes wrong with title/description-fields upon saving

### ISSUE THREAD

**Issue by Angamanga** [ushahidi/platform#3215]
**Describe the bug**
When I duplicate a survey and something goes wrong when saving one of the attributes in the new survey, I can still click save again. The same error-message appears again each time I click save. When I go back to the survey-list and hit reload, the survey appears and contains all the attributes that could be saved, duplicated as many times as I clicked "Save" and got an error-message.

**Where was the bug observed**
- Local dev-environment (old api)
- Sivico (https://sivico.ushahidi.com)

**To reproduce**
Its a little bit tricky to reproduce since you need one of the attributes to fail when saving. But you could: 
1. Change some values to faulty ones in the database for a survey, for example set input for title to 'varchar' (this was how this bug originally was found)
2. Duplicate that survey in the UI
3. Click save, there is an error-message and it looks like the survey is not saved.
4. Click save again, same error-message
5. Click save again, same error-message
6. Go back to survey-list and reload
7. The duplicated survey is there, click on it
All fields are duplicated 3 times, except the one that was wrong, that is not there at all

**Is there a workaround? What is it.**
The user could go in manually and delete the duplicated fields.

**Desktop Hardware Details (please complete the following information):**
OS: MacOS
Browser Chrome
Version 68

Aha! Link: https://ushahiditeam.aha.io/features/PROD-304

**Comment by rowasc** [comment]
@jrtricafort I think this is a P2. This is a bug, not a regression, and the original P1 bug is already fixed  (avoiding the title/desc fields from being duplicated https://github.com/ushahidi/account-management/issues/42)

**Comment by rohit645** [comment]
@Angamanga I would like to work on this issue. Also what is the expected behaviour in this case?
Duplicated survey should not appear in the surveys-list if I am getting it right.

**Comment by Angamanga** [comment]
@rohit645 This bug was a super-edge case we ran into some time back. It is hard to reproduce right now because we fixed part of it, but try to do this:

1. Change "text" to "varchar" here: https://github.com/ushahidi/platform-client/blob/develop/app/settings/surveys/survey-editor.directive.js#L144.
2. Create a new survey and save the survey. You will see an error-message
3. Go back to the survey-list, you will still see the new survey that you created, click on it
4. You will see the title-field is missing

This is what happens/the cause of the bug:
1. You create a survey with attributes
2. You start saving the survey, here is that code: https://github.com/ushahidi/platform-client/blob/develop/app/settings/surveys/survey-editor.directive.js#L574
3. As you can see, the survey itself gets created first, to get an id to connect the fields to (called attributes in the code) https://github.com/ushahidi/platform-client/blob/develop/app/settings/surveys/survey-editor.directive.js#L579
3. THEN the attributes are saved: https://github.com/ushahidi/platform-client/blob/develop/app/settings/surveys/survey-editor.directive.js#L591

So if something goes wrong with saving the attributes, we still have the survey with some of the attributes. This is especially bad if the Title or Description-fields goes wrong, because they are required and automatically created, and the survey would be useless because it would be impossible to add posts to it.

The expected behaviour here is that the survey is not created if something goes wrong in the saving-flow. But at the same time, we want to save the state of the survey-structure, so the user doesn't need to write it all again, they just want to be able to go back and fix the things that went wrong. If you can come up with a good solution to do this in a good way, we would be super happy!! I am happy to discuss any solutions you come up with 🎉 .

**Comment by rohit645** [comment]
Thanks for this detailed description and insight. I am on it :)

**Comment by rohit645** [comment]
@Angamanga  I had been working on this issue and found out two approaches:

1. If anything goes wrong with attributes of the survey (e.g. Title of the survey) in that case we can simply delete that survey in the error handler (so that it won't appear in the survey's list), display the error to the user and simply redirect the user to the survey-list page. SInce ID of that survey is deleted we cannot make PUT request to the API.  It notifies ID "x" is not found. Therefore deleting ID beforehand tends to prevent modification in the current state of the survey as it denies PUT request. But the way out is we can redirect the user to the survey list page and from there he can try to create a new survey.

2. When we render the list of the survey we can check the attributes of each survey and since *title* and *description* are important fields we can check if these two attributes are present in the survey or not. (this will catch faulty surveys that do not contain *title* field). We can prevent those surveys from being displayed. Therefore the survey is not displayed since it fails validation check.
whereas in the survey-edit page, it keeps on showing error until it is fixed. Approach 1 does not allow editing the same.

I would be happy to discuss any other approach. :)

**Comment by Angamanga** [comment]
Hm, I think we have to go with nb 1 since title and description is not something you can add yourself after saving a survey. Those two fields are a bit special. Could we simply delete the id from the post-object in the error-handler two and use the POST-request instead when saving the second time? The differentiation between PUT and POST happens here: https://github.com/ushahidi/platform-client/blob/develop/app/main/posts/modify/post-editor.directive.js#L267 if there is an id or not.

**Comment by Angamanga** [comment]
Closing this since will be solved in v5.
