### ISSUE TITLE
Can't access General Settings with "Manage Settings" permissions

### ISSUE THREAD

**Issue by crcommons** [ushahidi/platform#3261]
### Expected Behavior
As a user with "Manage Settings" role, I should be able to access settings->general and make changes to the settings

### Current Behavior
As a user with "Manage Settings" role, I am unable to accessing settings->general and am instead rerouted to 404

### Steps to reproduce
- [ ] create a role with "Manage settings"
- [ ] go to settings -> general
- [ ] see that you cannot access it

**Comment by webong** [comment]
Hello @Angamanga @crcommons ... help review my PR that should fix this bug https://github.com/ushahidi/platform/pull/3875 ... Thank you.

**Comment by rowasc** [comment]
This is in review, just made some comments, thanks again for all your contributions

**Comment by Angamanga** [comment]
@Obadha2 Could you test in Steve Buscemi?
Test checklist:
With an administrator user
- [ ] Create a role with the Manage Settings permission only
- [ ] Assign the role to a user
With a user who has the new role assigned
- [ ] login with that user, access the settings page (you should see this page instead of access denied)
- [ ] access the general settings
- [ ] change a general setting -  site name and regenerate API keys
- [ ] save
- [ ] the settings should save
- [ ] log out
- [ ] the site name should change to what you assigned to it (check the browser tab and the map view)
- [ ] You can check the API key changed in the database, too, or simply reload the settings admin page to see it

**Comment by Obadha2** [comment]
QA'd, passes. 👍
