### ISSUE TITLE
Load new posts bar is not displaying the correct number of posts

### ISSUE THREAD

**Issue by Angamanga** [ushahidi/platform#3325]
**Problem**
If the "Load new posts" bar is visible when the client is checking for new posts, the previous number of new posts is added to the total number of new posts

**Reproduce the bug**
1. Open the data-view in one browser
2. Add a new post in a second browser (or tab)
3. Go back to the first browser, wait until the "Load new posts" appear, it should say 1 new post.
4. Don't click on the load new posts-button
5. Go to the second browser and add a new post
6. Go back to the first browser and wait until the number of posts updates. It now says 3 new posts instead of 2.

## Implementation notes
- Fix in https://github.com/ushahidi/platform-client repo

**Comment by NidhiKJha** [comment]
@Angamanga I am an outreacchy aspirant and I want to work on this issue.

**Comment by Angamanga** [comment]
@NidhiKJha Thank you! 🎉

**Comment by NidhiKJha** [comment]
@Angamanga I have studied the issue in depth and it appears that the case is not just that two new post will say 3 new posts. It's not an issue of counting, but rather when a user makes a new post after the first one, instead of that one post being sent, the last one is sent again as well.
So when a user makes 2 posts, in actuality they're sending 3 posts, the first one is duplicated.
```
make 1 post  -> 1 sent,  no duplicate
make 2 posts -> 3 sent, 1 duplicate
make 3 posts -> 6 sent, 3 duplicates
make 4 posts -> 10 sent, 6 duplicates
make 5 posts -> 15 sent, 10 duplicates
make 6 posts -> 21 sent, 15 duplicates
```
This is not the only issue. There's a second issue here as weel.
When you leave it to update for a while it will increase by the number of posts you've made till then.
ie. 
When you've made 5 posts, it will say `15 new posts`. If you leave it to update and don't make any new posts, the count will increase by 5 every few second. So it will go.
```
15 new posts
20 new posts
25 new posts
30 new posts
35 new posts
.
.
.
.
.... and so on.
```

**Comment by NidhiKJha** [comment]
Could you point me to the code responsible for updation of this count.

**Comment by Angamanga** [comment]
@NidhiKJha Very interesting find! The code responsible for getting the new posts are found in the post-view-data directive, check out this function: https://github.com/ushahidi/platform-client/blob/develop/app/main/posts/views/post-view-data.directive.js#L492

**Comment by NidhiKJha** [comment]
@Angamanga I have submitted a Pull request that solves this issue. Please review it and give me feedback. Thank You!
