### ISSUE TITLE
Update Twitter data source to retrieve only the tweet and user ids

### ISSUE THREAD

**Issue by willdoran** [ushahidi/platform#3330]
The Twitter Data Source should only retrieve and store the Tweet ID and the User ID.

# Spec
- Update the Twitter DataSource to return just the twitter ID, not its content
- Update the Twitter DataSource to return the twitter user id, not their user name
- [Maybe] Stop returning the twitter geographic info (#3329 (comment))
- Don't pull the user's geo info

**Comment by rjmackay** [comment]
This should be fairly straight forward since its mostly removing code, not adding to it.

- Update the Twitter DataSource to return just the twitter ID, not its content
- Update the Twitter DataSource to return the twitter user id, not their user name
- *maybe* Stop returning the twitter geographic info (https://github.com/ushahidi/platform/issues/3329#issuecomment-430464152)
    - Definitely don't pull the users geo info (I think we do this now)

**Comment by rowasc** [comment]
note self: twitter username should change to twitter id
