### ISSUE TITLE
Research Twitter current usage, consider removal for new users

### ISSUE THREAD

**Issue by willdoran** [ushahidi/platform#3341]
- We believe the right to be forgotten wins here over the right to save the data (that should not have been saved)
- We are deleting all messages and blanking out post content and post.title where they match the tweet
- We need to notify the users of the twittter datasource so they know this is coming
- We can do this with a migration since it will apply to everyone who has used the Twitter datasource at any point
     - Messages.message will be blanked out for tweets
     - Posts.content will be blanked out _when_ it matches the tweet exactly. 
     - Posts.title will be replaced with `From twittter on {date}`  _when_ it matches the tweet exactly.

**Comment by rjmackay** [comment]
Quick summary from Slack (without details because this is a public issue)

- Only about 30 paid or grassroots deployments use Twitter at all
- Once we ignore draft posts, it gets down to just 6 deployments with a handful of posts
- Unpaid deployments will get archived if they don't upgrade soon

I think this means that a lot of the issue with old Twitter data will go away once free (aka basic) deployments start getting turned off when they don't upgrade.

For the remainder of them:
- Those we own, we could clean out the twitter data manually if needed
- The others we could reach out to and ask if we can remove twitter posts

The easiest solution then for new deployments would be to disable the Twitter data source entirely.

**Comment by rowasc** [comment]
@willdoran can you verify this is correct, from our chat last friday ? 
- We believe the right to be forgotten wins here over the right to save the data (that should not have been saved)
- We are deleting all messages and blanking out post content and post.title where they match the tweet
- We need to notify the users of the twittter datasource so they know this is coming 
- We can do this with a migration since it will apply to everyone who has used the Twitter datasource at any point

I'll send a PR in a bit if that's the case.

**Comment by willdoran** [comment]
@rowasc I agree with these but we need to check with @aoduor to make sure it's ok and how to communicate it. We should replace title with something like From Twitter and a date it was created.

**Comment by rowasc** [comment]
Ah yea Agree, `From twitter on {date}` maybe ?
