### ISSUE TITLE
Twitter display support for Mobile

### ISSUE THREAD

**Issue by willdoran** [ushahidi/platform#3342]
- Tweets should be displayed using Twitter api to fetch them.
- For Posts that contain Tweets or for Conversation with Author sections that are Tweets, the Mobile App should expect to use the Tweet ID to retrieve the Tweet directly from the Twitter API live.
      - this means we should have support for showing a tweet using the `data_source_message_id` from message.data_source_message_id that will come in the post object
- Ideally, we should reuse pre-existing elements and not design something completely new.
- Because we can't save a tweet's content, the description will not be shown.

Aha! Link: https://ushahiditeam.aha.io/features/PROD-31

**Comment by rowasc** [comment]
@dalezak we have this issue, related to this twitter data import epic https://github.com/ushahidi/platform/issues/3338  where we need to change the way we display posts that are coming from twitter so that we render the content directly from the Twitter API instead of getting the tweet's content from our database. The Platform API will return the tweet id which should be used to fetch the tweet from Twitter. The post will not have a description or title.  

A couple of things 
- I can have the API modifications ready tomorrow EOD. 
- Could you start reviewing and implement a way to show the tweets so once the API is ready we can just test with mobile  (assuming that you will get a tweet id in `message.data_source_message_id` ) ? 
- There's an open question about whether or not we should show the conversation with author section that I will update this ticket with once we resolve it https://github.com/ushahidi/platform/issues/3334#issuecomment-431138463 I posted the question here

This should be treated as a high priority issue. I am working on the API and will update you tomorrow.  

cc @willdoran

**Comment by dalezak** [comment]
@willdoran @rowasc @jrtricafort is there a possible simpler solution to this as temporary fix?

I don't know the full requirements, but perhaps a workaround to change the post title to include `(from Twitter)`?

For example, the post `Here's a post hole on my street` becomes `Here's a post hole on my street (from Twitter)`?

**Comment by willdoran** [comment]
@dalezak No, unfortunately not

**Comment by rowasc** [comment]
@dalezak sadly no. This is needed because of https://github.com/ushahidi/platform/issues/3329

**Comment by dalezak** [comment]
Hmm @willdoran @rowasc, I'm not sure whether the suggested solution is feasible, or at least not without a lot of effort.

Pulling tweets from Twitter API is a big job, several days of work to wire up the provider, refactor how posts are displayed, etc.

Isn't there another server side workaround? For example rather than displaying the tweet text, display the URL to tweet instead? This way the user can click the URL to show the tweet in the in-browser in the app.

**Comment by willdoran** [comment]
@dalezak Why is it difficult to retrieve a tweet with a given ID and display it formatted as a Tweet in Ionic?

This is pretty high priority so if the only option we have is to display the tweet as a link we will have to do that.

**Comment by dalezak** [comment]
@willdoran it will just take some time to wire up that functionality:
- setup a Twitter API key
- add Twitter NPM module
- add Twitter provider
- refactor data model to store `data_source_message_id`
- update page to use Twitter provider
- display that tweet in the page

Perhaps a better option is to just use the Twitter embed?

https://developer.twitter.com/en/docs/twitter-for-websites/embedded-tweets/overview.html

**Comment by rowasc** [comment]
@dalezak @willdoran I think the embed sounds good enough as a hotfix at least. We can do a follow up issue for better UX after going live next week, I think.

**Comment by dalezak** [comment]
@willdoran @rowasc I commented here https://github.com/ushahidi/platform/issues/3329#issuecomment-431410411, I'm wondering whether displaying Twitter's embed in the app is necessary to comply with Twitter ToS?

For example, if the data was purged or cleaned server side for deleted Tweets, then the mobile app wouldn't require any changes since it would pull those updated posts?

**Comment by willdoran** [comment]
@dalezak Can you estimate how long it will take to implement the embed option?

**Comment by rowasc** [comment]
bumping. @dalezak see  @willdoran question above. 
Also: note that the `data_source_message_id` used to load tweets will come in the post directly  (edited my original comment)

**Comment by rowasc** [comment]
@dalezak can we schedule the new twitter display change for this week/the next one?
cc @willdoran

**Comment by rowasc** [comment]
checkin... @dalezak was this change implemented?

**Comment by Erioldoesdesign** [comment]
@dalezak can you let us know asap whether this got done or whether it needs to be taken on by someone else please?

**Comment by dalezak** [comment]
@rowasc @Erioldoesdesign has the backend changes to the API been made for this yet?

If so, I can work on the mobile app changes, although it's been quite awhile since we've submitted an app update so will take some time to get things compiling again, then need to submit app updates to Apple Store and Google Play for it.
