### ISSUE TITLE
Migration process to v4

### ISSUE THREAD

**Issue by ArturoQuintana** [ushahidi/platform#3347]
Yesterday we started the migration process of our Ushahidi instance from v3 to v4.

Unfortunately, after applying all the commands to complete the process, our instance does not work correctly due to the following errors:

- There are some errors "500". This usually happens once you visit our page and reload it.
- If we reload the page, sometimes we lose the publications (that happens randomly, as well as some behaviors)
- There is a group of errors 401 that create a loop in the client's API. This implies that the map seems to be loading all the time.
- The login process is broken
- When we try to log in, there is an error in the connectivity related to the communication between the token - user (this creates a loop)
- We have lost the images

You can see these issues visiting this link:

https://map.informus.us/views/map

**Comment by rowasc** [comment]
@tuxpiper @willdoran adding context on the two issues that I've been trying to follow up on today. We need some help in point `2` first if one of you can, since nobody can log in to the site. 

1 - The .ENV variables are sometimes not being read. At the moment we verified this was the case by hardcoding the values in the ohanzee-db.php file and adding a database.php file like the one lumen has, which stopped the random 500s.  I'll have to investigate with Arturo after we mitigate the second issue so we can go back to using the .ENV file as we should, I suspect it's the dotenv library or lumen config issues with .ENV values (there's a long-standing issue with this and cache, but the known fix didn't solve it here)
2 - When logging in, the /me request always returns "unauthorized" 401, resulting in a loop in the client that keeps trying to login but never achieves it. The 401 also happens if I do an /oauth/token request and then /me request in postman manually (/me returns 401, using the bearer from /oauth/token)

**Comment by willdoran** [comment]
@ArturoQuintana 

Are you still experiencing the login in issue?

What version of the Ushahidi Client are you using?

I would suggest that you try the following:
1. Do a clean install on a completely clean server and clean DB
2. Test that you can login normally
3. If that works point the platform at your production DB
4. Report back if that works.

**Comment by rowasc** [comment]
Closing due to lack of recent activity. Please reopen if necessary or reach out in https://gitter.im/ushahidi/Community for community support . 
Thanks!
