### ISSUE TITLE
Default Step should be titled Step 1, not structure

### ISSUE THREAD

**Issue by caharding** [ushahidi/platform#337]

**Comment by jshorland** [comment]
Assigning to @brandonrosage for input.

**Comment by brandonrosage** [comment]
The "Mustang" Pattern Library suggests we call the Steps:

* Post
* Verify
* Translate

![image](https://cloud.githubusercontent.com/assets/1136279/14969486/54b2549c-1088-11e6-850f-0826ca8c6631.png)

The term "Post" is used much more sparingly in Mustang. But we use it in this case because, A, it's reasonably intuitive, and B, it doubles as a verb (particularly when someone is authoring or editing).

Also remember that steps may be used in order, but are not explicitly sequential. So we don't want to imply that one step must be completed before another, or that a later step is inaccessible.
