### ISSUE TITLE
Upload header "Choose File" button should be styled, not browser default

### ISSUE THREAD

**Issue by caharding** [ushahidi/platform#343]
<img width="456" alt="screen shot 2015-08-13 at 10 00 23 am" src="https://cloud.githubusercontent.com/assets/1618793/9256072/39f26378-41a2-11e5-85fa-6eda4fbb75df.png">

**Comment by rjmackay** [comment]
cc @seth 
Is it possible to easily style file upload buttons?
If not, I say we skip this. I don't want to start reimplementing browser UI in CSS .

**Comment by rjmackay** [comment]
Sorry cc @middle8media

**Comment by middle8media** [comment]
This is possible but will take some hacking and may not be worth the time spent.
http://stackoverflow.com/questions/572768/styling-an-input-type-file-button

@rjmackay if you want me to do this reassign to me, in the meantime I am assigning to you because of this - https://github.com/ushahidi/platform-pattern-library/commit/018903bd3a4b4070dcbd4bccbf151dcfb93187e3

**Comment by rjmackay** [comment]
Dropping it to low priority. And deassigning
