### ISSUE TITLE
Ability to automatically redirect a responder to a webpage or document

### ISSUE THREAD

**Issue by Erioldoesdesign** [ushahidi/platform#3480]
Bristol Women's Voice who own the deployment: https://bristolstreetharassmentproject.ushahidi.io/views/map

talked about wanting: The ability to automatically redirect a responder to a webpage or document that will help them e.g. they send a report about hate speech -> get a message about a resource by BWV to recover from Hate Speech threats or where to go for legal advice.

Aha! Link: https://ushahiditeam.aha.io/features/PROD-249

**Comment by Angamanga** [comment]
@Erioldoesdesign What would this look like? Would like to add it as a GsoC/Outreachy-issue but have a hard time grasping what it would look like?

**Comment by Erioldoesdesign** [comment]
@Angamanga 

Ah so let me try and go step by step what Bristol Women's Voice (BWV) wanted:

1. A deployment has an existing survey/s

2. A 'responder' clicks the (+) (or responds to the survey in another manner (embedded in an iframe, email, or possibly SMS etc.)

3. 'Responder' finishes the survey and then is shown a 'final message' where they can learn more about a certain campaign or topic. In the BWV case, if a person is reporting street harassment, they wanted to show a message with a link to their information page about reporting the street harassment to the police.

There are perhaps two ways this could be done, one is a message/content/link is shown after a survey based on the survey. So if I complete response to 'Survey 1' I get info relevant to 'survey 1'

When I was with this user they also spoke about wanting to show information/links *depending on one answer within a survey* which gets complicated due to needing some kind of survey logic e.g.

If responder answer 'yes' to question 3 then show a message at end of survey.
If responder answer 'no' to question 3 then *don not* show a message at end of survey.


It might be a little complicated for a GSoC/Outreachy project but without the logic version, it sounds doable. Possibly even using the snackbar UI as the delivery method of the message/link? 

But! how cool would survey logic be?! haha 😅

**Comment by Angamanga** [comment]
Yeah, survey-logic would be 🔥! Maybe we could use the modal instead for a snackbar? Similar to the confirmDelete modal or login-modal? That is more visible than the snack-bar.

**Comment by Erioldoesdesign** [comment]
@Angamanga totally up for modal! Perfect is the enemy of good enough here and I'd love to see if it's useful for users :)

**Comment by onyeepeace** [comment]
Hi @Angamanga , I am interested in fixing this. Can you please assign this to me? I will also write out my procedure on working on this as I contribute and link it as well.

**Comment by Angamanga** [comment]
@onyeepeace Thank you for your interest! Please go ahead! 🎉

**Comment by onyeepeace** [comment]
Okay, great. Thanks @Angamanga

**Comment by onyeepeace** [comment]
@Angamanga Please I will like to get a clear view on how this will work out. Are there links I should have for the redirection?

**Comment by rowasc** [comment]
@onyeepeace this is a full size feature, so we need to spec it out together. Ok so we need
1 - A way for survey admins to be able to add information with markdown. The submission input should be similar to the ones we have for field descriptions, with UI that allows you to edit styles.  We'll call this information a "post submit hook" (ie: after submit). Rough example of what that could look like. Right now I placed it after the "description" field in the survey editor but I suspect we'll want to place this on its own tab at some point in the future.
![Screenshot from 2020-10-20 19-57-22](https://user-images.githubusercontent.com/2434401/96653006-819dbb80-130e-11eb-89bc-bc8102a9d13c.png)

2- After a report is submitted by someone, if the post submit hook for that survey is not empty, we will display the information. To show the information we can use the same system we have for thanking the user (you can see it after submitting a post right now)

So that's the feature essentially: a way to setup and then display messages that come up once you submit your report. We won't really do automatic redirects here, not now at least, but we will allow links which would let people get to the information the survey admin wants them to see.

-----------

Now in terms of how to save this information...  I'm still wrapping my head around it. There's 3 ways I can think of right now
1 -  Add another metadata field to forms (surveys) that's specifically for saving the post_submit hook. This is the simplest approach, and the good thing about it is that it makes sense from a data perspective simply because we can treat it the same as the survey description (ie: read-only) instead of hacking around the tasks or field systems.
2 - Add a special type of stage (task) that is for read-only purposes and only comes up when you hit submit. This can get complex but also I kind of like the idea because it follows the pattern we have, and it's not the first time we've thought of read-only stages or fields. So it has potential for other usages, but we could always come to this if we need it instead of introducing the complexity early on.
3 - Add a special type of field (basically the same as the task idea but a field)


@tuxpiper @Angamanga @onyeepeace  what do you think? 

This feature was requested by a user group, and I  see the potential. It allows you to personalize thank you messages essentially, or provide critical follow up info. My only concern is that it's the kind of feature that can get too ambitious and I'd like to keep it contained and then test how much reception it gets if it makes it to production before investing a lot (but I suspect we may want to invest on it, specifically on conditional information... but again, just a guess). 

I recommend we do option (1) in terms of data, mainly because with a simple field on the forms table, at least it's low cost enough to be worth the experiment... and relatively easy to migrate off to more complex structures if we need them (compared to starting with more complexity).

**Comment by tuxpiper** [comment]
I kind of like 2, as a way for deployment teams to document and follow their own triaging/verification/etc process right within the tool. But I am not 100% is the best fit for that and I feel that the UX for that specific case would look different, so it looks like a long route to take advantage of that.

As for 1, I am not a great fan of adding database columns for each ad-hoc feature that pops up, but I'm not put off by it strongly enough to hinder the development of this feature.

I kind of have warm feelings towards 3 , a special type of field would have a lot of uses. However, I'm concerned about the conceptual mismatch between something that is part of the contents of the form (a field), as opposed to something that happens as a consequence of doing something on the form.

So yea, I think, pragmatically, 1.

**Comment by Erioldoesdesign** [comment]
Just having a read of the progress here and Its so cool to see this being worked on 😄 

Just saying from a UX pov the process you've gone through in speccing sounds great and as far as option 1,2 or 3, I think I'm not clearly understanding the options...I think one of them is that you add the post-submit details like you would any survey field type if you want it and populate it as such. Great for users that are familiar with all the field types and have time to investigate it. So Sounds like this would need some support docs to show users it's available.

I think I see another option where post-submit survey details field is treated like the two default survey field types when you make a survey (Title and description?) but if it's empty it doesn't get served to survey responders.

Let me know if I can help more on the UX and also, if you'd like this tested with the original user I interview/talked with that wanted this feature. I'm sure they'd happily have a chat about whether it goes some way to meet their expectations

**Comment by onyeepeace** [comment]
Hello @rowasc @Angamanga. I have created a new deployment to work on this. I still do not have a clear view on it yet. But here's what I have thought of;
Will this come under the build tab in the picture below?

![Screenshot (132)](https://user-images.githubusercontent.com/53520853/99545986-3979c380-29b6-11eb-9ed5-d2796f749085.png)

So will a field be added with the add field button and then the markdown option will be selected?

![Screenshot (133)](https://user-images.githubusercontent.com/53520853/99546278-907f9880-29b6-11eb-985c-22c9e86f8ac0.png)

And then it appears like this?

![Screenshot (134)](https://user-images.githubusercontent.com/53520853/99546416-ac833a00-29b6-11eb-8f00-7a651f38dfb0.png)

Or is it added as part of the options after clicking on the add field button?
