### ISSUE TITLE
Create End-to-End deployment helper running in browser

### ISSUE THREAD

**Issue by tuxpiper** [ushahidi/platform#3494]
A validation / diagnostics tool running on the browser, to be made available in a specific route ( i.e. https://deployment/diagnostics ) . 

This could be either ...

1. A separate module in the same application reachable through an application route
2. A completely separate application (Angular / ReactJS ? ) . This may work better to make this a truly stand-alone tool.

If an error happens while starting the main frontend app (i.e. API backend not reachable), there should be a link prompting the user to open the diagnostics.

Several different tests can be added to the diagnostic module / app . This may be just sequentially, although a tree structure could make more sense (i.e. run some test only if another previous test succeeds).

The output could be assumed to be just a list of tests, results and information about those. No interaction from the user is expected, aside from maybe digging into the available information.

**Comment by rowasc** [comment]
random thought. This could interact with the backend verifier (either as a listed "verified/failed" state or some other way) so that we get an "all clear" from the backend verification "endpoint" and can proceed with confidence knowing if there's any issue, it's going to be frontend specific

**Comment by rowasc** [comment]
May be a good idea to classify the types of common failures a user would encounter setting this up , starting in this thread for now 

- Server is unreachable
    - they pointed to the wrong url 
    - it's the correct url but the server is down 
- /config results in a 404 
    - they pointed to the wrong base url entirely (ie they point to a blog in the main url instead of an Ushahidi api hosted in the same server) 
    - they add unnecessary path parts like /api/v3 to the base url in .env
    - the url is the one they intend to use, but the server is misconfigured somehow so it's not where they expect it 
        - this would lead to nginx or apache configuration verification
- /config results in a 500
         - database missing or .env in backend has the wrong db config
         - didn't run composer
         - wrong php version

-Note:  I don't think /config  can result in a 503 in any situation right?


In addition to this scenarios , there are others that would come up by trying to authenticate: 
 - a 503 because of a bad client id / secret used in the frontend
- a 503 because the database doesn't have the default client secret/id

**Comment by rowasc** [comment]
Focusing more on specific frontend verification issues now
- an .ENV file verifier
- probably switching our approach to recommend users run gulp from `npm run start` so we can run the verifier and other tools as a cli step before the gulp command would make this better
- ?

**Comment by tuxpiper** [comment]
> maybe a way to make this better is by switching our approach to recommend users run gulp from npm run start so we can run the verifier and other tools as a cli step before the gulp command

That's actually a good point, if the checks are just about the presence and structure of variables in `.env`,  then a npm hook would be great .

**Comment by tuxpiper** [comment]
Another check that comes to mind:

* presence and content of config.json file, for the mobile app to work

**Comment by rowasc** [comment]
Notes from our meeting

Verifier frontend 
- Simple file /verifier.html
- If prod build without verifier flag, don’t add it
- If prod build with verifier flag, add it
- In dev, always available a /verifierr.html
- Cli script for env/config
- `npm run verifier` would verify formats

Verifier backend
- Composer script calls class (class not in lumen load)
    - Verify env file has all required 
- Fastcgi check
- PHP-info check
- Modify the docs to let people know they need to install the frontend ahead of time. Give them the rationale for it (there is a verifier that will help you ) 
- Hook migrations to post-install-cmd
- Final tests to env to post-install-cmd

----------

User flow: 

- Docs tell you “start with client setup”
- Client install
- Client /verify url tells you “setup the web server” and link to backend setup docs
    - Backend docs take you through the steps , adjust them to consider the verifier "handholding" mode if needed
- User setups web server
- Client tells you “everything is ok in the web server"
- Client tells you "now you need to run composer install”
- pre-install-cmd runs: 
    - “Please fix your .env file”
    - Verifies cli php version
    - Verifies file permissions
    - Verifies Redis server if enabled
    - Verifies database server setup
    - Verifies it can access lumen console commands (? maybe, not sure)
- Once pre-install cmd runs, the installer runs automatically, then the post-install-cmd
- The backend prrovides a /verify endpoint which will allow us to know the PHP version in the web, if the auth headers are coming through, etc 
- Once it all works, the client says "It woks, congratulations" and then shows a "One last thing" red screen informing you how to disable the verifier in the backend and how to check it's disabled. 
- Once verifier is disabled we show "You are done!" and it's green. We can also inform them, if it's a production build, that they need to run `npm run disable-verifier` so users cannot access this screen. 
-  `npm run disable-verifier` is a script that rebuilds with the verifier OFF in the frontend

**Comment by Erioldoesdesign** [comment]
Things the Eriol said when David took them through this:

- When users are doing an installation process, a pre-checklist goes down well e.g. 'Have you tidied up your existing projects lately?' 'Do you have X space on your HD?' "Have you thought about where to set this project up?'

- Users love a time frame for installations. "If you do this installation in one sitting, it will take you between 1 - 3 hours'. Since the checker will keep track of where users are, that helps. Most people with lives/responsibilities/kids/pets/office jobs will do long processes in chunks of 30 - 1 hour time intervals.

- People love positive affirmation and ticking off things themselves. It's great to have an automator that runs a check. But ticking a list yourself usually gives you warm fuzzy feelings towards [product/company/self]

- More advanced users like to be able to turn 'hints/installers/tips' on/off as it gives them a chance to learn/choose when to be helped

- If you want people to read technical instructions, make the sentences shorter, but more frequent. So like 5 separate pages of 1 sentence is better than 1 page of a paragraph.
Other tips for encouraging read vs. click-y clicking = Smaller buttons, requiring a checkbox tick to confirm you've read, asking the user a question about [instruction] before progressing (half learn half do approach)

- People will typically feel super good after completing the process! give them a clear call to action e.g. [check out our first time issues here] and they'll typically do the thing :D

- Give users access to customer support but not 'unguarded' e.g. ask them a set of reasonable questions to send a CS support request like: can you provide a screenshot of your installer/terminal and your system set up and any ideas you might have about the problem.
It's just enough of a barrier to push some people not to talk to CS but to try and fix it themselves but not too much that it's an unreasonable request. Try to make users feel like they solved the problem themselves = positive feelings!

**Comment by rowasc** [comment]
I would really like to have thoughts from @Erioldoesdesign on how to make it clear that this is a verifier, not an installer that you can click your way through. I worry that verifier may not be a term that makes sense to most people 🤔 , maybe "Installation Helper" ? -or am I worried about nothing?-

 I think the interactive ideas (checkboxes to confirm they read, etc) are really good, I think they may make it easier to ensure our instructions are followed and that if something fails people know in which step it failed when they report it.

Something I would like is to have the tool give a report on their environment so they can attach it to their support requests. ie getting the same inputs as the verifier we create a txt that they can then send to us.

**Comment by tuxpiper** [comment]
I would also really like a catchy, easy to grok, name for this thing . "The Fixer"? "The Mechanic"? Some really useful Pokémon?  :shrug:

**Comment by rowasc** [comment]
When we're naming this I'd make sure we it's either super obvious what it does ("verifier")  or that its gives zero information on what it does (Pokemon names). I like The mechanic and the fixer, but they both sound like it'll fix something on its own when in reality the user will be the one doing the bulk of the work so I don't know how I feel about using those names yet. 

I'd recommend using it in a phrase and checking how it works if you aren't familiar with platform. 
"Have you tried running <the mechanic>, platform's installation verifier?  What did it report? "
"Have you tried running <Evee>, platform's installation verifier? It should give you some help in figuring out the next step "
etc 

I'll report back if I have any names :D

**Comment by Erioldoesdesign** [comment]
@rowasc Sorry I missed your direct comment (so many ticket notifications lately!)

We'll do a lightweight design for the UI for the 1st round but we will for sure be considering more 'designed' for a next version.

**Comment by rowasc** [comment]
all good. Thanks 🚀 💯

**Comment by Erioldoesdesign** [comment]
Update: I'll look at light UI design after David L's first pass at the most basic of basic-ness UI wise so I can see what I'm working with before doing anything!

**Comment by rowasc** [comment]
Closing as the only missing things are bugfixes now
