### ISSUE TITLE
Data sources - "tweets" is always used to describe the content for the "Import to survey" field

### ISSUE THREAD

**Issue by Erioldoesdesign** [ushahidi/platform#3531]
**Describe the bug**
When setting up data sources, the data source type is hardcoded and is always "tweets" instead of the correct data source type. 

**Where was the bug observed**
Personal test deployment: https://lgbthistoryswuk.ushahidi.io/views/map

**To Reproduce**
1. Go to a deployment you have admin access to
2. Log in as 'an admin' 
3. Click on 'settings'
4. Scroll down to 'data sources'
5. Choose 'email', or any of the SMS data sources 
6. Toggle on 'Accept survey submissions from this source'
7. Toggle on 'Import to survey'
8. In the text that says 'Choose what should be assigned to each survey field
Each of the survey's fields are listed below. Choose the data from your *tweets* that you'd like to use to populate each of those fields.'

**Expected behavior**
The data source type shown in the description should match the one the user is looking at.
It should read 
- For the Twitter data source: Each of the survey's fields are listed below. Choose the data from *Twitter* that you'd like to use to populate each of those fields.'
- For the Email data source: Each of the survey's fields are listed below. Choose the data from *Email* that you'd like to use to populate each of those fields.'
.. etc ...

**Is there a workaround? What is it.**
No

**Screenshots**

<img width="829" alt="Screenshot 2019-05-07 at 12 45 22" src="https://user-images.githubusercontent.com/11681324/57297084-90ff5980-70c6-11e9-8469-4f28bfb0cc56.png">

**URL / Environment where this happened**
Any ushahidi.io or testing environment with Ushahidi V3 or V4

**Desktop Hardware Details (please complete the following information):**
- Applies to any OS
- Applies to any browser

## Working on this issue

- The repository for this change is https://github.com/ushahidi/platform-client.  Start here https://docs.ushahidi.com/platform-developer-documentation/getting-started if you have not set up the Ushahidi client before. Notice that you only need to install the platform-client (no need to set up the API for this) as long as you connect it to a live ushahidi.io or Ushahidi testing deployment.

## Implementation notes
- Fix in https://github.com/ushahidi/platform-client repo
- Hint :bulb: The file with all the language keys can be found here: https://github.com/ushahidi/platform-client/tree/develop/app/common/locales/en.json
- When you are done, 🔀 Start a Pull Request. There are two ways how you can start a pull request:

   1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

   2. You can also[ edit files directly in your browser](https://egghead.io/courses/how-to-contribute-to-an-open-source-project-on-github) and open a pull request from there.

- 🏁 When done Ask in comments for a review :)

## Changes required (first timers only)

- in the en.json file, look for the key "choose_survey_field_desc" and replace its value with 
```
"Each of the survey's fields are listed below. Choose the data from {{datasource_type}} that you'd like to use to populate each of those fields.",
```
- in the datasources.html file, look for the p with the translation key "survey.choose_survey_field_desc" and replace that <p> with 

```
<p translate-values="{datasource_type: provider.name}" translate="survey.choose_survey_field_desc">Each of the survey's fields are listed below. Choose the data from your tweets that you'd like to use to populate each of those fields.</p>
```

Ping @rowasc if you need help with this issue!

**Comment by Jenniline** [comment]
Hi, @rowasc sc  I saw this and I am interested in it. I  have already begun working on it. I Just have a question on the location of the data sources .html file. I am almost finished working on the issue. 
Thanks

**Comment by Jenniline** [comment]
Hi @rowasc,
I have made a Pull Request on this issue.
The Pull Request is on the edit in the en.json file
Please review it. 

Nevertheless, I still need help with finding the datasources,html file.

Thanks

**Comment by ritesh-pandey** [comment]
> Hi, @rowasc I saw this and I am interested in it.
> I will like to be assigned this issue.
> I have already begun working on it. I have a question on the location of the data sources .html file.
> I don't seem to find it in the DataSources folder.
> I am almost finished working on the issue.
> Thanks

Second change requires editing in this file.
`/app/settings/datasources/datasources.html`

**Comment by Angamanga** [comment]
@Jenniline Thank you for looking into this. @ritesh-pandey is right (thanks for helping out!), the files related to datasources are found here: https://github.com/ushahidi/platform-client/tree/develop/app/settings/datasources

**Comment by Jenniline** [comment]
Thanks @Angamanga and @ritesh-pandey. I have viewed the file and I have made the necessary changes. 
@Erioldoesdesign and @rowasc I have made a pull request for this issue here are the links 
for the en.json file: https://github.com/Jenniline/platform-client/pull/1
for the datasources.html file:  https://github.com/Jenniline/platform-client/pull/2.

Please review it. 
In addition, I will also like to be assigned this issue. 
Thanks

**Comment by rowasc** [comment]
Thanks @Jenniline . We'll review it and get back to you 🎉 thank you !

**Comment by Angamanga** [comment]
@Jenniline Thank you! Could you start with updating your fork with the newest changes in Ushahidis Platform-client-repo (a guide on how to do that can be found here: https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/merging-an-upstream-repository-into-your-fork) and then make a pull-request into this repo rather than into your own (a guide about that is found here: https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork)? Thank you :)

**Comment by Jenniline** [comment]
Hi @Angamanga I have updated my fork and made the pull Request please review and let me know thanks

**Comment by Angamanga** [comment]
@Jenniline I don't find the pull-request, can you please try to open it again? Thank you 🎉

**Comment by Jenniline** [comment]
Hi Anna, here is the link to the branch
https://github.com/Jenniline/platform-client/pull/4/commits
This time I  made the commits consisting the changes to the 2 files in 1 branch. Since you once told me it is better to manage that way.

**Comment by Angamanga** [comment]
@Obadha2 Can you QA in Steve buscemi please? 🙏 
Testing checklist:
- As logged in admin, go to settings->datasources
- Toggle on 'Accept survey submissions from this source'
- Toggle on 'Import to survey' (You may need to add data in each field in the datasource before these toggles appear, it doesn't need to be correct credentials :D )
- [ ] The text should says 'Choose what should be assigned to each survey field
Each of the survey's fields are listed below. Choose the data from your [[THE NAME OF THE SELECTED DATASOURCE HERE]] that you'd like to use to populate each of those fields.'

**Comment by Obadha2** [comment]
This fails QA.
It says " Choose the data from that you'd like to use......."
See attached screenshot:
<img width="1142" alt="Screenshot 2020-02-17 at 1 55 07 PM" src="https://user-images.githubusercontent.com/38259840/74647758-4fd7c200-518d-11ea-8185-0f4e9bd3440e.png">

cc @Jenniline @Angamanga

**Comment by Jenniline** [comment]
Hi @Obadha2 
Alright, let me look into it again.
Any tips or ideas on what I can do?
Thanks

**Comment by Angamanga** [comment]
Ah, I missed this! So @Jenniline there is a few things that needs to be done:
1. Change "{ provider: provider.name }" to "{ datasource_type: provider.name }" here: https://github.com/ushahidi/platform-client/blob/develop/app/settings/datasources/datasources.html#L77 (this is so that the translation values is mapped correctly in en.json.
2. Add back translate="survey.choose_survey_field_desc" as well to this row: https://github.com/ushahidi/platform-client/blob/develop/app/settings/datasources/datasources.html#L77 (instead of translate="")
3. On row 120, https://github.com/ushahidi/platform-client/blob/develop/app/settings/datasources/datasources.html#L120, add "{ datasource_type: provider.name }" in the same way as on row 77.

**Comment by Jenniline** [comment]
Alright @Angamanga I will do them.

**Comment by Angamanga** [comment]
@Obadha2 Could you recheck in Steve Buscemi please 🙏 ?

**Comment by Jenniline** [comment]
Hi Anna, 
I have looked into this issue again and what I have realised is that; In the datasources.html file, the changes you recommended already exists. you can see that here https://github.com/ushahidi/platform-client/pull/1442/files

In the en.json file, the issue there is that, the sentence does not make sense what I mean is it looks like this on line #316   "Each of the survey's fields are listed below.   "Choose the data from **_{{datasource_type}}_** that you'd like to use to populate each of those fields."

But it is displayed on the Platform-client this way:  "Each of the survey's fields are listed below. "Choose the data **_from_**  **_that_** you'd like to use to populate each of those fields." 

There is an omission between from and that because the code ({{datasource_type}}) cannot be displayed. 

So then in the pull requests I have just made, I removed the  **_{{datasource_type}}_**  and replaced it with data source type.  more of the description is in the pull request. Here is the link https://github.com/Jenniline/platform-client/pull/7.

Please review and let me know Thanks

**Comment by Obadha2** [comment]
This passes QA. 👍
