### ISSUE TITLE
Setting up a Twitter application is a lengthy process for new users

### ISSUE THREAD

**Issue by Erioldoesdesign** [ushahidi/platform#3533]
When setting up Twitter as a data source our first step that we advise users do is to 'Create a new Twitter application'

<img width="535" alt="Screenshot 2019-05-07 at 12 58 28" src="https://user-images.githubusercontent.com/11681324/57455138-60542700-7262-11e9-918d-6eefc4ad2f8c.png">

Recently Twitter has added a lengthy process to be approved for a twitter application and we could offer new users some more advice as to how to get approved and what Twitter needs to approve.

Links to Twitters application documentation would be useful for users.
https://developer.twitter.com/en/apps/create

You also must have a twitter account in order to set up an application and even view the docs.

**Is your feature request related to a problem? Please describe.**
Users would be frustrated if they needed to set up twitter feeds into platform within a short period of time. Especially if they are not familiar with this kind of set up.

**Describe the solution you'd like**
A short description on what a twitter application requires e.g. An existing or new Twitter account preferably linked to your project or organisation, a short description of what kind of twitter information you will gather and what you will do with it, 

A short text that reads ' Twitter applications may take a few hours or a few days to be approved by Twitter. Please be aware of this if you need this data quickly'

# To reproduce/see this section

**To Reproduce**
1. Go to a deployment you have admin access to
2. Log in as 'an admin' 
3. Click on 'settings'
4. Scroll down to 'data sources'
5. Choose 'Twitter'
You will see the "Create new twitter application" section/link.

# Task: Adding new descriptions to solve this ticket

6. In the text that says 'Create a new twitter application" add "Twitter applications may take a few hours or a few days to be approved by Twitter. Please be aware of this if you need this data quickly."  (note: please feel free to improve on this!) -> this section can be added to the en.json  key "intro_step_1_desc" in app/common/locales/en.json within the platform-client repo.

## Working on this issue

- The repository for this change is https://github.com/ushahidi/platform-client.  Start here https://docs.ushahidi.com/platform-developer-documentation/getting-started if you have not set up the Ushahidi client before. Notice that you only need to install the platform-client (no need to set up the API for this) as long as you connect it to a live ushahidi.io or Ushahidi testing deployment.

## Implementation notes
- Fix in https://github.com/ushahidi/platform-client repo
- Hint :bulb: The code handling users can be found here: https://github.com/ushahidi/platform-client/tree/develop/app/settings/users

- When you are done, 🔀 Start a Pull Request. There are two ways how you can start a pull request:

   1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

   2. You can also[ edit files directly in your browser](https://egghead.io/courses/how-to-contribute-to-an-open-source-project-on-github) and open a pull request from there.

- 🏁 When done Ask in comments for a review :)

## Want to work on this issue?🙋 
Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

Ping @rowasc if you need help with this issue!

**Comment by hyperhitesh** [comment]
Came across a project called [Twint](https://github.com/twintproject/twint), it doesn't need an API key and can do tweet scraping, just thought I'd share in case it's helpful.

**Comment by rowasc** [comment]
Hi @hyperhitesh twint is not something we can use at the time. The Twitter ToS prohibits scrapping without explicit consent from Twitter, so we cannot use it. Thanks anyway for the recommendation! :)

**Comment by Jenniline** [comment]
Hi @rowasc,
I will like to be assigned this issue.
 I need help with this issue. It is quite straight forward and the hint is a lot of help. However, I don't seem to find the line of code from where this issue is from. 
I have gone through the link on the hint and searched all the code files for the text that says **"Create a new Twitter application"** but I have not found it. 
Please direct me on where I can find the text so as that I can work on this issue. 

Thanks

**Comment by Angamanga** [comment]
@Jenniline Thanks for looking into this issue. You find the code for this issue in the datasources-folder: https://github.com/ushahidi/platform-client/tree/develop/app/settings/datasources. What makes it confusing is that the text is coming from the api at this point (https://github.com/ushahidi/platform/blob/develop/src/App/DataSource/Twitter/Twitter.php), so that is why you don't find it :) You could still add the description in the datasource.html-file!

Good luck and reach out if you need more guidance🎉 !

**Comment by leninpaulino** [comment]
@Jenniline are you currently working on this?

**Comment by Jenniline** [comment]
Hi @leninpaulino Yes i am currently working on this issue.
You can still find more issues on the issue tracker, and keep in mind that Ushahidi has a platform and a platform-client it is good that you set up environment for each because some issues will need you to run the problem and see the behavior before being able to solve.
You can reach me if you need help.

**Comment by Jenniline** [comment]
Hi @leninpaulino Yes I am. Almost done with it

**Comment by leninpaulino** [comment]
Nice, I'll try to do the setup and after that, I'll move with something else from the issues. Thanks.

**Comment by Jenniline** [comment]
Alright,  you can ping me anytime if you need help.

**Comment by Jenniline** [comment]
Hi @Angamanga and @rowasc  I have made a pull request for this issue https://github.com/ushahidi/platform-client/pull/1422#issue-371547833 

I edited the en.json file as described by @Erioldoesdesign in the problem description. 
Do I still need to edit the datasources.html file and the Twitter.php file? 
Please let me know

**Comment by Erioldoesdesign** [comment]
Hey @Jenniline I'm gonna comment in the pull request conversation as I have just a few wording tweaks from my perspective of having raised this issue :)

I hope that's okay @Angamanga and @rowasc

**Comment by Angamanga** [comment]
@Obadha2 Can you test QA this in Steve Buscemi please?
Testing checklist:
- As logged as admin, go to settings -> datasources
- Select Twitter
- [ ] The text should warn the user that setting up Twitter may take time (It should say: " Create a new Twitter application: Twitter applications may take a few hours or days to be approved by Twitter. Please be aware of this if you need this data quickly.

**Comment by Obadha2** [comment]
@Angamanga @Erioldoesdesign @Jenniline  could we have this appearing as two different sets of information such that the second part of the text appears as additional information, italicised perhaps. Rather than a long string of text, have something ilke:
Step 1: Create a New Twitter application.
_Twitter applications may take a few hours or days to be approved by Twitter. Please be aware of this if you need this data quickly._

**Comment by Erioldoesdesign** [comment]
@Obadha2 Makes sense. I would say it should be located after the text link 'new twitter application' that already exists in the layout in italics:
![Screenshot 2020-02-18 at 14 13 05](https://user-images.githubusercontent.com/11681324/74743724-d0172980-5258-11ea-857d-25784bb69a2e.png)

**Comment by Jenniline** [comment]
Ok, I see.
@Erioldoesdesign and @Obadha2 will it look better this way?

Step 1: Create a new Twitter application
_Create a new Twitter application_
_Twitter applications may take a few hours or days to be approved by Twitter. Please be aware of this if you need this data quickly. _

Is this better?

**Comment by Obadha2** [comment]
@Erioldoesdesign with that we'd have the text "Create a new Twitter application" appearing twice? I suggest we have that once looking like:

Step 1: Create a [new Twitter application.](linktonewTwitterApplication)
_Twitter applications may take a few hours or days to be approved by Twitter.
Please be aware of this if you need this data quickly._

**Comment by Obadha2** [comment]
> @Obadha2 Makes sense. I would say it should be located after the text link 'new twitter application' that already exists in the layout in italics:
> ![Screenshot 2020-02-18 at 14 13 05](https://user-images.githubusercontent.com/11681324/74743724-d0172980-5258-11ea-857d-25784bb69a2e.png)

@Erioldoesdesign with that we'd have the text "Create a new Twitter application" appear twice. I suggest we avoid that?
Would this appear better?

Step 1: Create a [new Twitter application.](linktoNewTwitterApplication)
_Twitter applications may take a few hours or days to be approved by Twitter.
Please be aware of this if you need this data quickly_

**Comment by Angamanga** [comment]
@Jenniline The change @Obadha2 suggests is good. Do you have time to go ahead and change that?

**Comment by Jenniline** [comment]
Yes I will. 
Thanks

**Comment by Jenniline** [comment]
Hi Anna,
I Have made the changes requested. Here is the link to the Pull request  
https://github.com/ushahidi/platform/pull/3858
I made the changes to the Twitter.php file because that was the file I thought needed the changes you mentioned above and since you had already merged the pull requests to the en.json file.
If not please let me know if I should make any more changes to any other files.

Thanks

**Comment by Angamanga** [comment]
@Obadha2 Could you recheck in Steve Buscemi? The text should now look like this (had to keep the link in the description because of styling-issues. The link did not look ok as a label/headline): 

<img width="733" alt="Screenshot 2020-03-02 at 14 31 45" src="https://user-images.githubusercontent.com/8624777/75680776-8dab0f00-5c92-11ea-887d-d1e571b5b12e.png">

**Comment by Obadha2** [comment]
Alright, this looks good @Angamanga  ! 👍 
Thanks @Jenniline
