### ISSUE TITLE
How to log issues on Github

### ISSUE THREAD

**Issue by Angamanga** [ushahidi/platform#3585]
I imagine this will be how to fill out our 'issue' template and when to add sections, remove sections and miss out sections depending on what you're logging. Also labels. Also who to tag to triage.

**Comment by rowasc** [comment]
I think I covered some of this in https://github.com/ushahidi/platform/issues/3586 

Regarding the issue template guide, I think if we need to add more information on how to fill each of the template fields, that information *should be in the template* since most people won't read the guide and it should be easy to understand without a guide.

**Comment by Angamanga** [comment]
@rowasc Yep, agreed, I think this is mostly to know that there ARE templates, where to find them etc. We don't want to go into detail what the templates contain since it may change and then we have to update it twice...
