### ISSUE TITLE
403 error while making a post request to submit the survey using the wrong POST body

### ISSUE THREAD

**Issue by NidhiKJha** [ushahidi/platform#3609]
**Describe the bug**
Server gives a 403 forbidden error when making a post request while submitting a survey.

**Where was the bug observed**
Bug was observed on a this deployment on the route: https://rominacsvsms.api.ushahidi.io/api/v3/posts

**To Reproduce**
Made a POST request using the fetch API, running in an react app.
```javascript
        // Make a post request to Ushahidi sever
        fetch('https://rominacsvsms.api.ushahidi.io/api/v3/posts', {
            method: 'POST',
            body: JSON.stringify(this.state.formData),
            headers: {
                Accept: 'application/json',
                'Content-Type': 'application/json',
                Authorization: `Bearer ${this.state.token.access_token}`
            }
        })
            .then(response => {
                return response.json();
            })
            .then(data => {
                console.log(`Success!!! \n ${data}`);
            })
            .catch(error => {
                console.log(error);
            });
```

**Expected behavior**
A 422 code is observed due to the fact that the body of the request is incorrectly formatted. 
Example of correct request body: 
```
        let postData = {
          "title": this.state.formData.title,
          "content":this.state.formData.description,
          "values": {
          "97eaefee-5351-4674-82f3-3617e368ffb8": "some content" 
          },
          "form":{
            "id": formId
          }
        }
```

**Is there a workaround? What is it.**
Describe any ways to get around this bug, even if they are not elegant.

Aha! Link: https://ushahiditeam.aha.io/features/PROD-201

**Comment by rowasc** [comment]
This seems to happen when you send the form data with the wrong format (verified it yesterday). I get a 204 when I format it correctly and a 403 when I don't..
still pretty bad because it should be a 422 , not a 403, but worth being aware. 
Important considerations:
- the values object sent in postData should have the keys and values of the form. Keys are a uuid, and in the past I've seen this was being sent with the field name instead. 
- the values object doesn't have to contain the title and description
- title and description are sent as part of the postData object, not inside the values key. The description field should be sent with the key `content ` (sorry, I know this is annoyingly confusing) 
Example

```
        let postData = {
          "title": this.state.formData.title,
          "content":this.state.formData.description,
          "values": {
          "97eaefee-5351-4674-82f3-3617e368ffb8": "some content" 
          },
          "form":{
            "id": formId
          }
        }
```

**Comment by NidhiKJha** [comment]
Okay! Thank you :)

**Comment by rowasc** [comment]
This was confirmed to be an issue in the formatting of the post, but I'm going to leave it open due to the fact that it should respond with a 422. Editing the ticket description now
