### ISSUE TITLE
Insert link into survey field title

### ISSUE THREAD

**Issue by fabiolreis** [ushahidi/platform#3611]
Feature request: as a deployer, I would like to be able to add links in a field's title and field's  description.
Feature request: as a reporter, I would like to see links in a field's title and field's description rendered as links (not plain text)

*original question* : Is there a way to insert a link within a question or description of a survey form question?

Tech spec: 
- A field's title should be able to handle markdown entries and render it correctly [PENDING]
- A field's description should be able to handle markdown entries and render it correctly [DONE!]

Aha! Link: https://ushahiditeam.aha.io/features/PROD-200

**Comment by rowasc** [comment]
Not right now. 

- There is no way to add a link in a field description/field name and have it rendered as a link, it'll just render it as plain text when shown to a user.

- You can have a markdown field where users can add markdown content in their reports, which will be rendered correctly as a link 


I'll edit this ticket into a feature request for triage, since it would actually be quite helpful to be able to do this. 
Thank you for taking the time to open this issue.

**Comment by rowasc** [comment]
Hi. Thank you for this feedback. While we still don't allow links in titles, and it's not in the plans to do it at the moment, it's now possible to add links in the description field and other basic styling.
I will edit the issue to reflect the feature that's missing (title links) only.

**Comment by renujain31** [comment]
Hey @rowasc, I would like to take up this issue! Can you assign this to me!

**Comment by rowasc** [comment]
@renujain31 hey if you don't have a ticket, yes go ahead! 
Ideally, the links should save as markdown and render as HTML (like we do for `markdown` fields) . For title, we should *only* support links, nothing else (ie no bold/no images/etc) since titles have a specific styling applied already. I'm thinking however that I don't know how links should look, so we may need to explore that a bit 

@Angamanga may have tips here but that's the general direction

**Comment by renujain31** [comment]
Okay! From what I understood we just wants that the user can add links in title just as user adds links in markdown but we don't want any other functionalities of markdown. 

So, do I have to write a markdown renderer myself with just the link functionality?

**Comment by rowasc** [comment]
@renujain31 ok so I believe If you add the 'linkify' directive to a tag, it'll automatically detect links. So at least that wouldn't require new markdown renderers/configurations. 
Example
        <h1 class="mode-context-title"><bdi linkify>{{post.form.name}}</bdi></h1>


The only problem really is unrelated (but maybe you can look at it while you are looking at this) and it's that we probably want to change the style for that h1 so that it's less ... large? It won't look pretty if the title is a long text and a link in there

Example:
![Screenshot from 2020-10-20 18-30-22](https://user-images.githubusercontent.com/2434401/96646320-58772e00-1302-11eb-9b76-96a1fccd29c0.png)


LMK if this makes sense. looking forward to the PR :)

**Comment by renujain31** [comment]
Oh okay! Yes I can make the title look small. Just for the confirmation, I would need to edit code in [platform-pattern-library](https://github.com/ushahidi/platform-pattern-library), right?

Maybe we can look for a solution that if the title size is greater than `<some x>` characters, we can change it to a smaller value or else we can keep it as it is.

**Comment by rowasc** [comment]
for styles, yeah definitely the pattern library. For the linkify change, in the platform-client. (Sorry for the delay!)_
Thanks @renujain31

**Comment by renujain31** [comment]
Thanks, I already filed two PRs regarding the same. Waiting for your review.
ushahidi/platform-pattern-library#253
ushahidi/platform-client#1596

**Comment by Angamanga** [comment]
@renujain31 Thank you!
