### ISSUE TITLE
Tell user video link is broken even though valid.

### ISSUE THREAD

**Issue by AmTryingMyBest** [ushahidi/platform#3612]
When user is submitting response on a survey, video field only accepts a recognisable Youtube or Vimeo link. However when the video is non-existent, even if the link is a valid one, user is not notified of this. 

**Suggested solution**
Perhaps instead of showing the generic YouTube error (see screenshot) maybe we could instead notify the user that the video does not exist, or that the link even though valid, is broken or leads to no content.
![Screenshot from 2019-07-23 13-17-32](https://user-images.githubusercontent.com/38259840/61704390-4350cf80-ad4c-11e9-803f-db610ece479e.png)

Aha! Link: https://ushahiditeam.aha.io/features/PROD-199

**Comment by Erioldoesdesign** [comment]
So this happens when say, a youtube video has been deleted or re-uploaded (therefor has a new link URL) 

Yes a message that gives direct actionable feedback is best. We can make it generic to say 'Please check the video URL is correct and exists'

I'm assuming that this happens in this flow:

- Person (not deployment owner) responds to a survey in a deployment. Adds a video link that may or may not be valid.
- Deployment receives post
- Deployment owner checking over posts notices that the video link is not valid
- Deployment owner can edit the post in the deployment, but may not know the valid URL
- Deployment owner would then need to contact the person who posted asking for an updated URL.

^^^ is this journey correct @Obadha2

**Comment by Obadha2** [comment]
@Erioldoesdesign this will happen when the respondent is filling the survey, before they submit. On providing a link it immediately pulls the video. If there's no video, they see the error as seen in the screenshot. 
This issue suggests telling them the video is unavailable from the link they provided. 
@rowasc confirm?

**Comment by Erioldoesdesign** [comment]
Ahhh ok in that case yes, the respondent can have a more direct error message like 'Please check the video link you provided is correct and still active'

**Comment by noone0212** [comment]
@Angamanga can I work on this issue?

**Comment by Angamanga** [comment]
@noone0212 Absolutely, please go ahead!

**Comment by treasurechristain** [comment]
@Angamanga can I work on this? Amadikwa Joy N from outreachy

**Comment by Angamanga** [comment]
@treasurechristain This issue is not available for the community right now. Please look here for issues:  https://github.com/ushahidi/platform/issues?q=is%3Aopen+is%3Aissue+label%3A%22Community+Task%22
