### ISSUE TITLE
Enhancements to searching for location by Lat / Lon 

### ISSUE THREAD

**Issue by crcommons** [ushahidi/platform#3634]
### Expected behaviour
- When I input an invalid latitude and longitude, it should give me an error that helps me correct my mistakes
- When I search for a location in the searchbar input, the lat and lon fields should update with the location's lat and lon and the "Update Map" button shouldn't be available to click because there is nothing to update @jshorland @justinscherer <<<This makes sense, correct?
### Actual behaviour
- I get no response except and error in the console when inputs are incorrect
- lat and lon are blank unless I manually add them

### Steps to reproduce the behaviour/error
- Add or edit a post with a map fieldset
- input _-1.2832533,_ into lat (include the comma to force it to error) and 36.8172449 into lon
- select update map

- search for a location by name; the lat long inputs will remain blank

Aha! Link: https://ushahiditeam.aha.io/features/PROD-499

**Comment by Angamanga** [comment]
Partly done. The input-boxes update when a new location is selected but I don't get an error for invalid inputs.
**TODO:**
- Show an error if invalid lat/long is entered

**To reproduce:** 
- Add or edit a post with a map fieldset
- input -1.2832533, into lat (include the comma to force it to error) and 36.8172449 into lon
- No error-message is seen

**Expected behaviour:**
- When I input an invalid latitude and longitude, it should give me an error that helps me correct my mistakes

**Comment by tuxpiper** [comment]
This is the important one to fix next up in 5.1.2:

> * When I input an invalid latitude and longitude, it should give me an error that helps me correct my mistakes

The other behavior 

> * When I search for a location in the searchbar input, the lat and lon fields should update with the location's lat and lon and the "Update Map" button shouldn't be available to click because there is nothing to update

we shall only fix it now if it's less than one hour.
