### ISSUE TITLE
New survey-button is not rtl

### ISSUE THREAD

**Issue by Angamanga** [ushahidi/platform#3641]
### Expected behaviour
The yellow button should go to the left and text to the right

### Actual behaviour
![Screen Shot 2018-04-18 at 12.09.49.png](https://images.zenhubusercontent.com/5a6f2bce4b5806bc2bc4b158/e8d8ae27-35f7-4813-bb95-ceec58206563)

### Steps to reproduce the behaviour/error

Aha! Link: https://ushahiditeam.aha.io/features/PROD-358

**Comment by hariclerry** [comment]
Hello @Angamanga and @rowasc, I'm an outreachy applicant. May I please work on this issue?

**Comment by rowasc** [comment]
Absolutely, go ahead @hariclerry

**Comment by hariclerry** [comment]
Okay. Working on it.

**Comment by hariclerry** [comment]
Hello @rowasc, I could use a bit of a pointer here please,  I can't seem to reproduce the issue from this link  https://ushahiditeam.aha.io/features/PROD-358 because I can't login. How do I access the survey tab locally? do I need to create/add a post first? Do I need to be logged in with a different role? I'm logged in currently but I can't see the survey tab. Thanks

**Comment by hariclerry** [comment]
Hello @rowasc, you can disregard the above inquiry. I have managed to access the survey tab. Thanks

**Comment by tuxpiper** [comment]
@all-contributors please add @hariclerry for code
