### ISSUE TITLE
Installer helper usability testing

### ISSUE THREAD

**Issue by rowasc** [ushahidi/platform#3660]
# Intro

We are testing a new installation experience (still very much a work in progress!) and would love to get any early feedback you might have. 
This ticket is especially good for anyone who is already planning on installing both the API and the Client repositories, since it involves both of them, but even if you plan to setup one of them but not the other, it'd be great to hear from you. 

~The work is happening in the `installer-helper`~ This is now available in develop and master branches in the Platform API and platform Client repositories (same branch in both of them).

The helper is designed to give you hints as you go along the installation instructions and ideally it should help you get an idea of what's gone wrong as you set it up. 

# Getting started with the repos
- If you are planning to work on the frontend application, you only need one part of the codebase, the [platform-client repository](https://github.com/ushahidi/platform-client). We will provide (through slack) a demo deployment hosted in our QA servers for anyone looking to test their client work against the API, doing triage, documentation, or testing issues. 

- If you plan to work on the backend, we recommend you install the [platform-api repository](https://github.com/ushahidi/platform) and the [platform-client repository](https://github.com/ushahidi/platform-client) locally so it's easy to check any changes. 

The full documentation to get started with coding in Ushahidi can be found [here](https://docs.ushahidi.com/platform-developer-documentation/development-and-code/getting-started). We recommend to follow the local setup instructions and reach out to me with any blockers or issues you might find (we are revamping our docs, and migrating to gitbooks, so we appreciate all your feedback) 

[Find the Getting Started documentation here](https://docs.ushahidi.com/platform-developer-documentation/development-and-code/getting-started)

Running the verifier 
- In the client `gulp verify`
- In the API `composer verify`

Aha! Link: https://ushahiditeam.aha.io/features/PROD-191

**Comment by Erioldoesdesign** [comment]
Recommend changing the term UX to Usability or just feedback as this doesn't describe a User Experience test process.

**Comment by rowasc** [comment]
cool cool... please do any edits as you see fit.
Thanks!

**Comment by Jenniline** [comment]
Hi, @rowasc 
I have set up The Platform API and the Platform -Client I have both of them up and running my deployment name is Jenniline.io.

Though I set them up before you opened this issue. So I don't know if there are additional features

I set up my environment with the installation using XAMPP on  Ubuntu Linux. 

I don't quite understand this issue here can you please direct me on how to go about it.

What I have in mind is that the issue requires that we test the new installation of the Platform-API and Platform-client using the new installation experience. So then I have checked the links to the documentation you have provided but it is not leading to the destination. I receive an error message  
**"Page not found" **
Please, can I be directed to the documentation that caries the documentation to the new installation experience?
Thanks

**Comment by rowasc** [comment]
Hi @Jenniline , thanks for letting us know of the 404 error. 
I have updated the links to the documentation in the issue. Let me know if that works? 
The installation helper documentation can be found here https://docs.ushahidi.com/platform-developer-documentation/development-and-code/installation-helper

Thanks
Romina

**Comment by Jenniline** [comment]
Hi, @rowasc I think this ticket needs a bit more explanation on the description of the issue and what is needed to be done or the expected outcome. 
I have read it multiple times and I still don't really get what the issue is. I understand you need feedback on the new installation experience but what sort of feedback is it? Do you need documentation edits or code contribution or a bug fixes?  
I need help in understanding what is to be done. 

Thanks 
Jenniline

**Comment by Jenniline** [comment]
Hi, @rowasc I am on it. I have decided to write documentation on my journey testing the Installer helper documentation. 
 It is more of a report. It contains: 

- The procedure I used 
- details of my system and 
- It gives the output of the commands on the doc
- The issues I faced and how I solved them?
- My Personal Analysis of the Installation Helper 

Any other section of the report you will like me to add?

I think this is a good way to have feedback on this issue which can also be said as solving this issue.
 
I say this because it gives the maintainers of the Ushahidi platform( and platform-client) and the writers of the Installation a better understanding of the issues that each user of the Installer usability will bring forth. 
This is because an issue can depend on many factors they might be Hardware, Software, Setup procedure(Vagrant, XAMPP, etc) and in order to know the origin of the issue and a way around it is with details of the user's procedure.

Thanks
Jenniline

**Comment by Erioldoesdesign** [comment]
Hi @Jenniline this sounds awesome :) 

@rowasc should approve this but I would suggest adding your report to this issue in the comments if you feel comfortable doing that. That way it's open and viewable by the team + community. 

I think the only other thing that could be useful is screen recordings of any issues you come across. You can use Quicktime player to record your screen when you get errors/confusing things happen in the installer helper.

**Comment by Jenniline** [comment]
Hi @Angamanga when trying out the Installation helper I encounter an error when I run the command  _gulp dev: verifier_ .  It says the _dev: verifier is not in my gulp file_. I will add that to my report so doc. 
Just wanted to let you know that is one of the errors I have faced while testing the Installation helper

**Comment by Jenniline** [comment]
Hi @Angamanga this is my report on the Installer helper Usability. 
[Installer Helper Usability testing for Ushahidi.pdf](https://github.com/ushahidi/platform/files/4319847/Installer.Helper.Usability.testing.for.Ushahidi.pdf)

Here is the Google doc link in case the link above fails:
https://docs.google.com/document/d/1c6ZeEUSUoEoHLFrfqm-jD9qmXLWc_UWa6yHb28wDzLE/edit?usp=sharing

Please review 
Thanks

**Comment by Angamanga** [comment]
@Jenniline Terribly sorry for later reply, it looks like you have a space between 'dev:' and 'verifier'. It should be `dev:verifier`. Could you also check that you have pulled the latest changes for your platform-client.

**Comment by Dev-Som** [comment]
Hi @Angamanga can you assign the issue here to me?

**Comment by Jenniline** [comment]
> @Jenniline Terribly sorry for later reply, it looks like you have a space between 'dev:' and 'verifier'. It should be `dev:verifier`. Could you also check that you have pulled the latest changes for your platform-client.

Hi @Angamanga. So sorry for the late reply. I will do the changes on the doc when I have finished setting up my Ushahidi environment and tested the commands again. Thanks

**Comment by Angamanga** [comment]
@Dev-Som Please go ahead :)  @Jenniline No problem!

**Comment by Dev-Som** [comment]
Hi @Angamanga After installing and deploying the platform pattern library and platform client and deployed them, I had no issues deploying them and no issues installing them, if there is any other way I can help on any other issue, I am available.

**Comment by Angamanga** [comment]
@Dev-Som Thank you for testing the installation-helper! Look out for new issues, adding more today!
