### ISSUE TITLE
Test our documentation for installation of Development with XAMPP

### ISSUE THREAD

**Issue by Angamanga** [ushahidi/platform#3662]
# Intro 📖 
We are continuously working with our documentation to provide a good and smooth experience when setting up the platform. In this ticket, we are asking for help to improve our documentation for installation of development environment with XAMPP.

# Task ✏️ 
- Go to https://docs.ushahidi.com/platform-developer-documentation/getting-started/setup_alternatives/xampp
- Follow the instructions and try to install the platform
- Document and write comments about the installation-process as comments below, it could be for example: 
  - Confusing instructions
  - Errors you get that is not mentioned in the documentation
  - Do you get stuck somewhere and don't manage to get past a point in the documentation? Where is that?
  - Do you have to do things that is not mentioned in the documentation to make it work? Where and what did you do?
  - Anything else that comes to mind, suggestions, comments etc when reading through the docs.

Thank you for your time and help 🎉 🙏 🙇‍♀

Aha! Link: https://ushahiditeam.aha.io/features/PROD-189

**Comment by muchirijane** [comment]
Hey @Angamanga, could I please work on this as part of my outreachy contribution?

**Comment by Angamanga** [comment]
Thank you @muchirijane! Please go ahead :)

**Comment by muchirijane** [comment]
Thanks 💯

**Comment by SaraLatif99** [comment]
Hi, Can I take this as part of Outreachy 2020 and hacktober first 2020 contributions?

**Comment by Angamanga** [comment]
@muchirijane You can write your suggestions here as a comment :)

**Comment by Angamanga** [comment]
@SaraLatif99 Yes, please go ahead :)

**Comment by muchirijane** [comment]
@Angamanga, I did a pull request an hour ago. Didn't know it was to be a comment. Oops.
https://github.com/ushahidi/platform/pull/4092
Let me copy the information here.

**Comment by muchirijane** [comment]
- In the documentation configuring the API section, Change the DB_USER to root in the `.env` file there is DB_USERNAME listed instead. That's what I changed. Maybe that section could be updated in the documentation. 
- When running `composer migrate` I got an error

composer migrate

> php artisan environment:verify
Running OAuth key checks
Good job! Your OAuth keys are in the right place.
We will check the environment file next.
Running ENV configuration checks
DB_PASSWORD is missing in the environment or .env file.
Please set the password to connect to your database in the DB_PASSWORD key
Running DB connectivity verification
We were able to connect to the DB. Well done!

`In EnvironmentVerify.php line 84:
Verification Failed.
Script PHP artisan environment: verify handling the verify event returned with error code 1
Script @verify was called via migrate `

- Configure the platform/.htaccess file - I could not see this file, I created a .htaccess myself and copied the code in the documentation.
- Got stuck at this section : Windows: In the XAMPP control panel, click the "Config" button next to Apache and select "Apache (httpd.conf)". This will open an editor with the file. In my case, I thought it was checking the [ ] Apache but an editor didn't open.

 ![xampp screenshot error](https://i.ibb.co/PNqYDYL/Screenshot-266.png)

- Suggestions - The last part can be a bit complex for someone who is a beginner in contribution. It would be helpful if the last part of the documentation could be turned into a video. The videos are really helpful especially since it's visual and you easily follow through the steps. 
- A suggestion on the videos: Please increase the audio of the videos, the instructor seems to be far from the mic or audio equipment used. Apart from that, they were really helpful

- Overall the documentation is clear and the videos are even more helpful.

**Comment by SaraLatif99** [comment]
Thanks @Angamanga

**Comment by codedladiesinnovate** [comment]
@Angamanga please can I do this as part of my outreachy contribution?

**Comment by UdokaVrede** [comment]
Hi you are using an organization account to make this request, please
recheck

**Comment by treasurechristain** [comment]
Sorry @Angamanga I forgot to logout of the organization mail.
I'm Amadikwa Joy N, can I work on it

**Comment by codedladiesinnovate** [comment]
Sorry @Angamanga It was a mistake. I was meant to use Amadikwa Joy N.

**Comment by Angamanga** [comment]
@treasurechristain No problem! Please go ahead :)

**Comment by Sunairaa** [comment]
Hey @Angamanga can I work as an outreachy contribution? I followed the whole tutorial and found some improvements need to be done in the documentation but in the end, I did some fixes too again not able to run the code. so I have to choose a vagrant option which is working perfectly on my side. can I suggest some editings in it.?

**Comment by treasurechristain** [comment]
![doc_break_link](https://user-images.githubusercontent.com/20610726/95866403-c7331500-0d5f-11eb-932d-b896df4bb422.PNG)
I think the above link is not correct because its taking me to empty page.
@Angamanga could the link below be the actual link?
https://docs.ushahidi.com/platform-developer-documentation/development-and-code/setup_alternatives/xampp

if yes, let me continue with the work

**Comment by treasurechristain** [comment]
Under Setting up the Platform API with XAMPP
Go to http://localhost and verify that you see the XAMPP welcome page.
should be Open your **browser** and type **http://localhost**

**Apache and MySql not starting do**

- click on **Apache Config button**

![apache_config](https://user-images.githubusercontent.com/20610726/95927177-faa08e80-0db5-11eb-8fd0-423dc2d42e0c.PNG)

- from the dropdown menu, select **Apache(httpd.conf)**

- On the notepad window, click **ctrl + f ** on your keyboard

- Type **80** on the search bar to locate it in the file

![port80to8080](https://user-images.githubusercontent.com/20610726/95927423-8e725a80-0db6-11eb-9567-0318a461c44c.PNG)

- Replace **12.34.56.75:80** with **12.34.56.75:8080** 

- Replace **Listen 80** with **Listen 8080**

- Replace **Servername Localhost :80** with **Localhost :8080** then **save the file**

- Goto Xampp Control Panel

- Click on **Apache config button**

- On the **dropdown menu,** select **Apache(httpd-ssl.conf)**

- On the **notepad** and click **ctrl + f ** on your keyboard

- Type **443** on the search bar to locate it in the file

- Replace **Listen 443** with **Listen 4343**
![listen443to4343](https://user-images.githubusercontent.com/20610726/95928060-5b30cb00-0db8-11eb-8533-01071062395f.PNG)

- Replace **<Virtualhost_default_:443>** with **Virtualhost_default_:4343>**
![virtaulhost443to4343](https://user-images.githubusercontent.com/20610726/95928040-52d89000-0db8-11eb-8c7b-85624c5c9256.PNG)

- Replace Servername **www.example.com:443** with  Servername**www.example.com:4343**
![servername443to4343](https://user-images.githubusercontent.com/20610726/95928273-dabe9a00-0db8-11eb-8c74-357be16c54b1.PNG)

**In a Situation Where MySQL is not Working, do the following: -**

- Select and click on **MySQL Config**
![mysqlerror](https://user-images.githubusercontent.com/20610726/95928499-67695800-0db9-11eb-8016-5a5c965c87d0.PNG)

- Select **my.ini**
![mysqlerorrMyini](https://user-images.githubusercontent.com/20610726/95928562-8ff15200-0db9-11eb-8329-7f137df85e1b.PNG)

- On the **Notepad window,** find **port=3306** and replace with **3307** . 
For password Section change  **port=3306** and replace with **3307** 
![mysql3306to3307](https://user-images.githubusercontent.com/20610726/95928770-30477680-0dba-11eb-9d75-4ad63a1254ec.PNG)

- **Save** the notepad document

- On the **Xampp Control Panel**

- Click on **Xampp Config**

- On the **pop up dialog window,** click on **service and port setting**
![xampp config](https://user-images.githubusercontent.com/20610726/95929315-9aace680-0dbb-11eb-987a-08e11397c951.PNG)

- On the **Popup window,** click on **MySQL tab** and replace **3306** with **3307**
![Config3306to3307](https://user-images.githubusercontent.com/20610726/95929279-8668e980-0dbb-11eb-9f50-cc3d2e66e910.PNG)

- Then **save all** changes and **start apache** 



**UNDER Configuring The API**

- I suggest this should be rephrased from 
**We will configure the API now. We will do this continuing working on the same terminal window that was opened in the previous steps.**    
with
**_We will configure the API now. Still working on the same terminal window that was opened in the previous steps._**
![apiconfigureinstruction](https://user-images.githubusercontent.com/20610726/95930333-1c057880-0dbe-11eb-9caf-7cf8a04df1ee.PNG)


- For windows, instead of _Change the DB_USER to root_  it should be _**Change the DB_USERNAME to root **_
![dbusername](https://user-images.githubusercontent.com/20610726/95930281-fed0aa00-0dbd-11eb-817e-191f338b428f.PNG)


- Instead of _Run composer install. Wait while composer installs all the dependencies_  it should be  _**In the CMD/terminal Run composer install. Wait while composer installs all the dependencies**_

- Environment Verified Failed
![environmentverifiedfailed](https://user-images.githubusercontent.com/20610726/95930023-5f131c00-0dbd-11eb-9095-bb782b30a3b5.PNG)
But I resolved it firstly by getting my github auth token
![auth_token](https://user-images.githubusercontent.com/20610726/95930108-95509b80-0dbd-11eb-9ac0-f94a4eccbabe.PNG)

Then changed the memory limit of xampp phpini file
![editphpinisize](https://user-images.githubusercontent.com/20610726/95930177-c4670d00-0dbd-11eb-95c2-a2541c5b8bc0.PNG)

Inside the  _**composer.json**_ I add  _**"nesbot/carbon": "2.41.0 as 1.39.0",**_   and    _**"kylekatarnls/laravel-carbon-2": "^1.0.0" **_
![composerenviroment](https://user-images.githubusercontent.com/20610726/95931277-97682980-0dc0-11eb-9b6b-88f387acceee.PNG)


On the xampp shell, inside the project file location , I ran _**composer require nesbot/carbon:^1.24.1**_
![workedcomposer](https://user-images.githubusercontent.com/20610726/95930522-91714900-0dbe-11eb-87d1-ebd2dc172bdd.PNG)

Still on the CMD shell, I ran _**composer update
![composerupdate](https://user-images.githubusercontent.com/20610726/95930615-c9788c00-0dbe-11eb-9b24-83694efb2129.PNG)
**_


Still on the CMD shell, I ran _**composer install
![composerinstallnew](https://user-images.githubusercontent.com/20610726/95930641-ddbc8900-0dbe-11eb-92c4-08aa5460ecf4.PNG)


**FROM  Configure the platform/httpdocs/.htaccess file**
I didn.t see any **.htaccess** rather I saw **template.htaccess**

And there is no  _**.htaccess**_  inside  **_platform/.htaccess_**


**Suggestion:**  The Instructions at **Setting up the Platform client** is not that clear because it's not at the beginners level to understand it easily.
And I suggest that some of  the instructions will easily be understood with symbols or images for illustration.

I must say, the video is awesome and straight forward. but making a video that covers the instructions on how to _**configure the platform/.htaccess**_ .



Thanks.

**Comment by treasurechristain** [comment]
@Angamanga This is what I came up with after going through https://github.com/ushahidi/platform/issues/3662
Hope it's helpful enough.

**Comment by Angamanga** [comment]
@treasurechristain Thank you for your contribution 🙏
