### ISSUE TITLE
Read and comment on our documentation - open to everyone!

### ISSUE THREAD

**Issue by Angamanga** [ushahidi/platform#3664]
# Intro 📖 
We recently updated our developer documentation for the Ushahidi platform. Any help with reading through, comments and suggestions are very helpful!

# Task ✏️ 
- Go to https://docs.ushahidi.com/platform-developer-documentation/
- Select a part of the documentation you want to read through
- Read through and write your comments and suggestions as a comment in this issue.

Thank you for your time and help 🎉 🙏 🙇‍♀ !

**Comment by HMuhammad** [comment]
Read this page: https://docs.ushahidi.com/platform-developer-documentation/

Currently reads:
Ushahidi is an open source web application for information collection, visualization and interactive mapping. It helps you to collect info from: SMS, Twitter, RSS feeds, Email. It helps you to process that information, categorize it, geo-locate it and publish it on a map.

Suggest Change to:
Ushahidi is an open source web application for information collection, visualization and interactive mapping. It helps you gather info from: SMS, Twitter, RSS feeds, Email. Then you can process that information, categorize it, geo-locate it and publish it on a map!

**Comment by Jenniline** [comment]
Before you start coding, read through the Development & Code section to get started and to get help setting up your environment!

Before you begin coding, read through the Development & Code section to get started and to get help setting up your environment! 

**Explanation** 
Here Start can be replaced with begin. Both words pertain to the commencement of an action. However, Begin in this context gives more meaning. It will give readers the idea that before coding you must have gone through and understood very well the Deployment & code. 
And not give them the impression that you must read the Deployment & code only before you are about to write code. Which is the impression that the word "Start" gives

**Comment by Jenniline** [comment]
Currently reads:
If you are a designer and want to contribute to Ushahidi, please contact the Ushahidi design team at design@ushahidi.com or through the Join the Ushahidi community section of these docs. While you are waiting for us to reply, start reading through our Design-docs.

Suggested change to:
The word "through" after the design@ushahidi@.com should be removed. 

**Explanation**
The statement is not clear from that point. It does not also give the statement a clear sense and in conclusion does not pass the message.

**Comment by Jenniline** [comment]
Hi @Angamanga 
I have the Ushahidi platform-client and the API up and running. 
I used the installation using XAMMP on Ubuntu Linux.
But before that, I encountered a lot of problems but I was able to find a solution to them. 
I will like to know if there is a section of the Documentation where I can add **Possible issues one might face while setting up their environment and also Possible solutions to the issues?**

**Comment by mariehposa** [comment]
Hi @Angamanga Can I work on this? I would love to.

**Comment by Angamanga** [comment]
@mariehposa Please go ahead 🎉 !

**Comment by blossom-babs** [comment]
Hello @Angamanga can I work on this too?

**Comment by IfyN** [comment]
Hello @Angamanga can I please work on this? I would love to contribute to this? I am also an outreachy applicant.

**Comment by rowasc** [comment]
Hey folks. Totally. This ticket is mainly about checking out the docs and reporting issues with it. Everyone can participate :tada: thanks! @IfyN @blossom-babs

**Comment by mariehposa** [comment]
Note: 
1. **Issues** are written in bold only.
2. **_Suggestions_** are written in bold and italics.


Page: https://docs.ushahidi.com/platform-developer-documentation/code-of-conduct

Currently reads:
Like Ushahidi's staff base, Ushahidi's community is incredibly diverse. **Ushahidi** is dedicated to creating an inclusive environment for everyone, regardless of race, ethnicity, religion, color, national origin, age, disability (physical or mental), sexual orientation, gender identity, parental status, marital status, and political affiliation as well as gender expression, mental illness, socioeconomic status or background, neuro(a)typicality, or physical appearance.

Suggest Change to:
Like Ushahidi's staff base, Ushahidi's community is incredibly diverse. _**It**_ is dedicated to creating an inclusive environment for everyone, regardless of race, ethnicity, religion, color, national origin, age, disability (physical or mental), sexual orientation, gender identity, parental status, marital status, and political affiliation as well as gender expression, mental illness, socioeconomic status or background, neuro(a)typicality, or physical appearance.


Page: https://docs.ushahidi.com/platform-developer-documentation/contributing-or-getting-involved

Currently reads:
Ushahidi is open source software created for the benefit of a large global community improving the world for themselves and others, holding governments accountable, and raising their voices to be more powerful together. As we see the COVID-19 pandemic wreak havoc globally, we have also seen a large interest and use of our tools. Today, we are reaching out to technologists everywhere to ask for **your help to make** Ushahidi Platform better. Head over to our COVID-19 specific page to learn more **on** how you can support us **helping** our users.

Suggest Change to:
Ushahidi is open source software created for the benefit of a large global community improving the world for themselves and others, holding governments accountable, and raising their voices to be more powerful together. As we see the COVID-19 pandemic wreak havoc globally, we have also seen a large interest _**in the**_ use of our tools. Today, we are reaching out to technologists everywhere to ask for _**help in making the**_ Ushahidi Platform better. Head over to our COVID-19 specific page to learn more _**about**_ how you can support us _**in**_ helping our users.

**Comment by IfyN** [comment]
Please Note:
- Issues are highlighted in bold 
- Suggestions are written in bold and italics 

Page in which text is derived: https://docs.ushahidi.com/platform-developer-documentation/contributing-or-getting-involved

Text currently reads:
Ushahidi **is** open source software created for the benefit of a large global community improving the world for **themselves** and others, holding governments accountable, and raising their voices to be more powerful together. As we see the COVID-19 pandemic wreak havoc globally, we have also **seen** a large interest and use of our tools. Today, we are reaching out to technologists everywhere **to ask** for your help to make Ushahidi Platform better. Head over to our COVID-19 specific page to learn more on how you can support us **_helping_** our users.

Suggestion: 
Ushahidi is **_an_** open source software created for the benefit of a large global community improving the world for **_ourselves_** and others, holding governments accountable and raising **_our_** voices to be more powerful together. As we see the COVID-19 pandemic wreak havoc globally, we have also **_noticed_** a large interest in the use of our tools. Today, we are reaching out to technologists everywhere, **_asking_** for your help in making the Ushahidi Platform better. Head over to our COVID-19 specific page to learn more on how you can support us **_in_** helping our users.

**Comment by IfyN** [comment]
Please Note:

- Issues are highlighted in **bold** .
- Suggestions are written in **_bold_** and **_italics_** .

 Page in which text is derived: https://docs.ushahidi.com/platform-developer-documentation/contributing-or-getting-involved

Text currently reads:
Ushahidi **is open** source software created for the benefit of a large global community improving the world for **themselves** and others, holding governments accountable, and raising **their** voices to be more powerful together. As we see the COVID-19 pandemic wreak havoc globally, we have also **seen** a large interest and use of our tools. Today, we are reaching out to technologists everywhere to ask for your help to make Ushahidi Platform better. Head over to our COVID-19 specific page to learn more on how you can support **us helping** our users.

Suggestion:
Ushahidi is **_an open_** source software created for the benefit of a large global community improving the world for **_ourselves_** and others, holding governments accountable and raising **_our_** voices to be more powerful together. As we see the COVID-19 pandemic wreak havoc globally, we have also **_noticed_** a large interest in the use of our tools. Today, we are reaching out to technologists everywhere, **_asking_** for your help in making the Ushahidi Platform better. Head over to our COVID-19 specific page to learn more on how you can support us **_in_** helping our users.

**Comment by hyounes4560** [comment]
@rowasc @Angamanga 
Hi there, Please kindly review my contribution to **The Ushahidi Platform Roadmap** documentation page found [here: ](https://docs.ushahidi.com/platform-developer-documentation/roadmap)
 
**I made many changes and rewrote the complete sections to better reflect the Ushahidi platform. I proofread and checked the grammar and punctuation of my final draft. Also, used appended links under words to create a better-looking document. I hope this contribution will be helpful.** 

**The Ushahidi Platform Roadmap**
**Where to find our roadmap**
•	We expand and modify Ushahidi's roadmap regularly based on the projects we have committed to working on, including various grant projects, customer requests, prioritized bugs, and features requested by the community. As we introduce more open roadmap planning strategies to our workflows, you will be able to access our upcoming roadmap shared on the public.
•	You can find features that we consider to add next to our roadmap using this tag [consider for upcoming cycle](https://github.com/ushahidi/platform/issues?q=is%3Aopen+is%3Aissue+label%3A%22consider+for+upcoming+cycle%22)
•	You can find the features we are currently working on by filtering using this [tag ](https://github.com/ushahidi/platform/issues?q=is%3Aopen+is%3Aissue+label%3A%22Stage%3A+In+progress%22)

**How a new item gets added to the roadmap**
•	We evaluate new features' requests in collaboration with Engineering, Product, Design, Support, and other teams in the Ushahidi platform. 
•	Ushahidi staff triage issues as they arrive. The following submission guidelines ensure that your feature requests and bug reports are appropriately described, well-understood and can be tackled:
o	Follow the issue submission guidelines. We have created some ready-to-use templates to report bugs and security vulnerabilities, or to request features, etc., which you can find [here ](https://github.com/ushahidi/platform/issues/new/choose)
o	You may receive follow-up questions from the team responsible for issue triage and prioritization. We accept you to respond to these questions as this will ensure the person triaging the issue can fully understand the scope of work and needs.
o	It helps to have a concise description, from a first-person point of view, of the problem you face and need to solve.
•	It's also worth noting that not all parts of the system are funded equally at any given point for feature development. This fact also influences when a feature will be prioritized and worked on by the Ushahidi staff. Funding for a specific goal (i.e. improve data triage process so that people can work more efficiently in an emergency) means our focus will generally be on a handful of improvements related to that goal.

**How we decide to prioritize one issue over the other**
•	For bugs, the decision is based on how critical the bug is, whether it is in a critical path to a specific function, and how common someone would run into this issue trying to execute this function. For example, triage issues are prioritized higher than problems in the webhook setup flows, since triage is a much more common action than webhook setup. Prioritization is also affected by the time necessary to fix an issue, the team available to fix it, and the required budget.
•	For features, we prioritize what we would like to see in the platform next with all of the Ushahidi team's help, their inputs as they interact with users, and user testing.
•	Alignment to Ushahidi platform goals, resources limits, and users' needs because it is essential to work on things that align closely with our mission. That means we will often have to say no to things that fall outside the product's scope or intent. For instance, while a calendar might sound like a great idea, it is not feasible to make a calendar from scratch since it is outside our product's scope and what we do best. Plus, we don't have the resources to maintain it. However, we may integrate an existing calendar if there was enough need for it. When you are requesting a new feature, we recommend that you clearly describe the problem you are trying to solve so that together we can figure out a solution that fits the Ushahidi Platform's scope.

**Next steps**
We are working hard on improving how we prioritize issues and move them into our roadmap. The next steps start with internal discussions among Ushahidi staff on the rules of engagement on roadmap decisions and initial documentation about the new roadmap decision-making structure; then, we seek community comments. As we adjust our workflows to become more open and transparent for everyone, we want to hear from you and open up our process for comments shortly.

**Comment by IjayAbby** [comment]
Hello  **@Angamanga** can I work on this too?

**Comment by Somaru-chan** [comment]
@Angamanga @rowasc 

### I didn't find any details about what type of documentation, so I hope a technical review of my setting-up experience isn't out of place.

# Vagrant Set Up Page

Page from which text is derived: https://docs.ushahidi.com/platform-developer-documentation/development-and-code/setup_alternatives/vagrant-setup

- Text currently reads:
Prerequisites
Please make sure you install everything in this list before you proceed with the platform setup.
Vagrant
Recommended: Vagrant host-updater plugin - this is useful to avoid having to update /etc/hosts by hand
VirtualBox - Note: Windows users may be required to Enable VT-X (Intel Virtualization Technology) in the computer's bios settings, disable Hyper-V on program and features page in the control panel, and install the VirtualBox Extension Pack (installation instructions here.)
Composer
**PHP >=7.0 <7.2 - if you are using Platform V4.0.0
PHP >=7.1 <7.4 - if you are using Platform V4.1.0 or later
PHP >=7.2 <7.4 - if you are using Platform V4.4.0 or later**

- Suggested change to:
Prerequisites
Please make sure you install everything in this list before you proceed with the platform setup.
Vagrant
Recommended: Vagrant host-updater plugin - this is useful to avoid having to update /etc/hosts by hand
VirtualBox - Note: Windows users may be required to Enable VT-X (Intel Virtualization Technology) in the computer's bios settings, disable Hyper-V on program and features page in the control panel, and install the VirtualBox Extension Pack (installation instructions here.)
Composer
**_PHP = 7.3 *_** 

Explanation: I believe it's required for a later step explained below in detail. Also, like the other prerequisites, would be better UX to provide **_download link: https://www.php.net/downloads.php_**


-------------------------------------------------------------------------------------------------------------------------------------

- Text currently reads:
sudo update-alternatives --set php /usr/bin/**php7.1**

- Suggested change to:
sudo update-alternatives --set php /usr/bin/**_php7.3_**

Explanation:
I faced an error while running the command "composer install" that required a PHP version 7.3 by several components. So I had to run sudo update again with php7.3 instead. 






# Platform Client Set Up Page

Page from which text is derived: 
https://docs.ushahidi.com/platform-developer-documentation/development-and-code/setup_alternatives/setting-up-the-platform-client

- Text currently reads:
Pre-requisite: Install **Node V10.x** or higher (you might want to use NVM for this) before continuing.

Explanation: 
The tutorial video mentioned Node must be version 8, so I wasn't sure if I should follow the video tutorial or the written documentation. Would also be user-friendly to include hyperlinks for Node download and NVM to save time.


-------------------------------------------------------------------------------------------------------------------------------------

- Text currently reads:
**BACKEND_URL=http://dont.copy.this.name.com**

- Suggested change to: 
**_BACKEND_URL=http://192.168.33.110/_**
PORT=8000
APP_LANGUAGES=en
OAUTH_CLIENT_ID=ushahidiui
OAUTH_CLIENT_SECRET=35e7f0bca957836d05ca0492211b0ac707671261

Explanation:
Better approach is to provide a usable example. In my case, my JSON object URL and the URL in the video tutorial were drastically different and I was hesitant about which is the correct one. Port number among other details can be omitted. 

-------------------------------------------------------------------------------------------------------------------------------------

- Text currently reads: 
The gulp command, although a bit funny-sounding, is key for all development tasks on the platform client.
By default, this command is hidden within the node_modules/.bin directory of your platform-client folder. **This makes it a bit awkward to invoke, see these examples:**

- Suggested change to: 
The gulp command, although a bit funny-sounding, is key for all development tasks on the platform client.
By default, this command is hidden within the node_modules/.bin directory of your platform-client folder. **_As a result, invoking the gulp command would be tedious each time._** See these examples: 


-------------------------------------------------------------------------------------------------------------------------------------

- Text currently reads: 
**That's too much typing.
To make it easy to call gulp when building and developing in the app, there are a couple approaches:**

- Suggested change to: 
**_That's a lot to remember! 
Instead, it's possible to call the gulp command when building and developing in the app via the following methods:_** 

### P.S. There's a typo in the statement following this one: his >>> this
-------------------------------------------------------------------------------------------------------------------------------------

- Text currently reads:
At that point the client should be available to the browser on the address **http ://localhost:3000** (unless you specified a PORT on your .env file).

- Suggested change to: 
At that point the client should be available to the browser on the address **_http ://localhost:8000_** (unless you specified a PORT on your .env file).

Explanation: 
If the details to be included in the .env file has changed per the modification suggestion above(fourth example), then this would follow suit. 

-------------------------------------------------------------------------------------------------------------------------------------

### PHEW! You guys are lifesavers for writing all these painstakingly detailed documentations and recording videos for the sake of developers and users. Please let me know if I can help in any way!

**Comment by Somaru-chan** [comment]
> Hello **@Angamanga** can I work on this too?

Hi @IjayAbby. Romina stated before this is open for everyone. So definitely!

> This ticket is mainly about checking out the docs and reporting issues with it. Everyone can participate 🎉 thanks!

**Comment by kivuvarosekivuvan** [comment]
Hello @Angamanga as an Outreachy applicant 2024, I would love to work on this

**Comment by Chiemezuo** [comment]
@Angamanga Here's my first comment. Sorry if it's bulky, but I tried to be thorough.

My review will be on my experience with the '[set up the developer environment](https://docs.ushahidi.com/platform-developer-documentation/v/set-up-the-developer-environment-for-ushahidi/)' section of the document. For the [workflow for adding code](https://docs.ushahidi.com/platform-developer-documentation/v/set-up-the-developer-environment-for-ushahidi/set-up-your-developer-environment/workflow-for-adding-code), most of my suggestions are grammar fixes and I would opt to do that in a different comment.
In this particular comment, I'll focus more on setting up the [API](https://docs.ushahidi.com/platform-developer-documentation/v/set-up-the-developer-environment-for-ushahidi/set-up-your-developer-environment/setting-up-the-api-with-docker) and the [platform-client](https://docs.ushahidi.com/platform-developer-documentation/v/set-up-the-developer-environment-for-ushahidi/set-up-your-developer-environment/setting-up-the-platform-client-for-development).

# Setup Review
I'll be grouping this comment into the categories of:
- What my setup was already like before Ushahidi.
- What I liked about the docs.
- Errors I encountered and how I navigated past them.
- What could be worked on.
- Nice-to-haves (but not entirely necessary).

## My already-existing setup
- Windows 11.
- Docker version 24.0.6 with **WSL 2** enabled.
- Visual Studio Code.
- Git version 2.43.0 With **autocrlf** set to true (This caused some issues I'll discuss).
- GNU Make 4.4.
- Google Chrome 122.0.6261.94
- Node v21.2.0

## What I liked
- Right away, I liked the simplicity of documentation.
- The easy navigation to other segments and the search option.
- The links to external resources.
- The success message to look for and call to action.

## Errors I encountered
I faced a lot of errors which led to more errors.
- `make start` failed a lot initially for no seemingly identifiable reason. I got to realize it was because on my local machine it was saved using the CRLF [EOL](https://itexus.com/glossary/eol-end-of-line/#:~:text=The%20term%20EOL%3A%20End%20of,a%20specific%20action%20or%20operation.) type. I converted appropriately.
- It still failed, because of the EOL types from `artisan` and `docker-php-ext-enable` were of the CRLF EOL type. I had to modify this.
- `make start` failed again because at some point in time, the `platform` service stopped running. I tried restarting the service several times, but it kept stopping. On going through the logs, I realized it was because of some errors in the scripts in the `docker` directory.
- Again, I noticed it was because of the EOL types, so I wrote a script to fix that problem. I did a `cd docker`, then ran `find . -type f -exec sed -i 's/\r$//' {} \;` to fix it, then I ran `cd ..` back to the parent directory, rebuilt and then ran the command again.
- It failed again some minutes after, but on confirming everything was running well, I realized it might have been because of a network fluctuation.
- At some other point in time, the services were not running for reasons I couldn't pinpoint. I retried a number of times and installed **Php** on my computer because it wasn't installed prior that.I did this, and somehow, it worked some time after(although I'm not sure if it was entirely because of that).
- On proceeding to the next stage: "setting up platform-client", I followed the guide and got an error when running `npm run web:serve`. It failed with a `listen EACCES: permission denied ::1:4200` error. It wasn't because of the EOL this time around, and neither was it due to a faulty installation. Thankfully, I tried something I saw on [Stackoverflow](https://stackoverflow.com/questions/60485038/ng-server-listen-eacces-permission-denied-127-0-0-14200). I opened my **Powershell**, then ran the commands one after the other:
```sh
  net stop winnat

  net start winnat
```
- It was successful. I opened the `http://localhost:4200/` on my browser and tried logging in with the default email of "**admin@example.com**" and password of "**admin**", but it failed. The password on the documentation is incorrect, as it has a minimum character requirement of **8**. I tried using "**admin123**" as the password, and that worked. I took a screenshot of my setup and shared to the [Discord](https://discordapp.com/channels/1166738829319884890/1212341847507083314/1214560053072363590) server.

## What could be worked on
- The document didn't account for potential errors that people would face. This could be worked on.
- I believe (but have not fully tested) that recommending `autocrlf` be switched to `false` would have resolved most of my errors, because `bash` files and `conf` files are often very senstive to line endings. A potential fix might be running `git config core.autocrlf false` in the folder the project was cloned into.
- Changing the section of the docs that says the default password is "**admin**" to "**admin123**".
- An FAQ section might also have been helpful, so that people wouldn't have to ask questions that have already been asked in the past.
- I noticed there wasn't a reference documentation, but I read that it's still being worked on.

## Nice-to-haves
- A video tutorial.
- Modify step 5 [here](https://docs.ushahidi.com/platform-developer-documentation/v/set-up-the-developer-environment-for-ushahidi/set-up-your-developer-environment/setting-up-the-api-with-docker) to enclose ".env.example" and ".env" in backticks (``) for inline code.

## TL;DR
The instructions were clean, but they lacked guidelines on how to fix potential installation errors.

**Comment by kivuvarosekivuvan** [comment]
#### Based on my personal experience setting up both the Ushahidi Platform API and Ushahidi Platform Client, here are some comments regarding the documentation:

### Good things I experienced:
1. Clear and concise instructions:
   - For example, the documentation outlined the exact commands and configurations needed to set up the API and platform client, making it easy for me to follow along and complete the setup successfully.

2. Explanation of configuration files:
   - The documentation provided clear explanations of the purpose and usage of configuration files like `.env` and `env.json`.

4. Default user credentials:
   - The documentation included information about the default user credentials for the local development environment.
   - For instance, it provided the default username and password that allowed me to log in and start interacting with the system immediately, without the need to create additional user accounts.


### Things that could be changed in the documentation:
1. Provide more context and overview:
   - For example, the documentation could include an introductory section that **highlights the key features and benefits of the Ushahidi Platform**, giving users a better understanding of its purpose and potential use cases.
   - Additionally, providing a **high-level overview of the API and platform client architecture** -_(also in simple terms)_ would help users grasp the system's structure and how the different components interact with each other.

2. Improve formatting:
   - Including visual elements like diagrams or screenshots  _(particularly following each command, what specific experiences should the user be encountering at that given moment?")_  can enhance the documentation's clarity and make complex concepts easier to understand. 

Like these:
- `npm run web:serve`
![Image](https://github.com/ushahidi/platform/assets/124133577/3a0125e8-4cf9-4812-919c-a7cf001d1b82)

- `sudo make start`
![Image](https://github.com/ushahidi/platform/assets/124133577/58b5ed30-1d18-495d-bedd-2f3ffd5bc8f7)



3. Include troubleshooting tips:
   - For example, the documentation could address common issues or errors that users may encounter during the setup process.
   - **Providing troubleshooting tips, error message explanations, and links to relevant resources** would help users overcome challenges more effectively and save time in searching for solutions including youtube videos and documentation

4. Expand on the purpose and usage of tools:
   - For instance, the documentation could **provide more details and examples on the purpose and benefits of using tools like Docker and Docker Compose** in the context of the Ushahidi Platform.
   - Explaining how these tools facilitate development, deployment, and scalability would help users appreciate their importance and make informed decisions during the setup process because for a first time contributor will get it hard understanding.I suggest also using very simple terms when explaining this.

**Comment by kivenalaric** [comment]
Here's what i would like to comment about the documentation, on the part of about "What does Ushahidi Do" not like there was aproblem there, but if there was maybe a video or a link to a video that explains better i think it would be better because from my own experience visual explanations are better.

**Setting Up the Project**
Normally following the steps found on the documentation, i didn't face any problems setting the project up but realised others in the discord channel had some errors which could be used to better the documentation by including possible errors and how to solve them, so one wont have to necessarily visit sites like **Stackoverflow** for solutions.

**Comment by MugoBrian** [comment]
Hello @kivuvarosekivuvan and @tubapervaiz1508 , the issue is open to everyone as stated in the updated title.

**Comment by shalini1008** [comment]
Subject: Feedback on Ushahidi Platform Setup Documentation

Hello Anna Iosif,

I hope this message finds you well. I'm Shalini, and I've been going through the documentation for setting up Ushahidi's platform. Overall, it's a valuable resource, but I wanted to share a couple of points where I found the information a bit confusing.

1.Point 3: Installing Make (Parsing Makefile)

Suggestion: Specify the recommended version for Make to download. I propose mentioning either the latest version or a version above 4.0. This would help users ensure compatibility during the installation process.

2.Point 6: Make Start Command

Suggestion: Clarify that the "make start" command will only function if the Makefile is downloaded or integrated into the user's window environment. Providing this information upfront would prevent potential confusion for users during the setup.
I believe these adjustments will enhance the clarity of the documentation and make the setup process smoother for users. Your attention to these details is highly appreciated, and I thank you for your dedication to improving the user experience.

Best regards,
Shalini

**Comment by pragya-p-github** [comment]
**Comments:**

**Values**: The outlined values of being considerate, respectful, inclusive, collaborative, transparent, mindful of people's privacy, and committed to self-improvement are crucial for fostering a positive and inclusive community. It's commendable that Ushahidi places emphasis on these values and encourages community members to uphold them.

**Unacceptable Behaviors**: The document does a good job of clearly defining unacceptable behaviors such as discrimination, harassment, exclusionary language, false claims, and posting inappropriate content. It also encourages reporting of such behaviors and outlines the actions that may be taken in response to violations, ensuring accountability and maintaining a safe environment for everyone.

**Suggestion:**

**Where does the Code of Conduct apply:** Clearly define the spaces, both physical and online, where the Code of Conduct applies. Provide examples of specific platforms or events covered by the Code of Conduct.

**Comment by lillian-busingye** [comment]
@Angamanga  summarised everything that I personally went through from when I joined the community and I couldn't explain it any further than they did. 
Thank you
