### ISSUE TITLE
Collections filters inactive

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#373]
When you select the ability to view certain collections, they all show at the top of the map as tags label. Nothing happens after clicking them.

**Comment by rjmackay** [comment]
I think this is saying that filtering by multiple collections doesn't work?

**Comment by willdoran** [comment]
@rjmackay I'm not sure I follow, are the following steps to reproduce correct:

1. Select collection
2. Filter collection based on tags
3. click on filter tag label to remove it

?

**Comment by rjmackay** [comment]
Honestly I'm not sure.. there were 2 bugs that this could be:
1. (already solved) if you view a collection it showed up in the active filter list
2. If you filter by multiple collections, it won't work.. because the set filters looks like this
```
if ($search->set)
		{
			$query
				->join('posts_sets', 'INNER')->on('posts.id', '=', 'posts_sets.post_id')
				->where('posts_sets.set_id', '=', $search->set);
		}
```
ie. doesn't handle multiple set ids. 
2. is what needs fixing now

**Comment by willdoran** [comment]
ok I'll address 2 so
