### ISSUE TITLE
Form field description placeholder is too limited

### ISSUE THREAD

**Issue by tuxpiper** [ushahidi/platform#3793]
**Which user group(s) are the primary audience for this feature/enhancement.**
Account-managed Ushahidi Platform customer.
This org distributes sophisticated forms for data collection nation-wide in the U.S.A. through a partner network.

**Is your feature request related to a problem? Please describe.**
The placeholder that allows deployers to describe each of the field is limited in terms of size (256 characters) and format (it doesn't allow or present line-breaks).

This doesn't allow enough expresiveness to introduce reporters to nuanced questions or situations. Sometimes this context is key to ensure more accurate responses to the survey as a whole.

**Describe the solution you'd like**
The field description placeholder should be changed to allow larger text sizes and present rich formatted texts (i.e. via rich text editor, or at least Markdown)

**Describe alternatives you've considered**
An alternative solution to the same problem, which wouldn't require altering the definition of this database row, could be to introduce a new type of survey field. 

This new type of survey field, let's call it "help text", would be presented at report time and not require response from reporters. It would be there just to be displayed inline in the survey.  It should allow lengthy text and support rich formatting (and presentation of links).

This alternative is further explored in a different issue (#3794)

**Comment by Erioldoesdesign** [comment]
Mostly copy pasting the conversation & files from the slack thread.

Right okay - I've been wrapping my head around this request. It's very... specific and actually not something you can do in many form/survey generators (google forms/typeforms etc.)
So what they want is to have long descriptions for questions in their survey that have more than just text so:

![ticket-3793- Form-field-description-formatting](https://user-images.githubusercontent.com/11681324/67201770-eaeaa600-f3fe-11e9-8cfb-64a7880f98b2.jpg)

I think the tricky this to design here is how other users, other than this user learns how this feature functions. It's just not very expected in form creation to have this amount of flexibility (not to say it isn't useful!)
So, the big lift design wise on ticket #3793 is the process in the survey creation section.
#3794 (Allow inserting blocks of content at arbitrary points in the form) actually would be harder to 'understand' from a user perspective without a lot of tutorial/onboarding. The adding of the arbitrary points in the form with the tutorial/learning would have to live in the 'edit field' section (below) which is...an odd place to put such flexibility and I'm not sure how useful that would be for more users.

<img width="553" alt="Screenshot 2019-10-21 at 09 38 27" src="https://user-images.githubusercontent.com/11681324/67201783-f8079500-f3fe-11e9-9e80-705da33025c8.png">

If we were going to do https://github.com/ushahidi/platform/issues/3794 I would want to have this designed/built as a larger (i hate to use this word) re-design or deeper look at the flow of survey creation/build

Anna says: Could we make the user choose between short and long/more complex description in the description-edit field? The short one as default and the more complex one to choose between? Or does it become too much clicking?

Eriol in response: Hmm I would say if we're going to make the 'edit field' section have more text formatting available I would just make that default and go with something that looks like...this: 

![edit-field](https://user-images.githubusercontent.com/11681324/67201834-1d949e80-f3ff-11e9-9b37-4b1128b9b7ee.jpg)

I know in the ticket we've suggested making markdown supported...this would remove the need for a 'text editor' but I'm very skeptical at the widespread use/knowledge of markdown and that again, we're adding/extending a feature that requires some hand-holding tutorial work and/or most people (other than this user) wouldn't use.
Markdown would be an acceptable stop-gap for the description field as long as we provide an external link & text that says 'If you want to format your field description more, you can use markdown (link) to add bullets, titles and links in the text you add' like this:

![edit-field-2](https://user-images.githubusercontent.com/11681324/67201864-2eddab00-f3ff-11e9-80bf-e1ab32530678.jpg)

So this would be the least intense design wise. In fact I think this is the design pretty much.

**Comment by Angamanga** [comment]
@rowasc @tuxpiper @Erioldoesdesign Have attempted to spec above solution, the trickiest thing turned out to be finding a WYSIWYG library that outputs markdown, most libraries output HTML, would that be an ok option?

- [ ] Update instructions-column in form_attributes to be of type text in the db + where needed in the backend
- [ ] Find library to handle wysiwyg in the fe and that saves as markdown (was hard, see below)
- [ ] Update description-input in `settings/surveys/attribute-editor` to be wysiwyg
- [ ] Update description display in the `main/posts/detail/post-value-edit` views to display markdown (possibly use the same method as the markdown field-type) or HTML.

**Libraries for WYSIWYG**
I have researched WYSIWYG editors that are easy for the user to understand and saves markdown and it was hard to find! The only one I found was this one: https://ghiscoding.github.io/angular-markdown-editor/#/reactive-editor. You cannot preview the actual formatting, you see the markdown in the editor, which may be confusing for users.

The other option is to use an editor that outputs HTML instead:

**Quill (This is my preference):** 
https://quilljs.com

**Examples with Angularjs:**
https://codepen.io/lenmorld/pen/yXrmBY
https://github.com/KillerCodeMonkey/ng-quill

Plus:
- Open Source
- Can remove formatting-options easily
- Actively maintained (latest released 9 Sept 2019).

Minus:
- Outputs HTML
- IS actively maintained but have been working on version 2. for a long time without releasing, may indicate low involvement?

**Trix:**
https://github.com/basecamp/trix

**Examples with Angularjs:** 
https://github.com/sachinchoolur/angular-trix
http://embed.plnkr.co/C4BTOHLoXV55lXDJ1tKh/

Plus:
- Actively maintained (latest release 17 Oct 2019)
- Free (MIT License)

Minus:
- Seems tricky to remove formatting-options
- Outputs HTML

**Comment by Angamanga** [comment]
@Erioldoesdesign A question I noticed about the behavior of the description-toggle. As it is now, the toggle is never switched on, even if there is a description, which is a bit confusing to the user, so I want to change that. See screen-recording here: https://recordit.co/JCEisus45G

My questions and assumptions are: 
1. When there is a description saved, the toggle should be green and the description field visible in the editor, is that right?
2. If the user turns the toggle off, even if there is a description added to the field, should that description be deleted or saved? 
3. If still saved and the user turns the toggle off, should that description be shown in the post-add-view or not?

**Comment by Erioldoesdesign** [comment]
> most libraries output HTML, would that be an ok option?

If this is the best option (because wysiwyg editors are poorly supported) I would say yes, HTML output works. We can test and review. :)

> When there is a description saved, the toggle should be green and the description field visible in the editor, is that right?
Yes! if the user has previously added a description to that field then it should be defaulted/remembered as 'on' and show the editor.

> If the user turns the toggle off, even if there is a description added to the field, should that description be deleted or saved?
Hmm...trickier...I would say it should be deleted/removed if the toggle is 'switched off' *but* there should be a modal/warning message before that happens. 'This action will delete your description text. Ok, delete the description. Cancel, do not delete the description.
(sorry for adding in an extra thing to code...)

If still saved and the user turns the toggle off, should that description be shown in the post-add-view or not?
I'm not sure I understand this question, can you do a video of this 'post-add-view' you say?

**Comment by Angamanga** [comment]
@Erioldoesdesign 
>If still saved and the user turns the toggle off, should that description be shown in the post-add-view or not?

So, what I meant was, if the description is saved in the form here, even if the toggle is turned off:
![Screenshot 2019-11-08 at 09 00 14](https://user-images.githubusercontent.com/8624777/68459648-375b2180-0206-11ea-8b03-602b563cd514.png)

Should the description be visible here then:
![Screenshot 2019-11-08 at 08 59 19](https://user-images.githubusercontent.com/8624777/68459673-493cc480-0206-11ea-9f6c-ee43e1d1b71b.png)

But if we delete the description when the toggle turns off, issue is resolved, there is no description to show :) I can use the same delete-warning as in the data-view when moving away from edit-mode without saving

**Comment by Angamanga** [comment]
When thinking about it, I like the idea to control the visibility of the description with the toggle instead of text in the form, in that way there are less clicks and warnings and the user can choose if they want to start working on a description, leave it there and turn the toggle on when ready. Would that be ok?

**Comment by Angamanga** [comment]
After chatting with Eriol we decided to go for the solution where the toggle decides if the description is shown in the post-add/edit view or not.

**Comment by rowasc** [comment]
@Obadha2 can you try this in steve-buscemi in the morning? 
Testing checklist from Anna:
- Go to settings-survey
- Add a new survey
- Add a new field, or edit title or description
- [ ] A markdown editor should appear below "Add field description (optional:)":
![Screenshot 2019-11-11 at 10 43 38](https://user-images.githubusercontent.com/8624777/68577365-39c0b400-0470-11ea-82f7-08e0486c09ee.png)
- [ ] For fields where it's possible to add a default value  (all field-types except "upload", "description", "title" and "tags"), the default value box should be displayed with no toggle-switch:
![Screenshot 2019-11-11 at 10 46 28](https://user-images.githubusercontent.com/8624777/68577529-91f7b600-0470-11ea-9bbd-2ed95665a362.png)

- Add some text in the description-editor, format it however you want to, and as long text as you want to
- Save the field
- Save the survey
- Choose to add a new post to this survey
- [ ] The description should be visible for the field you added description
- [ ] The description should have the same formatting as you did in the editor
- Save the post
- Go to data-view
- Select the post you added and select "edit"
- [ ] The description should be visible for the field you added description
- [ ] The description should have the same formatting as you did in the editor

Repeat the above steps for a survey that already exists

**Comment by Obadha2** [comment]
QA'd, passes. :+1:

**Comment by rowasc** [comment]
💯 💯 💯 💯 💯  THANK YOU all. Let's deploy this on monday morning !
