### ISSUE TITLE
Allow inserting blocks of content at arbitrary points in the form

### ISSUE THREAD

**Issue by tuxpiper** [ushahidi/platform#3794]
**Which user group(s) are the primary audience for this feature/enhancement.**
Account-managed Ushahidi Platform customer.
This org distributes sophisticated forms for data collection nation-wide in the U.S.A. through a partner network.

**Is your feature request related to a problem? Please describe.**
The placeholder that allows deployers to describe each of the field is limited in terms of size (256 characters) and format (it doesn't allow or present line-breaks).

This doesn't allow enough expresiveness to introduce reporters to nuanced questions or situations. Sometimes this context is key to ensure more accurate responses to the survey as a whole.

**Describe the solution you'd like**
Create a new kind of object that survey designers could add to the survey, just like they do now with fields of different types.

This new type of survey field, let's call it provisionally "help text", would be presented at report time and not require response from reporters. It would be there just to be displayed inline in the survey. It should allow lengthy text and support rich formatting (and presentation of links).

**Describe alternatives you've considered**
Alternatively, the field description placeholder could be changed to allow larger text sizes and present rich formatted texts (i.e. via rich text editor, or at least Markdown). This is explored in issue #3793

**Comment by Erioldoesdesign** [comment]
The comment from the slack thread relevant to this issue is:

If we were going to do #3794 I would want to have this designed/built as a larger (i hate to use this word) re-design or deeper look at the flow of survey creation/build.

and

#3794 (Allow inserting blocks of content at arbitrary points in the form) actually would be harder to 'understand' from a user perspective without a lot of tutorial/onboarding. The adding of the arbitrary points in the form with the tutorial/learning would have to live in the 'edit field' section (below) which is...an odd place to put such flexibility and I'm not sure how useful that would be for more users.

**Comment by rowasc** [comment]
Closing this wont-fix issue, as we addressed this (partially) with the simpler #3793 feature. Tagged "Theme: forms" so it's easy to find later.
