### ISSUE TITLE
Failed to validate posts entity error on image uploads for non-admin users.

### ISSUE THREAD

**Issue by rowasc** [ushahidi/platform#3826]
**Describe the bug**
-  When submitting posts with images in a form with tasks, a deployer is getting the error `Failed to validate posts entity : post.user_id.exists`
<img width="1060" alt="Screen Shot 2019-12-13 at 09 47 47" src="https://user-images.githubusercontent.com/2434401/70801433-a55ab180-1d8d-11ea-8e42-8be92e8e4c63.png">
- This happened to users with the following permissions: Manage Posts, Edit their own posts, Manage Collections and Saved Searches, and Bulk Data Import and Export.

**Where was the bug observed**
An ushahidi.io deployment with a grassroots plan. 

**To Reproduce**

1. Add a post with an image as admin
2. Edit post as user with permissions  Manage Posts, Edit their own posts, Manage Collections and Saved Searches, and Bulk Data Import and Export, change the image
3. Save
4. Error-message appears

**Expected behavior**
Users with permissions to submit posts should also be able to submit images. 

**Is there a workaround? What is it.**
The original reporter of this bug mentioned that giving a user "admin" level permissions solved it. 

**Desktop Hardware Details (please complete the following information):**
 - OS: Windows (not sure of version) 
 - Browser: Chrome

**Comment by Angamanga** [comment]
Steps to reproduce:
1. Add a post with an image as admin
2. Edit post as user with permissions  Manage Posts, Edit their own posts, Manage Collections and Saved Searches, and Bulk Data Import and Export, change the image
3. Save
4. Error-message appears

**Comment by Angamanga** [comment]
This issue is larger than just images.
My findings so far:
- When a user without Manage users-permissions read a post, the get /users fails
- This prevents getting the user_id to that specific post
- When the user then tries to save a post after editing, the post-validator stops it, because there is no user_id available in the post. 

Why the client asks for the whole user, and not accepts the post as it is, with a user_id, I have not yet figured out. Will be continued..

**Comment by Angamanga** [comment]
@rowasc We need to decide what the behavior should be for different permissions and access to users to solve this issue.
There two different options:

1. Only Admins and Users with manage Users permissions are allowed to read anything about users(like now). 
Need to do: We need to fix the fetching of users for everyone who has not the correct permissions, to not destroy the post-object that are sent to the api (and destroys the save after edit)
2. Users with manage posts permissions are allowed to read real-name to be able to see the full posts (they don't see the author right now if its not themselves)
Need to do: Fix permissions and let users with manage post-permission to read users names and id.

I lean towards 2 since in order to triage and manage posts, you need the full info of a post.

**Comment by rowasc** [comment]
hey Anna. This is great! Thank you for your findings. If we do 2, it would mean that we open information up that was previously private, no?

**Comment by Angamanga** [comment]
Yes, we open it up to those with Manage posts permissions :/ So its a bit delicate I think. But still, it might be hard to triage posts without knowing who has sent them? I am not sure if it always has been like that?

**Comment by rowasc** [comment]
:/ Yea. I think the only way to go here is to be more granular about permissions. *seeing usernames*  is quite different than *managing users* 

What I'm wondering about now is, do we really need the user_id to be accessed by the client, to enable uploading images or triaging of posts? It doesn't sound very likely to me. I mean certainly we do need them now but we shouldn't, no? I may be forgetting some internals @Angamanga . Is that what *1* is about?

**Comment by Angamanga** [comment]
Yes, a more granular permission I think is the best option. As it is now, we fetch the user to get hold of the username, that the only we really need the user_id for. But you are on to something, we could send the username directly with the post and not having to get it in the client? That would save us a request in the api too. *winwin*?

**Comment by Angamanga** [comment]
Decision on how to move forward:
1. Make the fix the fetching of users for everyone who has not the correct permissions, to not destroy the post-object that are sent to the api (and destroys the save after edit).
2. Usertest and make decision on how to solve more granular permissions for access to usernames.
3. Implement more granular permissions (if decided its needed)
New issue for more granular permissions is found here: https://github.com/ushahidi/platform/issues/3829

**Comment by Angamanga** [comment]
@Obadha2 Could you QA in Steve Buscemi? Testing-checklist: 

Testing checklist:
- [ ] Log in as a user with Manage Posts permissions, but without admin or Manage Users permissions
- [ ] Go to data-view
- [ ] Select a post added by another user than the current logged in one
- [ ] Click on edit, make a change
- [ ] Click on save, post should save without error-message

Pull-request (for reference): https://github.com/ushahidi/platform-client/pull/1397

**Comment by Obadha2** [comment]
QA'd, passes. 👍
