### ISSUE TITLE
Making fields more Intuitive.

### ISSUE THREAD

**Issue by noone0212** [ushahidi/platform#3891]
**Where is it observed**
-   Login to your deployment.
-   Click on survey settings.
-   Select a survey to edit.
-   Select any task to edit in that survey.

**Current Scenario**
We need to click on title of task to edit it. Also, current cursor type is text which does not make intuitive that by clicking on title of task we can edit it.
**Suggested Feature**
We may add options like:
-   Change cursor type to maybe pointer on title of task or any other.
-    Add edit button adjacent to task title.
-    Make text underlined.

Or any.
**Screenshot**
See cursor and text.
![Screenshot from 2020-03-22 09-43-51](https://user-images.githubusercontent.com/46659112/77242198-e3cffa00-6c21-11ea-97b0-329143f345eb.png)

Aha! Link: https://ushahiditeam.aha.io/features/PROD-147

**Comment by noone0212** [comment]
I am working on this issue.

**Comment by noone0212** [comment]
@Erioldoesdesign can you please suggest me how should I proceed ahead?

**Comment by Erioldoesdesign** [comment]
I didn't raise this issue - what problem is it trying to solve? It hasn't come from a user? 

Edit buttons are not part of our design system in line so this would need deeper design thinking as well as usertesting of prototypes.

**Comment by Erioldoesdesign** [comment]
Copy paste from #1480 

...but it may be worth sync or a longer conversation on what problems it's trying to solve and then I can dig around for older designs or see what I need to build/piece together and/or usertest and work with @noone0212 on. Any more detail in the issue would be very, very helpful because 'Making fields more Intuitive.' is quite broad!

Also fields in the UI refresh is....here!
ushahidi/platform#2655
ushahidi/platform#2655
