### ISSUE TITLE
Make registration button and endpoints optional

### ISSUE THREAD

**Issue by rowasc** [ushahidi/platform#3918]
**Which user group(s) are the primary audience for this feature/enhancement.**
Include deployment names if possible
A group using Ushahidi for COVID response needs to be able to disable the "Register" functionality. 
Their use case is that they explicitly only want people to join if they are invited to be a part of the site management group, rather than make registration open. 

Note on user testing: 
This is something I can see myself wanting for deployments where there is no reason to register if you aren't an admin, and one that we can see in many content management systems, so while I do not have extensive user tests about this, it's reasonable to assume there is value in having this option, and it is directly coming from a group using Ushahidi. 

**Is your feature request related to a problem? Please describe.**
Yes. Registration should be optional, with administrators being able to just invite people they want to have join their deployment rather than have people signing up all the time without needing to.

**Describe the solution you'd like**
- Have a new configuration option "Disable user sign up" 
- The option is OFF by default (meaning user register/sign-up flow is ON by default)
- When the option is ON:
    - Only users with permissions are allowed to invite others, nobody can register (disable at the API level)
    - Hide the sign up / register button from non-privileged users

**Describe alternatives you've considered**
Not doing it

Aha! Link: https://ushahiditeam.aha.io/features/PROD-132

**Comment by RachealN** [comment]
@rowasc, Here's the solution I thought could work as far as approaching this issue is concerned
1-Make the registration of users strictly by invitation. This approach will not allow public registration and send invitation links instead.
use case
- Users will be requesting an invite by entering their email and only admin or other management groups will make the registration.
- This approach will require a new BD table for handling invitations and other configuration options to make it work
NOTE. This approach can also work for paid membership privileges and pages that are not visible by other users.
Am requesting you assign this issue to me and I work on it, If you find this approach reliable Thanks

**Comment by A-DML** [comment]
Hi @rowasc @Angamanga i will like to work on this for my outreachy contribution .  if it's still available.

**Comment by rowasc** [comment]
@A-DML please go ahead ! thanks

**Comment by SaifurRahmanMohsin** [comment]
@rowasc It's been 2 weeks and I see there has been no progress on this yet. Is this hacktoberfest accepted issue? I'd like to take it up if so.

**Comment by rowasc** [comment]
@A-DML are you working on this? Do you need a hand? 
@SaifurRahmanMohsin cc
Thanks

**Comment by SaifurRahmanMohsin** [comment]
???

**Comment by SaifurRahmanMohsin** [comment]
@rowasc Hey, any update on this. Could I take it up?

**Comment by SaifurRahmanMohsin** [comment]
Hey, @rowasc could I take this up instead?

**Comment by SaifurRahmanMohsin** [comment]
@rowasc Hello, I've pushed PRs as per the spec you mentioned in the first comment. Kindly review and merge if everything is well. I would appreciate if this PR includes the hacktoberfest-accepted label. Thank you.

**Comment by tuxpiper** [comment]
@all-contributors please add @SaifurRahmanMohsin for code
