### ISSUE TITLE
Related Post not working

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#3929]
**Expected behavior**
When I add a related post field to a report, on display, I should be able to click on the link of the related post, and be redirected to it.

**Actual Behaviour**
The link seems to be broken. See https://kenyacovid19.ushahidi.io/posts/102

**Steps to Reproduce**

- [ ] Create a survey with a related post field
- [ ] Submit a post with another post attached as related.
- [ ] Navigate to view this post,
- [ ] Attempt to click on the link under the related post field.

Tested this out with Map Kibera Team

Aha! Link: https://ushahiditeam.aha.io/features/PROD-129

**Comment by rowasc** [comment]
oof I ran into this one in mobile and reported it a long long time ago :( Didn't realize it also happens in web. 

Going to tag as community ticket for the moment since nobody has any bandwith to take this one right now (and a few others) due to a lot of priorities, hopefully someone will be able to help out.
