### ISSUE TITLE
Create setting to visualise posts by category vs by survey?

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#3931]
**Which user group(s) are the primary audience for this feature/enhancement.**
Came up in a discussion with Map Kibera team who have prior history using v2 deployments

**Is your feature request related to a problem? Please describe.**
The way they have their data structure set up, it's not helpful to visualise posts on the map by survey, and would instead make sense to do this via categories. 

**Describe the solution you'd like**
Wondering if it may be worth creating a setting for a deployer to choose to either visualise posts on the map by category instead of by survey?

Aha! Link: https://ushahiditeam.aha.io/features/PROD-127

**Comment by rowasc** [comment]
That's something we've heard from other deployers too, yea. 
@CeciliaHinga I think you have flagged similar ones too? If yes it would be great to collect some of that data here 

Q for @aoduor 
- What kind of setup do they have that makes this useful to them? 

In deployments for help/requests, I'd want to be able to see the pins differentiated by "solved cases" vs " unsolved cases" with different color to easily get an idea of a situation on the ground, and since categories is one way to do that kind of setup, it would be useful for that.

**Comment by Angamanga** [comment]
Related to #1436
