### ISSUE TITLE
Input Numbers on the integer field type get's changed when the form is submitted

### ISSUE THREAD

**Issue by CeciliaHinga** [ushahidi/platform#3943]
**Describe the bug**
When you create an integer field type on your survey and enter the information you want, in this case, contact info, on submission the number changes from the initial number that you entered.

**Where was the bug observed**
Production

**To Reproduce**
1. Go to the setting page, then click on surveys.
2. Add a field
3. Click on Number(integer) and save
4. Submit a response and add the necessary information including the number info you want, click save and submit to the survey.
5. The number on the postcard changes from the one you entered.

**Expected behavior**
The number should not change from the one you entered.

**Is there a workaround? What is it.**
None

**Desktop Hardware Details (please complete the following information):**
 - OS: iOS]
 - Browser  chrome
-Version 80.0.3987.163 (Official Build) (64-bit)

Aha! Link: https://ushahiditeam.aha.io/features/PROD-122

**Comment by rowasc** [comment]
so far I tried with 
- 99 - all good
- my phone number (out of range error for integer, should return a friendlier error)
- Spaces in number (gets blanked out, should instead return an error)

**Comment by Obadha2** [comment]
@rowasc on investigating this i found out that, the entered value remains intact if the value is upto 10 digits long. The moment the value entered is 11 digits or over, the value is replaced with a constant value `2147483647`

**Comment by rowasc** [comment]
@jlittle22 yep, very likely. We need to find out where exactly it's happening. LMK if you want to give it a try otherwise we'll look into it ASAP

**Comment by TunrayoIlawole** [comment]
Hey @Angamanga Can i please work on this one?

**Comment by Angamanga** [comment]
@TunrayoIlawole Yep, please go ahead :)

**Comment by rowasc** [comment]
hey @TunrayoIlawole how is it going? Are you working on this issue? Thanks

**Comment by TunrayoIlawole** [comment]
> hey @TunrayoIlawole how is it going? Are you working on this issue? Thanks

No, I’m not. Please assign it to someone else

**Comment by rowasc** [comment]
Thanks!

**Comment by AngadSethi** [comment]
Hello!

I am working on this issue. According to me, the main problem arises because of the `Validator\Post\Integer` class, which just checks whether the input is a digit or not. I added another validation rule which checks whether the Integer input is within the given range or not, specifying the minimum value as the minimum value of INT in SQL and same for the maximum value.

The problem, however, arises when I try to format the error. The range error message is
` 'range'         => ':field must be within the range of :param2 to :param3'`

This expects two parameters, the min value (param2) and the max value (param3), but when we are validating it, we pass only one parameter, that is the value itself, so the error comes out to be `Failed to validate posts entity: values must be within the range of 7979797989898 to :param3`, where `7979797989898` is the bogus input, instead of `Failed to validate posts entity: values must be within the range of -2147483648 to 2147483647`.

This issue is because of this line:
`$validation->error('values', $error, [$attribute->label, $values]);`
where param2 is $values and there is no param3.

A bigger problem is with error messages which require a second/third parameter, that is **not** the input, namely, the `decimal`, `exact_length`, `matches`, `min_length`, `max_length`, `range` error messages. 

If I made some error in the above comment, please correct me. Also, should I explicitly handle these error messages, or is there some other solution?
