### ISSUE TITLE
Email address validation error

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#396]
When I save my post, I get the following error when I use my email address (email used to register V3 account) in the ‘add post’ form; but the post gets successfully saved when I use a different email address;

￼"Validation error: 'post.author_email.isUniqueEmail'"

**Comment by rjmackay** [comment]
@willdoran I think this was semi-intentional: we don't let you make an anonymous submission if theres an existing user with your email.. however the UI doesn't really manage to convey that.
You could:
- Remove that validation.. and just let people make anonymous submissions regardless.
- try to provide a better error message from the API.

**Comment by willdoran** [comment]
Yep, groovy, will do

**Comment by willdoran** [comment]
Removed validation - in future there should be a validation message created for is unique failure if putting it back becomes desirable.
