### ISSUE TITLE
Expired session logout

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#398]
Is there an expiry for the logged in session? I seem to get logged out after sometime without any notification

**Comment by willdoran** [comment]
Automatic Session Expiration creates a frustrating experience for the user. We should warn the user two minutes before their session is due to end and offer them the opportunity to renew the session.

First of all the Platform uses the [League Oauth2 Server](https://github.com/thephpleague/oauth2-server) and it's worth reading about how [OAuth tokens work](https://www.oauth.com/oauth2-servers/access-tokens/access-token-lifetime/) to get a basic understanding.

In the client the following code is responsible for [login/logout management](https://github.com/ushahidi/platform-client/tree/develop/app/common/auth)

As a first step, it would be good to warn the user that their session is going to expire - at this stage we just want to send them a notification that there session will expire in 2 minutes time.

For the client notifications are controlled by the Notify service.

For example to send the user a confirm notification I would do the following:

~~~~
 Notify.confirm('notify.notification.session_expiration_confirm').then(function () {
    // Do something about it
 });
~~~~

So to start with it's important to determine:
- When the session will expire from the Access Token information
- How to Notify the user of this 2 minutes before the expiration
- How to test this, [this tutoria](https://www.pluralsight.com/guides/front-end-javascript/introduction-to-angular-test-driven-development)l describes the testing framework that Ushahidi uses on the frontend

Ushahidi tries to use Test Driven Development as much as possible, as such the first step for this will be to define a set of tests that will describe the functions of the new service.

The session expiration warning can become part of the Authentication Service or it can be created as it's own Service.

Later, we will want to allow the user to renew the session using Refresh Tokens if they wish to do so when warned about session expiration.

**Comment by jshorland** [comment]
Closing in favor of #1497
