### ISSUE TITLE
Randomized location 

### ISSUE THREAD

**Issue by taramcwhinney** [ushahidi/platform#3982]
I thought I had my map locations hidden and randomized within 9 km. But it doesn't seem to be working. Can you help to fix this. People on my survey do not want their exact locations known.

Aha! Link: https://ushahiditeam.aha.io/features/PROD-105

**Comment by Obadha2** [comment]
Hi @taramcwhinney 
I'm not sure I quite understand the issue you are facing.
If a field is marked as private, responses to this particular field will only be seen to those who have the appropriate permissions.
We do not have a location randomizing feature on the platform. When submitting a response to a survey, the location that is selected will persist. Note that this is accurate as selected because we use longitude and latitude information to mark locations.
If location data is not needed, you could either 
- remove the field from the survey
- mark the location field as optional - this means users can submit responses to the survey without having to fill the location field.

I hope this helps. If not, please provide more context on the issue.

Thanks.
