### ISSUE TITLE
Custom field dates / datetimes need friendly date formatting

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#399]
When I view a post, format for date (When?), its not user friendly e.g. 2015-08-13 06:00:00

**Comment by sophshep** [comment]
Need to figure out when and why a user would need a timestamp. How do they edit that?

**Comment by rjmackay** [comment]
Which view is this on? screenshot? is this a custom field date or post date?
Formatting these should be pretty trivial.. but need to be careful about international date formats.

**Comment by sophshep** [comment]
This is on the post detail page, specifically on a "date" field (not the default one, but if I add a field for the date)

![image](https://cloud.githubusercontent.com/assets/527589/10581502/ad9861f8-7648-11e5-8caa-82fe9190b239.png)

Since this will be entered manually in the field, I'd suggest having "date" as one field option and "time" as another.

**Comment by rjmackay** [comment]
.. we already have 'date' or 'date + time' fields. Lets just confine this issue to the simple change: nice date formatting on custom fields

**Comment by rjmackay** [comment]
Did this get done @willdoran ?

**Comment by willdoran** [comment]
Yep, the format matches desired one. Though there is no default example text in those fields. Which would make sense as the user clicks to enter but perhaps it'd be good to have something in field given that all other fields have example text of some kind: "Enter a date" for example.
