### ISSUE TITLE
Warn users about identical options in checkboxes

### ISSUE THREAD

**Issue by Angamanga** [ushahidi/platform#3994]
**Describe the bug**
No warning is shown when a user adds 2 identical options for checkboxes. It saves as normal but when displaying the checkboxes, there is an error in ng-repeat that causes the list to not be shown.

**To Reproduce**
1. Go to 'settings>surveys', add or edit a survey with a checkbox-field
2. Add 2 identical options, save
3. Go to add a post for that survey
4. The checkbox-field will not be visible
5. There is an error in the console

**Expected behavior**
1. There should be a warning when trying to save 2 identical fields
2. The error should be handled in the post-editor-view and not just ignore displaying the options

**Is there a workaround? What is it.**
Nope, not really. Editing the survey and deleting one of the identical options

Aha! Link: https://ushahiditeam.aha.io/features/PROD-99

**Comment by renujain31** [comment]
Hey, Can I work on this one! Thanks!

**Comment by Angamanga** [comment]
@renujain31 Please go ahead :) 👍

**Comment by renujain31** [comment]
@Angamanga 
Here's a possible solution: We can disable the ADD button when the option added is same of any of the options already added by changing the code [here](https://github.com/ushahidi/platform-client/blob/develop/app/settings/surveys/attribute-editor.html#L38)

To prevent the error while adding posts I understand that I have to make changes [here](https://github.com/ushahidi/platform-client/blob/develop/app/main/posts/modify/post-value-edit.html#L61) but I don't see from where exactly those options are been fetched and how to handle this?

Any pointers or suggestions would be helpful. Thanks!

**Comment by rowasc** [comment]
Ah right so the problem happens because of the `track by` trying to use a repeated key. 
Error: [ngRepeat:dupes] Duplicates in a repeater are not allowed. Use 'track by' expression to specify unique keys. Repeater: option in attribute.options, Duplicate key: string:ad, Duplicate value: ad
https://errors.angularjs.org/1.8.0/ngRepeat/dupes?p0=option%20in%20attribute.options&p1=string%3Aad&p2=ad
    Angular 8

@Angamanga notes for consideration
I'm not entirely sure that we want to solve this by showing the checkboxes anyway because it kind of hides the problem... but then it'd also be sort of horrible to just show "The survey is wrongly configured" to end users .... 
Maybe a solution could be that if you're an admin testing your survey, you see "There's a problem with the checkbox configuration because of duplicates, please fix it by going to <survey link edit> " and if you're an end user we don't show the checkbox?


If we wanted to show them anyway, In terms of filtering out duplicates we may be able to do that in the activate function, I think https://github.com/ushahidi/platform-client/blob/develop/app/main/posts/modify/post-value-edit.directive.js ? or do we have to handle it earlier ? :thinking: 


@renujain31 I would start by fixing the surevy editor side of things (ie block the ADD button if duplicates and show a warning) while we discuss the above . Also if you have thoughts on how best to handle it please let me know !

**Comment by renujain31** [comment]
@rowasc I agree in the case when the user is admin, but for general user a possible solution might also be to display the checkbox where we take care of duplicate options by removing just the duplicate options. 

Is there anything I could help you with in fixing the issue @rowasc? Maybe I can take care of the part to display the warning when user is admin? Thanks!

**Comment by rowasc** [comment]
@renujain31 Definitely definitely please work on the warning and the blocking of the add button :ship:  on monday we can catch up here on the other part that's not clear regarding regular users

**Comment by renujain31** [comment]
Update 1: I have worked on disabling the add option when duplicates are present. So it looks like this now:
![image](https://user-images.githubusercontent.com/70752431/95713280-e0669380-0c83-11eb-860c-9501e71f8547.png)

Let me know if this is what we want or not. Thanks
