### ISSUE TITLE
Merge arabic translation fixes **to Transifex**:

### ISSUE THREAD

**Issue by rowasc** [ushahidi/platform#4069]
ushahidi/platform#4037, ushahidi/platform#4038, ushahidi/platform#4039, ushahidi/platform#4040, ushahidi/platform#4041, ushahidi/platform#4042

We'll give it a few more days in case the original contributor sends them to transifex but if they are not there by Monday we'll do it manually (and of course credit them )

Aha! Link: https://ushahiditeam.aha.io/features/PROD-777

**Comment by tuxpiper** [comment]
Found a significant hitch while working on this one. It turns out that we are not doing translations well :( 

Unfortunately, as far as I have been able to tell, with .php resource files, transifex can't parse structures like this:

```php
array(
  'key1' => 'wording for key1',
  ...
  'category1' => array(
    'key1.1' => 'wording for category1 , key1'
  )
)
```

They need to be flattened:
```php
array(
  'key1' => 'wording for key1',
  'key1.1' => 'wording for category1, key1'
)
```

cc: @rowasc : do you know if we can use JSON translation files with Lumen? Nothing I found gave me a positive feeling it was possible/practical.

**Comment by rowasc** [comment]
ouch, ok. I'm pretty sure there's no native JSON support but I'll take a look at the options. Flattening may work if we extend the translation features, I guess, but not ideal either
