### ISSUE TITLE
Hdx-logo is not showing

### ISSUE THREAD

**Issue by Angamanga** [ushahidi/platform#4122]
**Describe the bug**
The hdx-logo on /settings/user-settings is not showing. In the dev-tools the image url is shown as "[object Module]". This is likely due to how we load images in Webpack 4.

**Where was the bug observed**
locally and in .io

**To Reproduce**
1. Go to settings->Configure HDX api
2. The logo in the upper right corner is not displayed.

**Expected behavior**
The logo should be visible

**Screenshots**
<img width="222" alt="Screenshot 2020-10-16 at 14 44 16" src="https://user-images.githubusercontent.com/8624777/96259637-2c844180-0fbe-11eb-87d2-5a83d7bd2580.png">

<img width="543" alt="Screenshot 2020-10-16 at 14 44 45" src="https://user-images.githubusercontent.com/8624777/96259604-255d3380-0fbe-11eb-8cfd-478e5e60d729.png">

**Comment by Sunairaa** [comment]
Hey @Angamanga can I work on this issue?

**Comment by Dev-Som** [comment]
@Angamanga Can I work on this issue?

**Comment by codifyit** [comment]
Hi @Angamanga Can i work on this? I haven't had my first issue yet

**Comment by Angamanga** [comment]
@Sunairaa Please go ahead. @Dev-Som I pinged you on this issue: https://github.com/ushahidi/platform/issues/2347 and @codifyit on this one https://github.com/ushahidi/platform/issues/1880. Please let me know if you want to work on these issues.

**Comment by Sunairaa** [comment]
Hey @Angamanga thanks for assigning me this issue.. I have confusion when I login on to my local with my profile credentials I am not able to see settings options. do I need to login as an admin? if yes share credentials?

**Comment by rowasc** [comment]
@Sunairaa to work on this, you need a backend setup locally or to link up with (your  own) ushahidi.io backend. Check out the gitter channel for an explainer on that a few days ago (where I explain that you can create and connect to ushahidi.io instances) 
We will not provide admin privileges
Thanks

**Comment by Sunairaa** [comment]
Hey @Angamanga @rowasc 
I have figured out with deployment instances and now I am able to see settings options and user settings and I also got where hdx logo is missing.

In the issue description, it was mentioned that I need to configure hdx. 
![image](https://user-images.githubusercontent.com/66335481/96509026-516ff300-1210-11eb-923e-6f1c89ab7abd.png)

for this, I need hdx maintainer ID and API key and it is stated maintainer ID and API key can be found from HDx profile..
so my question are:

1. Do I need to sign up hdx with my profile data? and got an API key from there? something else I need to do?
2. Well I also signup with my credentials and I got user I'd and an API key from profile now I am confused about what I need to do further as the logo is still not showing in the right corner.

![image](https://user-images.githubusercontent.com/66335481/96509443-e246ce80-1210-11eb-9d21-7416c99cd6c1.png)


Am I doing in the right way? or making any mistake? Any guidance will be helpful

**Comment by rowasc** [comment]
@Sunairaa you shouldn't have to fully configure HDX with valid credentials to make the logo appear (since as you can see it should be appearing there). The issue mentions "Configure HDX api" as in "go to the configure HDX api screen", not as an action (sorry that may have been confusing!)
Regarding the deployment yeah that's fine, as long as you're connecting from your local client to it, which I see in the screenshot that you are.
The thing to fix here is making the logo appear.

**Comment by Angamanga** [comment]
@Sunairaa Don't worry about configuring the HDX-api, this bug probably comes from is how we bundle the code and process the images. We use Webpack 4 to do that and there is something in that config that makes the image-url become an object instead of the url.

**Comment by Sunairaa** [comment]
Thanks @rowasc and @Angamanga for the reply. I am working on it!

**Comment by Sunairaa** [comment]
Hey, @Angamanga @rowasc I have go through the issue and got an error in the console about manifest (screenshot attached) but when I go through platform-client files I didn't get any manifest even it was also linked in index.html. 

Screenshot are also attacthed. 
![image](https://user-images.githubusercontent.com/66335481/96755561-b8fc7e80-1387-11eb-92dd-519f324a3f73.png)
![image](https://user-images.githubusercontent.com/66335481/96755214-47243500-1387-11eb-86df-57ce76470214.png)

Can you please help me to find that file? or this error may be due to missing of that file?

**Comment by Sunairaa** [comment]
Hey @rowasc @Angamanga this is what you want from me to do.. to show logo on hdx API configure screen.
![image](https://user-images.githubusercontent.com/66335481/96767038-d41fbc00-1390-11eb-8d0f-2f57ea506b0e.png)

**Comment by Sunairaa** [comment]
@rowasc @Angamanga review my work here https://github.com/ushahidi/platform-client/pull/1598
Thanks 👍
