### ISSUE TITLE
Focus Trap in dropdown menus

### ISSUE THREAD

**Issue by renujain31** [ushahidi/platform#4198]
**Describe the bug**
Focus isn't trapped in dropdown menus..

**Where was the bug observed**
.io deployment

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to the "sort and filter" option.
2. The focus isn't trapped in the filter dropdown menu.

**Expected behavior**
The dropdown menu should trap focus alternatively close when focus is outside of the dropdown.

**Hints**
- Check the modal-directive for similar solution: https://github.com/ushahidi/platform-client/blob/develop/app/common/directives/modal-container.directive.js

**Comment by Ifycode** [comment]
@Angamanga can I work on this issue instead? @renujain31 I may need some help while working on this one.

**Comment by Angamanga** [comment]
@Ifycode Assigning you! Check the code here https://github.com/ushahidi/platform-client/blob/develop/app/common/directives/modal-container.directive.js#L70 and here https://github.com/ushahidi/platform-client/blob/develop/app/common/directives/modal-container.directive.js#L107. We are trapping the focus within the modal by purpose since we don't want to tab outside of the box without closing it first. I think we can do a similar solution for the sort and filter, but instead of the close-button, we remove the trap once someone selects to apply/view the filters, restore the filters and possibly also add a cancel button along with the other 2 buttons in the bottom of the dropdown. Experiment and see if it looks ok :). I trust you will figure it out.

**Comment by Ifycode** [comment]
Alright @Angamanga will use the info you sent, and start work on it.

**Comment by Ifycode** [comment]
Save this here:
https://www.npmjs.com/package/focus-trap
