### ISSUE TITLE
The color-code configured for each survey is not displayed on the mode-context bar in map and data view 

### ISSUE THREAD

**Issue by CeciliaHinga** [ushahidi/platform#4303]
**Describe the bug**
The color-code configured for each survey is not displayed on the mode-context bar in map and data view. However, the color associated with that particular survey is displayed on the mode bar on the survey editor page and the pointers on the map.

**Where was the bug observed**
Ushahidi.io

**To Reproduce**
1. Go to settings
2. Click on surveys
3. Click on an existing survey, then click on "configurations."
4. Select a color or hex value that will be associated with that survey, click on save
5. You will notice the color on the mode-content bar representing that survey has changed if you click on the survey again to edit.
6. Click on "map" or "data" (if any posts were submitted for that particular survey)
7. You will see the mode content bar does not display the color code configured for that survey in map view or on the posts submitted for that survey in the data view

**Expected behavior**
When one configures a color for a survey, the color selected should be displayed on the mode-context bar associated with the survey on the map view and data view.

**Is there a workaround? What is it?**
No

**Screenshots**
<img width="303" alt="Posts_-_test254" src="https://user-images.githubusercontent.com/20906968/131642136-9e11e63a-cde9-46bb-b47c-d069401254e2.png">
<img width="533" alt="Posts_-_test254" src="https://user-images.githubusercontent.com/20906968/131642392-8220c119-1ea5-4190-acdd-59fa5198d812.png">

**URL / Environment where this happened**
Production

**Desktop Hardware Details (please complete the following information):**
 - OS: iOS
 - Browser: Brave

**Comment by Angamanga** [comment]
There is good and bad news here. The colours are saved in the database so they are not gone. 

In the mode-context bar here:
<img width="303" alt="Posts_-_test254" src="https://user-images.githubusercontent.com/20906968/131642136-9e11e63a-cde9-46bb-b47c-d069401254e2.png">

we use a specific option to only request specific information from the API. It is called 'list_and_permissions' and returns less information than when asking for the full form. The colours are not included in that smaller response 😭 . If I ask for the full form object, I get the colour information.

A quick and easy solution would be to ask for the full object but that may have an impact on the performance. The most solid thing would be to fix it in the API.  Any thoughts around this since it affects the backend @tuxpiper @webong?

For the data view, the problem is client-side only so I'll fix that and send a PR.

**Comment by tuxpiper** [comment]
> A quick and easy solution would be to ask for the full object but that may have an impact on the performance. The most solid thing would be to fix it in the API.

Ah that's fine, I think including this field in the API `list_and_permissions` format is a one-liner change. Could you please look into it @webong ? (I think it's in the v5/Http/Resources/) folder.
