### ISSUE TITLE
cannot see all the posts unless one reloads several times.

### ISSUE THREAD

**Issue by CeciliaHinga** [ushahidi/platform#4429]
**Describe the bug**
While testing, we noticed that a user who had permission to manage posts had to reload the data view page several times to see all three posts on the data view mode. It would be all three posts on one occasion or two posts.

**Where was the bug observed**
(https://uchaguzi.staging.ush.zone/views/data)

**To Reproduce**
1. Go to(https://uchaguzi.staging.ush.zone/views/data)
2. Log in as a user who can only manage posts
3. Click on the data view mode
4. See all 3posts or two posts. It kept changing when the page was reloaded.

**Expected behavior**
Reloading the page should not affect the number of posts displayed on the screen.

**Is there a workaround? What is it.**
Keep reloading the page to see all posts.

**URL / Environment where this happened**
staging

**Desktop Hardware Details (please complete the following information):**
 - OS: iOS
 - Browser: Brave

**Comment by CeciliaHinga** [comment]
It was always the same of the three and it was the newest.

**Comment by tuxpiper** [comment]
Thank you @CeciliaHinga . I have tried to quickly create a new post and see if it would appear missing for the user that can only manage posts... but to no avail.

@AmTryingMyBest  I'm leaving this in your more capable hands. If you are able to reproduce this, we may add it to our queue during the next sprint. 

Feel free to follow up with @CeciliaHinga about more details, let me know if I can help with any setup.

**Comment by AmTryingMyBest** [comment]
@tuxpiper I tried to recreate this, unsuccessfully. 
Unable to reproduce.

**Comment by tuxpiper** [comment]
@CeciliaHinga  do you feel like giving this another try and see if it appears again?

If you can see it happening again we will all sit down together and try to look under the hood.

**Comment by tuxpiper** [comment]
@Mh-Asmi managed to make sense of this:

to reproduce the issue
1. Log in
2. Click on the data view button
3. you will see a list of posts and a top of them you will see a number of posts ex: 5 of 5 posts"
4. Click on any post other than the first one  " ex : click on third post"
5. reload the page
6. you will note there are some posts are hidden and the number of post will be different also "ex: 3 of 3 posts"
7. Click on data view button again
8. you will see the original list again.

the issue happens  because
- in case "1" when clicked data view icon , the API that returns the list of posts is
api/v3/posts?has_location=all&limit=20&order=desc&order_unlocked_on_top=true&orderby=created&reactToFilters=true&source...........
- in case "2" when refresh the page while display a post details , the API that returns the list of posts is
api/v3/posts?created_before_by_id=10000&has_location=all&limit=20&order=desc&order_unlocked_on_top=true&orderby=created&source ...........

in case "2" we can note there is an extra parameter created_before_by_id=10000 , This parameter causes the API to return only posts that were created before the currently displayed post

this video explain the issue https://slack-files.com/T024G41EQ-F03Q081KDLL-1639be8557
