### ISSUE TITLE
Change Confirmation message text

### ISSUE THREAD

**Issue by tuxpiper** [ushahidi/platform#4734]
The confirmation message after changing post status says "Post Status have been changed"

This happens when you change post status from either "Published" or from "Under Review"

Let's change this to read "Post status changed" or "Post status has changed"

---
Created automatically from USH-832 (https://linear.app/ushahidi/issue/USH-832/change-confirmation-message-text)

**Comment by bintus-ux** [comment]
Can I be assigned this?

**Comment by JUNNY12** [comment]
Can I be assigned to this issue @tuxpiper @Angamanga ?

**Comment by goodylove** [comment]
@Angamanga i can work on this too

**Comment by Angamanga** [comment]
@JUNNY12 I assigned you to this one: https://github.com/ushahidi/platform/issues/4109 @goodylove Please go ahead with this issue 🎉 @bintus-ux In order to start an issue, you need to follow the steps in this discussion: https://github.com/ushahidi/platform/discussions/4713 Have you set up your developer environment yet? Once you have done that, ping me on another issue and I'll assign you!

**Comment by goodylove** [comment]
@Angamanga thank you

**Comment by goodylove** [comment]
@Angamanga please i have been trying to locate where the confirmation message  is but am yet to find it please where can i find it

**Comment by bintus-ux** [comment]
> @JUNNY12 I assigned you to this one: #4109 @goodylove Please go ahead with this issue 🎉 @bintus-ux In order to start an issue, you need to follow the steps in this discussion: #4713 Have you set up your developer environment yet? Once you have done that, ping me on another issue and I'll assign you!

I see, my bad

**Comment by goodylove** [comment]
@Angamanga please i have fix the  issues here is my PR link:
https://github.com/ushahidi/platform-client-mzima/pull/825
