### ISSUE TITLE
Finish Front-End Guidelines

### ISSUE THREAD

**Issue by middle8media** [ushahidi/platform#650]
Need to parse through app to make sure we are following our own rules.

Also there are a few elements that need to be added:

* declaration sorting
* extends
* naming conventions
* commenting
* css ruleset

**Comment by middle8media** [comment]
Update docs
Include RTL
neat grid overrides

**Comment by sophshep** [comment]
Just a comment as I'm designing new components: on the RTL section, it would be great to have a "cheatsheet" AKA a list of all the RTL mixins that we are using that I can just copy and paste from.

**Comment by jshorland** [comment]
is this done?

**Comment by middle8media** [comment]
This is not done, I need to step up and finish, I have put it off for too long.

**Comment by middle8media** [comment]
@sophshep is this sufficient? any thoughts?
http://github.ushahidi.org/platform-pattern-library/assets/html/front-end-guidelines/read-direction/

**Comment by sophshep** [comment]
It would be helpful to have an introduction to explain why this is important. Also to give an overview of how it is compiled together into different style sheets. If we're using the same method as what we read up on in a blogpost, we should reference that (both for credit and for additional explanation). 

I think it's important to note that the default is LTR, which is why a mixin would say `@include float(left);` for what we think of as left, and then the RTL is generated from there.

Weren't there also some RTL conflicts with how we use neat? (Like we had to manually write values?) If so, we should write about that as well.

**Comment by middle8media** [comment]
Thanks @sophshep I am making edits and additions, will push soon.

**Comment by middle8media** [comment]
Read Direction is done - http://github.ushahidi.org/platform-pattern-library/assets/html/front-end-guidelines/read-direction/

now to finish:

* declaration sorting
* extends
* naming conventions
* commenting
* css ruleset

**Comment by middle8media** [comment]
completed via abed8c9f7bedd4c39fcb011deab5d1cb4b06192d
