### ISSUE TITLE
Auto tag, location, structure, publish for posts

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#660]
SMS submissions to the platform are unstructured, and require manual verification and publishing. This is unfeasible for some clients (specifically Norwegian Red Cross), since they receive thousands of reports per month; we could implement a filter in the platform which would automatically sort and tag incoming messages, but that would lead to the same situation they are trying to leave (relying on external consultants to maintain filtering scripts).

Aha! Link: https://ushahiditeam.aha.io/features/PROD-731

**Comment by sebm90** [comment]
An organisation like the Norwegian Red Cross would ideally want an automatic filtering and tagging tool for incoming SMS messages that's comprehensive and flexible enough for them to set up and maintain themselves out-of-the-box.

**Comment by rjmackay** [comment]
I believe this is what Chambua is for.. developed as part of SwiftRiver

**Comment by hnykda** [comment]
Hello. We were working on similar task on last Hackathon in Malmo. Even though Chambua and SwiftRiver are finished, we haven't found single mention in this code base connected to them. 

We created our own plugin for V3, which is able to get meaningful informations for potentially arbitrary source (we tried that with twitter and plain text)  using any analyser which supports e.g. HTTP API. Our solution is dirty and messy (we played with data-provider plugin), but this is something which should be easily implementable using e.g. events. We unfortunately haven't enough time to make it nicely, but with your help we might.

What we basically did was that after fetching twitter message, we send it to Alchemy using Bluemix and got things like persons, contacts, locations etc. Then we append the result (in JSON) to the message. It should be easy to either populate appropriate fields of posts to ease approval and also prioritize those post. 

If you give us some hint how this should be implemented properly (I am thinking about some trigger `before_save`), we can take a look at it. Then should be easy to plug in whatever preprocessing you want to do - formated messages, semantic analysis, alchemy...

**Comment by rjmackay** [comment]
@hnykda Chambua and SwiftRiver aren't connected to the Platform at all.
Swiftriver is entirely discontinued as a product. But we did have plans to integrate Chambua directly with platform eventually.

You're right that this is messy right now. We don't have a fixed way to hook into triggers.. but desperately need one. Where do you think the best place to hook in would be for you? Just before a tweet or SMS messages is saved? or earlier?
Would you want a general event (for every post) or just twitter / data providers?

**Comment by hnykda** [comment]
Hello. Thank you for the information! Honestly, Chambua is out for two years - it starts to be obsolete already (just joking :smile: ). 

I would definitely go for a general event so we don't need to limit ourselves - it can be then used even for SMS and whatever pocahontas facetwitmailsms input we'll have in two years from now. And not just for those - there should be possibility to use this even for posts submitted through the web client. They can be e.g. automatically tagged, transalted or prioritised based on words and stuff.

Based on that I can answer your first question. Since it should be also done for the (web) posts themselves, it would be probably necessary to implement this just before saving - as far as I know the codebase there is nothing really going on after submitting and saving the post.

**Comment by hnykda** [comment]
Bump.

**Comment by aoduor** [comment]
Hi @hnykda, pardon our delayed action/response on this. Most of our dev team is still away on holiday but will be back in the next couple of days and be in touch with a response.
