### ISSUE TITLE
Cloud setup: customize deployment step

### ISSUE THREAD

**Issue by sophshep** [ushahidi/platform#670]
Does it make more sense for [this page](http://github.ushahidi.org/platform-pattern-library/assets/html/5_layouts/setup-customize.html) to be in the context of a full layout of the deployment? (with the left side nav, etc.)

cc/ @rjmackay

**Comment by rjmackay** [comment]
I've built a first version of this in a modal just for simplicity. However I'm happy to switch to a full page layout if thats preferred.

Its also doubling as a first login flow for OSS deployments too. OSS deployments will also ask for the site name, since we haven't had a chance to set it yet.

https://www.dropbox.com/s/jy1xd35elmeqgif/Screenshot%202015-09-04%2013.41.34.png?dl=0

**Comment by sophshep** [comment]
The modal looks good. I'll let @brandonrosage follow up, but my understanding is that the deployment tour that Brandon is building now will end on the settings>appearance page, with explanation about how a user can customize their deployment. It should be a nice transition from the tour to the actual deployment.

**Comment by brandonrosage** [comment]
@rjmackay: This "Customize your deployment" view no longer exists as part of the "Create new deployment" onboarding flow. So it can go away in its current form.

As it's represented in onboarding, it's currently [a simple "step" in the tour](http://github.ushahidi.org/platform-pattern-library/assets/html/5_layouts/tour.html#customize), where we call out that "Settings" is where customization happens.

In the not too distant future, I'd like to expand the 'Tour' framework we've built to facilitate _the completion of a customization_, like defining the deployment's description within the onboarding flow. I punted that particular feature, though, in favor of getting something together that I knew could meet our technical constraints.
