### ISSUE TITLE
Create a list of what all the filters should be

### ISSUE THREAD

**Issue by sophshep** [ushahidi/platform#690]
cc @brandonrosage

**Comment by rjmackay** [comment]
Just to add to this:
- We built the post type and current step filters without design input.. I'd love to see alternative approaches for the stage filter, maybe combined with the post type filter somehow? right now its just confusing
- Sometime soon we need to look at how we handle filtering by custom fields too

cc @vbhv since we talked about grouping by custom fields in the context of graph and timeline views a while back. And there's probably crossover there

**Comment by rjmackay** [comment]
ping @sophshep is this still on the radar?

**Comment by brandonrosage** [comment]
# Posts
(includes All Posts, Saved Searches, and Collections)

* **Keyword**: Text input; visible to everyone
* **Categories**: Multi-select checkboxes, optionally nested; visible to everyone
* **Post Type**: Multi-select checkboxes, optionally nested with its Steps (selecting a Step indicates that you want to see posts that have completed that Step); visibility maps to each Post Type's visibility, as well as its Steps
* **Date range**: Dual datepickers for "start date" and "end date"; visible to everyone
* **Who can see it**: Radio buttons for "Everyone" and each available user role; visible to logged-in users, and only displays the roles they have permission to see.
* **Custom fields**: For each custom field that has been selected to be "filterable," it appears with the appropriate control (e.g. text input for custom text inputs, location picker for custom location fields).

We will design a filter control that demonstrates each of these, since a few of them are new or revised concepts. "Custom fields," is also presumably a later-phase addition.

# Settings: Users
* **Keyword**: Text input
* **Role**: Multi-select checkboxes

/cc @sophshep @rjmackay

**Comment by sophshep** [comment]
Can you specify what you mean by custom fields and how the select for something being filterable should work? If this is a later phase thing, we should add in "location" as a filter until it's ready.

Filters also show up on the [Activity Timeline](http://github.ushahidi.org/platform-pattern-library/assets/html/5_layouts/activity-timeline.html) with a new option of "Activity Type" which I would define as: New Post, Edited Post, Completed Step, New Collection, Edited Collection, New Saved Search, Edited Saved Search, & New User

**Comment by brandonrosage** [comment]
## RE: Custom fields
There would be an accordion item for each of the custom fields belonging to the included Post Types' Structure. 

So if the user was viewing two Post Types -- one with an added location field and the other with an added select field -- those fields would be represented as accordion items. The "location" accordion item would be labeled with the custom field's name and reveal a location search control. The "select" accordion item would be labeled appropriately and reveal a fieldset of radio buttons matching the field's available options.

In the near term, I think a location accordion item should be ready to display under the condition that a location field is being used on at least one Post Type.

**Comment by brandonrosage** [comment]
@rjmackay Is this Issue still in my court? Or do you have what you need?

What more can I provide?

**Comment by rjmackay** [comment]
I'll assign to myself for now. Need to review how this differs from the current UI and see if I have further Qs.
