### ISSUE TITLE
Failed login on fresh installation with missing an access token

### ISSUE THREAD

**Issue by sanel** [ushahidi/platform#698]
Hi guys,

Just installed fresh installation from git, after I failed to make it running with v.3.0.0. I was following this tutorial: http://docs.ushahidi.org/install/installing-on-linux.html and after I got up the site, I'm not able to login with *admin*/*admin* credentials.

After some inspection with Firebug, I got this:

```
POST http://api.routeofhope.com/oauth/token 200 OK 2.48s
GET http://api.routeofhope.com/api/v3/users/me 400 Bad Request 136ms
```

Here is the full trace:

```
{
    "errors": [
        {
            "message": "The request is missing an access token in either the Authorization header or
 the access_token request parameter.",
            "code": 400,
            "class": "Kohana_HTTP_Exception",
            "file": "/home/routeofhope/domains/api.routeofhope.com/public_html/platform/application/classes
/Ushahidi/Rest.php",
            "line": 294,
            "trace": [
                {
                    "file": "/home/routeofhope/domains/api.routeofhope.com/public_html/platform/application
/classes/Ushahidi/Rest.php",
                    "line": 73,
                    "function": "_check_access",
                    "class": "Ushahidi_Rest",
                    "type": "->",
                    "args": [

                    ]
                },
                {
                    "file": "/home/routeofhope/domains/api.routeofhope.com/public_html/platform/vendor
/kohana/core/classes/Kohana/Controller.php",
                    "line": 69,
                    "function": "before",
                    "class": "Ushahidi_Rest",
                    "type": "->",
                    "args": [

                    ]
                },
                {
                    "function": "execute",
                    "class": "Kohana_Controller",
                    "type": "->",
                    "args": [

                    ]
                },
                {
                    "file": "/home/routeofhope/domains/api.routeofhope.com/public_html/platform/vendor
/kohana/core/classes/Kohana/Request/Client/Internal.php",
                    "line": 97,
                    "function": "invoke",
                    "class": "ReflectionMethod",
                    "type": "->",
                    "args": [
                        {
                            "request": {

                            },
                            "response": {

                            }
                        }
                    ]
                },
                {
                    "file": "/home/routeofhope/domains/api.routeofhope.com/public_html/platform/vendor
/kohana/core/classes/Kohana/Request/Client.php",
                    "line": 114,
                    "function": "execute_request",
                    "class": "Kohana_Request_Client_Internal",
                    "type": "->",
                    "args": [
                        {

                        },
                        {

                        }
                    ]
                },
                {
                    "file": "/home/routeofhope/domains/api.routeofhope.com/public_html/platform/vendor
/kohana/core/classes/Kohana/Request.php",
                    "line": 997,
                    "function": "execute",
                    "class": "Kohana_Request_Client",
                    "type": "->",
                    "args": [
                        {

                        }
                    ]
                },
                {
                    "file": "/home/routeofhope/domains/api.routeofhope.com/public_html/platform/httpdocs
/index.php",
                    "line": 29,
                    "function": "execute",
                    "class": "Kohana_Request",
                    "type": "->",
                    "args": [

                    ]
                }
            ]
        }
    ]
}
```
I'm getting these errors with both git and v3.0.0 versions.

Any idea?

**Comment by rjmackay** [comment]
Are you using mod php? or cgi? or php fpm? .. we've had some issues with Apache stripping Authentication headers from PHP cgi requests. I think similar happens with PHP FPM depending on config

**Comment by sanel** [comment]
php with fastcgi. I presume then it is the same behavior as for FPM/cgi. Is there any ticket related to this issue I can follow?

**Comment by naheedakhtar** [comment]
I am getting exactly the same error; Please advise.  I am running on Ubuntu 14 & Nginx

**Comment by rjmackay** [comment]
I don't have a solution for this at all yet. Either:
- Run apache with mod php
- Run nginx with php fpm and add the option `fastcgi_pass_header Authorization;`
.. as far as apache and php-fpm or apache and php cgi I don't know sorry.

**Comment by naheedakhtar** [comment]
It took me long time to configure ushahidi on ubuntu 14, NGINX and PHP 5 FPM ; hence i am posting the configuration so that it can be useful to others:

I made 2 folders: 
 
CLIENT FILES LOCATION /var/www/ushahidi/platform-client

SERVER FILES LOCATION /var/www/ushahidi/platform

CLIENT .ENV File CONTENT

   NODE_SERVER=false
   BACKEND_URL=http://ushahidi.XYZABC.com/    ====> // REPLACE xyzabc with your domain



USHAHIDI SERVER NGINX CONFIG:
----------------------------------------

       server {
           listen 80;
	   server_name ushahidi.XYZABC.com ;  // REPLACE xyzabc with your domain

           root /var/www/ushahidi/platform/httpdocs;
           index index.html;

         

        location / {
                index index.php;
                try_files $uri $uri/ /index.php$uri?$args;
        }

        location ^~ /index.php {
                allow all;
               include php.conf;  //CHECK BELOW 
                break;
        }

      

}

PHP.conf
------------

fastcgi_split_path_info ^(.*\.php)(.*)$;

include fastcgi_params;  // Check below

fastcgi_param SCRIPT_FILENAME           $document_root$fastcgi_script_name;
fastcgi_param PATH_INFO                 $fastcgi_path_info;
fastcgi_param HTTP_HOST                 $host;
fastcgi_param SERVER_NAME               $host;
fastcgi_intercept_errors                on;
fastcgi_index                           index.php;
fastcgi_pass                            unix:/var/run/php5-fpm.sock;

fastcgi_params
-------------------
fastcgi_param   QUERY_STRING            $query_string;
fastcgi_param   REQUEST_METHOD          $request_method;
fastcgi_param   CONTENT_TYPE            $content_type;
fastcgi_param   CONTENT_LENGTH          $content_length;

fastcgi_param   SCRIPT_FILENAME         $document_root$fastcgi_script_name;
fastcgi_param   SCRIPT_NAME             $fastcgi_script_name;
fastcgi_param   PATH_INFO               $fastcgi_path_info;
fastcgi_param       PATH_TRANSLATED         $document_root$fastcgi_path_info;
fastcgi_param   REQUEST_URI             $request_uri;
fastcgi_param   DOCUMENT_URI            $document_uri;
fastcgi_param   DOCUMENT_ROOT           $document_root;
fastcgi_param   SERVER_PROTOCOL         $server_protocol;

fastcgi_param   GATEWAY_INTERFACE       CGI/1.1;
fastcgi_param   SERVER_SOFTWARE         nginx/$nginx_version;

fastcgi_param   REMOTE_ADDR             $remote_addr;
fastcgi_param   REMOTE_PORT             $remote_port;
fastcgi_param   SERVER_ADDR             $server_addr;
fastcgi_param   SERVER_PORT             $server_port;
fastcgi_param   SERVER_NAME             $server_name;
fastcgi_param   HTTPS                   $https;
fastcgi_param   REDIRECT_STATUS         200;


USHAHIDI CLIENT NGINX CONFIG:
----------------------------------------
    server {
				listen 80;

				#charset UTF-8;
				
				root /var/www/ushahidi/platform-client/server/www/;
				index index.html;

				server_name XYZABC.com www.XYZABC.com;
				location / {
        				try_files $uri $uri/ @missing;
  				  }

  				  # Rewrite 404s back to index.html for pushState support
   				  # All routing is handled by Angular.
   				 location @missing {
   					     rewrite ^ /index.html last;
   					 }


     }
 

 I am pointing the server to sub-domain (ushahidi.XYZABC.com) and the client on main domain (XYZABC.com)

**Comment by rjmackay** [comment]
@naheedakhtar Thank you! Thats super helpful. Any chance you could send a pull request to https://github.com/ushahidi/docs.ushahidi.com to complete the documentation?
If not, I'll merge some of this in within a few weeks.

**Comment by naheedakhtar** [comment]
Sorry for delayed response as i was travelling...i will be sending the pull request as requested

**Comment by panterz** [comment]
Had the same issue as well. On apache 2.2, php 5.5 by adding this on .htaccess

SetEnvIf Authorization "(.*)" HTTP_AUTHORIZATION=$1

**Comment by rjmackay** [comment]
@tuxpiper could you look at the documentation todo's on this while documenting a bundled install?

**Comment by tuxpiper** [comment]
The apache php-cgi , apache mod-php and nginx php-fpm setups I've tried haven't exhibited this problem. (the configuration files as the ones that can be found in https://github.com/ushahidi/platform-release/tree/master/dist )

This may be something that arises in some setups only under specific circumstances.

Because of that, I'm not going to add it to the documentation yet, but keep this PR as reference in case someone comes across the same problem.

**Comment by tuxpiper** [comment]
Please do comment and mention me if you come across this in any of your setups.

**Comment by tinodj** [comment]
@tuxpiper I just came across this problem. It was ubuntu 12.04 with php-fpm 5.5 and apache 2.4. 

The fastcgi was defined in Apache virtual host as: 

FastCgiExternalServer /usr/lib/cgi-bin/php5-fcgi-www **-pass-header Authorization** -socket /var/run/php5-fpm

Adding the bold part helped me resolve the issue - without that part it was not working.

**Comment by NonSecwitter** [comment]
On a fresh install, I ran into a problem of not being able to log in as admin/admin, or creating a new user.

1) Attempting to login returned no errors or information whatsoever, other than failed login.

2) Creating a user returned "The request is missing an access token in either the Authorization header or the access_token request parameter. " (searching for this brought me here.

As @panterz mentioned above, adding the following line to .htaccess fixed this for me

SetEnvIf Authorization "(.*)" HTTP_AUTHORIZATION=$1

**Comment by NonSecwitter** [comment]
@tuxpiper 
Another interesting development in this:
I have the site up and running, and almost everything seems to be working fine. However, any images that I upload, such as deployment logo and images attached to survey submissions, do not render. The images are successfully uploaded to the proper directory with the proper name. If I download the image from from the server's file manager, the images is still good.

Doing some packet capturing, I found that the site is requesting the jpg, but receiving the index.html in repsonse, instead of the actual image:

`HTTP GET /media/uploads/5/8/58445ec0afe71-file.jpg`
`HTTP HTTP/1.1 200 OK  (text/html)`

Obviously this should be a mediatype instead of (text/html). Here is the text of the response:

`Line-based text data: text/html`

    <!doctype html>\n
    <html lang="en" ng-strict-di>\n
        <head ng-controller="PageMetadata">\n
            <meta charset="utf-8">\n
            <meta http-equiv="X-UA-Compatible" content="IE=edge">\n
            <meta name="viewport" content="width=device-width, initial-scale=1">\n
            <link href="/fonts/Lato/css/fonts.css" rel="stylesheet" type="text/css">\n
            \n
            <link rel="stylesheet" href="/css/vendor.css">\n
            <link rel="stylesheet" href="/css/style.css" ng-href="{{rtlEnabled ? '/css/rtl-style.css' : '/css/style.css'}}">\n
            <script src="/config.js"></script>\n
    \n
            <title ng-bind-template="{{pageTitle}} {{siteTitle}}"></title>\n
            <meta name="description" ng-attr-content="{{pageDescription}}">\n
            <meta name="keywords" ng-attr-content="{{pageKeywords}}">\n
            <meta name="robots" ng-attr-content="{{pageRobots}}">\n
            <base href="/">\n
        </head>\n
    \n
        \n
        <body ng-class="{ rtl : rtlEnabled, 'modal-visible': modalVisible }" class="{{ globalLayout }}" canvas>\n
            <div id="bootstrap-loading">\n
                \n
                <div class="loading">\n
                    <div class="line"></div>\n
                    <div class="line"></div>\n
                    <div class="line"></div>\n
                </div>\n
                \n
            </div>\n
    \n
            <div id="bootstrap-error" class="hidden">\n
                <div class="wrapper">\n
                    <main class="page-content">\n
                        <div class="alert error">\n
                            <p>Sorry, something went wrong. Try reloading the page.</p>\n
                        </div>\n
                    </main>\n
                </div>\n
            </div>\n
    \n
            <div id="bootstrap-app" class="hidden">\n
    \n
                <mode-bar embed-only=false current-user="currentUser"></mode-bar>\n
    \n
                <ng-view></ng-view>\n
    \n
                \n
                <ush-slider></ush-slider>\n
                <ush-modal-container></ush-modal-container>\n
            </div>\n
    \n
            <script src="/js/bundle.js"></script>\n
    \n
            <script type="text/javascript">\n
                if (window.ushahidi && window.ushahidi.doorbellEnabled) {\n
                    window.doorbellOptions = {\n
                        tags: ['platform'],\n
                        appKey: window.ushahidi.doorbellAppKey,\n
                        properties: {\n
                            apiUrl: window.ushahidi.apiUrl\n
                        },\n
                        onShow: function () {\n
                            injector = angular.element(document).injector();\n
                            auth = injector.get('Authentication');\n
                            session = injector.get('Session');\n
    \n
                            if (auth && session) {\n
                                doorbell.setOption('email', session.getSessionDataEntry('email'));\n
                                doorbell.setProperty('loggedIn', auth.getLoginStatus());\n
                                doorbell.setProperty('role', session.getSessionDataEntry('role'));\n
                                doorbell.setProperty('realname', session.getSessionDataEntry('realname'));\n
                            }\n
                        }\n
                    };\n
                    (function(d, t) {\n
     [truncated]                    var g = d.createElement(t);g.id = 'doorbellScript';g.type = 'text/javascript';g.async = true;g.src = 'https://embed.doorbell.io/button/2005?t='+(new Date().getTime());(d.getElementsByTagName('head')[0]||d.ge
                    }(document, 'script'));\n
                }\n
            </script>\n
            \n
            <script type="text/javascript">\n
                (function(){\n
                  var per_app_intercom_widget;\n
    \n
                  function getAppId() {\n
                    if (typeof window.intercomSettings !== 'undefined' &&\n
                      typeof(window.intercomSettings.app_id) !== 'undefined') {\n
                      return window.intercomSettings.app_id\n
                    } else if (typeof window.analytics !== 'undefined' &&\n
                      typeof window.analytics._integrations !== 'undefined' &&\n
                      typeof analytics._integrations.Intercom !== 'undefined' &&\n
                      typeof analytics._integrations.Intercom.options !== 'undefined' &&\n
                      typeof analytics._integrations.Intercom.options.appId !== 'undefined') {\n
                      return analytics._integrations.Intercom.options.appId;\n
                    } else {\n
                      return '';\n
                    }\n
                  }\n
    \n
                  per_app_intercom_widget = 'https://widget.intercom.io/widget/' + getAppId();\n
                  var script_tag = document.createElement('script');\n
                  script_tag.type = 'text/javascript';\n
                  script_tag.async = true;\n
                  script_tag.src = per_app_intercom_widget;\n
    \n
                  var existing_script = document.getElementsByTagName('script')[0];\n
                  existing_script.parentNode.insertBefore(script_tag, existing_script);\n
                })();\n
            </script>\n
            <div ng-controller="intercom"></div>\n
    \n
            <script>\n
                if (window.ushahidi && window.ushahidi.gaEnabled) {\n
                    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){\n
                    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),\n
                    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)\n
                    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');\n
    \n
                    ga('create', window.ushahidi.gaKey, 'auto');\n
                    ga('send', 'pageview');\n
                }\n
            </script>\n
            <script>\n
                if (window.ushahidi && window.ushahidi.ravenUrl) {\n
                    (function(d, t, c, s) {\n
     [truncated]                    var g = d.createElement(t);g.id = 'ravenScript';g.type = 'text/javascript';g.async = true; g.src = 'https://cdn.ravenjs.com/3.8.0/angular/raven.min.js';g.onload=c;g.onreadystatechange=c; s = d.getElementsByT
                    }(document, 'script', function () {\n
                        Raven.config(window.ushahidi.ravenUrl).install();\n
                    }));\n
                }\n
            </script>\n
    \n
            \n
              <div id="fb-root"></div>\n
              <script>(function(d, s, id) {\n
                var js, fjs = d.getElementsByTagName(s)[0];\n
                if (d.getElementById(id)) return;\n
                js = d.createElement(s); js.id = id;\n
                js.src = "//connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v2.8";\n
                fjs.parentNode.insertBefore(js, fjs);\n
              }(document, 'script', 'facebook-jssdk'));</script>\n
        </body>\n
    </html>\n
