### ISSUE TITLE
"Report a bug" button on web version of ushahidi.io should point to doorbell feedback form

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#791]
I know we have the "Feedback" form at the bottom of the page, but "Report a bug" tends to be more visible.

Recommendation is either get rid of one, or have "Report a bug" link to our doorbell.io feedback form.

Thoughts?

**Comment by aoduor** [comment]
pinging @rjmackay @jshorland what do you guys think?

**Comment by rjmackay** [comment]
- I agree they should go to the same place, or we should probably remove one.
- I'm actually pretty tempted to drop doorbell entirely, and use Helpscout Beacons instead.. since we already have support@ going into helpscout, and we need to start paying doorbell otherwise.
- Helpscout looses the auto push feedback into github **but** I've only used it once so far.. I don't think copy/pasting to github is really going to be a burden right now.
@jshorland what do you think?

**Comment by jshorland** [comment]
Streamlining is good. Agreed that it's not going to be difficult to copy and paste to github. I also know @aoduor absolutely despises helpscout, and she'll be the one using it the most, so I'd like to leave her as the decision maker on this.

**Comment by aoduor** [comment]
To be quite honest, doorbell is more user friendly. I'd would much rather move help scout over to doorbell than the other way round. I think we also still pay for for help scout at the moment.

Handheld Sent,

Angela Oduor Lungati,
Director of Community Engagement,
Ushahidi | www.ushahidi.com

**Comment by rjmackay** [comment]
I don't think doorbell is really a helpscout replacement, it has a much narrower scope: just user feedback. Vs  helpscout which is built as a shared inbox, and more complete customer support suite.
But obviously I don't have to use it much so I'm not hitting the pain points.
I'd really like to find something that works for us and covers both bases.
Lets take this discussion out of public github issues though.

For this issue: lets just remove the "Report a bug" or make it trigger the doorbell form. But make doorbell the only channel.

**Comment by caharding** [comment]
no longer using doorbell
