### ISSUE TITLE
Changing post type name does not change post type name in Filters without refreshing

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#797]
Steps to recreate issue:
1. create a deployment from scratch
2. Navigate to "post types" under settings menu
3. Click on "basic post" to edit the post type settings
4. Click post type settings
5. Rename to something other than "basic post"
6. Click "save post type"
7. Navigate to "home"
8. Navigate to post-type filter
*at this point, the post type has not changed names and still reads, "basic post"
9. Refresh page
10. Post type now reads the new name

Expected outcome:
- Upon returning to the home screen, I expected the name to change in the filters immediately. I did not realize I needed to refresh. It took some trial and error to figure that out

Actual outcome:
- had to try over and over again to navigate from home to post type settings, save the name multiple times, then tried refreshing. Refreshing worked, but very frustrating. 

The same issue applies to categories, steps, and collections

Proposed solutions:
Either
1. ensure filters are changed as post type are changed WITHOUT the user having to refresh, or if this isn't possible,
2. indicate that a user needs to refresh the page with a notification after she clicks "save post type"

**Comment by rjmackay** [comment]
@willdoran @jasonmule we should chat about how best to manage these types of issues everywhere.
Adding caching will only make this issue *worse* .. so we need to push events for changes to models throughout the app.

I'm tempted to tend towards something more like the 'Flux' architecture.  Where instead of pulling data directly from Endpoint services, we listen for events which return data, and trigger updates when needed.
