### ISSUE TITLE
Selecting audience for "who can see this" when adding a post sets off an error alert

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#914]
Steps to recreate:
1. click "add post" when logged into deployment
2. write title of post
3. click drop down menu for "who can see this" and select "admin"
4. See error message appear

![screen shot 2016-02-17 at 8 22 13 am](https://cloud.githubusercontent.com/assets/3224856/13110791/253a2d20-d550-11e5-90b2-3a5fa18a2dd7.png)

Confusing for me as it appears I need to select the audience second in the order of things.

**Comment by willdoran** [comment]
@jshorland taking a look at this now.

**Comment by jshorland** [comment]
@rjmackay added #1042  recently. Is that related to this?

**Comment by willdoran** [comment]
@jshorland I think this was a slightly different issue to do with not being able to mark structure completed. That was fixed in responder and I forgot to close this. #1042 should hide or disable the 'who can' option when it's not relevant. That change is pretty quick to add once everything else lands.
