### ISSUE TITLE
Report a bug links to GitHub which requires login

### ISSUE THREAD

**Issue by caharding** [ushahidi/platform#989]
### Expected behaviour

Link will pop up a form that allows me to fill in information about the bug. The submission would collect the user email, and deployment name/info 
### Actual behaviour

Pops up GitHub which asks you to login, which will reduce the number of bugs 
### Steps to reproduce the behaviour/error

Click on the Report A Bug link at the bottom of any deployment

**Comment by rjmackay** [comment]
@jshorland @caharding I'm not keen to implement a standalone bug reporting mechanism as thats yet another thing to maintain.. could we just push the "Report a bug" link to intercom?

**Comment by aoduor** [comment]
@jshorland @caharding I agree with @rjmackay. Too many channels to maintain. This is why we have doorbell integrated. I'm not comfortable with this being sent to intercom as i'm not sure intercom has a "push to github" feature like Doorbell does. Intercom IDEALLY shouldn't be used for technical support/bug reporting i would think? But happy to hear more of your thoughts on this.

**Comment by rjmackay** [comment]
I thought we were turning off doorbell when we add intercom? I don't think it makes sense to have both. And the kind of feedback we get through doorbell is very similar to what comes via intercom.

Intercom is already being used for tech support.. we're just manually copying confirmed bugs to github. I don't think thats an issue.. there are often multiple reports of the same bug, intercom does ok at keep track of those so we can respond to the users.

**Comment by caharding** [comment]
Whatever the solution it should not link directly to github

On Tue, Mar 22, 2016 at 12:27 PM, Robbie Mackay <notifications@github.com>
wrote:

> I thought we were turning off doorbell when we add intercom? I don't think
> it makes sense to have both. And the kind of feedback we get through
> doorbell is very similar to what comes via intercom.
>
> Intercom is already being used for tech support.. we're just manually
> copying confirmed bugs to github. I don't think thats an issue.. there are
> often multiple reports of the same bug, intercom does ok at keep track of
> those so we can respond to the users.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/ushahidi/platform/issues/989#issuecomment-199975558>
>



-- 
Charlie Harding
Product Director

**Comment by caharding** [comment]
Meaning the link on the page should not open github.

On Tue, Mar 22, 2016 at 1:02 PM, Charles Harding <charles@ushahidi.com>
wrote:

> Whatever the solution it should not link directly to github
>
> On Tue, Mar 22, 2016 at 12:27 PM, Robbie Mackay <notifications@github.com>
> wrote:
>
>> I thought we were turning off doorbell when we add intercom? I don't
>> think it makes sense to have both. And the kind of feedback we get through
>> doorbell is very similar to what comes via intercom.
>>
>> Intercom is already being used for tech support.. we're just manually
>> copying confirmed bugs to github. I don't think thats an issue.. there are
>> often multiple reports of the same bug, intercom does ok at keep track of
>> those so we can respond to the users.
>>
>> —
>> You are receiving this because you were mentioned.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/ushahidi/platform/issues/989#issuecomment-199975558>
>>
>
>
>
> --
> Charlie Harding
> Product Director
>



-- 
Charlie Harding
Product Director

**Comment by rjmackay** [comment]
ping @aoduor any final comments on this?

**Comment by aoduor** [comment]
Yes. I would much rather keep doorbell and minimise bug reports coming in via intercom. The whole idea behind intercom is customer service/support. If we can find ways of offloading some elements of bug reporting to our users, that would be great. Leaving this on intercom alone puts 90% of the work of bug reporting on us(since we're trying to reduce the need for logins to github as a requirement to submit a bug report.)

**Comment by rjmackay** [comment]
I don't really understand the distinction you're making between customer
support and bug reporting.. answering a bug report IS customer support IMO.
Can you explain what the different needs are?

I don't think doorbell has been working well for us:
- looking at past submissions the quality of the reports is low.
- We have a total of 6 issue created in github via doorbell - which I think
means the 'push to github' feature isn't helping us much.
- We haven't been regularly responding to them. And when followed up they
often don't reply. (Intercom seems to be more successful at this)
- We're already getting bug reports to intercom.. in general we're getting
better info there because we're responding quicker
- We're getting more general support requests in doorbell.. but not
responding quickly becuase not everyone is on doorbell.
- In a few instances people are confused between giving feedback to
Ushahidi vs reporting between the deployer themselves

I'm not clear how doorbell reduces the work of bug reporting for us? It
adds another channel to log into, vs just intercom.
I think we should try pushing EVERYTHING to intercom for a few months and
then revisit if its actually causing problems.

On OSS: deployers already have to grab code from github. It makes sense for
them to report there. So I don't think doorbell serves much purpose for
them.

On Fri, Apr 1, 2016 at 8:01 PM, Angela Oduor Lungati <
notifications@github.com> wrote:

> Yes. I would much rather keep doorbell and minimise bug reports coming in
> via intercom. The whole idea behind intercom is customer service/support.
> If we can find ways of offloading some elements of bug reporting to our
> users, that would be great. Leaving this on intercom alone puts 90% of the
> work of bug reporting on us(since we're trying to reduce the need for
> logins to github as a requirement to submit a bug report.)
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/ushahidi/platform/issues/989#issuecomment-204276660>
>



-- 
Robbie Mackay

Head of engineering
Ushahidi Inc
m: +64 27 576 2243
e: robbie@ushahidi.com
skype: robbie.mackay

**Comment by aoduor** [comment]
I'm not sure we're on the same page here. I didn't say bug reporting isn't part of customer support. All i would like to see is more empowerment of users to report their issues(in an easier way than having someone on the team having to act as the middle man, troubleshoot AND then file a bug report, which is what leaving things on intercom will lead to.). Having all this coming to intercom means anyone manning the tool will now be responsible for filing all bug reports that come in there, i.e read intercom, troubleshoot, and then open github and file the report in there, which is alot of work.

Could we have a review of the reasons for low uptake of doorbell on ushahidi.io? Also, if we made the language much clearer, i.e "Report a bug" as opposed to "Feedback", we will likely get bug reports as opposed to confusion between bug reporting and feedback.
